.gitignore, package.json
Added production startup script.
Please test pull requests with ```npm run start:prod```
This will build and run in production using AoT compilation.
=> Added production startup script: this connects to #11

package.json
=> Global dependencies

package.json
This PR connects to [#50](https://github.com/DSpace/dspace-angular/issues/50)
=> postcss script changed

npm-shrinkwrap.json, package.json
to prevent issues with different OS-es
This PR connects to #54
=> removed optional dependencies from npm-shrinkwrap.json 

package.json, src/app/app.reducers.ts, yarn.lock
=> ngrx-store-freeze added and configured

src/app/core/cache/models/normalized-community.model.ts, src/app/core/cache/models/normalized-dspace-object-factory.ts, src/app/core/cache/models/normalized-dspace-object-type.ts, src/app/core/core.module.ts, src/app/core/data/community-data.service.ts, src/app/core/shared/community.model.ts, src/backend/api.ts, src/backend/communities.ts
=> Add support for Communities

e2e/app.e2e-spec.ts, e2e/app.po.ts, resources/i18n/en.json, src/app/app.component.html, src/app/app.component.scss, src/app/app.component.spec.ts, src/app/app.component.ts, src/app/core/cache/models/normalized-community.model.ts, src/app/core/cache/models/normalized-dspace-object-factory.ts, src/app/core/cache/models/normalized-dspace-object-type.ts, src/app/core/core.module.ts, src/app/core/data/community-data.service.ts, src/app/core/shared/community.model.ts, src/app/home/home-news/home-news.component.html, src/app/home/home-news/home-news.component.ts, src/app/home/home.component.html, src/app/home/home.module.ts, src/app/home/top-level-community-list/top-level-community-list.component.html, src/app/home/top-level-community-list/top-level-community-list.component.ts, src/backend/api.ts, src/backend/communities.ts
This PR adds some initial content to the home page: a news section and the list of top level communities
The news is hardcoded for now,  and the top level community list isn't paginated, both of those can be improved later. The goal of this PR is just to make a start.
I moved the message that shows whether the development or production environment is active to the console.
This PR depends on #92
=> Initial home page content

src/app/collection-page/collection-page.component.ts, src/backend/items.ts
Fixed an issue where incomplete item mock data caused an error on collection homepages
Also added an unsubscribe for the logo's subscription on collection homepages
This PR connects to #112
=> Fix Collection Homepage Errors

src/app/collection-page/collection-page.component.ts, src/app/core/cache/response-cache.service.ts, src/app/object-list/object-list.component.html, src/app/shared/object-list/object-list.component.ts, src/app/shared/pagination/pagination.component.html, src/app/shared/pagination/pagination.component.spec.ts, src/app/shared/pagination/pagination.component.ts
This connect to #119 
Ready for review
=> Fix pagination issues

src/app/core/cache/builders/remote-data-build.service.ts, src/app/core/cache/models/normalized-bitstream.model.ts, src/app/core/shared/bitstream.model.ts, src/app/core/shared/item.model.spec.ts, src/app/item-page/full/field-components/file-section/full-file-section.component.html, src/app/item-page/simple/field-components/file-section/file-section.component.html, src/app/shared/comcol-page-logo/comcol-page-logo.component.html, src/app/thumbnail/thumbnail.component.html, src/app/thumbnail/thumbnail.component.spec.ts
This connect to #125 
Rename HAL link for the bitstreams from 'retrieve' to 'content'
=> Rename the HAL link

src/app/pagenotfound/pagenotfound.component.ts, src/app/shared/server-response.service.ts, src/app/shared/shared.module.ts
This connects to #91.
I've kept `ServerResponseService` to the minimum, but I can add more methods if you think it might be useful in the future.
=> Bugfix 91:  404 page status code

.travis.yml
Travis' build is failing for what seems to be a reason unrelated to the code. Trying out a few different configuration options that could fix the problem.
=> Fix travis build issue

e2e/search-page/search-page.e2e-spec.ts
This PR closes #175 
Added the wait callback method to the search page e2e tests to make sure navigating to a new URL has completed.
=> Fixed issue with e2e tests after merging

src/app/app-routing.module.ts, src/app/app.module.ts
=> re-export RouterModule in AppRoutingModule

package.json, src/app/+search-page/search-filters/search-filter/search-facet-filter/search-facet-filter.component.spec.ts, src/app/+search-page/search-filters/search-filter/search-filter.component.spec.ts, src/app/+search-page/search-page.component.spec.ts, src/app/+search-page/search-sidebar/search-sidebar.component.ts, src/app/header/header.component.spec.ts, src/app/shared/route.service.ts
=> Let linting exit with a nonzero status

src/app/core/cache/object-cache.effects.spec.ts, src/app/core/cache/object-cache.effects.ts, src/app/core/cache/response-cache.effects.spec.ts, src/app/core/cache/response-cache.effects.ts, src/app/core/cache/response-cache.reducer.spec.ts, src/app/core/cache/response-cache.service.spec.ts, src/app/core/cache/response-cache.service.ts, src/app/core/core.effects.ts, src/app/core/data/request.reducer.spec.ts, src/app/core/index/uuid-index.reducer.spec.ts, src/app/object-list/object-list.component.html, src/app/object-list/object-list.component.spec.ts
This PR connects to #130 
I added a couple of tests to increase our general test coverage. 
Will add some more in the upcoming week.
=> Increase test coverage

src/main.browser.ts
=> Fix CSR only issue

src/app/shared/search-form/search-form.component.html
This PR closes #222.
I added an action to the form, to make sure the request always redirects to the `/search` page.
=> Fixed search form that did not work without javascript

README.md, docs/Configuration.md
=> Added docs about Angulartics providers

src/app/shared/mocks/mock-admin-guard.service.ts, src/app/shared/shared.module.ts
Issue: https://github.com/DSpace/dspace-angular/issues/257
=> Mock AdminGuard

docs/Configuration.md, src/config.ts, src/server.ts
=> Set ip and port by an env variable.

src/app/core/data/data.service.spec.ts, src/app/core/data/data.service.ts, src/app/core/data/request.models.ts
Added startsWith option to request.models.ts and data.service.ts
Added basic tests for getFindAllHref in DataService
This PR closes #247
=> ISSUE-247:  Added startsWith param to getFindAllHref

resources/i18n/nl.json
=> Issue #295 Dutch translation

src/app/shared/comcol-page-logo/comcol-page-logo.component.html, src/app/shared/comcol-page-logo/comcol-page-logo.component.scss
=> issue 323 comcol page logo bottom padding

config/environment.default.js, src/app/app.component.ts, src/app/header/header.component.html, src/app/shared/lang-switch/lang-switch.component.html, src/app/shared/lang-switch/lang-switch.component.scss, src/app/shared/lang-switch/lang-switch.component.spec.ts, src/app/shared/lang-switch/lang-switch.component.ts, src/app/shared/shared.module.ts, src/config/global-config.interface.ts, src/config/lang-config.interface.ts
This PR closes #304
This PR closes #298
This PR closes #301
Hopefully final rebased and squashed version of the language switch feature, including successful tests.
=> Issue 298 Language switch

resources/i18n/en.json, resources/i18n/nl.json, src/app/+home-page/top-level-community-list/top-level-community-list.component.html, src/app/+home-page/top-level-community-list/top-level-community-list.component.ts, src/app/shared/object-collection/object-collection.component.html
This PR fixes an issue with pagination on the home page.
The pagination on the Top-Level Community list on the home page has been broken for a while.
Some outputs were not passed on to their parent components correctly.
I also refactored this code a bit to get rid of bad practices and to align its implementation with similar code.
=> Home pagination issue fix

e2e/app.e2e-spec.ts, e2e/app.po.ts, src/app/+home-page/home-news/home-news.component.html
=> issue 321 home news rewording

config/environment.test.js, src/app/entity-groups/journal-entities/item-grid-elements/journal-issue/journal-issue-grid-element.component.spec.ts, src/app/entity-groups/journal-entities/item-grid-elements/journal-volume/journal-volume-grid-element.component.spec.ts, src/app/entity-groups/journal-entities/item-grid-elements/journal/journal-grid-element.component.spec.ts, src/app/entity-groups/research-entities/item-grid-elements/orgunit/orgunit-grid-element.component.spec.ts, src/app/entity-groups/research-entities/item-grid-elements/person/person-grid-element.component.spec.ts, src/app/entity-groups/research-entities/item-grid-elements/project/project-grid-element.component.spec.ts, src/app/shared/object-grid/item-grid-element/item-types/publication/publication-grid-element.component.spec.ts
This PR fixes travis tests that currently fail on master since the addition of #402 .
=> master travis test fixes

src/app/core/auth/auth.service.spec.ts, src/app/core/auth/auth.service.ts
Fixes https://github.com/DSpace/dspace-angular/issues/510
=> Prevent encoding of query after login redirect.

resources/i18n/cs.json5, resources/i18n/de.json5, resources/i18n/en.json5, resources/i18n/nl.json5
=> Fix translation

src/app/core/cache/models/normalized-item.model.ts
Fix for DS-4400 - Error with writing operations regarding Items
See: https://jira.lyrasis.org/browse/DS-4400
Can now edit metadata of person names (ex. dc.contributor.name).
=> [DS-4400] Fix for minor edit metadata bug

.travis.yml
=> Upgrade Travis image to 'bionic'

e2e/search-navbar/search-navbar.e2e-spec.ts, e2e/search-navbar/search-navbar.po.ts, e2e/search-page/search-page.po.ts, protractor.conf.js, src/app/app.module.ts, src/app/header/header.component.html, src/app/search-navbar/search-navbar.component.html, src/app/search-navbar/search-navbar.component.scss, src/app/search-navbar/search-navbar.component.spec.ts, src/app/search-navbar/search-navbar.component.ts, src/app/shared/animations/slide.ts
This PR adds an expandable search input box to the header. Expands by clicking the search icon; collapses at search or by clicking outside of the input box. Allows simple search queries from any page.
To test there is a spec file for the component and e2e tests.
=> Header search box

resources/i18n/en.json5
adding a missing relationships.isContributorOf entry to the translations file.
=> adding relationships.isContributorOf i18n support

config/environment.default.js, resources/i18n/nl.json5
Rebase of #557 + enabling Dutch by default
Tested with yarn run watch & yarn run start. I couldn't find any breaking changes.
=> Partial Dutch Translation by @muiltje

src/app/core/auth/auth-request.service.ts, src/app/core/auth/auth.actions.ts, src/app/core/auth/auth.effects.spec.ts, src/app/core/auth/auth.effects.ts, src/app/core/auth/auth.reducer.spec.ts, src/app/core/auth/auth.reducer.ts, src/app/core/auth/auth.service.spec.ts, src/app/core/auth/auth.service.ts, src/app/core/auth/server-auth.service.ts, src/app/shared/form/builder/parsers/field-parser.ts, src/app/shared/testing/auth-request-service-stub.ts, src/app/shared/testing/auth-service-stub.ts
This PR is to resolve https://github.com/DSpace/dspace-angular/issues/599 and https://github.com/DSpace/dspace-angular/issues/600
=> Issues#599 and issues#600 fixes

src/app/core/cache/builders/link.service.spec.ts, src/app/core/cache/builders/link.service.ts
Ensure the link resolver doesn't crash when a HALResource has a HALLink that isn't available on every instance
=> Allow optional HALLinks

src/app/+my-dspace-page/my-dspace-page.component.html, src/app/+my-dspace-page/my-dspace-page.component.ts, src/app/core/data/bitstream-data.service.ts, src/app/core/eperson/group-data.service.ts, src/app/core/shared/search/search.service.ts, src/app/core/tasks/models/claimed-task-object.model.ts, src/app/core/tasks/models/pool-task-object.model.ts, src/app/core/tasks/models/task-object.model.ts, src/app/entity-groups/research-entities/metadata-representations/org-unit/org-unit-item-metadata-list-element.component.spec.ts, src/app/shared/mydspace-actions/claimed-task/claimed-task-actions.component.html, src/app/shared/object-detail/my-dspace-result-detail-element/claimed-task-search-result/claimed-task-search-result-detail-element.component.html, src/app/shared/object-detail/my-dspace-result-detail-element/claimed-task-search-result/claimed-task-search-result-detail-element.component.spec.ts, src/app/shared/object-detail/my-dspace-result-detail-element/claimed-task-search-result/claimed-task-search-result-detail-element.component.ts, src/app/shared/object-detail/my-dspace-result-detail-element/item-detail-preview/item-detail-preview.component.html, src/app/shared/object-detail/my-dspace-result-detail-element/item-detail-preview/item-detail-preview.component.spec.ts, src/app/shared/object-detail/my-dspace-result-detail-element/item-detail-preview/item-detail-preview.component.ts, src/app/shared/object-detail/my-dspace-result-detail-element/pool-search-result/pool-search-result-detail-element.component.html, src/app/shared/object-detail/my-dspace-result-detail-element/pool-search-result/pool-search-result-detail-element.component.spec.ts, src/app/shared/object-detail/my-dspace-result-detail-element/pool-search-result/pool-search-result-detail-element.component.ts, src/app/shared/object-list/my-dspace-result-list-element/claimed-search-result/claimed-search-result-list-element.component.html, src/app/shared/object-list/my-dspace-result-list-element/claimed-search-result/claimed-search-result-list-element.component.spec.ts, src/app/shared/object-list/my-dspace-result-list-element/claimed-search-result/claimed-search-result-list-element.component.ts, src/app/shared/object-list/my-dspace-result-list-element/pool-search-result/pool-search-result-list-element.component.html, src/app/shared/object-list/my-dspace-result-list-element/pool-search-result/pool-search-result-list-element.component.spec.ts, src/app/shared/object-list/my-dspace-result-list-element/pool-search-result/pool-search-result-list-element.component.ts, src/app/submission/sections/form/section-form.component.spec.ts, src/app/submission/sections/form/section-form.component.ts
This PR resolves https://github.com/DSpace/dspace-angular/issues/603 and is based on work done in https://github.com/DSpace/dspace-angular/pull/594
=> #603 mydspace fixes

resources/i18n/en.json5, src/app/app-routing.module.ts, src/app/core/auth/auth.service.ts, src/app/core/cache/server-sync-buffer.effects.spec.ts, src/app/core/cache/server-sync-buffer.effects.ts, src/app/core/data/data.service.spec.ts, src/app/core/data/data.service.ts, src/app/core/data/dso-change-analyzer.service.ts, src/app/core/data/request.models.ts, src/app/core/eperson/eperson-data.service.ts, src/app/profile-page/profile-page-metadata-form/profile-page-metadata-form.component.html, src/app/profile-page/profile-page-metadata-form/profile-page-metadata-form.component.spec.ts, src/app/profile-page/profile-page-metadata-form/profile-page-metadata-form.component.ts, src/app/profile-page/profile-page-routing.module.ts, src/app/profile-page/profile-page-security-form/profile-page-security-form.component.html, src/app/profile-page/profile-page-security-form/profile-page-security-form.component.spec.ts, src/app/profile-page/profile-page-security-form/profile-page-security-form.component.ts, src/app/profile-page/profile-page.component.html, src/app/profile-page/profile-page.component.spec.ts, src/app/profile-page/profile-page.component.ts, src/app/profile-page/profile-page.module.ts, src/app/shared/auth-nav-menu/user-menu/user-menu.component.html, src/app/shared/auth-nav-menu/user-menu/user-menu.component.ts
This PR adds the manage profile page. You can reach it by clicking the Profile link in the header dropdown or by navigating to `/profile`.
=> Manage account profile

LICENSE, LICENSES_THIRD_PARTY
Adding official LICENSE and LICENSES_THIRD_PARTY files to this codebase, based on those in https://github.com/DSpace/DSpace
=> Add LICENSE info to this codebase

resources/i18n/de.json5
Just an update on the German translation
=> Update German Translation

config/environment.default.js, resources/i18n/lv.json5
Contribution to the Latvian translations of DSpace7
=> Latvian translations for DSpace 7

resources/i18n/ar.json5, resources/i18n/cs.json5, resources/i18n/de.json5, resources/i18n/es.json5, resources/i18n/fi.json5, resources/i18n/fr.json5, resources/i18n/ja.json5, resources/i18n/lv.json5, resources/i18n/nl.json5, resources/i18n/pl.json5, resources/i18n/pt.json5, resources/i18n/sw.json5, resources/i18n/tr.json5
Execution of the [i18n sync script](https://wiki.lyrasis.org/pages/viewpage.action?pageId=117735441#DSpace7TranslationInternationalization(i18n)Localization(l10n)-Syncingexistingtranslationswithchangestoen.json5) to bring the catalogs up to date with all recently added messages in en.json5
Because of the sheer size of this PR, I'm not comfortable merging this one without another review, even though it's i18n related.
=> Extending catalogs with missing messages April 9th

src/assets/i18n/fi.json5, src/environments/environment.common.ts
_Add references/links to any related tickets or PRs. These may include:_
* Link to [Angular issue or PR](https://github.com/DSpace/dspace-angular/issues) related to this PR, if any
* Link to [JIRA](https://jira.lyrasis.org/projects/DS/summary) ticket(s), if any
This includes Finnish translations after rebasing our fork from dspace master. There remains some keys to be translated.
* First, ...
* Second, ...
_This checklist …
=> Add Finnish translations (first set after master rebase)

src/app/+admin/admin-sidebar/expandable-admin-sidebar-section/expandable-admin-sidebar-section.component.scss, src/app/community-list-page/community-list-datasource.ts, src/app/community-list-page/community-list-service.spec.ts, src/app/community-list-page/community-list-service.ts, src/app/community-list-page/community-list/community-list.component.spec.ts, src/app/community-list-page/community-list/community-list.component.ts, src/app/core/cache/builders/remote-data-build.service.ts
* https://github.com/DSpace/dspace-angular/pull/505
We noticed some problems with the initial Community and Collection Tree implementation. This PR:
* Refactored the service/component/datasource so the service is stateless again
* Refactored the code so it builds the list page by page, instead of retrieving all objects at once from the server when you already have a few pages
* Resolved issues with observables
* Changes the variable determining Community/Collection pagesize in tree
* Simplifies the showMore node determination
* Adjusts the Tests for the applied changes
It's best to test this PR with a big community/collection tree (many root node, many child nodes)
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this …
=> Community and Collection Tree fixes

src/modules/app/browser-app.module.ts
This PR closes #754
I added `scrollPositionRestoration: 'enabled'` to the config of the router for browser-app.module.ts. ([docs](https://angular.io/api/router/ExtraOptions)). This should mimic the behavior of a browser when navigating back and forth different web pages.
You can test this by making your browser window very small, going to a page that doesn't fit the window, and clicking on an internal link at the bottom. You should see the top of the new page as you would if it were a regular html page.
* I added `scrollPositionRestoration: 'enabled'` to the config of the router for browser-app.module.ts
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR …
=> Reset scroll position on route change

src/app/shared/mocks/external-source.service.mock.ts, src/app/submission/import-external/import-external-searchbar/submission-import-external-searchbar.component.scss, src/app/submission/import-external/import-external-searchbar/submission-import-external-searchbar.component.ts, src/app/submission/import-external/submission-import-external.component.html, src/app/submission/import-external/submission-import-external.component.spec.ts, src/app/submission/import-external/submission-import-external.component.ts, src/assets/i18n/en.json5
This PR fixes small bugs present in the import from external source page : 
* Fix issues with route changing from and to the `/import-external`
* Fix issue with dropdown of the extenal providers that showed only the first 5 entries
to reproduce the test : 
- go to https://dspace7-demo.atmire.com/import-external page
- try to go back to mydspace page, the page should show an hanging loading icon. if redirecting to mydspace page works, you should have the same problem if you try to go again to `/import-external` page
- if open the dropdown menu you have only 5 entries even if the total entries are more than 5 
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always …
=> miscellaneous fixes for import from external source page

src/assets/i18n/hu.json5, src/environments/environment.common.ts
Create a new file for Hungarian translation and translate it, bases on latest en.json5 file.
=> Add Hungarian translation

src/assets/i18n/de.json5
Provide missing german translations. Some translations are still missing.
=> German translation fixes

src/assets/i18n/lv.json5
=> latvian translation update

src/app/+import-external-page/import-external-page.module.ts, src/app/core/data/comcol-data.service.spec.ts
* Fixes #997 
Go to the the import external page and verify that the error reported in the issue no longer occurs
=> Fix issue with import from external source page

src/app/app.component.spec.ts, src/app/app.component.ts, src/app/statistics/google-analytics.service.spec.ts, src/app/statistics/google-analytics.service.ts, src/config/global-config.interface.ts, src/environments/environment.common.ts, src/environments/mock-environment.ts, src/main.browser.ts, src/modules/app/browser-app.module.ts
* Fixes #244 
* Requires DSpace/DSpace#2762
Create `GoogleAnalyticsService` with `addTrackingIdToPage` method. It fetches `google.analytics.key` from the REST endpoint and adds it to the page. 
* remove `gaTrackingId` from config (not relevant anymore)
* remove `addGoogleAnalytics()` in `main.browser.ts` (not relevant anymore)
* create `GoogleAnalyticsService`
* provided in `browser-app.module.ts` (i.e. service active only on client side)
* create `addTrackingIdToPage` method
* tracking snippet modified to use js template literals
* call `addTrackingIdToPage` in `AppComponent` (only if service has been provided)
* unit test `GoogleAnalyticsService` and `AppComponent`
* factored out TestBed config of `AppComponent` such that it can be overridden in certain tests …
=> W2p 76634 google analytics tracking id from backend

src/assets/i18n/hu.json5
Translate newly added English lines to Hungarian
=> Translate new lines to Hungarian

src/assets/i18n/ar.json5, src/assets/i18n/cs.json5, src/assets/i18n/de.json5, src/assets/i18n/es.json5, src/assets/i18n/fi.json5, src/assets/i18n/fr.json5, src/assets/i18n/hu.json5, src/assets/i18n/ja.json5, src/assets/i18n/lv.json5, src/assets/i18n/nl.json5, src/assets/i18n/pl.json5, src/assets/i18n/pt-BR.json5, src/assets/i18n/pt-PT.json5, src/assets/i18n/sw.json5, src/assets/i18n/tr.json5
Applied the [sync-i18n](https://wiki.lyrasis.org/pages/viewpage.action?pageId=117735441#DSpace7TranslationInternationalization(i18n)Localization(l10n)-Syncingexistingtranslationswithchangestoen.json5) script to bring the catalogs with translations up to date with the latest contents of en.json5.
* First, ...
* Second, ...
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not …
=> Sync up translations with latest changes to en.json5

src/app/shared/mocks/submission.mock.ts, src/app/shared/uploader/uploader.component.html, src/app/shared/uploader/uploader.component.ts, src/app/submission/form/submission-form.component.html, src/app/submission/form/submission-form.component.spec.ts, src/app/submission/form/submission-form.component.ts, src/app/submission/sections/sections.service.spec.ts, src/app/submission/sections/sections.service.ts
This is a newer version of #1053, without [the issue that broke the submission form](https://github.com/DSpace/dspace-angular/pull/1053#issuecomment-812728007).
Like #1053, this PR closes #849 and #957
=> Submission dropzone issues [Fixed]

.github/workflows/build.yml, e2e/protractor-ci.conf.js, package.json
* Alternative to #1097
Alternative attempt to sync webdriver and chrome. This time using the chromedriver npm package
=> Sync webdriver and chrome versions

src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/external-source-tab/dynamic-lookup-relation-external-source-tab.component.html, src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/external-source-tab/dynamic-lookup-relation-external-source-tab.component.spec.ts, src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/external-source-tab/dynamic-lookup-relation-external-source-tab.component.ts, src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/search-tab/dynamic-lookup-relation-search-tab.component.spec.ts, src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/search-tab/dynamic-lookup-relation-search-tab.component.ts, src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/selection-tab/dynamic-lookup-relation-selection-tab.component.html, src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/selection-tab/dynamic-lookup-relation-selection-tab.component.spec.ts, src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/selection-tab/dynamic-lookup-relation-selection-tab.component.ts
Fixes #1117
This PR fixes the pagination in the author lookup window for the different tabs.
* Login as an Admin
* Start a new Submission to the “Articles” collection (or any collection which has Publication Entities enabled)
* Click the Lookup button next to the “Author” field
* Look up an author in the first tab and verify that the pagination works correctly
* Click on the ORCID tab & run a search with many results (e.g. “Donohue”)
* Verify that the pagination works correctly by navigating through the pages
=> Fix pagination in author lookup window

src/assets/i18n/fr.json5
Since new EN wordings were added since the first version of the FR wordings, these wordings were to be translated in `fr.json5`.
No other files than `fr.json5` are modified in this PR.
=> Updated version of the FR wordings

src/app/+collection-page/delete-collection-page/delete-collection-page.component.html
Fixes #1231 
This is a tiny PR to fix incorrect i18n tags. I've tested it and it fixes the issue.
=> Fix incorrect i18n tags in Collection Delete page

src/app/admin/admin-search-page/admin-search.module.ts, src/app/admin/admin-workflow-page/admin-workflow.module.ts, src/app/admin/admin.module.ts, src/app/browse-by/browse-by.module.ts, src/app/entity-groups/journal-entities/journal-entities.module.ts, src/app/entity-groups/research-entities/research-entities.module.ts, src/app/item-page/item-page.module.ts, src/app/my-dspace-page/my-dspace-search.module.ts, src/app/navbar/navbar.module.ts, src/app/shared/shared.module.ts, src/app/submission/submission.module.ts
* Fixes #1450
This PR fix issue on Submission UI with SSR
Check the issue described in #1450 is resolved
=> Fix SSR issue with submission after migrate to angular 11

README.md
=> Minor readme configuration corrections

src/app/core/shared/search/search-configuration.service.ts, src/app/shared/search/models/paginated-search-options.model.ts
* Fixes #1499
fixes bug reported in the #1499
check if bug reported is resolved
=> Fix issue with grid view mode

src/app/item-page/edit-item-page/item-delete/item-delete.component.spec.ts, src/app/item-page/edit-item-page/item-delete/item-delete.component.ts
* Fixes #1501
* Fixes #1082 
* Fixes #1481 
The issue only occurred when the  `dspace.entity.type` field was present but empty or invalid.
The reason entity types are involved here is because we have code to save relationships as metadata when an item gets deleted (e.g. if you delete a Person you get the option to save that Person's name as plain text metadata in the related publications)
If there was an entity type metadata field, but no valid entity type was found [this subscribe](https://github.com/DSpace/dspace-angular/blob/74a6e3ce6a59b22f96d7ba491132627423381215/src/app/item-page/edit-item-page/item-delete/item-delete.component.ts#L345-L351) would never fire, and the delete wouldn't happen.
This PR fixes that by turning the types$ observable into a behaviorsubject and initializing …
=> Fix deleting an item with an empty or invalid entity type

src/app/core/auth/models/auth.method-type.ts, src/app/core/auth/models/auth.method.ts, src/app/shared/log-in/methods/oidc/log-in-oidc.component.html, src/app/shared/log-in/methods/oidc/log-in-oidc.component.spec.ts, src/app/shared/log-in/methods/oidc/log-in-oidc.component.ts, src/app/shared/shared.module.ts, src/assets/i18n/en.json5
* Fixes DSpace/DSpace#8087
* Requires DSpace/DSpace#8088 be applied to backend
Adds UI elements to support OIDC (OpenID Connect) logins in DSpace-Angular. This code is a direct port of the OIDC code from DSpace-CRIS 7.
You must have the changes in DSpace/DSpace#8088 applied to the REST-API you're using to test, and you must have an OIDC provider of some sort available and configured to work with your REST-API server (see docs on DSpace/DSpace#8088). 
* src/app/core/auth/models/auth.method-type.ts
* src/app/core/auth/models/auth.method.ts
* src/app/shared/log-in/methods/oidc/log-in-oidc.component.html
* src/app/shared/log-in/methods/oidc/log-in-oidc.component.spec.ts
* src/app/shared/log-in/methods/oidc/log-in-oidc.component.ts
* src/app/shared/shared.module.ts …
=> Port OIDC (OpenID Connect) auth plugin from DSpace-CRIS

src/assets/i18n/gd.json5
Translated and proofed by Stòrlann Nàiseanta na Gàidhlig.
None
Translations into Scottish Gaelic have been made by staff at Stòrlann as part of their migration from DSpace 5.x to DSpace 7.x. They are offered to the community in hopes they will be useful.
All strings have been translated and then checked by a second reviewer. However, there may still be typos, and there may be instances where the translation is incorrect (sometimes the context in which the original phrase was used could not be determined, and this may affect, for example, whether it is used as a command or as a title.)
For testing, note that the language code for Scottish Gaelic is "gd" and the language label should be "Gàidhlig".
File has been run against the yarn json5 validator and passes. If there is anything else …
=> Full Scottish Gaelic translation.

config/config.example.yml, src/config/default-app-config.ts
Enable new Scottish Gaelic translation, see #1508
=> Enable Scottish Gaelic

src/assets/i18n/fr.json5
Hi!
A few parameters were missing in the fr.json5, I have added them and provided a french translation for each.
Thanks!
=> Adding missing parameters to fr.json5 

src/assets/i18n/de.json5
also corrected comment search.search-form.placeholder --> home.search-form.placeholder
=> Updated German translation

src/assets/i18n/tr.json5
Hi everyone. As İstanbul Technical University IT Office, we have translated ui to Turkish.
* Fixes #[issue-number]
* Requires DSpace/DSpace#[pr-number] (if a REST API PR is required to test this)
* First, ...
* Second, ...
_This checklist provides a reminder of what we are going to look for when reviewing your PR. …
=> Turkish Translation

src/assets/i18n/en.json5
Fixes https://github.com/DSpace/DSpace/issues/3359
In this PR I have add all the missing i18n keys.
see comment also: https://github.com/DSpace/DSpace/pull/8237#pullrequestreview-969893725
=> [CST-5303] Live Import providers i18n keys

src/assets/i18n/de.json5
Added several missing translation keys in German i18n resource file.
=> added missing German translations

src/assets/i18n/de.json5
The PR fixes a minor typo in `de.json5` (Deposit licence step in submission form).
=> fixed minor typo in German translation

src/app/shared/object-list/my-dspace-result-list-element/item-list-preview/item-list-preview.component.html
* Fixes #1730
fix missing space between author names MyDspace our submissions
Added one line in src/app/shared/object-list/my-dspace-result-list-element/item-list-preview/item-list-preview.component.html
Line 22 <span *ngIf="!last">; </span>
The same step to reproduce the bug in bug report
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If …
=> fix missing space between author names MyDspace our submissions #1730

src/styles/_bootstrap_variables.scss
- adds enable-responsive-font-sizes toggle to the main bootstrap
variables scss file
- [docs available](https://getbootstrap.com/docs/4.4/content/typography/#responsive-font-sizes)
* discussed on DSpace slack, tested by myself and @mspalti 
This PR adds the enable-responsive-font-sizes toggle to the main bootstrap variables scss file, and toggles it on.
You'll need a phone to really test this change, compare the home page type with and without this toggle turned on. With it on, the home page content better fits the phone's viewport, and is thus more usable.
* adds the enable-responsive-font-sizes toggle to the main bootstrap variables scss file, and toggles it on
**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, …
=> Enable responsive font sizes

src/assets/i18n/es.json5
Spanish translation updated and improved, all new missing messages from english translation included.
* es.json5 updated
=> Spanish translation updated

config/config.example.yml
* Fixes #1843 
Provides the correct YAML configuration for configuring the default bundles configuration.
* Provides the correct YAML configuration for configuring the default bundles configuration.
See Steps in https://github.com/DSpace/dspace-angular/issues/1843:
1) Checkout the codebase, and this pull request, following the "Quick start" instructions in the "README.md" file:
```
git clone https://github.com/DSpace/dspace-angular.git
cd dspace-angular
git fetch origin pull/1844/head:pull1844
git checkout pull1844
```
2) Edit the "config/config.yml" file:
```
vi config/config.yml …
```
=> Issue 1843 - Fix default bundles example in config.example.yml

src/assets/i18n/pt-BR.json5
Just a translation update.
I synchronized the Brazilian Portuguese language translation file with the latest en.json5 file and also updated some lines of translations.
=> Updated the Brazilian Portuguese translation.

src/app/register-page/create-profile/create-profile.component.ts
* Partially Fixes #[1859](https://github.com/DSpace/dspace-angular/issues/1859)
* Requires DSpace/DSpace#[8492](https://github.com/DSpace/DSpace/pull/8492) 
UI has been updated in order to show message coming from REST backend in case password does not meet minimum security requirements.
=> Registration page password validation

src/assets/i18n/fr.json5
Addition of missing parameters for french translations.
=> Adding missing language parameters in french translations file (fr.json5)

src/assets/i18n/pt-BR.json5
Add missing keywords, and correct translations in pt-BR
=> Add missing translations in version 7.4 pt-BR

src/assets/i18n/pt-BR.json5
Ficheiro is used only in pt-PT in pt-BR is used arquivo
=> Update pt-BR to replace ficheiro (pt-PT)

src/assets/i18n/kk.json5
* Fixes #[issue-number]
* Requires DSpace/DSpace#[pr-number] (if a REST API PR is required to test this)
* First, ...
* Second, ...
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always …
=> Kazakh Translations

.github/workflows/build.yml, .github/workflows/docker.yml, .github/workflows/issue_opened.yml, .github/workflows/label_merge_conflicts.yml
Applies the changes in https://github.com/DSpace/DSpace/pull/8559 from @sashashura to this `dspace-angular` repository.
See that ticket for more details.
=> GitHub Workflows security hardening (for dspace-angular)

src/assets/i18n/en.json5, src/assets/i18n/es.json5, src/assets/i18n/hi.json5, src/assets/i18n/kk.json5, src/assets/i18n/pt-BR.json5
* Fixes health page typo
We have found minor typos in Healt page's labels, this little PR fixes them
* updated i18n files with correct labels
=> Fix Health section labels

.github/workflows/build.yml, .github/workflows/docker.yml
Small PR to ensure we are running the latest version of all GitHub actions.
Seeing some random-ish CodeCov issues which may be the result of an older version of that action. Decided to upgrade everything at once.
**Assuming this passes all our CI checks**, then I'll merge this immediately.
=> Update to the latest version of all GitHub actions

src/app/shared/cookies/browser-klaro.service.ts
* Fixes https://github.com/DSpace/dspace-angular/issues/2027
* Changed the import used for Klaro back to `'klaro/dist/klaro-no-translations'`
* Removed a sneaky `console.log` 
Confirm that Klaro uses DSpace i18n messages once again.
=> Fix Klaro i18n messages

src/app/browse-by/browse-by-date-page/browse-by-date-page.component.ts, src/app/browse-by/browse-by-metadata-page/browse-by-metadata-page.component.html, src/app/browse-by/browse-by-metadata-page/browse-by-metadata-page.component.spec.ts, src/app/browse-by/browse-by-metadata-page/browse-by-metadata-page.component.ts, src/app/browse-by/browse-by-title-page/browse-by-title-page.component.ts
* Fixes #2046 
With this pull request, the Community/Collection logo is shown while browsing results.
* Added the `<ds-comcol-page-logo>` component in `browse-by-metadata-page.component.html`;
* Created the `updateLogo` method in `browse-by-metadata-page.component`. This method updates the newly created `logo$` observable;
* Called `updateLogo()` right after `updateParent(...)` in `browse-by-metadata-page.component` and other components that extend it.
You can find all steps to reproduce the bug on the linked issue.
=> CST-8165 show logo when browsing collections

src/app/core/metadata/metadata.service.spec.ts, src/app/core/metadata/metadata.service.ts
* Fixes https://github.com/DSpace/DSpace/issues/8648
Changes the code that generates the citation_pdf_url meta tag to only check the first page of bitstreams for one with an appropriate format, when there's no primary bitstream and there's more than one. 
It will stop once it finds one that matches.
I also set the page size used for this to the value of `item.bitstream.pageSize` in the config (rather than the rest's default of 20 if you leave out the page size) to further improve the performance, and make it match what's rendered on the page exactly.
Verify that for items with a lot of bitstreams (I used https://demo7.dspace.org/items/48f53b51-2721-4aea-8165-636b219aa2f2 to test this) the performance issue is gone, …
=> Only check 1 page of bitstreams when generating the citation_pdf_url tag

src/assets/i18n/es.json5
This PR completes the current spanish translation, corrects some typos, spaces and improve some translations. 
=> Update spanish translation

config/config.example.yml, src/assets/i18n/ca.json5, src/config/default-app-config.ts
Add a first complete version of Catalan translation and enable it by default.
=> Catalan translation

src/assets/i18n/de.json5
Fixed some German translation in `de.json5`.
* some translation keys were **added**
* some obsolete translation keys which are not present in `en.json5` were **removed**
=> German translation fixes in security form

src/app/shared/input-suggestions/dso-input-suggestions/dso-input-suggestions.component.html, src/app/shared/shared.module.ts
Hello @tdonohue i alredy worked on this task and i hope this can be worth for this issue. I will be attentive 👍 
* Fixes #2101 
I added a the suggestion option text to display them in bistream upload.
i just added the suggestionOption.name in the bitstream upload section.
* suggestionOption.name in _dso-input-suggestions.component.html_
1. login as Admin
2. edit any input
3. go to bitstreams section
4. click on upload bitstream section
5. select a Bundle.
6. You will see that the bundle names is displayed.
=> Fix for "No option appears for Bundle when the user is loading a bitstream of an item"

src/app/access-control/epeople-registry/eperson-form/eperson-form.component.spec.ts, src/app/access-control/epeople-registry/eperson-form/eperson-form.component.ts
* Fixes DSpace/DSpace#8670
* This PR fixes a small issue with @atarix83 's #2104, so it includes the commit in that PR as well.
Fixes the issue described in DSpace/DSpace#8670
I've tested this locally and it works for me.  @atarix83 's #2104 PR was nearly correct, and this provides a minor fix to it.
=> Fix issue with admin reset password functionality

src/app/access-control/epeople-registry/eperson-form/eperson-form.component.spec.ts, src/app/access-control/epeople-registry/eperson-form/eperson-form.component.ts
* Fixes #[8670](https://github.com/DSpace/DSpace/issues/8670)
Check if the bug reported is fixed
=> [CST-8952] Fix issue with admin reset password functionality

src/app/item-page/simple/field-components/file-section/file-section.component.html, src/app/shared/file-download-link/file-download-link.component.html, src/app/shared/object-list/search-result-list-element/item-search-result/item-types/item/item-search-result-list-element.component.html
* Fixes #2087
* Fixes #2088
This PR fixes two small UI problems.
- If there's no issue date, but there is a publisher no comma should be rendered for publication search results
- Added some spacing between a file name and the lock icon
* Create publications with a publisher without an issue date and make sure the comma isn't there anymore:
* Also view an item page with a file you don't have access to. Make sure the lock icon isn't stuck to the file name anymore:
=> Fixed UI issues #2087 and #2088

src/app/shared/form/builder/ds-dynamic-form-ui/models/array-group/dynamic-form-array.component.html
Hello @tdonohue ✋ . i have been working on this task. i hope it is for worth, i will be attentive for any comments.
* Fixes #2089 
User can be select the text inside the input field when the input has repeatable submission fields.
The only way to achieve this activity was to avoid the drag and drop functionality within the inputs and make it available for the icon only.
* i moved the cdkDragHandle from the parent div to the child div which has the drag and drop icon.
* The div which has the input now cannot be dragged.
1. Login.
2. create a new item
3. create 2 or more options for any multiple input.
4. try to drag and drop using the drag and drop icon. you should be able to drag it.
5. Try to drag and drop the input, you should not be able to drag it.
6. Try …
=> avoiding drag and drop in put for multiple select option

src/assets/i18n/es.json5
N/A
Contribution to spanish translation
This is an update to spanish translation.
* First, ...
* Second, ...
=> Spanish translation contribution

src/app/bitstream-page/edit-bitstream-page/edit-bitstream-page.component.ts
Removes metadata field entry dc.description from the bitstream's metadata
* Fixes #1612
The change in the commit deletes the key for 'dc.description' for updated metadata's hashmap if no value is entered on the bitstream edit page.
* Edit any bitstream via the Edit item section
* Clear the description
* Check via the API HAL browser for the api - /server/api/core/bitstreams/da4dec13-67dc-4aaa-8297-2f7d0ffb255c or /server/api/core/bitstreams/{bitstream_id}
* and _if-else_ statement has been added in 'edit-bitstream-page.component.ts' file.
**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, screenshots or description of a new feature, or …
=>  Fixed: Clear metadata if value has not set. Reference issue no #1612

src/assets/i18n/hu.json5
Improve translation
* Fixes #`issue-number` (if this fixes an issue ticket)
* Requires DSpace/DSpace#`pr-number` (if a REST API PR is required to test this)
* First, ...
* Second, ...
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist …
=> Update hu language file with dspace7.5 strings

src/assets/i18n/fr.json5
Add translations for the System wide alert feature as well other various missing parameters.
=> Update to fixe french labels for System-wide alert

src/assets/i18n/fr.json5
Adding corrections suggested in the following PR review: https://github.com/DSpace/dspace-angular/pull/2154
=> Small updates to french translations

src/main.browser.ts
=> DS-2077: removes external Google font

config/config.example.yml, src/assets/i18n/it.json5, src/config/default-app-config.ts
* Fixes #1917
* Italian language support
* First bunch of translations
=> Italian language

src/assets/i18n/en.json5
Add i18n English string for publisher in live import item preview.
* Requires: https://github.com/DSpace/DSpace/pull/8866
Add one new English string for publisher, used in the CrossRef live import item preview.
Test the CrossRef live import function to see if the new string appears properly in the item preview popup.
=> src/assets: add i18n string for publisher

src/app/core/data/bitstream-data.service.spec.ts, src/app/core/data/bitstream-data.service.ts, src/app/item-page/edit-item-page/item-bitstreams/item-bitstreams.component.spec.ts, src/app/item-page/edit-item-page/item-bitstreams/item-bitstreams.component.ts, src/app/shared/testing/bitstream-data-service.stub.ts
- Fixes https://github.com/DSpace/DSpace/issues/8029
- Requires https://github.com/DSpace/DSpace/pull/8485
- REST Contract https://github.com/DSpace/RestContract/pull/203
- Related #2173 (by changing the endpoint this issue could potentially be closed)
This PR only switches the endpoint that is used for deleting bitstreams to the `PATCH` endpoint
* Added a new method `removeMultiple` to `BitstreamDataService` which requires a list of Bitstreams
* Used the new `BitstreamDataService#removeMultiple` in `ItemBitstreamsComponent`
**Guidance for how to test this PR:**
- Add multiple bitstreams to an item in multiple Bundles
- Check that you can delete multiple Bitstreams at once even when they are in different Bundles
- Check that you are also still able to remove …
=> Fix multiple bitstream deletion not working

src/assets/i18n/en.json5
Normalize whitespace in i18n/en.json5. This file should be clean, as it is the "upstream" of all other language assets and produces a lot of whitespace changes every time strings are merged. This causes merge conflicts during rebases for sites that are maintaining custom themes in git.
I did this by copying the stock `en.json5` to the custom theme and then merging it against itself:
```console
$ cp src/assets/i18n/en.json5 src/themes/custom/assets/i18n
$ yarn merge-i18n -s src/themes/custom/assets/i18n
```
There are no changes to any strings themselves—only whitespace.
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in …
=> src/assets/i18n/en.json5: lint

src/assets/i18n/fi.json5
Add a few Finnish language UI strings. In the interest of time and at @reetagithub's request, I am making a new PR with Reeta's changes to help resolve the whitespace conflicts.
- Obsoletes #2303
=> src/assets: update fi.json5

src/app/community-list-page/community-list/community-list.component.html, src/app/core/shared/collection.model.ts, src/app/core/shared/community.model.ts, src/app/shared/object-list/collection-list-element/collection-list-element.component.html, src/app/shared/object-list/collection-list-element/collection-list-element.component.spec.ts, src/app/shared/object-list/community-list-element/community-list-element.component.html
* Fixes #1787
* Requires DSpace/DSpace#8843
Displaying item counts at Communities  views. It uses a new field from Collection and Community models. 
* Extending Collection and Community models
* Displaying items counts at /community-list and /communities views
To test it you should create at least one item in collection. Expected behaviour is to show item counts for communities and collections:
=> Displaying item counts at Communities and Collections list view.

src/assets/i18n/en.json5
Fix what I believe is a typo of "Serial"
=> Fix typo for the word Series

src/assets/i18n/en.json5
Re-word two messages for better English and consistency with other similar strings.
For example, on the homepage we say "Communities **in** DSpace":
<p align="center">
</p>
... but on the sub-community pages we say "Communities **of** _community name_" and "Collections **of** _community name_":
<p align="center">
</p>
It sounds more natural in English to say "in", and is more consistent with the language on the homepage.
Build and run the application to see if the new strings appear on sub-community pages.
* Update two English strings
_This checklist provides a reminder of what we …
=> src/assets/i18n: update English strings

src/app/collection-page/collection-form/collection-form.component.ts
* Replaces #2329 
* Fixes https://github.com/DSpace/DSpace/issues/8911
`ngOnInit()` is implemented for `collection-form.component.ts `.
* First, the `ngOnInit()` is implemented for `src/app/collection-page/collection-form/collection-form.component.ts`. When a collection is edited, `ngOnChanges` is called before `ngOnInit`, so on `ngOnInit` we need to check if the `formModel` is already initialized and if it is not, we need to initialize it. We also need to check the `dso`  to be different from null in order to initialize the form.
Steps to reproduce a bug are the same as mentioned in #2329.
=> "Add Collection"  form loads

src/app/request-copy/deny-request-copy/themed-deny-request-copy.component.ts
* Fixes https://github.com/DSpace/dspace-angular/issues/2351
The themed-deny-request-copy.component erroneously includes the custom theme's deny-request-copy component instead of its own. This _appears_ to work, but breaks when the custom theme is missing (and of course the application should not be relying on the custom theme at all).
Build the application and see if the deny request copy functionality is working as expected (including the themed component in the custom theme).
* Fix path to `deny-request-copy.component`
=> src/app: fix path to deny-request-copy component

src/assets/i18n/fi.json5
Contributed by Reeta Kuukoski from the National Library of Finland. Consolidated from previous pull request:
- #2342
* Updated Finnish language strings
Build the Angular UI and check to make sure the Finnish UI strings load and display properly.
=> src/assets/i18n: update Finnish language strings

src/app/item-page/simple/item-types/shared/item-relationships-utils.ts
If one or more related items in a list (eg. left items displayed on their corresponding right item's page) cannot be retrieved for some reason (for instance, authZ policies mean a 401 response for some people, or some other issue prevents a successful 200 response with good payload), the function that converts the relations to items will not continue to process the rest of the list.
This pull request might need more work - it is my first attempt at mitigating the problems / assumptions introduced by `getFirstSucceededRemoteDataPayload`. There may be more elegant ways of handling this, and we should write some new spec tests to prove the old way fails and the new way doesn't.
* Have 2-5 relationships between items eg. author and publication or project and publication
* Make sure each item …
=> Catch and handle unsuccessful "convert rels to items" responses

src/app/process-page/detail/process-detail.component.spec.ts
Port of #2408 by @Atmire-Kristof to `dspace-7_x`
=> [Port dspace-7_x] ProcessDetailComponent test improvement

src/app/shared/theme-support/theme.service.ts, src/app/shared/theme-support/themed.component.ts, src/config/config.util.ts
(Manual) Port of #2395 by @alexandrevryghem to `dspace-7_x`.
For this port I had to filter out all merge commits *except* for one, see 8b57a2f6af9b779189640033d3cf20945be4cf63 This merge commit appears to be from a separate branch & was necessary to apply to ensure all the code changes in the original PR were copied to this one.
=> [Port dspace-7_x] Fix themed components duplicating themself when switching themes

src/assets/i18n/es.json5
* Fixes https://github.com/DSpace/DSpace/issues/9002
New spanish translation updated to 7.6
=> Spanish translation updated to 7.6

package.json, server.ts, yarn.lock
When dspace-angular is stopped, it just dies.  This is unfriendly to clients and leads to error reports from monitoring applications.  This patch handles SIGINT signals sent by typing ^C or telling PM2 to stop a process, sending flow control headers to the client and properly closing the HTTP(S) server at the end of any in-progress request.  In particular this should give reverse proxies better information about the state of a persistent connection.
* Set up a "terminator" object to manage the server.
* Catch SIGINT and initiate shutdown.
**Include guidance for how to test or review your PR.** This may …
=> Graceful shutdown on SIGINT (e.g. from 'pm2 stop').

src/assets/i18n/de.json5
Minor translation with reference to #1199 
Minor translation for the German language.
This changes the German translation only. This doesn't contain any code changes.
=> Translate community as 'Bereich' in de.json5

src/app/navbar/navbar.component.html, src/app/shared/auth-nav-menu/auth-nav-menu.component.html, src/app/shared/auth-nav-menu/auth-nav-menu.component.spec.ts, src/app/shared/auth-nav-menu/user-menu/themed-user-menu.component.ts, src/app/shared/shared.module.ts, src/themes/custom/app/shared/auth-nav-menu/user-menu/user-menu.component.ts, src/themes/custom/lazy-theme.module.ts
Manual port of #2362 by @Leano1998 to `dspace-7_x`
=> [Port dspace-7_x] Making user menu component themeable

src/app/item-page/edit-item-page/item-move/item-move.component.html, src/assets/i18n/en.json5
* Required by REST PR: https://github.com/DSpace/DSpace/pull/9019
Adds a tooltip to the "Inherit policies" checkbox on the "item move" page informing the user about the meaning of this option and warning them that the operation cannot be undone.
* In `ItemMoveComponent` template: Adds a tooltip to `inheritPoliciesCheckbox`. 
* Visit the item move page and hover over the "Inherit policies" checkbox to verify that the tooltip shows up.
=> Fix inherit policies at item move (Angular)

src/app/browse-by/browse-by-date-page/browse-by-date-page.component.ts, src/app/browse-by/browse-by-metadata-page/browse-by-metadata-page.component.html, src/app/browse-by/browse-by.module.ts, src/app/forgot-password/forgot-password-email/forgot-email.component.html, src/app/home-page/recent-item-list/recent-item-list.component.html, src/app/login-page/login-page.component.html, src/app/navbar/navbar.component.scss, src/app/register-email-form/register-email-form.module.ts, src/app/register-email-form/themed-registry-email-form.component.ts, src/app/register-page/register-email/register-email.component.html, src/app/shared/auth-nav-menu/auth-nav-menu.component.html, src/app/shared/browse-by/shared-browse-by.module.ts, src/app/shared/browse-by/themed-browse-by.component.ts, src/app/shared/log-in/log-in.component.spec.ts, src/app/shared/log-in/themed-log-in.component.ts, src/app/shared/search/search-filters/search-filter/search-filter.component.html, src/app/shared/search/search-filters/search-filter/search-filter.component.scss, src/app/shared/shared.module.ts, src/app/submission/sections/cc-license/submission-section-cc-licenses.component.html, src/themes/custom/app/entity-groups/research-entities/item-pages/person/person.component.ts, src/themes/custom/app/login-page/login-page.component.html, src/themes/custom/app/register-email-form/register-email-form.component.ts, src/themes/custom/app/shared/browse-by/browse-by.component.ts, src/themes/custom/app/shared/log-in/log-in.component.ts, src/themes/custom/app/shared/object-list/browse-entry-list-element/browse-entry-list-element.component.ts, src/themes/custom/eager-theme.module.ts, src/themes/custom/lazy-theme.module.ts, src/themes/dspace/app/navbar/navbar.component.scss
Manual port of #2442 by @alexandrevryghem to `dspace-7_x`
=> [Port dspace-7_x] New themed components & minor CSS fixes

src/assets/i18n/pt-BR.json5
Fix and update the pt-BR language file
None
Fix and update the pt-BR language file
* Many to list, but only in dspace-angular/src/assets/i18n/pt-BR.json5 file.
=> fix(pt-BR.json5): fix and update the language file

src/app/item-page/mirador-viewer/mirador-viewer.component.ts
Prepend name space to Mirador viewer path.
Deploy under a context path using `ui.nameSpace` other than `/`.
=> Add UI nameSpace context path to Mirador viewer path

src/app/info/feedback/feedback-form/feedback-form.component.html, src/app/root/root.component.html, src/app/root/root.component.scss, src/app/root/root.component.ts, src/assets/i18n/en.json5, src/styles/_global-styles.scss
Manual port of #2607 by @alexandrevryghem to `dspace-7_x`.
=> [Port dspace-7_x] Added skip to main content button

src/app/shared/form/builder/ds-dynamic-form-ui/ds-dynamic-form-control-container.component.spec.ts, src/app/shared/form/builder/ds-dynamic-form-ui/models/date-picker/date-picker.component.html, src/app/shared/form/builder/ds-dynamic-form-ui/models/date-picker/date-picker.component.spec.ts, src/app/shared/form/builder/ds-dynamic-form-ui/models/date-picker/date-picker.model.ts, src/app/shared/form/builder/form-builder.service.spec.ts
Manual port of #2620 by @LotteHofstede to `dspace-7_x`
=> [Port dspace-7_x] Fix for repeatable date field labels

src/app/shared/menu/menu.component.spec.ts, src/app/shared/menu/menu.component.ts, src/app/shared/menu/menu.service.ts
Manual port of #2610 by @alexandrevryghem to `dspace-7_x`
=> [Port dspace-7_x] Fixed menu not updating when a new sub section is added after rendering has already completed

src/assets/i18n/de.json5
This PR adds missing German translation of all feedback page translation keys.
=> German translations of feedback page translation keys

src/assets/i18n/en.json5
* Requires DSpace/DSpace#9132
Add translation key
=> Add translation for DOI multiple parallel import source.

src/app/home-page/home-news/home-news.component.html, src/themes/dspace/app/home-page/home-news/home-news.component.html
Just changing the name presented in the homepage to be DSpace 8.
=> Renaming DSpace to DSpace 8

package.json, yarn.lock
Manual port of #2881 by @dependabot  to dspace-7_x.
=> [Port dspace-7_x] Bump express from 4.18.2 to 4.19.2

yarn.lock
Manual port of #2894 by @dependabot to `dspace-7_x`
=> [Port dspace-7_x] Bump axios to 1.6.8

.github/workflows/build.yml, .github/workflows/issue_opened.yml, .github/workflows/pull_request_opened.yml
Manual port of #2910 to `dspace-7_x`
=> [Port dspace-7_x] Update all GitHub Actions & add token for Codecov.io

src/app/shared/comcol/comcol-forms/edit-comcol-page/comcol-role/comcol-role.component.html
* Fixes #`issue-number` (if this fixes an issue ticket)
* Requires DSpace/DSpace#`pr-number` (if a REST API PR is required to test this)
* First, ...
* Second, ...
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your …
=> typo in role name

src/app/lookup-by-id/objectnotfound/objectnotfound.component.spec.ts, src/app/lookup-by-id/objectnotfound/objectnotfound.component.ts
Manual port of #2816 by @jensvannerum to `dspace-7_x`
=> [Port dspace-7_x] Return 404 Not Found status code on missing identifiers

src/app/shared/search/search-labels/search-label/search-label.component.html, src/app/shared/search/search-labels/search-label/search-label.component.scss, src/app/shared/search/search-labels/search-label/search-label.component.ts, src/app/shared/search/search-labels/search-labels.component.html, src/app/shared/search/search-labels/search-labels.component.scss, src/app/shared/search/search.component.html
Manual port of #2675 by @LotteHofstede to `dspace-7_x`
=> [Port to dspace-7_x] Multiline selected facet badge on search page 

src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.html, src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.spec.ts, src/assets/i18n/en.json5
This PR adds an option to dropdown to clear your previously selected value, this was previously not possible
This PR adds a section to each dropdown rendered showing an option to clear the value
It can be tested in the submission process of an item by selecting a value, clearing it an submitting the item.
- Verify no value for that metadata was added
=> Reset dropdown values

src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.html, src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.spec.ts, src/assets/i18n/en.json5
Manual port of #2933 by @jensvannerum to `dspace-7_x`
=> [Port dspace-7_x] Reset dropdown values 

config/config.example.yml, src/assets/i18n/ar.json5
Manual Port of #2863 by @mohamedali654321 to `dspace-7_x`
=> [Port dspace-7_x] Added Arabic Translation

src/app/item-page/simple/item-types/publication/publication.component.html, src/app/item-page/simple/item-types/untyped-item/untyped-item.component.html
Fixes #3022
Corrected coar.notify.endorsedBy on item page
Check that any item related to COAR (e.g. https://sandbox.dspace.org/entities/publication/62ca9347-25c1-4a23-be6a-eab2c33bf258) has the coar.notify.endorsedBy  on simple view.  
=> [DURACOM-259] add correct metadata

src/app/submission/import-external/import-external-preview/submission-import-external-preview.component.html, src/app/submission/import-external/import-external-preview/submission-import-external-preview.component.spec.ts, src/app/submission/import-external/import-external-preview/submission-import-external-preview.component.ts
Manual port of #2954 by @jensvannerum to `dspace-7_x`
=> [Port dspace-7_x] Live import preview should show all metadata values, not only the first one

src/app/info/feedback/feedback-form/feedback-form.component.html
Manual port of #2771 by @saschaszott to `dspace-7_x`.
=> [Port dspace-7_x] improved layout of feedback form (increase vertical spacing)

src/assets/i18n/cs.json5
Manual port of #3025 to `dspace-7_x`
=> [Port dspace-7_x] Czech DSpace 7 UI translation by NTK

config/config.example.yml, src/environments/environment.production.ts, src/environments/environment.test.ts, src/environments/environment.ts
Manual port of #2944 to `dspace-7_x`
=> [Port dspace-7_x] Disable inlineCriticalCss by default for better SSR performance

src/app/shared/search/search-filters/search-filter/search-authority-filter/search-authority-filter.component.html, src/app/shared/search/search-filters/search-filter/search-facet-filter/search-facet-filter.component.ts, src/app/shared/search/search-filters/search-filter/search-hierarchy-filter/search-hierarchy-filter.component.html, src/app/shared/search/search-filters/search-filter/search-text-filter/search-text-filter.component.html
Manual port of #3061 by @VictorHugoDuranS to `main` branch.
=> [Port main] Hide search text field when number of facet values is less than the maximum

src/app/shared/starts-with/text/starts-with-text.component.html, src/app/shared/starts-with/text/starts-with-text.component.scss, src/assets/i18n/en.json5, src/assets/i18n/es.json5, src/assets/i18n/pt-BR.json5
Browse by Author "serious" issues #1176
Fixes #1176
This change was addressed in issue #1176, which now allows the correction of the placeholder text problem "Type the first few letters and click the Search button" in the search bar of the author, title, and subject navigation pages.
In the "starts-with-text" component I modified and added some standard bootstrap classes and HTML tags. The search bar of the "starts-with-text" component was too small for smaller screen sizes, so I removed the "col-8" class and added the "col-auto" class from bootstrap. Another change was to insert a smaller placeholder text; the original text was added in a "small" tag under the search bar so that in smaller dimensions it could appear in full without being cut off.
* Change of …
=> Fix "Browse by Author" remaining serious accessibility issues

src/styles/_custom_variables.scss, src/styles/_global-styles.scss
Manual port of #3039 by @VictorHugoDuranS to `main`.
=> [Port main] Fix - Change color Contrast in cookie settings box

yarn.lock
Manual port of #3123 by dependabot to `dspace-7_x`
=> [Port dspace-7_x] Bump braces from 3.0.2 to 3.0.3

yarn.lock
Port of #2915 by dependabot to `dspace-7_x`
=> [Port dspace-7_x] Bump tar to 6.2.1

yarn.lock
Port of #3124 by dependabot to `dspace-7_x`
=> Bump express from 4.18.2 to 4.19.2

yarn.lock
Port of #3125 by dependabot to `dspace-7_x`
=> [Port dspace-7_x] Bump postcss to 8.4.38

yarn.lock
Port of #3129 by dependabot to `dspace-7_x`
=> [Port dspace-7_x] Bump ws from 7.5.9 to 7.5.10

src/app/shared/cookies/klaro-configuration.ts
Manual port of #3146 by @LotteHofstede  to `dspace-8_x`
=> [Port dspace-8_x] Fixed bug when declining Google ReCaptcha cookie preferences

docker/db.entities.yml
I didn't create an issue for this.  Encountered as I was trying to complete the docker installation instructions for the configurable entities test data.   (In case this is OS-specific, I'm running the install on Mac Sonoma 14.5 (Apple M3 Pro chip)
Fixes the syntax in the path for the image for the postgres-pgcrypto image (I think all that was needed was to change :: to : but I also referenced the DOCKER-OWNER environment variable in the path for consistency with the other files.)
* Changed the path to the image postgres-pgcrypto image 
Confirm that command `docker compose -p d8 -f docker/docker-compose.yml -f docker/docker-compose-rest.yml -f docker/db.entities.yml up -d` succeeds.
_This checklist provides a reminder of what we are going to look for when …
=> fixes image path for dspace-postgres-pgcrypto

.github/pull_request_template.md, src/assets/i18n/fr.json5
None
Change the french translation of `submission.workspace.generic.view-help` to match the other `submission.workflow.generic.view-help` french translation. 
They are the same in english and should be the same in french as well.
A sentence in `pull_request_template.md` was in my opinion not correct so I corrected it.
Not special instructions required this PR only changes texts.
* Fix a french translation to be consistent
* Fix a sentence in `pull_request_template.md`
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome).
However, reviewers may request that you complete any actions in this list if you have not done so. If you are …
=> Minor fix in french translation file

src/assets/i18n/fr.json5
Manual port of #3172 by @pastr to `dspace-8_x`. Includes all translation changes but excludes the changes to the Pull Request template
=> [Port dspace-8_x] Minor fix in french translation file

src/assets/i18n/fr.json5
Manual port of #3172 by @pastr to `dspace-7_x`.  Includes all translation changes but excludes the changes to the Pull Request template
=> [Port dspace-7_x] Minor fix in french translation file

src/assets/i18n/de.json5
This PR adds missing translation keys in `de.json5`. The keys were introduced by `WorkspaceItemsDeletePageComponent`.
=> Missing translations in de.json5 (translation key prefix workspace-item)

src/assets/i18n/de.json5
Port of #3235 by @saschaszott to 8.x
=> [Port dspace-8_x] Missing translations in de.json5 (translation key prefix workspace-item) 

src/app/shared/search/search-filters/search-filter/search-range-filter/search-range-filter.component.html, src/app/shared/search/search-filters/search-filter/search-range-filter/search-range-filter.component.ts
Manual port of https://github.com/DSpace/dspace-angular/pull/3236 by @Simone-Ramundi to dspace-7_x.
=> [Port dspace-7_x] #3094 - Update date slider to prevent automatic page reloads

package.json, yarn.lock
Manual port of #3273 to `dspace-7_x`
=> [Port dspace-7_x] Bump axios from 1.6.7 to 1.7.4

yarn.lock
Manual port of #3284 to `dspace-7_x`
=> [Port dspace-7_x] Bump micromatch to 4.0.8

src/modules/app/browser-init.service.ts
Manual port of #3011 by @mspalti to `dspace-7_x`
=> [Port dspace-7_x] Fixed page and admin menu for Shibboleth auth

package.json, yarn.lock
Manual port of #3318 and #3324 to `dspace-7_x`.
=> [Port dspace-7_x] Bump Express to v4.20.0

package.json, server.ts, yarn.lock
Manual port of #3329 to `dspace-8_x`. I tested it using the same procedure in the PR to `main`.
=> [Port dspace-8_x] updates isbot dependency to newest version

src/app/item-page/simple/related-entities/tabbed-related-entities-search/tabbed-related-entities-search.component.html, src/app/navbar/expandable-navbar-section/expandable-navbar-section.component.html, src/app/shared/form/vocabulary-treeview/vocabulary-treeview.component.html
Port of #3251 to `dspace-8_x`.
=> [Port dspace-8_x] Minor accessibility fixes

src/app/item-page/simple/related-entities/tabbed-related-entities-search/tabbed-related-entities-search.component.html, src/app/navbar/expandable-navbar-section/expandable-navbar-section.component.html, src/app/shared/form/vocabulary-treeview/vocabulary-treeview.component.html
Port of #3251 to `dspace-7_x`.
=> [Port dspace-7_x] Minor accessibility fixes

src/assets/i18n/de.json5
This PR adds 3 missing German translations related to the 500 error page.
=> missing German translations (500 error)

src/assets/i18n/de.json5
This PR adds missing periods in `de.json5`.
=> minor change: added missing periods in German translations

src/app/navbar/navbar.component.scss
https://github.com/DSpace/dspace-angular/pull/2444 only fixes the DSpace theme, not the base (and custom) theme.
* Fixes #2372 (for base and custom theme)
* This issue for the custom theme was discussed here: [https://groups.google.com/g/dspace-tech/c/cmRsLl0-J9w/m/B7BcBcSxBAAJ](https://groups.google.com/g/dspace-tech/c/cmRsLl0-J9w/m/B7BcBcSxBAAJ)
Since the pull request #2444 only fixes the dspace theme, I modified the navbar.component.scss in the base theme to also fix the base and subsequently the custom theme.
* I only modified the …
=> Fix to Mobile navbar hamburger menu for base (custom) theme

src/app/item-page/edit-item-page/item-operation/item-operation.component.html, src/app/item-page/edit-item-page/item-status/item-status.component.html
Manual port of #3148 by @Andrea-Guevara to `dspace-7_x`.
=> [Port dspace-7_x] Accessibility of the status page

src/assets/i18n/fr.json5
Capitalized "Collections au sein de cette communauté"
Added capitalization. Deploy PR and observe capitalization is now present.
=> Update fr.json5 to add capitalization

src/app/thumbnail/thumbnail.component.html, src/app/thumbnail/thumbnail.component.spec.ts, src/app/thumbnail/thumbnail.component.ts
Manual port of #3221 by @alexandrevryghem to `dspace-8_x`
=> [Port dspace-8_x] Removed unnecessary *ngVars from ThumbnailComponent

yarn.lock
Manual port of #3395 to `dspace-8_x`
=> [Port dspace-8_x] Bump rollup from 4.21.2 to 4.24.0

cypress.config.ts, cypress/e2e/item-edit.cy.ts, cypress/e2e/login-modal.cy.ts, cypress/support/commands.ts, package.json, yarn.lock
Manual port of #3315 to `dspace-8_x`
=> [Port dspace-8_x] Upgrade to Cypress 13.15.0

src/app/home-page/top-level-community-list/top-level-community-list.component.html
* Fixes #3399
Noticed a minor typo on the homepage that prevented a label from being translated. See #3399 for more details.
=> Fixed #3399 - minor typo

src/app/home-page/top-level-community-list/top-level-community-list.component.html
Manual Port of #3400 by @aseyedia to `dspace-7_x`.
=> [Port dspace-7_x] Fixed #3399 - minor typo

src/app/item-page/versions/item-versions.component.html, src/app/item-page/versions/item-versions.component.ts
Port of #3253 to `dspace-7_x`.
=> [Port dspace-7_x] Fixed Edit Item's Version History crashing

package.json, yarn.lock
Manual port of #3407 to `dspace-7_x`
=> [Port dspace-7_x] Bump cookie, cookie-parser and socket.io

src/app/item-page/versions/item-versions.component.html, src/app/item-page/versions/item-versions.component.ts
- Port of #3253 to `dspace-8_x`.
- Port of https://github.com/DSpace/dspace-angular/commit/87cff6c90792553b2170e6a9326fdabdd478456c to `dspace-8_x`.
=> [Port dspace-8_x] Fixed Edit Item's Version History crashing

src/assets/i18n/ar.json5
Update Arabic Translation by KnowledgeWare Technologies Est.
Update  ar.json5 translation
* Fixes #`issue-number` (if this fixes an issue ticket)
* Requires DSpace/DSpace#`pr-number` (if a REST API PR is required to test this)
* First, ...
* Second, ...
_This checklist provides a reminder of what we are going to …
=> Update Arabic Translation

src/assets/i18n/de.json5
This PR adds translations (related to metadata import) in `de.json5`.
=> Add German translations (metadata import)

cypress/e2e/header.cy.ts, src/app/shared/lang-switch/lang-switch.component.html
Manual port of #3461 to `dspace-7_x`
=> [Port dspace-7_x] Add basic e2e testing for i18n

angular.json, package-lock.json, package.json
Manual port of #3509 to `main`.  These three dependencies are not used on `main` either.
* Verify tests all still succeed.
* If desired, test the UI. However, I've already done this.
=> [Port main] Remove unused dependencies (sortablejs, sanitize-html, webfontloader)

src/styles/_custom_variables.scss, src/styles/_global-styles.scss
Manual port of #3328 by @Andrea-Guevara to `dspace-7_x`
=> [Port dspace-7_x] Klaro Accessibility cookie settings

src/app/item-page/item-page.resolver.ts
Fixed the item authorization tab failing to load properly in dev mode. 
* Moved the dispatch `ResolvedAction` back into a separate subscribe
**Guidance for how to test or review this PR.**
* Start the frontend in dev mode with `npm run start:dev`
* Go to `/items/{uuid}/edit/authorizations` and verify that no errors are logged and that the tables are populated
=> Fixed authorization tab not loading in dev mode

src/assets/i18n/fr.json5
* Related to  #3578 
Includes all french labels for subcriptions, plus a few other missing things.
=> French translations for subscriptions feature

src/app/collection-page/create-collection-page/create-collection-page.component.html, src/app/community-page/create-community-page/create-community-page.component.html, src/app/notifications/qa/events/quality-assurance-events.component.html, src/app/notifications/qa/source/quality-assurance-source.component.html, src/app/notifications/qa/topics/quality-assurance-topics.component.html, src/app/shared/mydspace-actions/workspaceitem/workspaceitem-actions.component.html, src/app/shared/object-list/my-dspace-result-list-element/item-list-preview/item-list-preview.component.html, src/app/shared/search-form/scope-selector-modal/scope-selector-modal.component.html, src/app/shared/search/search-results/search-results.component.html, src/app/submission/sections/upload/section-upload.component.html, src/app/workspaceitems-edit-page/workspaceitems-delete-page/workspaceitems-delete-page.component.html
Manual port of #3225 by @alisaismailati to `dspace-8_x`
=> [Port dspace-8_x] Fixed headings by their rank

src/app/collection-page/create-collection-page/create-collection-page.component.html, src/app/community-page/create-community-page/create-community-page.component.html, src/app/shared/mydspace-actions/workspaceitem/workspaceitem-actions.component.html, src/app/shared/object-list/my-dspace-result-list-element/item-list-preview/item-list-preview.component.html, src/app/shared/search-form/scope-selector-modal/scope-selector-modal.component.html, src/app/shared/search/search-results/search-results.component.html, src/app/submission/sections/upload/section-upload.component.html, src/app/workspaceitems-edit-page/workspaceitems-delete-page/workspaceitems-delete-page.component.html
Manual port of #3225 by @alisaismailati to `dspace-7_x`.  NOTE: This contains fewer changes because some of the changes in #3225 were to pages that were added in 8.x.
=> [Port dspace-7_x] Fixed headings by their rank

src/app/core/breadcrumbs/item-breadcrumb.resolver.ts, src/app/core/browse/browse.service.spec.ts, src/app/core/browse/browse.service.ts, src/app/core/cache/object-cache.reducer.ts, src/app/core/cache/object-cache.service.ts, src/app/core/data/dspace-rest-response-parsing.service.ts, src/app/core/data/relationship-data.service.spec.ts, src/app/core/data/relationship-data.service.ts, src/app/core/data/version-history-data.service.ts, src/app/core/index/index.effects.ts, src/app/home-page/recent-item-list/recent-item-list.component.ts, src/app/item-page/edit-item-page/abstract-item-update/abstract-item-update.component.ts, src/app/item-page/edit-item-page/item-delete/item-delete.component.ts, src/app/item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.ts, src/app/item-page/item-page.resolver.ts, src/app/item-page/item.resolver.ts, src/app/shared/form/builder/ds-dynamic-form-ui/ds-dynamic-form-control-container.component.ts, src/app/shared/utils/relation-query.utils.ts
Port of #3415 to `dspace-8_x`.
=> [Port dspace-8_x] Added support for caching embedded objects without a self link & null responses

src/app/shared/dso-selector/modal-wrappers/create-community-parent-selector/create-community-parent-selector.component.html, src/app/shared/dso-selector/modal-wrappers/create-community-parent-selector/create-community-parent-selector.component.spec.ts, src/app/shared/dso-selector/modal-wrappers/create-community-parent-selector/create-community-parent-selector.component.ts
Port of https://github.com/DSpace/dspace-angular/pull/3308 by @Simone-Ramundi to dspace-7_x.
=> [Port dspace-7_x] #3288 - Enabled 'admin-div' only for Site Administrator

src/app/shared/file-download-link/file-download-link.component.html, src/app/shared/file-download-link/file-download-link.component.ts, src/assets/i18n/en.json5, src/assets/i18n/es.json5, src/assets/i18n/pt-BR.json5
Manual port of #3264 by @Andrea-Guevara to `dspace-8_x`
=> [Port dspace-8_x] More accessible file download link for users who use a screen reader

src/app/shared/file-download-link/file-download-link.component.html, src/app/shared/file-download-link/file-download-link.component.ts, src/assets/i18n/en.json5, src/assets/i18n/es.json5, src/assets/i18n/pt-BR.json5
Manual port of #3264 by @Andrea-Guevara to `dspace-7_x`
=> [Port dspace-7_x] More accessible file download link for users who use a screen reader 

src/app/shared/form/vocabulary-treeview/vocabulary-treeview.component.html, src/app/shared/form/vocabulary-treeview/vocabulary-treeview.component.ts
Manual port of #3367 by @Andrea-Guevara to `dspace-7_x`
=> [Port dspace-7_x] Accessibility in vocabulary treeview

src/assets/i18n/hu.json5
Updating Hungarian translations for DSpace 8.0. Translating a lot of non-translated values and fixing some weird automatic translations.
- Pull my changes on the hu.json5 file
- Start the dspace-angular frontend
- Change the language from English to Hungarian
=> Updating Hungarian translations for DSpace 8.0

src/app/entity-groups/research-entities/submission/item-list-elements/org-unit/org-unit-search-result-list-submission-element.component.ts
This minor PR fixes the value of the selector in the `Component` annotation.
=> fix selector in OrgUnitSearchResultListSubmissionElementComponent compontent

README.md
Angular 17.x needs Node.js 18.x or 20.x, which come with NPM v10.
See: https://angular.dev/reference/versions
See: https://nodejs.org/en/about/previous-releases#looking-for-latest-release-of-a-version-branch
=> README.md: update Node.js and NPM versions

README.md
Angular 17.x needs Node.js 18.x or 20.x, which come with NPM v10.
See: https://angular.dev/reference/versions
See: https://nodejs.org/en/about/previous-releases#looking-for-latest-release-of-a-version-branch
=> [Port dspace-8_x] README.md: update Node.js and NPM versions

src/assets/i18n/es.json5
Manual port of #3192 by @Andrea-Guevara to `dspace-8_x`
=> [Port dspace-8_x] Spanish translation keys 

src/assets/i18n/de.json5
This PR adds missing translation keys and corrects existing ones related to the process view in `de.json5`.
=> add German translation of process view related keys

src/app/shared/form/builder/ds-dynamic-form-ui/models/lookup/dynamic-lookup.component.html, src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.html, src/app/shared/form/form.service.ts
Port of #3724 to `dspace-7_x`.
=> [Port dspace-7_x] Fixed dropdown/lookup & lookup-name fields being reset when hitting enter

src/app/core/shared/browse-definition.model.ts, src/app/core/shared/hierarchical-browse-definition.model.ts, src/app/core/shared/non-hierarchical-browse-definition.ts, src/app/item-page/simple/field-components/specific-field/abstract/item-page-abstract-field.component.spec.ts, src/app/item-page/simple/field-components/specific-field/author/item-page-author-field.component.spec.ts, src/app/item-page/simple/field-components/specific-field/date/item-page-date-field.component.spec.ts, src/app/item-page/simple/field-components/specific-field/generic/generic-item-page-field.component.spec.ts, src/app/item-page/simple/field-components/specific-field/img/item-page-img-field.component.spec.ts, src/app/item-page/simple/field-components/specific-field/item-page-field.component.spec.ts, src/app/item-page/simple/field-components/specific-field/item-page-field.component.ts, src/app/item-page/simple/field-components/specific-field/uri/item-page-uri-field.component.spec.ts, src/app/shared/testing/browse-service.stub.ts
Manual port of #3701 by @KoenP to `dspace-8_x`
=> [Port dspace-8_x] Reduce browse definition requests on simple item page (#3701)

src/assets/i18n/es.json5
Manual port of #3814 for dspace-8x
=> [Port dspace-8_x] Update spanish translation

src/assets/i18n/ca.json5
Manual port of #3797 for dspace-8x
=> [Port dspace-8_x] Update catalan translation

src/app/dso-shared/dso-edit-metadata/metadata-field-selector/metadata-field-selector.component.html, src/app/dso-shared/dso-edit-metadata/metadata-field-selector/metadata-field-selector.component.scss, src/app/dso-shared/dso-edit-metadata/metadata-field-selector/metadata-field-selector.component.spec.ts, src/app/dso-shared/dso-edit-metadata/metadata-field-selector/metadata-field-selector.component.ts
Manual port of #3096 by @VictorHugoDuranS to `dspace-7_x`
=> [Port dspace-7_x] Change - Metadata field selector, add infinite scroll for data paginated

src/app/dso-shared/dso-edit-metadata/metadata-field-selector/metadata-field-selector.component.html, src/app/dso-shared/dso-edit-metadata/metadata-field-selector/metadata-field-selector.component.scss, src/app/dso-shared/dso-edit-metadata/metadata-field-selector/metadata-field-selector.component.spec.ts, src/app/dso-shared/dso-edit-metadata/metadata-field-selector/metadata-field-selector.component.ts
Manual port of #3096 by @VictorHugoDuranS to `dspace-8_x`
=> [Port dspace-8_x] Change - Metadata field selector, add infinite scroll for data paginated

src/app/profile-page/profile-page.component.html, src/app/profile-page/profile-page.component.spec.ts, src/app/profile-page/profile-page.component.ts, src/assets/i18n/en.json5, src/themes/custom/app/profile-page/profile-page.component.ts
Manual port of #3105 by @VictorHugoDuranS to `dspace-8_x`
=> [Port dspace-8_x] Fix for User profile (/profile): only 20 group memberships shown instead of all 

cypress/e2e/admin-add-new-modals.cy.ts, cypress/e2e/admin-edit-modals.cy.ts, cypress/e2e/admin-export-modals.cy.ts, cypress/e2e/item-edit.cy.ts
Manual port of #3842 to `dspace-8_x`
=> [Port dspace-8_x] Attempt to stabilize a few randomly failing e2e tests

cypress/e2e/admin-add-new-modals.cy.ts, cypress/e2e/admin-edit-modals.cy.ts, cypress/e2e/admin-export-modals.cy.ts, cypress/e2e/item-edit.cy.ts
Manual port of #3842 to `dspace-7_x`
=> [Port dspace-7_x] Attempt to stabilize a few randomly failing e2e tests

cypress/e2e/admin-add-new-modals.cy.ts, cypress/e2e/admin-edit-modals.cy.ts, cypress/e2e/admin-export-modals.cy.ts
* Follow-up to #3842 
This is a small PR which attempts to stablize e2e tests that require opening the Admin sidebar.  While these tests pass sometimes, they also will sometimes fail if the Admin sidebar doesn't open quickly enough.
This PR is a **work in progress** to try out some strategies to get these tests to pass more frequently.
* This PR only touches e2e tests. No application code is changed.
=> Stabilize e2e tests that use admin sidebar menu

src/app/profile-page/profile-page.component.ts
Manual port of #3818 by @VictorDuranEscire to `dspace-7_x`
=> [Port dspace-7_x] Changing metadata in a user profile without specifying a password brings up a success and an error panel

src/app/browse-by/browse-by-date-page/browse-by-date-page.component.ts, src/app/browse-by/browse-by-metadata-page/browse-by-metadata-page.component.ts, src/app/browse-by/browse-by-title-page/browse-by-title-page.component.ts, src/app/core/data/base/base-data.service.ts
Port of #3846 to `dspace-7_x`.
=> [Port dspace-7_x] Browse performance fixes

src/app/shared/search/search-filters/search-filter/search-facet-filter-options/search-facet-option/search-facet-option.component.html, src/app/shared/search/search-filters/search-filter/search-facet-filter-options/search-facet-option/search-facet-option.component.ts, src/assets/i18n/en.json5, src/assets/i18n/es.json5, src/assets/i18n/pt-BR.json5
Manual port of #3385 by @Andrea-Guevara to `dspace-8_x`
=> [Port dspace-8_x] Accessibility when selecting a search filter

src/app/shared/form/builder/ds-dynamic-form-ui/models/array-group/dynamic-form-array.component.html, src/app/shared/form/builder/ds-dynamic-form-ui/models/array-group/dynamic-form-array.component.scss, src/app/shared/form/builder/ds-dynamic-form-ui/models/array-group/dynamic-form-array.component.spec.ts, src/app/shared/form/builder/ds-dynamic-form-ui/models/array-group/dynamic-form-array.component.ts, src/assets/i18n/en.json5
Manual port of #3372 by @AndreaBarbasso to `dspace-8_x`
=> [Port dspace-8_x] Make submission reorder buttons keyboard accessible

src/app/bitstream-page/edit-bitstream-page/edit-bitstream-page.component.html, src/app/bitstream-page/edit-bitstream-page/edit-bitstream-page.component.spec.ts, src/app/bitstream-page/edit-bitstream-page/edit-bitstream-page.component.ts, src/app/core/data/bitstream-data.service.ts, src/app/core/data/bundle-data.service.ts, src/app/core/data/relationship-type-data.service.ts, src/app/core/metadata/metadata.service.ts, src/app/item-page/edit-item-page/item-bitstreams/item-bitstreams.component.html, src/app/item-page/edit-item-page/item-bitstreams/item-bitstreams.component.ts, src/app/process-page/form/scripts-select/scripts-select.component.html, src/app/process-page/form/scripts-select/scripts-select.component.scss, src/app/process-page/form/scripts-select/scripts-select.component.spec.ts, src/app/process-page/form/scripts-select/scripts-select.component.ts, src/app/shared/form/builder/ds-dynamic-form-ui/models/list/dynamic-list.component.html, src/app/shared/form/builder/ds-dynamic-form-ui/models/list/dynamic-list.component.ts, src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.html, src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.ts, src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.model.ts, src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/search-tab/dynamic-lookup-relation-search-tab.component.spec.ts, src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/search-tab/dynamic-lookup-relation-search-tab.component.ts, src/app/submission/sections/cc-license/submission-section-cc-licenses.component.html, src/app/submission/sections/cc-license/submission-section-cc-licenses.component.scss, src/app/submission/sections/cc-license/submission-section-cc-licenses.component.spec.ts, src/app/submission/sections/cc-license/submission-section-cc-licenses.component.ts, src/assets/i18n/en.json5
Backporting of https://github.com/DSpace/dspace-angular/pull/3694 to `dspace-7_x`
=> [Port dspace-7_x] Prevent request with page size of 9999

src/assets/i18n/ca.json5
8x port: #3816
Add missing o modified keys to catalan translation file.
=> Update catalan translation

src/assets/i18n/fr.json5
Adding and changing parameters after upgrading to 8.1.
=> Changes to fr.json5 following version 8.1

src/assets/i18n/en.json5
* Fixes https://github.com/DSpace/DSpace/issues/9636
* Backend/API: https://github.com/DSpace/DSpace/pull/10170  
Just some translation keys for the datacite import for projects.
* added translation key for the new import source
* Appearing here:
* added translation keys for new import preview fields:
* Appearing here: …
=> translation keys for datacite project import

src/app/core/metadata/head-tag.service.ts
Port of #4034 to `dspace-8_x`.
=> [Port dspace-8_x] Add citation_doi tag to head meta

src/app/app-routes.ts
* Related #3227
Currently the breadcrumbs are not showing on collection pages on the latest version of `main`. This seems to have been done by mistake so I have reverted that change.
=> Restored breadcrumbs on collection pages

src/assets/i18n/de.json5
Made with results of the i18n-sync tool against en.json5. Added missing German translations and reviewed translations where the English text has changed. Only includes missing message keys as at DSpace 8.0. 
Sponsored by The Library Code.
Rebase notes:
All non-conflicting diffs applied during rebase, and some translations replaced (for review)
=> Translation additions, fixes and updates for German message catalogue

src/assets/i18n/en.json5, src/assets/i18n/fr.json5, src/assets/i18n/pt-PT.json5
* Requires DSpace/DSpace#10434
Translations required by https://github.com/DSpace/DSpace/pull/10434
=> Translations for access status filter

src/app/core/auth/auth.service.spec.ts, src/app/core/auth/auth.service.ts, src/app/core/auth/server-auth.service.ts, src/app/core/services/cookie.service.ts, src/app/core/services/server-cookie.service.ts
=> No platform specific code in abstract services 8_x

src/app/core/auth/auth.service.spec.ts, src/app/core/auth/auth.service.ts, src/app/core/auth/server-auth.service.ts, src/app/core/services/cookie.service.ts, src/app/core/services/server-cookie.service.ts
=> No platform specific code in abstract services 7_x

src/themes/dspace/app/home-page/home-news/home-news.component.html
Manual port of #4129 to `dspace-8_x`
=> [Port dspace-8_x] Add note with link to Release Notes on homepage

src/assets/i18n/ar.json5, src/assets/i18n/bn.json5, src/assets/i18n/ca.json5, src/assets/i18n/cs.json5, src/assets/i18n/de.json5, src/assets/i18n/el.json5, src/assets/i18n/es.json5, src/assets/i18n/fi.json5, src/assets/i18n/fr.json5, src/assets/i18n/gd.json5, src/assets/i18n/hi.json5, src/assets/i18n/hu.json5, src/assets/i18n/it.json5, src/assets/i18n/ja.json5, src/assets/i18n/kk.json5, src/assets/i18n/lv.json5, src/assets/i18n/nl.json5, src/assets/i18n/pl.json5, src/assets/i18n/pt-BR.json5, src/assets/i18n/pt-PT.json5, src/assets/i18n/sr-cyr.json5, src/assets/i18n/sr-lat.json5, src/assets/i18n/sv.json5, src/assets/i18n/sw.json5, src/assets/i18n/tr.json5, src/assets/i18n/uk.json5, src/assets/i18n/vi.json5
None
I ran `npm run sync-i18n`. This will update all the i18n files based on the added and changed keys in the english file. There will be // TODO comments for every key that needs to be updated in those languages files.
Nothing should look different. Missing keys would already fallback to english. The only difference is that they are now directly in the other language files as well
=> Ensure all i18n files are up to date with the english version

src/app/bitstream-page/edit-bitstream-page/edit-bitstream-page.component.html, src/app/item-page/edit-item-page/item-bitstreams/item-edit-bitstream-bundle/item-edit-bitstream-bundle.component.html
* Fixes #4141
I added our existing  `dont-break-out` css class to the header on the edit bitstream page. I also noticed the same issue in the bitstreams tab on the edit item page, so I added it there as well
- Create a bitstream with a very long name, either by uploading a new one, or editing the name of an existing one
- verify that the name now wraps, instead of moving off screen
=> Wrap long bitstream filenames

.github/workflows/build.yml
Manual port of #4189 to `dspace-7_x`
=> [Port dspace-7_x] Add additional automated server-side rendering (SSR) tests for all Entity Types

.eslintrc.json
Manual port of https://github.com/DSpace/dspace-angular/pull/2317.
=> [Port dspace-7_x] Update ESLint configuration for json5 files

src/assets/i18n/cs.json5
https://github.com/DSpace/dspace-angular/pull/4219
The Czech translation was updated by [michdyk](https://github.com/michdyk) here: https://github.com/DSpace/dspace-angular/pull/4219/files#diff-2adb7da35ea504568231fb86fa719a689e0df38dc0205425cddc23a1ef47f2e7, but the changes are not accurate or consistent across all thumbnail-related translations. We suggest reverting the last update, as the previous translation was more accurate and consistent.
However, reviewers may request that you complete any actions in this list if you have not done so. If you are unsure about an item in the checklist, don't …
=> Fix the last update to the Czech Translation

src/app/core/data/bitstream-data.service.spec.ts, src/app/core/data/bitstream-data.service.ts, src/app/item-page/edit-item-page/item-bitstreams/item-edit-bitstream-bundle/item-edit-bitstream-bundle.component.ts
Manual port of #4212 by @jesielviana to `dspace-7_x`
=> [Port dspace-7_x] Fix: prevent bitstream format cache issue by disabling cached version

src/app/item-page/edit-item-page/item-bitstreams/item-bitstreams.component.ts
=> [Port dspace-7_x] Fix bitstream tables being duplicated

src/assets/i18n/de.json5
* 8.x port of the merged work to main: #3980 
Made with results of the i18n-sync tool against en.json5. Added missing German translations and reviewed translations where the English text has changed. Only includes missing message keys as at DSpace 8.0.
Sponsored by The Library Code.
Rebase notes:
All non-conflicting diffs applied during rebase, and some translations replaced (for review)
=> German de.json5 additions, fixes and updates (port of https://github.com/DSpace/dspace-angular/pull/3980)

src/assets/i18n/en.json5
Hi @tdonohue, I'am @jtimal partner, I like to share this PR with you.
* Fixes #4220
* Requires DSpace/DSpace#pr-number (if a REST API PR is required to test this)
I added missing metadata tags in the import preview of publications from SCOPUS.
* Added missing i18n keys to the `en.json5` file for metadata preview labels:
- `item.preview.dc.relation.hasversion`
- `item.preview.dc.relation.ispartofseries`
- `item.preview.dc.rights`
- `item.preview.dc.identifier.other`
* Synced the translations using `yarn run sync-i18n`.
=> Fixed Missing Tags in Import Popup from External Sources - 4220

src/assets/i18n/en.json5
Manual port of #4282 by @guillermo2519 to `dspace-8_x`
=> [Port dspace-8_x] Fixed Missing Tags in Import Popup from External Sources - 4220

src/assets/i18n/en.json5
Manual port of #4282 by @guillermo2519 to `dspace-7_x`
=> [Port dspace-7_x] Fixed Missing Tags in Import Popup from External Sources - 4220

src/assets/i18n/fr.json5
Random updates based on the "TODO New keys" tags.
* Partially fixes:  #4306
=> Updates on the fr.json5

.github/workflows/build.yml
Manual port of #4326 to `dspace-7_x`
=> [Port dspace-7_x] Add basic automated tests to ensure common HTTP Return Codes do not break

.github/workflows/build.yml
Manual port of #4326 to `dspace-8_x`
=> [Port dspace-8_x] Add basic automated tests to ensure common HTTP Return Codes do not break

src/app/dso-shared/dso-edit-metadata/metadata-field-selector/metadata-field-selector.component.spec.ts, src/app/dso-shared/dso-edit-metadata/metadata-field-selector/metadata-field-selector.component.ts
Port of #4340 by @alexandrevryghem
=> [Port dspace-8_x] Fix unqualified metadata field validation in Edit Metadata tab by sorting fields in validation request

package.json, yarn.lock
`zone.js` is a peer dependency of Angular so we should keep it in sync to avoid dependency conflicts. DSpace 8.x uses Angular 17.x so we can pin `zone.js` to version `~0.14.0`.
See: https://github.com/angular/angular/blob/17.3.x/packages/core/package.json
* Update zone.js version pin in `package.json` and `yarn.lock`
Make sure all tests are passing in CI and `yarn build:prod` works (this is the only place we use zone.js …
=> Pin zone.js dependency for DSpace 8.x

src/app/info/accessibility-settings/accessibility-settings.component.ts
SSR fix for issue mentioned in #3615.
=> [Port dspace-7_x] Accessibility settings page SSR Fix

src/app/shared/form/vocabulary-treeview/vocabulary-treeview.component.spec.ts, src/app/shared/form/vocabulary-treeview/vocabulary-treeview.component.ts
=> [Port dspace-9_x] Vocabulary preloadlevel fix

.github/dependabot.yml
@ngtools/webpack is provided by the Angular team and follows the same versioning so we should group it with Angular in dependabot.
See: https://github.com/angular/angular-cli
* Add @ngtools/webpack to the Angular group managed by dependabot …
=> .github/dependabot.yml: group @ngtools/webpack with Angular

src/app/core/data/version-history-data.service.ts
The reason for creating a new version is now encoded in the URL.
* Fixes [#4327](https://github.com/DSpace/dspace-angular/issues/4327)
The summary entered by an author when creating a new version of an item is now URL-encoded to ensure that characters (such as `&`, `?` or `#`) do not alter the URL in an unintended way. 
Steps to check and reproduce the behaviour:
* Open an item as the author or an administrator
* Click on the "versioning" icon on the top right of the page
* Enter a summary text with any special character
* Make sure the POST request is sent correctly and the whole summary is completly transmitted to the backend
=> fix(versioning): Encode summary

package-lock.json, package.json
As of DSpace 10.0-SNAPSHOT we currently support Node.js v18 and v20 so we should—_in theory_—be using appropriate types.
Also note that, as of this writing, [Node.js v20 and v22 are the currently supported LTS versions](https://nodejs.org/en/about/previous-releases) of Node.js. We should bump our versions.
* First, update `@types/node` from `^14.14.9` to `^18.11.9`.
**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, screenshots or description of a new feature, or reasons behind specific changes.
Make sure the application builds and TypeScript-aware editors …
=> Update @types/node to ^18.11.9

.github/pull_request_template.md, CONTRIBUTING.md, README.md
Update DSDOC references to DSDOC9x in GitHub templates.
=> Update GitHub template references to DSDOC9x

.github/workflows/codescan.yml
CodeQL Action v2 was deprecated in January, 2024 (!) after the release of v3. It has been showing warnings in the CI logs since January, 2025.
See: https://github.blog/changelog/2025-01-10-code-scanning-codeql-action-v2-is-now-deprecated/
* First, update codeql-action references from v2 to v3
Make sure code scanning task in CI works.
_This checklist provides a reminder of what we are going to look for when reviewing your PR. …
=> .github/workflows/codescan.yml: use codeql-action v3

README.md, src/app/footer/footer.component.html
We have many occurrences of plaintext HTTP links to www.dspace.org in the UI and license notices. In 2025 we should not be using plaintext links anywhere, and www.dspace.org even returns an HTTP 301 permanent redirect to the HTTPS version.
I used this command to find and replace all occurrences:
```
$ grep -rl 'http://www.dspace.org' * \
| xargs sed -i 's_http://www.dspace.org_https://www.dspace.org_'
```
We should do the same on all other currently supported branches but the pull requests will need to be manual.
Make sure the frontend still builds and runs.
However, reviewers may request that you …
=> Replace plaintext links to www.dspace.org

src/assets/i18n/fr.json5
This commit is adding the missing French translations to fr.json5 file.
=> Adding the missing French translations (dspace-7_x)

src/assets/i18n/en.json5, src/assets/i18n/pt-BR.json5, src/assets/i18n/pt-PT.json5
* https://github.com/DSpace/DSpace/pull/11041#issuecomment-3159935326
Added missing i18n keys from the ROR API to the en.json5 and pt-BR.json5 files.
Trigger an ROR import and check whether the labels display correctly in both English and Brazilian Portuguese.
* Added missing ROR API i18n keys to `en.json5`
* Added missing ROR API i18n keys to `pt-BR.json5`
=> Fix untranslated i18n keys ror api

src/app/shared/object-select/collection-select/collection-select.component.html
* Fixes #4726 
When adding mappings in the item mapper we should use the save icon instead of the trash icon. Screenshots of the modified behavior on sandbox.dspace.org (currently DSpace 10.0-SNAPSHOT).
**Adding a mapping**
**Removing a mapping**
* First, add a conditional using `ngClass` to use the appropriate icon depending on whether the user is adding or removing mappings
**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, screenshots or description of a new feature, or reasons behind …
=> src/app: use correct icon in item mapper
