README.md
I added the missing `npm run global` to the description of the installation process.
=> Update documentation of installation process

.travis.yml, karma.conf.js
Turns out Travis CI comes with yarn. So that makes this easier. 
@artlowel I reset the branch and it wiped out the pull request. This pull request does not have the yarn dependency in the global script.
=> Travis CI: this connects to #76

.travis.yml
Here are some details on preventing timeouts: https://docs.travis-ci.com/user/common-build-problems/#My-builds-are-timing-out
I implemented a conservative approach. I simply added retries to installs and a wait to the build. The default is 3 retries if the install times out. This can be increased by adding `bundler_args: --retry 5` to the .travis.yml file. The wait is done using travis_wait wrapper that will wait greater then 10 minutes for output before timing out. The documentation says to be cautious using this. If we need we can have it wait longer by adding a minute value after the wrapper command, i.e. `travis_wait 30 yarn build`.
=> Travis build timeout: this connects to #101

src/app/shared/pagination/pagination.component.spec.ts, src/app/shared/pagination/pagination.component.ts, src/app/shared/testing/router-stubs.ts
This PR connects to #109 
Remove matrix URL notation and add the possibility to keep any other parameters, in the URL, which do not belong to PaginationComponent
=> remove Matrix URL notation

src/app/search/search-result.model.ts, src/app/search/search.models.ts, src/app/search/search.module.ts, src/app/search/search.service.ts, src/app/search/searchresult.model.ts
This PR connects to #134
The mock-data consist of some items that are randomly sorted to mimic "changed" results.
Highlights are dc.description.abstract metadata with some random ```<em>``` tags to represent a matching "hit".
The following can be applied to a local codebase to test this PR.
It adds the returned SearchResults with their associated items and highlighted metadata to the home page
https://gist.github.com/jonas-atmire/734c688ea8956763caca8cfff3769240
=> Ds 134 search service with mock data

config/environment.default.js, src/app/shared/empty.util.spec.ts
Since the REST API enabled https I've noticed CORS issues in some cases when using http. 
This PR enables https by default.
=> switch rest demo to https in the default config

src/app/item-page/simple/field-components/file-section/file-section.component.html
=> Bugfix 121: Detail page for an item without fulltext is broken

e2e/search-page/search-page.po.ts
This PR closes #175 
Fixed an issue with an e2e test where sometimes the default scope was selected, which resulted in no scope being visible in the URL. This made the test fail once in a while.
=> Fixed e2e search page test

src/app/+search-page/search-page.component.spec.ts, src/app/+search-page/search-page.component.ts, src/app/+search-page/search-page.module.ts, src/app/+search-page/search-service/facet-value.model.ts, src/app/+search-page/search-service/filter-type.model.ts, src/app/+search-page/search-service/search-filter-config.model.ts, src/app/+search-page/search-service/search.service.ts
This PR closes #153.
I added 2 new methods to the mock service that return Remote Data objects with info about facets/filters.
- getConfig(): returns all filter configuration 
- getFacetValuesFor(searchFilterConfigName: string): returns the facet values for a specific filter
=> Added facet/filter methods to the mock search service 

resources/i18n/en.json, src/app/+search-page/search-options.model.ts, src/app/+search-page/search-page.component.html, src/app/+search-page/search-page.component.ts, src/app/+search-page/search-service/search.service.spec.ts, src/app/+search-page/search-service/search.service.ts, src/app/shared/shared.module.ts, src/app/shared/view-mode-switch/view-mode-switch.component.html, src/app/shared/view-mode-switch/view-mode-switch.component.scss, src/app/shared/view-mode-switch/view-mode-switch.component.spec.ts, src/app/shared/view-mode-switch/view-mode-switch.component.ts
Fixes #171
@artlowel finally I didn't need to return the URL from `SearchService` to make it work without JavaScript. I hadn't tested it yet when we discussed, but it turns out the non-JavaScript case was already working through the attributes in the `a` tags.
=> Bug 171:  List grid view switcher

src/app/shared/pagination/pagination.component.html
This PR connects to #185
Used NgbDropdown's input `placement` to specify where the menu should go rather than using a bootstrap class.
=> Moved dropdown menu placement to the bottom right

src/app/+collection-page/collection-page.component.html, src/app/+community-page/community-page.component.html, src/app/+home-page/home-news/home-news.component.html, src/app/+home-page/home-news/home-news.component.scss, src/app/+home-page/home-page.component.html, src/app/+item-page/full/full-item-page.component.html, src/app/+item-page/simple/item-page.component.html, src/app/+search-page/search-page.component.html, src/app/app.component.html, src/app/shared/comcol-page-logo/comcol-page-logo.component.html
This PR connects to #174 
Apologies for any mistakes I make: I'm a noob.
In the bootstrap docs it says that although containers can be nested, most layouts don't need them, so I removed the app level `container-fluid` class and wrapped each page in a `container` to make sure there wasn't any nesting. For rows without columns, I added the `no-gutters` class, but maybe the content in those rows should be in columns, then `no-gutters` could be removed. Also, I changed the shared logo's class from `img-responsive` to `img-fluid` because it was messing up the content width for the sub-collection-list for mobile sizes.
It looks like I changed way more than I did because of indenting!
Please let me know what I need to fix :)
=> Limit content width for pages

src/app/app.module.ts, src/app/core/dspace-rest-v2/dspace-rest-v2.service.spec.ts, src/app/core/dspace-rest-v2/dspace-rest-v2.service.ts, src/app/shared/api.service.ts
Relates to #194 
I tried to replace Http with HttpClient in the DSpaceRESTv2Service and ApiService, removing unused imports.
It doesn't seem like ApiService is used, so I didn't add tests, but I did add a test suite for the DSpaceRESTv2Service. It is pretty much a boilerplate HTTP test suite though because I'm not sure how to create a mock DSpaceRESTv2Response (it's just an empty object for now).
Yet again, I don't really know what I'm doing, so I'd appreciate any suggestions on how to improve this PR! Thank you :)
=> Replaced Http with HttpClient

src/app/shared/pagination/pagination.component.ts
Fix a issue on PaginationComponent. 
In a paginated page, when page size is changed out of PaginationComponent and in the route is missing page parameter (it happens in the search page) this generate a infinite loop in the navigation.
To see the issue remove the totalElements limit here
https://github.com/DSpace/dspace-angular/blob/90c3d16e8e99b4810b6b44e3f0ce7cb3e986a2ad/src/app/%2Bsearch-page/search-service/search.service.ts#L143
navigate to the search page and change the "Result per page" option
=> Fix pagination issue on change page size

.travis.yml
This PR closes #232 
Fixes an issue where protractor can't find the right chrome version when running in travis, see https://github.com/angular/angular-cli/wiki/stories-continuous-integration#using-travis-ci
=> Fix travis chrome issue

src/app/+community-page/community-page.component.html, src/app/+community-page/sub-collection-list/community-page-sub-collection-list.component.html, src/app/+community-page/sub-collection-list/community-page-sub-collection-list.component.ts
Fixes #122 
Ensures that Collection listing is generated from `/community/[uuid]/collections` endpoint, instead of `/collections` (which lists all Collections, regardless of parent).
This is a quick fix for the known bug.  
**Pagination Notes for Further Discussion:**
This implementation does NOT yet include pagination (which would be ideal, since the number of Collections under a Community may be large).  The reason I left out pagination is that I couldn't figure out an easy way to use the `/community/[uuid]/collections` endpoint (i.e. the Community model's [`collections` property](https://github.com/DSpace/dspace-angular/blob/master/src/app/core/shared/community.model.ts#L61)) with the existing PaginatedList component.
(Unless I'm missing something) The current PaginatedList component …
=> Fix #122 : ensure collections are listed based on current community

package.json
I disabled the gecko webdriver, as we're not using it, and downloading it can cause rate limit issues on github
=> Fix travis github ratelimit issue when downloading gecko webdriver

src/app/+search-page/search-service/search.service.ts, src/app/core/browse/browse.service.spec.ts, src/app/core/browse/browse.service.ts, src/app/core/cache/builders/remote-data-build.service.ts, src/app/core/cache/response-cache.models.ts, src/app/core/core.module.ts, src/app/core/data/browse-entries-response-parsing.service.spec.ts, src/app/core/data/browse-entries-response-parsing.service.ts, src/app/core/data/browse-response-parsing.service.spec.ts, src/app/core/data/browse-response-parsing.service.ts, src/app/core/data/request.models.ts, src/app/core/shared/browse-definition.model.ts, src/app/core/shared/browse-entry.model.ts, src/app/core/shared/operators.spec.ts, src/app/core/shared/operators.ts, src/app/shared/empty.util.spec.ts, src/app/shared/empty.util.ts, src/app/shared/mocks/mock-remote-data-build.service.ts, src/app/shared/mocks/mock-request.service.ts, src/app/shared/mocks/mock-response-cache.service.ts
This PR closes #255.
It adds `getBrowseDefinitions` and `getBrowseEntriesFor()` to `BrowseService`
`getBrowseDefinitions()` fetches and parses the browse definitions at: https://dspace7.4science.it/dspace-spring-rest/#https://dspace7.4science.it/dspace-spring-rest/api/discover/browses
And `getBrowseEntriesFor()` will fetch and parse the `entries` endpoint for a given definition ID: e.g. https://dspace7.4science.it/dspace-spring-rest/#https://dspace7.4science.it/dspace-spring-rest/api/discover/browses/author/entries
=> Fetching and parsing browse entries

src/app/+home-page/home-news/home-news.component.html
Adds the demo accounts on the rest server to the home page news
=> or2018 - add accounts to the news component

src/app/shared/truncatable/truncatable-part/truncatable-part.component.scss
Related to Google Chrome browser and the issue #234, this minor fix works since the `::after` pseudo element blocks elements behind it. Adding `pointer-events: none` to the `::after` pseudo element fixed the issue.
=> Fix truncated text being difficult to select

resources/i18n/en.json, src/app/+search-page/search-results/search-results.component.html, src/app/+search-page/search-results/search-results.component.spec.ts, src/app/+search-page/search-results/search-results.component.ts, src/app/shared/testing/query-params-directive-stub.ts, src/app/shared/testing/test-module.ts
If there is an error 400 or a search returns an empty result this commit will show a link with the query quoted. 
Also improved testing of search results component as the component has changed.
This PR closes #293.
=> #293 Added link with the query quoted for search results if empty

src/app/core/metadata/metadata.service.spec.ts, src/app/core/metadata/metadata.service.ts
This PR closes #311 
The Error occurs when calling the `first()` operator on an observable that doesn't emit any values. 
There are two ways around this issue. One is to use the `take(1)` operator, which does the exact same, but doesn't throw an error when no value is being emitted by the observable. The other is to catch the error thrown by the `first()` operator.
I decided catching the error and returning an empty array is the most elegant solution to the issue.
I also added a test case to metadata-service which tests if the error is being thrown or not.
=> Issue 311: No files item page bugfix

src/app/core/cache/builders/remote-data-build.service.spec.ts, src/app/core/cache/builders/remote-data-build.service.ts, src/app/core/data/base-response-parsing.service.ts, src/app/core/shared/item.model.ts, src/app/core/shared/operators.ts, src/app/shared/loading/loading.component.ts, yarn.lock
This PR closes #313 
`RemoteDataBuildService.aggregatePaginatedList` expected the payload of the RemoteData to contain an array. This method is refactored to `toPaginatedList`, which accepts a remotedata of an array as well as a PaginatedList.
On top of this, in BaseResponseParsingService, some isNotEmpty calls have been replaced with hasValue, because isNotEmpty checks for a property called size, which conflicts with the property size from the PaginatedList, resulting in isNotEmpty always returning false.
I’ve also added two test cases for this bug. One testing `toPaginatedList` being called with an array, the other with a PaginatedList. Both should return the same PaginatedList.
=> Issue 313: add support for paginated properties on dspace objects

src/app/core/auth/auth.service.ts
Overriding `this.router.routeReuseStrategy.shouldReuseRoute` breaks navigating to the same url but with different query parameters. This causes visible issues when you are logged in and try to add or remove facets on the search page.
I replaced this by using `this.router.onSameUrlNavigation = 'reload'` instead, as suggested here:
https://github.com/angular/angular/issues/13831#issuecomment-422683314
=> Fixed issue where facets could not be changed when you are logged in

src/app/+item-page/field-components/metadata-field-wrapper/metadata-field-wrapper.component.html, src/app/+item-page/field-components/metadata-field-wrapper/metadata-field-wrapper.component.spec.ts
Continuing on issue https://github.com/DSpace/dspace-angular/issues/302 and PR https://github.com/DSpace/dspace-angular/pull/303
Angular will sometimes inject empty spans, due to the way animations work. When that happens the content element will have children, but no visible contents. The labels are then still showing when they don’t have values.
To fix this we check the textContent instead of the number of children. We also hide the simple-view-element instead of the label because otherwise the margins are still shown and there is empty space that shouldn’t be there.
=> Hide the wrapper component when there is no text content

src/app/+search-page/search-filters/search-filter/search-filter.component.scss
Changed search filters cursor to pointer so it is more obvious that the search filters are clickable.
As an aside, I noticed that although most files use two spaces for indentation, some use four. I just changed this one to be a bit more consistent.
=> Changed search filter cursor to pointer

src/app/+search-page/search-filters/search-filter/search-boolean-filter/search-boolean-filter.component.scss, src/app/+search-page/search-filters/search-filter/search-facet-filter-options/search-facet-option/search-facet-option.component.scss, src/app/+search-page/search-filters/search-filter/search-facet-filter-options/search-facet-option/search-facet-option.component.ts, src/app/+search-page/search-filters/search-filter/search-facet-filter-options/search-facet-range-option/search-facet-range-option.component.scss, src/app/+search-page/search-filters/search-filter/search-facet-filter-options/search-facet-range-option/search-facet-range-option.component.ts, src/app/+search-page/search-filters/search-filter/search-facet-filter-options/search-facet-selected-option/search-facet-selected-option.component.scss, src/app/+search-page/search-filters/search-filter/search-facet-filter-options/search-facet-selected-option/search-facet-selected-option.component.ts, src/app/+search-page/search-filters/search-filter/search-hierarchy-filter/search-hierarchy-filter.component.scss, src/app/+search-page/search-filters/search-filter/search-range-filter/search-range-filter.component.scss, src/app/+search-page/search-filters/search-filter/search-text-filter/search-text-filter.component.scss
This PR fixes a small UI issue introduced by PR #374.
After #374 PR, the link styling of the facets was not taken into account anymore because some parts of the facets were split up into separate components.
This PR moves the facet link styling CSS to these components.
=> Fixed facets UI issue 

src/app/core/data/object-updates/object-updates.effects.spec.ts, src/app/core/data/object-updates/object-updates.effects.ts, src/app/core/registry/registry.service.ts, src/app/shared/notifications/notifications.service.ts
@Atmire-Kristof discovered a small issue with my previous Edit Metadata PR #362
When a user discards all changes a notification appears and the Discard button turns into an Undo button.
However, when clicking - and therefore closing - the notification, the undo button would stay in place and only turn back into a Discard button after initial the time-out has finished. This PR solves this issue.
After fixing this specific issue, @artlowel also discovered a caching issue with the metadata fields. When the user would go directly to the edit metadata page, already logged in, the code would not be able to correctly retrieve the list of available metadata fields. When the user subsequently tried to edit the field, every metadata field would be rendered as invalid and the auto complete feature …
=> Admin Edit Metadata - bugfix

src/app/core/data/request.service.ts, src/app/core/dspace-rest-v2/dspace-rest-v2.service.spec.ts, src/app/core/dspace-rest-v2/dspace-rest-v2.service.ts
This PR fixes an issue with missing Content-Types and relates to https://jira.duraspace.org/browse/DS-4216
In some requests, the Content-Type HTTP header was missing.
This PR makes sure `application/json; charset=utf-8` is added as a default Content-Type HTTP header, when no Content-Type header has previously been set.
=> Content-Type fallback

src/app/+admin/admin-sidebar/admin-sidebar.component.ts, src/app/+admin/admin-sidebar/expandable-admin-sidebar-section/expandable-admin-sidebar-section.component.ts, src/app/+collection-page/collection-page.component.html, src/app/+collection-page/collection-page.component.ts, src/app/+collection-page/collection-page.resolver.ts, src/app/+community-page/community-page.component.ts, src/app/+community-page/community-page.resolver.ts, src/app/+item-page/full/full-item-page.component.ts, src/app/+item-page/item-page.resolver.ts, src/app/+item-page/simple/item-page.component.spec.ts, src/app/+item-page/simple/item-page.component.ts, src/app/+search-page/filtered-search-page.component.ts, src/app/core/shared/operators.spec.ts, src/app/core/shared/operators.ts, src/app/header/header.component.html, src/app/shared/menu/menu-item/link-menu-item.component.html, src/app/shared/menu/menu-item/link-menu-item.component.ts, src/app/shared/menu/menu.module.ts, src/app/shared/services/route.service.ts
This PR solves some small remaining issues for the preview release.
It takes care of:
- Making sure clicking the search icon in the header actually directs the user to the search page
- Admin menu links that do not direct to a useful page yet, are greyed out
- The admin menu link to New --> Item now links the user to `/submit`
- Going to item/collection/community pages that don't exist, will now show you a 404 page instead of crashing
The tests failed due to the [dspaceObject -> indexableObject issue](https://github.com/DSpace/dspace-angular/issues/391#issuecomment-490005103). So we merged in the [MyDSpace PR](https://github.com/DSpace/dspace-angular/pull/384) to get them to pass. 
[Here](https://github.com/4Science/dspace-angular/compare/mydspace...atmire:Miscellaneous-fixes) you can see …
=> Miscellaneous fixes

src/app/+collection-page/collection-page.component.ts
This PR fixes the following issues with the most recent items section on collection homepages
- The most recent items on a collection homepage were retrieved using ItemDataService instead of SearchService, and were therefore not actually the most recent items. This was already fixed in #288, but was broken again due to a merge. 
- The list was re-rendered whenever the pagination returned _any_ event. I added a check for differences before a re-render.
=> [DS-4236] fix issues with collection recent submissions

resources/i18n/en.json, src/app/+search-page/filtered-search-page.component.spec.ts, src/app/+search-page/filtered-search-page.component.ts, src/app/+search-page/search-filters/search-filter/search-filter.component.ts, src/app/+search-page/search-filters/search-filter/search-fixed-filter.service.spec.ts, src/app/+search-page/search-filters/search-filter/search-fixed-filter.service.ts, src/app/+search-page/search-page.component.html, src/app/+search-page/search-page.component.ts, src/app/+search-page/search-results/search-results.component.html, src/app/+search-page/search-results/search-results.component.ts, src/app/+search-page/search-service/search-configuration.service.spec.ts, src/app/+search-page/search-service/search-configuration.service.ts, src/app/+search-page/search-settings/search-settings.component.html, src/app/+search-page/search-sidebar/search-sidebar.component.html, src/app/+search-page/search-switch-configuration/search-switch-configuration.component.spec.ts, src/app/+search-page/search-switch-configuration/search-switch-configuration.component.ts, src/app/app.component.ts, src/app/core/core.effects.ts, src/app/core/core.reducers.ts, src/app/core/index/index.actions.ts, src/app/shared/object-list/search-result-list-element/item-search-result/item-search-result-list-element.component.spec.ts, src/app/shared/services/route.action.ts, src/app/shared/services/route.actions.ts, src/app/shared/services/route.effects.ts, src/app/shared/services/route.reducer.ts, src/app/shared/services/route.service.spec.ts, src/app/shared/services/route.service.ts, src/app/submission/form/collection/submission-form-collection.component.html, src/app/submission/form/collection/submission-form-collection.component.ts
This PR resolves issues with the fixed filter search.
When a filtered search page (Eg. /search/person) was loaded using preboot, the SSR would return correct results, but CSR would request all search results (not filtered on entity type).
It also makes sure the loading icons are shown when the user changes pages or other parameters on the search page and new results are loading.
Edit: I found a small remaining issue on the MyDSpace page and fixed it.
Also, travis wasn't able to build anymore because the latest angular-cli version asks whether you want to send usage analytics back to google, and waits for a user prompt. This was causing a time out.
This question started appearing because Travis ran the `global` script before every build, causing the latest version of angular-cli to be …
=> Fixed filtered search page

src/app/+search-page/search-service/search.service.ts
This PR fix #423 that occurred after this [commit](https://github.com/DSpace/dspace-angular/commit/487ee9f75668c4cca13bd6f28c10ca42a7ff4400)
=> Fix issue with getSearchLink

src/app/+search-page/search-service/search.service.ts, src/app/+search-page/search-settings/search-settings.component.html
I reverted the changes from #424.
This issue was fixed earlier in this commit https://github.com/DSpace/dspace-angular/commit/49dc4b86e22b64f8136fab95de52746ab42c5dd3#diff-c793158e8f9f65b6e8317b40dcb28bc9
I believe that the SearchService:getSearchLink() method should not return a different path for each page that could possibly contain a search page, like for example the MyDSpace page.
If we were to do this anyway, we would also need this method to return the search links for the journal and person pages, because these also contain search pages; similar to the MyDSpace page.
This is why I refactored this in #398 to make sure the `InPlaceSearch` boolean was added to the necessary components, that - when true - will make sure to use the current page as a search page instead of the `/search` …
=> Reverted #424

resources/i18n/en.json, src/app/+item-page/simple/item-types/publication/publication.component.html, src/app/entity-groups/journal-entities/item-list-elements/journal-issue/journal-issue-list-element.component.html, src/app/entity-groups/journal-entities/item-list-elements/journal-issue/journal-issue-list-element.component.spec.ts, src/app/entity-groups/journal-entities/item-list-elements/journal-volume/journal-volume-list-element.component.html, src/app/entity-groups/journal-entities/item-list-elements/journal-volume/journal-volume-list-element.component.spec.ts, src/app/entity-groups/journal-entities/item-list-elements/journal/journal-list-element.component.html, src/app/entity-groups/journal-entities/item-list-elements/journal/journal-list-element.component.spec.ts, src/app/entity-groups/journal-entities/item-pages/journal-issue/journal-issue.component.html, src/app/entity-groups/journal-entities/item-pages/journal-issue/journal-issue.component.spec.ts, src/app/entity-groups/journal-entities/item-pages/journal-volume/journal-volume.component.html, src/app/entity-groups/journal-entities/item-pages/journal-volume/journal-volume.component.spec.ts, src/app/entity-groups/journal-entities/item-pages/journal/journal.component.html, src/app/entity-groups/journal-entities/item-pages/journal/journal.component.spec.ts, src/app/entity-groups/research-entities/item-list-elements/orgunit/orgunit-list-element.component.html, src/app/entity-groups/research-entities/item-list-elements/orgunit/orgunit-list-element.component.spec.ts, src/app/entity-groups/research-entities/item-list-elements/orgunit/orgunit-metadata-list-element.component.html, src/app/entity-groups/research-entities/item-list-elements/person/person-list-element.component.html, src/app/entity-groups/research-entities/item-list-elements/person/person-list-element.component.spec.ts, src/app/entity-groups/research-entities/item-list-elements/person/person-metadata-list-element.component.html, src/app/entity-groups/research-entities/item-list-elements/project/project-list-element.component.html, src/app/entity-groups/research-entities/item-list-elements/project/project-list-element.component.spec.ts, src/app/entity-groups/research-entities/item-pages/orgunit/orgunit.component.html, src/app/entity-groups/research-entities/item-pages/orgunit/orgunit.component.spec.ts, src/app/entity-groups/research-entities/item-pages/person/person.component.html, src/app/entity-groups/research-entities/item-pages/person/person.component.spec.ts, src/app/entity-groups/research-entities/item-pages/project/project.component.html, src/app/entity-groups/research-entities/item-pages/project/project.component.spec.ts
One of the priorities identified in https://wiki.duraspace.org/display/DSPACE/2019-05-23+DSpace+7+Entities+WG+Meeting was the migration of the metadata fields for new entity types to schema.org
This PR removes the temporary metadata fields from phase 1 of the configurable entities which is also part of https://jira.duraspace.org/browse/DS-4223 and includes the new metadata fields and search facets on the item pages
Of course any other flat metadata schema can also be configured, DSpace does support the metadata registry to easily configure the desired metadata schema
This is related to https://github.com/DSpace/DSpace/pull/2443 and would preferably be merged simultaneously with that PR
=> DS-4223 Metadata Schemas for configurable entities

src/app/core/core.module.ts, src/app/core/data/metadata-schema-data.service.ts, src/app/core/data/resource-policy.service.spec.ts, src/app/core/data/resource-policy.service.ts, src/app/submission/sections/upload/section-upload.component.spec.ts, src/app/submission/sections/upload/section-upload.component.ts
This adds the missing `ResourcePolicyService`. The call to `this.collectionDataService.findByHref` only succeeds, because the full href is used and typescript does not check the return type.
I do not know if the `resouce-policy.service.ts` file should be placed in something like `src/app/core/authz/`, but it's only a single file.
=> Add missing ResourcePolicyService

src/app/+item-page/simple/item-types/publication/publication.component.ts, src/app/+item-page/simple/item-types/shared/item-relationships-utils.ts, src/app/+item-page/simple/item-types/shared/item.component.spec.ts, src/app/entity-groups/journal-entities/item-pages/journal-issue/journal-issue.component.ts, src/app/entity-groups/journal-entities/item-pages/journal-volume/journal-volume.component.ts, src/app/entity-groups/journal-entities/item-pages/journal/journal.component.ts, src/app/entity-groups/research-entities/item-pages/orgunit/orgunit.component.ts, src/app/entity-groups/research-entities/item-pages/person/person.component.ts, src/app/entity-groups/research-entities/item-pages/project/project.component.ts
This PR allows for filtering a list of relationships on one side, depending on the item you're fetching relationships for. This can be useful in cases where two entities of the same type have a relationship with each other, for example child-parent relationships. Without one-sided filtering, you wouldn’t know when to display the parent or child relationship on item pages.
To achieve this, `filterRelationsByTypeLabel` now has an optional parameter for the item's ID. Using the item's ID, we can filter out irrelevant relationships where the item is on the same side as the label requested.
To avoid having to call both operators every time you're filtering relations, I’ve also added a new operator called `getRelatedItemsByTypeLabel`, essentially combining the other two operators into one.
All …
=> One-sided relationship filtering and refactoring

config/environment.default.js
After the merger of https://github.com/DSpace/DSpace/pull/2459, the REST API demo site has been updated to use the new default `/server` path.  It's now available at https://dspace7.4science.cloud/server
This PR updates the Angular UI to use that new path by default.
=> Update environment.js with new demo site path

package.json, yarn.lock
Travis has switched to chrome 76, which is out of the range of supported versions used by the webdriver-manager that ships with the latest version of protractor. This PR adds the latest version of webdriver-mangager as a direct dependency, and patches protractor after `yarn install`. This patch and the direct dependency on webdriver-manager and ncp (needed to do the patch) can be removed after a protractor update that includes webdriver-manager >= 12.1.6
=> Patch protractor with the latest webdriver-manager

package.json, protractor.conf.js
This PR connects to #453 
It removes e2e tests from the Travis CI npm script, and restores the protractor timeouts that were increased fix the issues with Travis
=> Remove e2e tests from the ci task

src/app/shared/comcol-forms/comcol-form/comcol-form.component.ts
The i18n labels on edit collection and community pages are based on the resource type. It used to be a string, but was changed in to an object recently causing the i18n labels to break:
This PR fixes that
=> Fix the labels on edit collection and community pages

.travis.yml
The travis trusty image [has an issue installing chrome](https://github.com/DSpace/dspace-angular/pull/348#issuecomment-530304706). This PR adds a workaround: it [updates dpkg manually](https://github.com/travis-ci/travis-ci/issues/9361#issuecomment-408431262) before installing chrome. However we should [switch to a newer ubuntu image](https://github.com/DSpace/dspace-angular/issues/481) to prevent similar issues in the future.
=> Fix travis chrome install issue

.travis.yml
A new set of docker compose files have been created for DSpace 6 and DSpace 7.  These compose files load a local.cfg file rather than setting properties through environment variables.  These compose files make use of a dedicated image dspace/dspace-cli to invoke command line actions.
https://github.com/DSpace-Labs/DSpace-Docker-Images/tree/master/docker-compose-files/dspace-compose-v2
This PR makes use of the new compose files for the travis ci step.
The d7.cli.assetstore.yml currently indexes the entire repo (including bitstreams) before returning.  These actions could be simplified if this content is not used for ci purposes.
=> Use the improved DSpace Docker Compose files to create the ci image

package.json, yarn.lock
This PR fixes [CVE-2019-10747](https://nvd.nist.gov/vuln/detail/CVE-2019-10747)
For future reference, I [read about](https://github.com/yarnpkg/yarn/issues/4986#issuecomment-530206555) a way to make this process a lot easier: You can add a `"resolutions"` section to package.json with any minimum version requirements for transitive dependencies, in this case:
```json
"resolutions": {
"set-value": ">= 2.0.1"
},
```
and then run `yarn install` and yarn will update yarn.lock to honor those requirements for you, or warn you if it can't. The package doesn't need to be a direct dependency for this to work. ~And after yarn.lock has been updated, you might as well remove it from package.json again before you commit, to keep the amount of clutter down.~ 👈 that last bit didn't work, it allowed the …
=> Update set-value to fix CVE-2019-10747

src/app/+search-page/search-page.module.ts
A "SearchFilterService" declaration is duplicated.
=> Remove duplicated "SearchFilterService"

src/app/header/header.component.scss, src/styles/_bootstrap_variables.scss, src/styles/_custom_variables.scss
This PR adds the `$header-icon-color` sass variable, which defaults to `$link-color` to allow you to override the color of the icons in the header more easily
=> Add header icon color variable

src/app/+item-page/simple/item-types/shared/item-relationships-utils.ts, src/app/core/cache/models/items/normalized-relationship-type.model.ts, src/app/core/shared/item-relationships/relationship-type.model.ts
This PR includes the Angular changes for https://github.com/DSpace/DSpace/pull/2488
Since the property is renamed in https://github.com/DSpace/DSpace/pull/2488, Angular has to be updated as well
=> Rename relationship type properties

src/app/+item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.spec.ts, src/app/+item-page/edit-item-page/item-relationships/edit-relationship/edit-relationship.component.spec.ts, src/app/+item-page/edit-item-page/item-relationships/item-relationships.component.spec.ts, src/app/core/data/relationship.service.spec.ts, src/app/core/data/relationship.service.ts
After the recent merge of #461 into master, my local builds were failing.
This is the error I received:
```
ERROR in src/app/core/data/relationship.service.ts(185,25): error TS2339: Property 'leftLabel' does not exist on type 'RelationshipType'.
src/app/core/data/relationship.service.ts(187,25): error TS2339: Property 'rightLabel' does not exist on type 'RelationshipType'.
```
I renamed these leftover properties to their appropriate name (as they seem to have been forgotten in the PR mentioned above).
=> Small bug-fix due to changes to relationship-type

docker/local.cfg
This is a tiny PR to fix #498 after the server-side received a fix in https://github.com/DSpace/DSpace/pull/2554
This PR simply corrects the `dspace.baseUrl` in the `local.cfg` used by our e2e tests.
I'm creating this as a PR to ensure Travis succeeds before merging
=> Correct baseUrl in local.cfg used by e2e tests

package.json, yarn.lock
Update for the e2e tests to work with the current version of chrome on travis
=> Update webdriver-manager library

src/app/core/data/dso-redirect-data.service.spec.ts
After merging #468 followed by #490, a few of the new tests created by #490 failed.  This is because they were not aligned with the updates in #468.  
This is a small PR to fix the broken tests of #490 to align with changes in #468
=> Fix broken tests on master

package.json, resources/i18n/cs.json5, resources/i18n/de.json5, resources/i18n/en.json5, resources/i18n/nl.json5, scripts/sync-i18n-files.js, yarn.lock
This PR adds a script to sync i18n message files to the latest english version. It will add missing keys to the other language files, and add TODO comments above them to indicate to the translator what has changed.
This will enable translators to start their work today, and keep tabs on how complete or incomplete the catalogs are.
To run the script type yarn run sync-i18n in the project root dir.
yarn run sync-i18n -h will give you an overview of the options
Please refer to https://wiki.duraspace.org/pages/viewpage.action?pageId=117735441 for further documentation.
=> I18n sync script

src/app/+lookup-by-id/lookup-by-id-routing.module.ts
As of the recent merge of #490 , running an AoT build results in the following error:
```
ERROR in Error during template compile of 'LookupRoutingModule'
Function expressions are not supported in decorators in 'ɵ0'
'ɵ0' contains the error at app/+lookup-by-id/lookup-by-id-routing.module.ts(11,18)
Consider changing the function expression into an exported function.
```
As angular suggests, a simple solution is to move the lambda function on that line into an exported function.
This solves the error during the AoT build.
=> AoT build error fix

resources/i18n/en.json5
We accidentally ended up with some bad characters in `en.json5` during the merger of #504 (earlier today). These characters were added accidentally during a merge conflict resolution.  They were causing `e2e` test failures in Travis currently: https://travis-ci.org/DSpace/dspace-angular/jobs/612448996#L5424
The error message from Travis is:
`Error in SSR, serving for direct CSR. Error details :  { SyntaxError: JSON5: invalid character '<' at 418:1`
This is a tiny, obvious PR to fix those parse errors. If Travis approves of this, I'll merge immediately.
=> Remove bad characters from en.json5

package.json, resources/fonts/README.md, themes/mantis/app/entity-groups/journal-entities/item-pages/journal-volume/journal-volume.component.html, webpack/webpack.common.js, webpack/webpack.test.js, yarn.lock
This PR adds the ability to serve custom fonts, either from the `/resources/fonts` directory, or from`/themes/${theme-name}/resources/fonts`. 
If a file with the same name exists in both places and the theme is active, the themed version will get priority.
=> Add support for locally hosted fonts

src/app/core/data/status-code-only-response-parsing.service.spec.ts, src/app/core/data/status-code-only-response-parsing.service.ts, src/app/statistics/track-request.model.ts
This PR fixes an error that is sometimes thrown when the statistics/viewevents endpoint returns an object with an `id: null`. While this shouldn't happen, and this will be fixed on the rest side as well, the UI also shouldn't parse the response beyond the status code, as we don't need the data for anything.
This PR adds a new StatusCodeOnlyResponseParsingService that will ignore everything but the statuscode, status text and whether the response was successful or not
It will use that service to parse statistic event responses.
=> Disregard the response body for statistic event calls

tslint.json
The changes in [the recently merged Angular 7 PR](https://github.com/DSpace/dspace-angular/pull/547) also updated Codelyzer to a more recent version. This version of Codelyzer [renamed some tslint rules](https://github.com/mgechev/codelyzer/blob/master/CHANGELOG.md#breaking-changes), that have not been updated in our code base yet. This PR fixes the broken rules by replacing the deprecated names.
=> Fixed renamed TSLint rules

src/app/+community-page/sub-collection-list/community-page-sub-collection-list.component.html, src/app/+community-page/sub-collection-list/community-page-sub-collection-list.component.spec.ts, src/app/+community-page/sub-collection-list/community-page-sub-collection-list.component.ts, src/app/+community-page/sub-community-list/community-page-sub-community-list.component.html, src/app/+community-page/sub-community-list/community-page-sub-community-list.component.spec.ts, src/app/+community-page/sub-community-list/community-page-sub-community-list.component.ts, src/app/+home-page/top-level-community-list/top-level-community-list.component.spec.ts, src/app/+home-page/top-level-community-list/top-level-community-list.component.ts, src/app/shared/pagination/pagination.component.ts
This PR added pagination for sub-communities and collections in the Community page.
Currently sub-communities and collections are limited to the ones embedded in the Community object, so is not possible to navigate through them all
=> Pagination on community page

src/app/+search-page/configuration-search-page.component.ts
The parameter name was incorrect
This causes e.g. https://dspace7-demo.atmire.com/items/03dce7cb-687d-44c8-8945-1b9b6623eecd to display all publications in the search instead of just https://dspace7-demo.atmire.com/items/0157eef4-2dc8-4ddd-8124-94cdabc15f6e
=> Fixed configuration-search-page fixedFilterQuery parameter

docker/docker-compose-rest.yml, docker/docker-compose-travis.yml, docker/local.cfg
This PR includes minor updates the the Docker configurations for dspace-angular required by these backend PRs:
* https://github.com/DSpace/DSpace/pull/2654 : PR to upgrade to JDK11
* https://github.com/DSpace/DSpace/pull/2657 : PR to change DSpace URL configs
This PR should be merged **only after the above two PRs are merged on the backend**.
NOTE: Please be aware this PR is expected to error in Travis CI, as it depends on changes in the above two PRs.  Therefore, it will only succeed in Travis once the above two PRs are merged.
=> DS-4380 and DS-4257: Minor updates to Docker configs for JDK11 and new URL configs

src/modules/app/browser-app.module.ts, src/modules/app/server-app.module.ts
This is a fix for https://github.com/DSpace/dspace-angular/issues/560: The Serverside-rendering is broken on specific pages where Angulartics is active
Usage of the Routerless module is considered experimental according to [the readme](https://github.com/angulartics/angulartics2#using-without-a-router) but I have not seen a problem with it. I have tested that requests for both DSpace statistics and Google Analytics are being still being fired in the browser. And the server side rendering is now working as expected.
=> Use Angulartics' Routerless module

.dockerignore
This is a minor, but important bugfix to our `.dockerignore` file.  Currently in `master` the `node_modules` folder is listed as `node-modules` (hyphen instead of underscore).  
This causes Docker to NOT ignore the `node_modules` folder, and attempt to use it in the Docker build process (it also slows the Docker build down significantly -- by minutes).
I've corrected this mistake & reorged the `.dockerignore` file into sections, aligned with our .gitignore.
Once Travis approves, I'll merge this immediately as it's not a UI code change, just a correction to the Docker build process.
=> [Docker] .dockerignore doesn't ignore "node_modules"

yarn.lock
Updates yarn.lock with a re-resolved dependency to the latest 1.x fsevents version (a transitive dependency), which is compatible with node 12. https://github.com/fsevents/fsevents/issues/278
=> Lock fsevents version compatible with node 12

src/app/core/submission/submission-rest.service.spec.ts, src/app/core/submission/submission-rest.service.ts
This is a replacement for https://github.com/DSpace/dspace-angular/pull/582 that requests full projection for all HTTP verbs on submission rest endpoints, to cover submission creation and edit use cases that were failing prior.
=> Use full projection for submission REST requests

src/app/+admin/admin-registries/bitstream-formats/bitstream-formats.component.spec.ts, src/app/+admin/admin-registries/bitstream-formats/bitstream-formats.component.ts, src/app/+item-page/edit-item-page/item-delete/item-delete.component.spec.ts, src/app/+item-page/edit-item-page/item-delete/item-delete.component.ts, src/app/app.module.ts, src/app/core/data/bitstream-format-data.service.spec.ts, src/app/core/data/bitstream-format-data.service.ts, src/app/core/data/data.service.ts, src/app/shared/comcol-forms/delete-comcol-page/delete-comcol-page.component.spec.ts, src/app/shared/comcol-forms/delete-comcol-page/delete-comcol-page.component.ts, src/app/shared/mydspace-actions/workspaceitem/workspaceitem-actions.component.spec.ts, src/app/shared/mydspace-actions/workspaceitem/workspaceitem-actions.component.ts, src/app/submission/edit/submission-edit.component.spec.ts, src/app/submission/edit/submission-edit.component.ts, src/app/submission/sections/upload/file/edit/section-upload-file-edit.component.ts, src/app/submission/sections/upload/file/edit/section-upload-file-edit.model.ts, src/app/submission/sections/upload/section-upload.component.ts, src/app/submission/submit/submission-submit.component.spec.ts, src/app/submission/submit/submission-submit.component.ts
This PR resolves https://github.com/DSpace/dspace-angular/issues/592 and fixes other minor bug found.
=> fix Submission cannot be completed #592

src/app/core/data/request.service.spec.ts, src/app/core/data/request.service.ts, src/app/core/index/index.effects.ts, src/app/core/index/index.selectors.spec.ts, src/app/core/index/index.selectors.ts, src/app/core/url-combiner/url-combiner.ts
Since #588 was merged we're getting more cache misses because the embed params are taken in to account when comparing request urls. They shouldn't. The embeds that were used don't influence the resource itself and should therefore be ignored when checking whether or not that resource is cached.
This PR filters out embed params when storing a request url in the index, and when searching that index later on.
=> Disregard embeds when checking request index

src/app/core/data/base-response-parsing.service.spec.ts, src/app/core/data/base-response-parsing.service.ts
We noticed while developing in REST, the Angular UI currently breaks if REST contains a type not (yet) known to Angular.
Each time a new REST type is implemented and somehow returned, an exception is thrown and the page rendering is aborted.
This change will avoid breaking the page, Angular will ignore any types it doesn't know (yet). It will display a warning though to ensure this is visible because it's not a typical use case for a production environment
=> Cache behavior for unknown type

resources/i18n/en.json5, src/app/+admin/admin-access-control/admin-access-control-routing.module.ts, src/app/+admin/admin-access-control/admin-access-control.module.ts, src/app/+admin/admin-access-control/epeople-registry/epeople-registry.actions.ts, src/app/+admin/admin-access-control/epeople-registry/epeople-registry.component.html, src/app/+admin/admin-access-control/epeople-registry/epeople-registry.component.spec.ts, src/app/+admin/admin-access-control/epeople-registry/epeople-registry.component.ts, src/app/+admin/admin-access-control/epeople-registry/epeople-registry.reducers.spec.ts, src/app/+admin/admin-access-control/epeople-registry/epeople-registry.reducers.ts, src/app/+admin/admin-access-control/epeople-registry/eperson-form/eperson-form.component.html, src/app/+admin/admin-access-control/epeople-registry/eperson-form/eperson-form.component.spec.ts, src/app/+admin/admin-access-control/epeople-registry/eperson-form/eperson-form.component.ts, src/app/+admin/admin-routing.module.ts, src/app/+admin/admin-sidebar/admin-sidebar.component.ts, src/app/+admin/admin.module.ts, src/app/app.reducer.ts, src/app/core/cache/object-cache.service.ts, src/app/core/data/data.service.ts, src/app/core/eperson/eperson-data.service.spec.ts, src/app/core/eperson/eperson-data.service.ts, src/app/shared/testing/eperson-mock.ts, src/app/shared/testing/group-mock.ts
This PR adds the admin access control pages for EPeople.
Functionalities:
- (Read) Initial page load gives you a pageable list of all EPeople. This list is searchable by scope, the default scope is byMetadata; byEmail is also selectable. Per EPerson ID, Name and Email is shown.
- (Create) EPerson form to create new EPerson
- (Delete) EPerson can be deleted
- (Update) EPerson form to edit their info (happens via patches to the backend)
This is dependent on backend PR: https://github.com/DSpace/DSpace/pull/2686. The Groups admin page will be coming in an upcoming PR.
=> Access-control - EPeople admin page

resources/i18n/en.json5, src/app/+item-page/full/full-item-page.component.html, src/app/+item-page/simple/item-page.component.html, src/app/shared/item/item-versions/notice/item-versions-notice.component.html, src/app/shared/item/item-versions/notice/item-versions-notice.component.spec.ts, src/app/shared/item/item-versions/notice/item-versions-notice.component.ts, src/app/shared/shared.module.ts
This feature builds upon #585, as it makes use of the objects and services created there.
This PR adds a notice on top of simple and full item pages for items whose version history contains a newer version.
The notice is displayed in a non-dismissible warning alert and reads: “This is not the latest version of this item. The latest version can be found here.” with “here” as a link to the item page of the latest version, as seen in the screenshot below.
Item pages of items that don’t contain any versioning, or are the latest item within their version history will not display any notice.
=> Notice regarding the availability of new version on item pages

.github/pull_request_template.md
This PR creates a Pull Request template for all new PRs to `master` based on 
https://help.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository
The content here is based on the PR Template for the Backend (REST API), which was added in https://github.com/DSpace/DSpace/pull/2721
Feedback is welcome!  I created this in a shared branch so that others can help contribute to this PR easily.
=> Create an initial PR template for DSpace 7 UI

src/app/+collection-page/collection-page-routing.module.ts, src/app/+community-page/community-page-routing.module.ts, src/app/shared/comcol-forms/comcol-form/comcol-form.component.spec.ts, src/app/shared/comcol-forms/comcol-form/comcol-form.component.ts
* https://github.com/DSpace/dspace-angular/issues/639
Create community and collection was broken, this has been resolved
This is just a bug fix to the create functions. Because they were at the end, the COLLECTION_CREATE_PATH was interpreted as a collection ID
=> Broken create community

src/app/+item-page/bitstreams/upload/upload-bitstream.component.spec.ts, src/app/+item-page/bitstreams/upload/upload-bitstream.component.ts
This PR fixes a bug present in the recently merged #577 explained in [this comment](https://github.com/DSpace/dspace-angular/pull/577#issuecomment-607928607).
**Technical details**
After the URL of the uploader changes (by either creating a new bundle, or selecting one from the dropdown), the uploader component is re-initialised to apply the changes to the uploader options by calling its `ngOnInit` method. However, this removes the callback methods from the uploader defined in `ngAfterViewInit`.
Simply calling `ngAfterViewInit` after `ngOnInit` fixes the issue.
=> Upload bitstream bug-fix

resources/i18n/en.json5, src/app/+admin/admin-access-control/admin-access-control-routing.module.ts, src/app/+admin/admin-routing.module.ts, src/app/+community-page/edit-community-page/community-roles/community-roles.component.html, src/app/+community-page/edit-community-page/community-roles/community-roles.component.spec.ts, src/app/+community-page/edit-community-page/community-roles/community-roles.component.ts, src/app/core/eperson/group-data.service.spec.ts, src/app/core/eperson/group-data.service.ts, src/app/core/shared/collection.model.ts, src/app/core/shared/community.model.ts, src/app/shared/comcol-forms/edit-comcol-page/comcol-role/comcol-role.component.html, src/app/shared/comcol-forms/edit-comcol-page/comcol-role/comcol-role.component.spec.ts, src/app/shared/comcol-forms/edit-comcol-page/comcol-role/comcol-role.component.ts, src/app/shared/comcol-forms/edit-comcol-page/comcol-role/comcol-role.ts, src/app/shared/shared.module.ts
This PR adds functionality to create/delete an admin group for a community.
This is added to the ‘Edit roles’ tab of the edit community page by the CommunityRolesComponent.
A ComcolRole class has been added to represent the different roles for a community or collection (currently only ADMIN is added since this is the only role for a community).
The relevant CRUD methods POST & DELETE for a role group have been added to the GroupDataService.
A ComcoleRoleComponent has been added to display a single role for a community or collection, along with a button to add/create a corresponding group, a link to edit this group, and an explanation.
This PR is dependent on
https://github.com/DSpace/dspace-angular/pull/613
=> Edit Community - Assign Roles/Groups

src/app/core/data/request.service.spec.ts, src/app/core/data/request.service.ts
requestService.getUUID() didn't work for UUIDs of requests that aren't sent because they were already cached. 
The reason was that there was an observableRace to find which observable that returns first: the one in the cache or the one in the index that maps unsent UUIDs to the cached ones.
Because ngrx selectors return undefined immediately if they have no result, in practice the call that checked the requestcache always won the race because its undefined came before the result from the index.
The way to fix it was to add an hasValueOperator() to each of the race observables. That way they can only win if they return something.
I also optimized getByHref by ensuring it doesn't pass calls on to getByUUID if the UUID is empty
_This checklist provides a reminder of what we are going to look …
=> Request by UUID issue

resources/i18n/en.json5, src/app/+admin/admin-access-control/admin-access-control-routing.module.ts, src/app/+admin/admin-routing.module.ts, src/app/+collection-page/edit-collection-page/collection-roles/collection-roles.component.html, src/app/+collection-page/edit-collection-page/collection-roles/collection-roles.component.spec.ts, src/app/+collection-page/edit-collection-page/collection-roles/collection-roles.component.ts, src/app/+community-page/edit-community-page/community-roles/community-roles.component.html, src/app/+community-page/edit-community-page/community-roles/community-roles.component.spec.ts, src/app/+community-page/edit-community-page/community-roles/community-roles.component.ts, src/app/core/eperson/group-data.service.spec.ts, src/app/core/eperson/group-data.service.ts, src/app/core/shared/collection.model.ts, src/app/core/shared/community.model.ts, src/app/shared/comcol-forms/edit-comcol-page/comcol-role/comcol-role.component.html, src/app/shared/comcol-forms/edit-comcol-page/comcol-role/comcol-role.component.spec.ts, src/app/shared/comcol-forms/edit-comcol-page/comcol-role/comcol-role.component.ts, src/app/shared/comcol-forms/edit-comcol-page/comcol-role/comcol-role.ts, src/app/shared/shared.module.ts
This PR adds functionality to create/delete an admin group for a collection.
This is added to the ‘Edit roles’ tab of the edit collection page by the CollectionRolesComponent.
New ComcolRole instances have been added, along with the relevant messages:
* 'collection_admin' (community admin role has been renamed to 'community_admin')
* 'submitters'
* 'item_read'
* 'bitstream_read'
The workflow roles are retrieved by the CollectionRolesComponent from the collection links starting with 'workflowGroups/'.
I couldn't find a way in the front-end to link the workflow steps to the workflow roles, so the page is a bit different from the DSpace 6 equivalent because it displays the workflow roles by the role rather than by the step.
For example:
* DSpace 6: 'Edit Metadata Step'
* DSpace 7: …
=> Edit collection - assign roles groups

server.ts
After #625 was merged, the production server always used the default port, not the one in environment.prod.ts
This PR fixes that issue
=> Hotfix: use the server port from the environment file

tsconfig.json
All *.spec files showed errors in IDEs, even though they would compile.
This was caused by the fact that IDEs only recognize a single tsconfig.json file, even though we use a separate one for *.spec files.
Adding type "jasmine" to the root tsconfig.json file solves this issue.
=> [Quickfix] Fix IDE issues with spec files

package.json
* https://github.com/DSpace/dspace-angular/pull/625#issuecomment-625272758
* https://wiki.lyrasis.org/pages/viewpage.action?pageId=117735441
The sync-i18n-files script fails if the person executing it has never executed "yarn run config", causing environment.ts to be absent
Observations pre-fix: executing "yarn run sync-i18n" produces the error Error: Cannot find module '../src/environments/environment.ts'
Observations post-fix: sync-18n works again
* Include tests for different user types (if behavior differs), …
=> Ensuring environment.ts is present before sync-i18n-files invocation

docker/local.cfg
Recently, all PRs began failing e2e tests (which run against a Docker-based REST API in Travis).  See for example the latest `master` build: https://travis-ci.com/github/dspace/dspace-angular/builds/167632878
This began when https://github.com/DSpace/DSpace/pull/2735 was merged, and I've tracked it down to a configuration problem for the Docker REST API backend.  Simply put, in https://github.com/DSpace/DSpace/pull/2735, the REST API CORS headers were updated to limit access to only URLs defined in `rest.cors.allowed-origins`, which only includes `dspace.ui.url` by default.
Unfortunately, in the REST API, currently `dspace.ui.url` still defaults to http://localhost:3000, while the frontend now defaults to port 4000 (as of #625)
So, this PR simply changes our Travis Docker REST API …
=> Quick fix to Travis e2e testing issues (running against a Docker backend)

src/app/breadcrumbs/breadcrumbs.component.html, src/app/breadcrumbs/breadcrumbs.component.spec.ts, src/app/breadcrumbs/breadcrumbs.component.ts, src/app/core/breadcrumbs/collection-breadcrumb.resolver.ts, src/app/core/breadcrumbs/community-breadcrumb.resolver.ts, src/app/core/breadcrumbs/dso-breadcrumb.resolver.ts, src/app/core/breadcrumbs/dso-breadcrumbs.service.ts, src/app/core/breadcrumbs/i18n-breadcrumb.resolver.ts, src/app/core/breadcrumbs/i18n-breadcrumbs.service.ts, src/app/core/breadcrumbs/item-breadcrumb.resolver.ts
The issue was mentioned in an [Angular issue comment](https://github.com/DSpace/dspace-angular/pull/645#issuecomment-624645477)
> > I also noticed, but it seems an issue with breadcrumbs change detection because after the first triggered change detection the right trail appears
>
>You're right. I see why as well. I'll create a small PR to fix it.
​
Fix to correctly update the breadcrumb when navigating directly to a DSpace page.
​
There was an issue with the breadcrumb not updating automatically when using the browser to directly go to a DSpace page.
This fix solves that issue.
​
To verify the fix:
* Open the homepage of the repository.
* Navigate to an item page. Verify that the breadcrumb updates upon navigation.
* Hard refresh your browser on the item page. Verify that the breadcrumb …
=> Fix delay in breadcrumb rendering

src/app/core/auth/auth.effects.spec.ts, src/app/core/auth/auth.effects.ts, src/app/shared/log-in/methods/password/log-in-password.component.html, src/app/shared/testing/auth-service.stub.ts
https://github.com/DSpace/dspace-angular/issues/289
This resolve issue #289 with authentication that didn't work properly when SSR is disabled. The issue was due that JWT cookie was deleted, without checking if is valid, when authenticated status is false during store rehydration. This happened because it assumed checking of JWT had already been done on SSR.
- Run application with `yarn start:dev`
- login 
- refresh the browser page 
with the previous code the session was lost now is maintained
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete …
=> Authentication issue csr

src/app/core/auth/auth.interceptor.spec.ts, src/app/core/auth/auth.interceptor.ts
This PR is related to [Angular issue 678](https://github.com/DSpace/dspace-angular/issues/678)
This PR fixes the logout request to correctly send the token to be logged out to the server.
This PR ensures that the authorization token is sent with a logout request so the server knows which user to log out.
To verify the changes the following can be done
* Log in into the UI.
* Obtain the authorization token from a request in the request tab.
* Use the authorization token in a curl or postman to perform a GET request to the items endpoint (.../api/core/items).
* Verify that this gives a list of items.
* Log out in the UI.
* Use the same authorization token in a curl or postman to perform a GET request to the items endpoint.
* Verify that your request is unauthorized.
* Include tests for …
=> Angular UI does not properly log out when clicking logout

docker/README.md, docker/docker-compose.yml, docker/environment.dev.ts, docs/Configuration.md
Today, while bug fixing https://github.com/DSpace/DSpace/pull/2772, I stumbled on a bunch of outdated references to `environment.*.js` configurations.
This PR cleans up those references, including:
* One typo in the default `docker-compose.yml` which causes the `environment.dev.ts` for Docker to not be loaded.
* Also fixed a compilation bug in `environment.dev.ts` which was previously undiscovered as it wasn't being used/loaded by Docker. See https://github.com/DSpace/dspace-angular/pull/693/commits/b1d39feedad5b3d932eae4c61a8b64f249f33457
* Fixed several references to `environment.dev.js` in configuration docs & Docker README
* I also cleaned up our separate configuration Docs which had not been updated
=> Fix all outdated references to environment.*.js. 

src/app/core/auth/auth.effects.spec.ts, src/app/core/auth/auth.effects.ts
This PR fixed a small bug with authentication that occurred only when the current page has the AuthGuard enabled and the SSR is disabled. Indeed when you are on a protected page (i.e `/mydspace`) reloading the browser page works only once, the second time authentication is lost and you are redirect to login page
- Run application with yarn start:dev
- login
- go to a protected page (i.e `/mydspace`)
- refresh the browser page several times
with the previous code the session was lost after the first refresh now is maintained
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're …
=> Fixed authentication issue with protected page on CSR

src/app/shared/comcol-forms/comcol-form/comcol-form.component.spec.ts, src/app/shared/comcol-forms/comcol-form/comcol-form.component.ts, src/app/shared/comcol-forms/create-comcol-page/create-comcol-page.component.ts, src/app/shared/comcol-forms/edit-comcol-page/comcol-metadata/comcol-metadata.component.spec.ts, src/app/shared/comcol-forms/edit-comcol-page/comcol-metadata/comcol-metadata.component.ts, src/app/shared/dso-selector/modal-wrappers/create-collection-parent-selector/create-collection-parent-selector.component.spec.ts, src/app/shared/dso-selector/modal-wrappers/create-community-parent-selector/create-community-parent-selector.component.html, src/app/shared/dso-selector/modal-wrappers/create-community-parent-selector/create-community-parent-selector.component.spec.ts, src/app/shared/dso-selector/modal-wrappers/create-item-parent-selector/create-item-parent-selector.component.spec.ts, src/app/shared/dso-selector/modal-wrappers/dso-selector-modal-wrapper.component.html, src/app/shared/dso-selector/modal-wrappers/dso-selector-modal-wrapper.component.spec.ts, src/app/shared/dso-selector/modal-wrappers/dso-selector-modal-wrapper.component.ts, src/app/shared/dso-selector/modal-wrappers/edit-collection-selector/edit-collection-selector.component.spec.ts, src/app/shared/dso-selector/modal-wrappers/edit-community-selector/edit-community-selector.component.spec.ts, src/app/shared/dso-selector/modal-wrappers/edit-item-selector/edit-item-selector.component.spec.ts, src/assets/i18n/en.json5
https://github.com/DSpace/dspace-angular/issues/665
https://github.com/DSpace/dspace-angular/issues/666
This PR addresses some issues with the Community & Collection edit pages.
* (DSOSelectorModalWrapperComponent): the mechanism to automatically select the current Community/Collection in the new/edit menu has been fixed
* (ComcolMetadataComponent): the request method used by the edit Community/Collection page has been changed from PUT to PATCH to repair the edit functionality
* (ComcolMetadataComponent): an appropriate error message is shown when the user doesn't have sufficient edit rights. I didn't add error message for other cases, because I don't think a 'Bad Request' or an 'Internal Server Error' message would have an added value to most end users.
* …
=> Misc edit community and collection fixes

src/app/+my-dspace-page/my-dspace-new-submission/my-dspace-new-submission.component.html, src/app/+my-dspace-page/my-dspace-new-submission/my-dspace-new-submission.component.spec.ts, src/app/+my-dspace-page/my-dspace-new-submission/my-dspace-new-submission.component.ts, src/app/core/data/collection-data.service.spec.ts, src/app/core/data/collection-data.service.ts, src/app/shared/collection-dropdown/collection-dropdown.component.html, src/app/shared/collection-dropdown/collection-dropdown.component.scss, src/app/shared/collection-dropdown/collection-dropdown.component.spec.ts, src/app/shared/collection-dropdown/collection-dropdown.component.ts, src/app/shared/dso-selector/modal-wrappers/create-item-parent-selector/create-item-parent-selector.component.html, src/app/shared/dso-selector/modal-wrappers/create-item-parent-selector/create-item-parent-selector.component.ts, src/app/shared/notifications/notifications.service.ts, src/app/shared/shared.module.ts, src/app/submission/form/collection/submission-form-collection.component.html, src/app/submission/form/collection/submission-form-collection.component.spec.ts, src/app/submission/form/collection/submission-form-collection.component.ts, src/assets/i18n/en.json5
Fixes #671
Fixes #673
In this PR has been added:
- a new shared component used to display list of collections. This component is used as the collection dropdown in the Submission UI, as the collection selector in the Admin Sidebar menu and to start a new submission from the MyDSpace page
- support to enable/disable the collection dropdown in the Submission UI
- This PR must have to testing with REST API presents in another PR (https://github.com/DSpace/DSpace/pull/2771)
- to test the status (enabled/disabled) of the collection dropdown in the Submission UI comment/uncomment the collection step in the submission configuration.
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft …
=> Collection dropdown on MyDSpace & support enable/disable in Submission UI

src/app/+item-page/edit-item-page/item-bitstreams/item-bitstreams.component.spec.ts, src/app/community-list-page/community-list-service.spec.ts, src/app/shared/mocks/request.service.mock.ts
Fixes current travis failures with #707 and #722 
I noticed a few spec files that regularly cause travis builds to fail, but work when you run the exact same build again. 
Currently the [builds for #707](https://travis-ci.com/github/DSpace/dspace-angular/jobs/355325264#L6607) and [for #722](https://travis-ci.com/github/DSpace/dspace-angular/jobs/355238104#L5453) are failing in this way.
On closer inspection both seemed to be caused by running async code in the beforeEach sections of the spec file, without waiting for it to complete.
I recently added a section to the [testing guide on the wiki](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide#CodeTestingGuide-WritingUnit(spec)Tests) on this subject and how to prevent it. I'll add a note about beforeEach with a link back to this …
=> Wait for async code in beforeEach

README.md
Minor documentation change for DSPACE_HOST. 
This configuration it's supposed to be applied for hosts, URLs are not expected here. If you try them, then you will get an Exception like `An unhandled exception occurred: getaddrinfo ENOTFOUND`
=> DSPACE_HOST example fix

.github/workflows/issue_opened.yml
(Copy of DSpace/DSpace#2861 to this repository)
This creates a new "issue_opened.yml" workflow configuration which enables a [GitHub Action](https://docs.github.com/en/actions) for all newly created Issues which are either _unlabeled_ or labeled with `needs triage`.
More specifically, the [Create Project Card action](https://github.com/marketplace/actions/create-project-card-action) is run to check for new issues to add to the [DSpace Backlog project board](https://github.com/orgs/DSpace/projects/10).  The purpose of this Board is to capture incoming issues that need triaging/scheduling for a specific release...although there's also an "Unscheduled backlog" column on that board for anything that is currently unscheduled.
At this time, only issues flagged as `needs triage` (which will be …
=> Automatically add new Issues to "DSpace Backlog" project board

.github/workflows/pull_request_opened.yml
(Copy of https://github.com/DSpace/DSpace/pull/2857 to this repository)
This creates a new "pull_request_opened.yml" workflow configuration which enables a [GitHub Action](https://docs.github.com/en/actions) for all newly created Pull Requests on the `main` branch.
More specifically, the [Pull Request Assigner](https://github.com/marketplace/actions/pull-request-assigner) action is run to auto-assign all Pull Requests to the creator of that PR.  While this sounds a bit strange, it's really useful for our new [Project Boards](https://github.com/orgs/DSpace/projects), as it makes it a ton easier to see who is working on each PR / issue by simply filtering on "assignee".
I'm creating this PR simply as documentation of this decision & to test the process in GitHub (to make sure it works as …
=> Auto Assign new Pull Requests to "main" branch to the PR creator

src/app/shared/form/form.component.ts, src/app/submission/sections/form/section-form-operations.service.ts
* Fixes #817 
The reason for the error was that the value returned for scrollable dropdowns was bound to the field, and therefore readonly. So [cloning it before trying to modify it](https://github.com/DSpace/dspace-angular/pull/830/files#diff-69f602a806621adc6980f67794e68fd5R314) fixed the exception.
Afterwards I found another issue with scrollable dropdowns where if the field is empty, and you add multiple values before the first (auto)save, only the last would be saved. This was because when a field was added, the formControl wasn't updated like it was for other fields because the values had a different format compared to all the other fields. [I added a section to update the formcontrol value in the correct format](https://github.com/DSpace/dspace-angular/pull/830/files#diff-903cfa6a81 …
=> Fix issue with repeatable scrollable dropdowns in the submission

src/app/+admin/admin-access-control/epeople-registry/epeople-registry.component.html, src/app/+admin/admin-access-control/epeople-registry/epeople-registry.component.spec.ts
* Fixes https://github.com/DSpace/dspace-angular/issues/840
I added a div in the epeople-registry.component.html page that included the whole search section in order to hide it with a *ngIf
=> Hide EPerson search section in the edit mode

src/app/+collection-page/collection-item-mapper/collection-item-mapper.component.ts, src/app/+collection-page/collection-page.component.ts, src/app/+item-page/edit-item-page/item-collection-mapper/item-collection-mapper.component.ts, src/app/+item-page/edit-item-page/item-move/item-move.component.ts, src/app/shared/dso-selector/dso-selector/dso-selector.component.html, src/app/shared/dso-selector/dso-selector/dso-selector.component.spec.ts, src/app/shared/dso-selector/dso-selector/dso-selector.component.ts, src/app/shared/dso-selector/modal-wrappers/create-collection-parent-selector/create-collection-parent-selector.component.ts, src/app/shared/dso-selector/modal-wrappers/create-community-parent-selector/create-community-parent-selector.component.html, src/app/shared/dso-selector/modal-wrappers/create-community-parent-selector/create-community-parent-selector.component.ts, src/app/shared/dso-selector/modal-wrappers/create-item-parent-selector/create-item-parent-selector.component.ts, src/app/shared/dso-selector/modal-wrappers/dso-selector-modal-wrapper.component.html, src/app/shared/dso-selector/modal-wrappers/dso-selector-modal-wrapper.component.spec.ts, src/app/shared/dso-selector/modal-wrappers/dso-selector-modal-wrapper.component.ts, src/app/shared/dso-selector/modal-wrappers/edit-collection-selector/edit-collection-selector.component.ts, src/app/shared/dso-selector/modal-wrappers/edit-community-selector/edit-community-selector.component.ts, src/app/shared/dso-selector/modal-wrappers/edit-item-selector/edit-item-selector.component.ts, src/app/shared/dso-selector/modal-wrappers/export-metadata-selector/export-metadata-selector.component.spec.ts, src/app/shared/dso-selector/modal-wrappers/export-metadata-selector/export-metadata-selector.component.ts, src/app/shared/search/paginated-search-options.model.spec.ts, src/app/shared/search/paginated-search-options.model.ts, src/app/shared/search/search-options.model.spec.ts, src/app/shared/search/search-options.model.ts, src/app/statistics/statistics.service.spec.ts, src/app/statistics/statistics.service.ts, src/assets/i18n/en.json5
This PR adds functionality to do a search where multiple dsoTypes are allowed to be returned (instead of just one or all). This is used by the export metadata modal in admin sidebar to export collections and communities (created in https://github.com/DSpace/dspace-angular/pull/798).  Other search modals still expect just one type of dso in their results and the general search works as before. 
In the statistics search event request creation, just the first one of the list of dsoTypes is added since the regular search will not have multiple dsoTypes and admin sidebar search will not count towards statistics
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always …
=> Support multiple dso type values in discovery

src/app/curation-form/curation-form.component.spec.ts, src/app/curation-form/curation-form.component.ts
* Fixes [PR related issue](https://github.com/DSpace/DSpace/pull/2926#pullrequestreview-477868288)
This PR will remove the "email/-e" option from the curate script on Angular's end. See linked PR for REST related info.
**In the CurationFormComponent:**
* All authentication related code is removed
* authService and it's related calls are removed
* The -e option is not added to the call anymore
**In the related test component**
* -e option is not added anymore
* unused code is cleaned up 
=> Removal of email option for the curation script

src/app/submission/sections/upload/section-upload.component.html, src/app/submission/sections/upload/section-upload.component.spec.ts
* Fixes [GitHub issue](https://github.com/DSpace/dspace-angular/issues/844)
When using the UploadStep with a different ID than "upload" (e.g. to use other access conditions or make the file upload optional), the UI breaks.
This is occurring because the UI mixes the ID with the type (it uses the type assuming it's the ID)
Steps to reproduce the behavior:
1. In item-submission.xml create an upload step with ID upload2 and type upload
2. Upload a file in the UI
3. The ID of the section is now used to determine which files are associated
4. The uploaded file is now displayed
Without a different item-submission.xml, no changes are present
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR …
=> 844: Fix file upload to use section ID instead of 'upload'

server.ts
Fixes issue introduced by #863
This PR fixes an issue introduced by #863, which caused the error handler on the express server to be triggered when there were no errors.
In #863 we switched to the native express error handler. But we noticed on dspace-demo that the error fallback happens for every request. 
The reason is that it's not a dedicated error handler, but simply the next function in the chain that can make changes to the response. There's only an error if `err` is defined. 
This PR fixes that issue by checking if there's an error, and if not, passing the data from the previous function (the angular app) through.
To test it, triggering a 404 (as suggested in #863) is not sufficient for causing an actual express error. So I suggest you simply add `throw new Error('A test error');` …
=> Ensure CSR fallback only happens on actual errors

src/app/+item-page/full/field-components/file-section/full-file-section.component.html, src/app/+item-page/full/field-components/file-section/full-file-section.component.spec.ts, src/app/+item-page/full/field-components/file-section/full-file-section.component.ts, src/app/+item-page/simple/field-components/file-section/file-section.component.spec.ts, src/app/+item-page/simple/field-components/file-section/file-section.component.ts, src/app/core/data/bitstream-data.service.ts, src/app/core/data/bundle-data.service.ts, src/assets/i18n/en.json5
This is a fix to an issue introduced in #838
This PR fixes an issue that is visible in the browser console when loading an item without any bitstreams: [example](https://dspace7-demo.atmire.com/items/b7c3a324-3e07-466c-887a-57bf8be42f2d)
* Fix an issue with the bitstream loading on the item page when no bitstreams are present
* Add an error notification when an error occurs with retrieving the item bitstreams
* Hide the labels for empty bundles on the full item page
* Navigate to an item without any bitstreams
* Verify that no error message is shown in the browser console and that the page fully loads 
* Verify that the full item page doesn't show labels for empty bundles
* Verify that loading extra pages of bitstreams on the simple or full item pages is not affected by this fix
=> Fix bug concerning bistream pagination on the item page

docs/Configuration.md, scripts/set-env.ts, src/app/core/metadata/metadata.service.spec.ts, src/app/core/metadata/metadata.service.ts, src/app/core/services/browser-hard-redirect.service.spec.ts, src/app/core/services/browser-hard-redirect.service.ts, src/app/core/services/hard-redirect.service.spec.ts, src/app/core/services/hard-redirect.service.ts, src/app/core/services/server-hard-redirect.service.spec.ts, src/app/core/services/server-hard-redirect.service.ts, src/app/shared/file-download-link/file-download-link.component.spec.ts, src/app/shared/file-download-link/file-download-link.component.ts, src/config/global-config.interface.ts, src/environments/environment.common.ts
* Fixes #737
* Fixes #846
This PR adds an option to rewrite URLs for Bitstream downloads and the `citation_pdf_url` `<meta>` tag using the UI domain. It also fixes the `citation_abstract_html_url` field, and adds docs on how to configure the proxy for bitstream downloads using httpd.
This PR adds a `rewriteDownloadUrls` environment property, that defaults to `false`. When set to `true` it will change download URLs and the `citation_pdf_url` `<meta>` tag on item pages to be based on the UI [origin](https://developer.mozilla.org/en-US/docs/Glossary/Origin) instead of the REST origin.
That way, if you're hosting the rest api and the UI on different domains, download links will still appear to be hosted on the UI.
It also ensures the `citation_abstract_html_url` `<meta>` tag always uses the …
=> Google scholar fixes

.github/pull_request_template.md, src/app/core/shared/operators.ts, src/app/info/info-routing-paths.ts, src/app/info/info-routing.module.ts
- Fixes an issue introduced in #862 the same way #850 did
#862 [added new circular dependencies](https://travis-ci.com/github/DSpace/dspace-angular/jobs/386237237#L7772-L7800). This PR removes them, and adds a line to the PR template checklist to verify that a new PR isn't introducing new circular dependencies.
As in #850, I didn't add any new code, just moved a few functions and variables to a different file.
You can test this PR by verifying that it doesn't break anything involving the user agreement or privacy statement page.
=> Remove circular dependencies part 2

.travis.yml, docker/environment.dev.ts, docs/Configuration.md, src/environments/environment.common.ts, src/environments/environment.template.ts
* Addresses [a comment in #826](https://github.com/DSpace/dspace-angular/issues/826#issuecomment-700879946)
* Rest namespaces ending in `/api` were deprecated by #825 
This PR removes `/api` from the rest namespaces of `environment.common.ts` and `.travis.yml`, as it was deprecated in #825
- Test this PR by verifying the travis build works, and that the build logs don't show the deprecation warning.
- Test that if you don't override the rest namespace in your local environment files, you don't get the deprecation warning when building.
If you notice any other uses of `/api` I've forgotten please let me know.
=> remove remaining uses of /api in the rest namespace

src/app/+admin/admin-workflow-page/admin-workflow-search-results/admin-workflow-search-result-grid-element/workflow-item/workflow-item-search-result-admin-workflow-grid-element.component.spec.ts, src/app/shared/object-grid/search-result-grid-element/search-result-grid-element.component.ts
* Fixes an issue I noticed when reviewing #901 
Item search results in grid view are supposed to only get a shadow when you click them to expand the truncated text. But they get it all the time, which looks strange when they're between results that aren't truncated:
The screenshot below shows the situation as it is now. The first two are truncated, the third isn't
---
With this PR none of them have a shadow initially:
---
Only if you click a truncated card to open it, will it get a shadow, that will disappear when you close it again
---
**Note**: while this PR restores the intended behavior, it is still slightly confusing in my opinion, as Collection results aren't truncated, and therefore can't be clicked and will never get a shadow. But if we decide that's a problem, we can fix it in a …
=> Fix grid search result shadows

src/app/shared/object-list/search-result-list-element/item-search-result/item-types/publication/publication-search-result-list-element.component.html
Fixes #904 
Add a comma between publisher name and issue date
=> bugfix of issue #904

.gitignore, README.md
* Fixes #879
General description of how to use the product of running the `build:prod` script.
Note that configuration is collected and fixed at build time.
Please consider whether the changes accurately reflect the build process and its result.
* Small updates to README.md
=> [#879] Clarify the use of the production build script, and when configuration is processed

src/app/core/data/lookup-relation.service.ts, src/app/entity-groups/research-entities/submission/item-list-elements/external-source-entry/external-source-entry-list-submission-element.component.ts, src/app/shared/form/builder/ds-dynamic-form-ui/ds-dynamic-form-control-container.component.ts, src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/dynamic-lookup-relation-modal.component.ts, src/app/shared/object-collection/shared/importable-list-item-control/importable-list-item-control.component.html, src/app/shared/object-list/object-list.component.html, src/assets/i18n/en.json5
https://github.com/DSpace/dspace-angular/issues/867
This PR adds the missing labels mentioned in https://github.com/DSpace/dspace-angular/issues/867 .
It also solves an issue that the search result list items for the external sources (ex PubMed) were not rendering in the lookup Author modal during submission. Cause was that there was no @listableObjectComponent for the case that there were *no* name variants configured.
  Lastly, it solves an issue that the count of number of results in sources tab wasn’t updating (remained on (0)) for the external sources.
Submission => Author lookup => External source tab like PubMed/arXiv
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs …
=> Submission relationship lookup externalsources: Missing i18n labels & other issues

package.json
* Fixes #945 
Cleans node at end in order to avoid rimraf deleting itself.
Quick fix
=> #945 Clean node at end to avoid rimraf error

src/app/+item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.html, src/app/+item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.scss, src/app/+item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.spec.ts, src/app/+item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.ts, src/app/+item-page/edit-item-page/item-relationships/edit-relationship/edit-relationship.component.html, src/app/+item-page/edit-item-page/item-relationships/edit-relationship/edit-relationship.component.spec.ts, src/app/+item-page/edit-item-page/item-relationships/edit-relationship/edit-relationship.component.ts, src/app/+item-page/edit-item-page/item-relationships/item-relationships.component.html, src/app/+item-page/edit-item-page/item-relationships/item-relationships.component.ts, src/app/core/data/entity-type.service.ts, src/app/core/data/object-updates/object-updates.reducer.ts, src/app/core/data/object-updates/object-updates.service.ts, src/app/core/data/relationship.service.ts, src/app/entity-groups/research-entities/item-list-elements/person/person-list-element.component.html, src/app/entity-groups/research-entities/item-list-elements/search-result-list-elements/person/person-search-result-list-element.component.html, src/app/entity-groups/research-entities/item-list-elements/search-result-list-elements/person/person-search-result-list-element.component.ts, src/app/entity-groups/research-entities/submission/item-list-elements/person/person-search-result-list-submission-element.component.ts, src/app/shared/form/builder/ds-dynamic-form-ui/existing-metadata-list-element/existing-metadata-list-element.component.spec.ts, src/app/shared/form/builder/ds-dynamic-form-ui/existing-metadata-list-element/existing-metadata-list-element.component.ts, src/app/shared/object-collection/shared/listable-object/listable-object-component-loader.component.ts, src/app/shared/object-collection/shared/object-collection-element/abstract-listable-element.component.ts, src/assets/i18n/en.json5
This PR adds the ability to add new relationships from the edit item page as an admin. It builds on #541, #540, #539, #531 and #530
In the edit relationships tab, an add button was added next to each relationship type header that will open a modal similar to the one used in the submission that allows you to search for related entities of that type.
Newly added relationships will only be added after the user submits the edit relationships form, consistent with the way that page already worked.
Note: the PR is still a work in progress.
=> Create relationships as an admin in edit item

src/app/core/data/dso-redirect-data.service.ts
This PR refers to issue [#833](https://github.com/DSpace/dspace-angular/issues/883).
This PR fixes the issue where navigation to a handle page (Example: http://localhost:4000/handle/10673/1490) fails.
To test that the handle redirect works, perform the following steps:
* Navigate to a handle page that corresponds to an item in the repository. The aforementioned example can be used when using the default 4science backend.
* Verify that you get redirected to the corresponding item. When using the aforementioned item, this should resolve to the item with id 17307a98-0e78-45a6-83c3-7829eee024c6.
* Navigate to an invalid handle.
* Verify that you get redirected to the "No item found for the identifier" page.
=> Fix for handle redirects

package.json, server.ts, src/config/global-config.interface.ts, src/config/ui-server-config.interface.ts, src/environments/environment.common.ts, src/environments/mock-environment.ts, yarn.lock
This PR resolves 2 security issues flagged by LGTM:
1. Addition of a rate limiter to prevent a DOS attack
2. Add a warning in the log when using a self-signed ssl certificate and disabling the validation. The corresponding LGTM error is suppressed due to the presence of this warning
To verify the rate limiter, you can do the following:
* Build the app in production mode using the default settings
* Browse through the app as a normal user and verify that the rate limiter does not interfere with this behaviour
* Hard refresh the app multiple times and verify that refreshing gets blocked and shows a message saying "Too many requests, please try again later" on a white page.
To disable the rate limiter, do the following:
* Overwrite or change the environment constant `rateLimiter` to …
=> Fix security issues reported by LGTM

src/app/+collection-page/create-collection-page/create-collection-page.component.spec.ts, src/app/+collection-page/create-collection-page/create-collection-page.component.ts, src/app/+collection-page/delete-collection-page/delete-collection-page.component.spec.ts, src/app/+collection-page/delete-collection-page/delete-collection-page.component.ts, src/app/+community-page/create-community-page/create-community-page.component.spec.ts, src/app/+community-page/create-community-page/create-community-page.component.ts, src/app/+community-page/delete-community-page/delete-community-page.component.spec.ts, src/app/+community-page/delete-community-page/delete-community-page.component.ts, src/app/core/data/comcol-data.service.spec.ts, src/app/core/data/comcol-data.service.ts, src/app/core/data/remote-data.ts, src/app/core/shared/operators.ts, src/app/shared/comcol-forms/create-comcol-page/create-comcol-page.component.spec.ts, src/app/shared/comcol-forms/create-comcol-page/create-comcol-page.component.ts, src/app/shared/comcol-forms/delete-comcol-page/delete-comcol-page.component.spec.ts, src/app/shared/comcol-forms/delete-comcol-page/delete-comcol-page.component.ts, src/app/shared/remote-data.utils.ts
* Fixes #842 
After a collection or community is created or deleted, href request to its parent is removed from requests cache, so that list of communities or collections belonging to a given community, at any level, from top level on, has to be reloaded and new collection / community is immediately displayed in case of creation or not displayed anymore in case of deletion.
a new function named `refreshCache` has been added to `CreateComColPageComponent` and `DeleteComColPageComponent`, and it is called by the `onSubmit` function of `CreateComColPageComponent` during the flow that observes result of `DSpaceObject` creation performed by `dsoDataService`, and by the `onConfirm` function of `DeleteComColPageComponent` …
=> Communities and collections not shown right after creation

src/app/community-list-page/community-list-datasource.ts, src/app/community-list-page/community-list-service.ts, src/app/community-list-page/community-list/community-list.component.html, src/app/community-list-page/community-list/community-list.component.ts
* Fixes https://github.com/DSpace/dspace-angular/issues/899
* Fixes https://github.com/DSpace/dspace-angular/issues/908
This PR fixes the issues mentioned above.
Issue 908: where chevrons don’t appear if not page selects (appeared in dev mode)
Previously (how to recreate error):
- Go to page {dspaceUI}/community-list => immediately click out of browser => chevrons previously didn’t appear until focusing back into browser
Issue 899: where tree didn’t appear if directly going to {dspaceUI}/community-list without going via menu (only in prod mode)
Previously (how to recreate error):
- OK: navigate to home => navigate to all of dspace => communities & collection => has tree
- BUG: go directly to {dspaceUI}/community-list in new tab => Empty list
=> Should now both be fixed
_This checklist …
=> Fix com/col tree issues (#899 & #908)

.codecov.yml
As we don't require Codecov `patch` checks to succeed, I'm switching them to informational mode only.  This mode keeps the check enabled, but ensures the check **always** returns success.   See https://docs.codecov.io/docs/commit-status#informational
If this works as planned, I'm hoping this will ensure the (optional) `patch` check no longer places a red ❌ on PRs which otherwise pass all other checks.  This red ❌ is misleading, as it can make you assume the PR has a build/test failure, when it's just an optional check that failed.
(Sidenote: If this doesn't work as expected, we may need to disable `patch` checks entirely.  However, ideally, it'd be nice to keep it around if we can...the `patch` check's purpose is to check the code coverage of _just the new code added by the PR_.  So, when …
=> Switch codecov 'patch' checks to informational only

scripts/set-env.ts
Fixes #826
In #825 , the use of /api in the nameSpace of the rest server config became deprecated. A workaround was added back then in #877. This PR removes the workaround.
To verify the fix, the following steps can be performed: 
* Configure a correct nameSpace without 'api'
* Verify that the UI works
* Configure an incorrect nameSpace ending with '/api', e.g. `nameSpace: '/server/api'`
* Verify that no warning is shown and the UI does not work
=> Remove workaround for baseUrl ending in /api

src/app/core/eperson/eperson-data.service.spec.ts, src/app/core/eperson/eperson-data.service.ts, src/app/profile-page/profile-page.component.spec.ts, src/app/profile-page/profile-page.component.ts
* Fixes https://github.com/DSpace/DSpace/issues/2988
* Requires https://github.com/DSpace/DSpace/pull/3041
This PR changes the Replace PATCH operations for the EPerson Password Replacement to an Add PATCH operation as changed in the backend in the linked PR.
* Changed the REPLACE patch operations to ADD patch operations
How to test this PR:
* Setup a local backend with the linked PR's code and this PR's code
* Follow the steps in the linked issue
* Verify that everything works as expected
=> Issue 2988: Password (re)set for eperson with add PatchOperation

src/app/+collection-page/edit-collection-page/collection-curate/collection-curate.component.spec.ts, src/app/+community-page/edit-community-page/community-curate/community-curate.component.spec.ts, src/app/core/shared/collection.model.spec.ts, src/app/core/shared/collection.model.ts, src/app/core/shared/community.model.spec.ts, src/app/core/shared/community.model.ts, src/app/shared/comcol-page-handle/comcol-page-handle.component.spec.ts, src/app/shared/comcol-page-handle/comcol-page-handle.component.ts, src/app/shared/dso-selector/modal-wrappers/export-metadata-selector/export-metadata-selector.component.spec.ts, src/app/shared/search-form/search-form.component.spec.ts, src/app/shared/search/search-results/search-results.component.spec.ts
* Fixes [#887](https://github.com/DSpace/dspace-angular/issues/887)
* Requires DSpace/DSpace [#3046](https://github.com/DSpace/DSpace/pull/3046)
The Community and Collection rest repositories should now return the handle value inside the metadata attribute 'dc.identifier.uri'. We ensure that that value is presented in place of the previously used handle field.
The community and community objects have been enhanced with a getter method for the handle field. The getter takes care of fetching the value from the metadata. The old value is still stored in a private field (_handle) but never used.
=> Metadata identifier for Communities and Collections 

.github/workflows/build.yml
* Replaces https://github.com/DSpace/dspace-angular/pull/958
* Updates original PR #956 
* Copy of https://github.com/DSpace/DSpace/pull/3072 (backend PR of the same type)
Based on discussion in Slack & PR https://github.com/DSpace/DSpace/pull/3069 , this just updates our `build.yml` to run on every push/PR to the current branch.  @abollini pointed out (in Slack) that this seems to be the ideal build process, as GitHub is smart enough to only use the `build.yml` for the current branch.
=> Update build.yml to not limit by branch

src/assets/i18n/ar.json5, src/assets/i18n/cs.json5, src/assets/i18n/de.json5, src/assets/i18n/en.json5, src/assets/i18n/es.json5, src/assets/i18n/fi.json5, src/assets/i18n/fr.json5, src/assets/i18n/ja.json5, src/assets/i18n/lv.json5, src/assets/i18n/nl.json5, src/assets/i18n/pl.json5, src/assets/i18n/pt.json5, src/assets/i18n/sw.json5, src/assets/i18n/tr.json5
https://github.com/DSpace/DSpace/pull/2780
This small PR fixex i18n keys as required in 
https://github.com/DSpace/DSpace/pull/2780#pullrequestreview-533946575
- [X ] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
=> replaced orcidV2 label keys with orcid

docker/README.md, docker/cli.assetstore.yml, docker/cli.ingest.yml, docker/cli.yml, docker/db.entities.yml, docker/docker-compose-ci.yml, docker/docker-compose-rest.yml, docker/docker-compose.yml
The Docker compose scripts in the Angular UI have become outdated, and were never updated when the Entities test data set was updated on the backend in https://github.com/DSpace/DSpace/pull/2623
This means that the data set being used for `e2e` tests in GitHub CI is outdated, and this has recently resulted in errors which are not reproducible on the more recent Entities test data set. For example in https://github.com/DSpace/dspace-angular/pull/961/checks?check_run_id=1524916589
This PR updates all Docker compose scripts to include:
* Comments describing / linking back to related dockers scripts (in backend project)
* Updates Entities data sets to the same ones used by Backend.
* Other minor updates to sync the scripts with related backend scripts (as necessary)
=> Sync Docker compose scripts with backend (DSpace/DSpace)

src/app/+item-page/simple/related-entities/related-entities-search/related-entities-search.component.spec.ts, src/app/shared/utils/relation-query.utils.spec.ts, src/app/shared/utils/relation-query.utils.ts
* Fixes #966 
Altering the item view relationship queries to use exact matching for the UUID of the item. 
See the issue for detailed instructions
=> Item view relationship query fix

src/app/core/data/entity-type.service.ts
Fixes https://github.com/DSpace/dspace-angular/issues/964
=> issue 964 properly impl getEntityTypeByLabel

README.md, docs/Configuration.md, src/environments/environment.common.ts
Update mentions in config and docs of the default rest hostname to api7.dspace.org
=> Update the rest hostname to api7.dspace.org

src/app/+collection-page/collection-page.component.ts, src/app/shared/pagination/paginationChangeEvent.interface.ts
Fixes #680 
I've updated the event change references to valid ones so the `onPaginationChange(event)` functions properly. Tested my additions in my local environment.
NOTE: The following error was reported before my changes but seems rather strange that this particular error is still present in my console given I've seen the pattern I used elsewhere in the code base without such an error. It's unclear to me why `paginationConfig` properties throw an error when attempting to be set. Would be great to get some insight on this: 
`core.js:4002 ERROR TypeError: Cannot read property 'currentPage' of undefined
at CollectionPageComponent.push../src/app/+collection-page/collection-page.component.ts.CollectionPageComponent.onPaginationChange (collection-page.component.ts:112)
at …
=> 680 Fix change event reference for recent submission

server.ts
* Fixes #1002
Replaces the relative path to index.html for the CSR fallback in server.ts with an absolute path
Disable preboot, build in mode and verify that the CSR fallback works now.
=> Fix prod mode with preboot disabled

src/app/+collection-page/collection-item-mapper/collection-item-mapper.component.html, src/app/+collection-page/collection-item-mapper/collection-item-mapper.component.spec.ts, src/app/+collection-page/collection-item-mapper/collection-item-mapper.component.ts, src/app/+collection-page/collection-page-routing.module.ts, src/app/+collection-page/edit-collection-page/edit-collection-page.routing.module.ts, src/app/+item-page/edit-item-page/edit-item-page.routing.module.ts, src/app/+item-page/edit-item-page/item-collection-mapper/item-collection-mapper.component.html, src/app/+item-page/edit-item-page/item-collection-mapper/item-collection-mapper.component.spec.ts, src/app/+item-page/edit-item-page/item-collection-mapper/item-collection-mapper.component.ts, src/assets/i18n/en.json5
* Fixes #974
* Depends on #975
This PR fixes the item and collection mapper pages created in #348 and adds links to them as tabs on the respective edit collection and edit item pages as tabs. 
This PR seems a lot bigger than it is, because it depends on #975 You can see only the changes in this PR [here](https://github.com/atmire/dspace-angular/compare/cache-redesign-part-2...atmire:collection-mapper)
Go to a collection edit page > Item Mapper tab:
Try to map new items to the collection and remove some of them.
Go to one of the mapped items > edit page > Collection Mapper tab:
Your previous collection should be present in mapped collections.
Try to add/remove mapped collections of item on collection mapper tab.
=> Collection mapper

src/app/app.module.ts, src/app/core/auth/auth.service.ts, src/app/core/xsrf/xsrf.interceptor.spec.ts, src/app/core/xsrf/xsrf.interceptor.ts
* Replaces #833 (Based heavily on this PR)
* Replaces #907 
* Requires https://github.com/DSpace/DSpace/pull/3103
This PR creates a customized `XsrfInterceptor` which responds to the Backend/Server Webapp based on the custom CSRF Protection added in https://github.com/DSpace/DSpace/pull/3103
Namely, the behavior is as follows:
1. Backend generates XSRF token & stores in a *server-side* (only) cookie named `DSPACE-XSRF-COOKIE`. This cookie is **not** read/used by Angular, but is returned (by user's browser) on every subsequent request to backend.
2. Backend also sends XSRF token in a header named `DSPACE-XSRF-TOKEN` to Angular.
3. A custom `XsrfInterceptor` looks for `DSPACE-XSRF-TOKEN` header in a response. If found, its value is saved to a *client-side* (only) cookie named `XSRF-TOKEN`. …
=> Enable Customized CSRF Protection in Angular UI

package.json, src/app/core/data/relationship-type.service.spec.ts, src/app/core/data/relationship-type.service.ts, src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/dynamic-lookup-relation-modal.component.html, src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/dynamic-lookup-relation-modal.component.spec.ts, src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/dynamic-lookup-relation-modal.component.ts, src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/relationship.effects.spec.ts, src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/relationship.effects.ts, src/app/shared/form/builder/models/relationship-options.model.ts, src/app/shared/object-list/selectable-list/selectable-list.service.ts, src/app/submission/submission.module.ts, src/assets/i18n/en.json5
- Fixes #943
- Depends on #975
- The configured REST API requires [PR #3109](https://github.com/DSpace/DSpace/pull/3109) for the external sources to be limited.
Currently, the lookup window for relationships during submission displays all the available external sources to import from, even sources that don't match the field you're trying to import a relationship to.
This PR aims to only display only the configured external sources depending on the [new configuration returned by the REST API](https://github.com/DSpace/DSpace/pull/3109), as well as display error notifications when creating the relationship fails.
This PR seems a lot bigger than it is, because it depends on #975 You can see only the changes in this PR [here](https://github.com/atmire/dspace-angular/compare/cache-redesign-part …
=> Submission external sources limited on metadata field

src/app/+admin/admin-access-control/group-registry/group-form/group-form.component.ts, src/app/+admin/admin-access-control/group-registry/group-form/members-list/members-list.component.html, src/app/+admin/admin-access-control/group-registry/group-form/members-list/members-list.component.ts, src/app/+admin/admin-access-control/group-registry/group-form/subgroup-list/subgroups-list.component.ts, src/app/+admin/admin-access-control/group-registry/groups-registry.component.html, src/app/+admin/admin-access-control/group-registry/groups-registry.component.ts, src/app/core/eperson/eperson-data.service.ts, src/app/core/eperson/models/eperson-dto.model.ts, src/app/core/eperson/models/group-dto.model.ts, src/app/core/eperson/models/group.model.ts, src/app/core/shared/dspace-object.model.ts, src/assets/i18n/en.json5
* Fixes #962
The 404 errors in network tab (dev tools) should no longer appear when you start a new group, nor when you delete a group from the group repository. Some refactoring with DTO's to prevent unneeded calls.
- Open dev tools network tab & log in as admin
- Go to groups registry at /admin/access-control/groups
- 1. "+ Add group" to add a new group => No 404 errors in network tab
- 2. When deleting a group from the groups registry view => No 404 error in network tab (for /object /epersons and /subgroups)
=> Fix unnecessary calls when creating/deleting groups

src/app/+search-page/configuration-search-page.component.spec.ts, src/app/+search-page/configuration-search-page.component.ts, src/app/+search-page/search.component.spec.ts
* Fixes #1016
Reset the Store values of `fixedFilterQuery` and `properties` to `undefined` when `ConfigurationSearchPageComponent` gets destroyed to prevent them from carrying over
Verifying the fix:
* Open a page with a `ConfigurationSearchPageComponent` (e.g. https://demo7.dspace.org/items/4b0bb46a-9086-4398-a6b4-09840404d8dc)
* (Optional: execute a query from the search form)
* Go to the search page
* Results for an empty query should be shown instead of the results of the previous page
* [`ConfigurationSearchPageComponent` resets the `RouteService` parameters set in `ngOnInit()` back to `undefined` in `ngOnDestroy()`](https://github.com/DSpace/dspace-angular/compare/main...atmire:w2p-769 …
=> Fix: Search filter from entity page carries over to discovery

src/app/core/config/models/config-access-condition-option.model.ts, src/app/core/submission/models/submission-upload-file-access-condition.model.ts, src/app/shared/mocks/submission.mock.ts, src/app/submission/sections/upload/accessConditions/submission-section-upload-access-conditions.component.html, src/app/submission/sections/upload/file/edit/section-upload-file-edit.component.spec.ts, src/app/submission/sections/upload/file/edit/section-upload-file-edit.component.ts, src/app/submission/sections/upload/file/edit/section-upload-file-edit.model.ts, src/app/submission/sections/upload/file/section-upload-file.component.html, src/app/submission/sections/upload/file/section-upload-file.component.spec.ts, src/app/submission/sections/upload/file/section-upload-file.component.ts, src/app/submission/sections/upload/section-upload.component.html, src/app/submission/sections/upload/section-upload.component.spec.ts, src/app/submission/sections/upload/section-upload.component.ts
* Angular part of [DSpace/dspace-angular#869](https://github.com/DSpace/dspace-angular/issues/869) (Does not fully fix issue though)
* Related to [REST Contract](https://github.com/DSpace/Rest7Contract/pull/152)
* Related to https://github.com/DSpace/DSpace/pull/3136
This is the Angular part to fix the embargo bug [DSpace/dspace-angular#869](https://github.com/DSpace/dspace-angular/issues/869)
It removes the group select as discussed in the issue and REST contract
Keep in mind for this change, the REST part is also required. The REST contract details how the access conditions can be defined
* The 'groupUUID' and 'selectGroupUUID' fields have been removed from the AccessConditionOption model, which is used by the SubmissionUploadModel, for which the contract has been changed
* The …
=> fix #869 Submission embargo bug

src/app/+item-page/edit-item-page/edit-item-page.routing.module.ts
* Fixes #1005 
See #1005 for bug description. This simply comments out those tabs as they are currently unimplemented.  (The TODO comments already existed, I just moved them around the entire tab definition.)
* Review code
* Optionally, test the Edit Item screen to ensure those tabs no longer appear (I've already done this myself).
=> Comment out Edit Item tabs which are not yet implemented.

src/assets/i18n/en.json5
* Fixes #1010
As described in ticket, removes keys that are duplicated in `en.json5`.  
Also renamed `administrativeView.search.results.head` to be simply `admin.search.results.head` (and corrected `admin-search-page.component.html` to support that change), as this places it alphabetically alongside the other Admin Search keys.
* Review changes
* Optionally test Admin Search & Profile to verify no keys are missing.
=> Cleanup duplicative or incorrect Angular UI i18n keys

src/app/+my-dspace-page/my-dspace-new-submission/my-dspace-new-submission.component.spec.ts, src/app/core/xsrf/xsrf.interceptor.spec.ts, src/app/core/xsrf/xsrf.interceptor.ts, src/app/shared/mocks/http-xsrf-token-extractor.mock.ts, src/app/shared/uploader/uploader.component.spec.ts, src/app/shared/uploader/uploader.component.ts
* Fixes #1023 
* Relates to #977  
As noted in #1023, after merging PR #977 to add CSRF protection, all file uploads are failing with a `403 Forbidden: Access is denied. Invalid CSRF token.` error.
The reason for this error is that our current upload library (`ng2-file-upload`) doesn't currently support Angular Http Interceptors (like our `xsrf.interceptor.ts` which manages CSRF/XSRF tokens for all parts of our Angular app).  This is a known issue in `ng2-file-upload` for many years and described in more detail at https://github.com/valor-software/ng2-file-upload/issues/950
I've solved this issue in our `Uploader` component by _temporarily_ duplicating much of the logic of our `xsrf.interceptor.ts` into the `uploader.component.ts`.  This includes the following logic:
* Added logic to …
=> Add CSRF support to uploader Component

src/app/community-list-page/community-list-service.ts, src/app/core/data/comcol-data.service.ts, src/app/core/data/community-data.service.ts, src/app/core/data/data.service.spec.ts, src/app/core/data/data.service.ts, src/app/core/data/dspace-rest-response-parsing.service.ts, src/app/core/index/index.selectors.spec.ts, src/app/core/index/index.selectors.ts
* Fixes https://github.com/DSpace/dspace-angular/issues/918
* See also DSpace/DSpace#3174
The communities and collections expandable tree at {baseUrl}/community-list has been refactored so the requests required to find out if a node in the tree has children (i.e. if a community has sub-communities or collections) are now embedded in the initial request with the new embed and nested embed size functionalities. (see https://github.com/DSpace/DSpace/pull/3114)
This should reduce the number of requests needed for rendering the ComCol tree nodes and their shevrons to the ones mentioned in the review instructions (fixes issue https://github.com/DSpace/dspace-angular/issues/918)
Might be an issue with the embed sizes resulting in non-identical result alternative links (see …
=> Use of embed sizes in the ComCol tree

scripts/set-env.ts, src/app/core/shared/metadata.utils.ts
* Fixes https://github.com/DSpace/dspace-angular/issues/909
This PR ensures that you can merge the common environment with the dev environment. Any values that are specified in the dev environment, will be getting priority over the common profile. If any properties aren't present in the dev file, they'll be taken from the common file.
This PR also ensures that lists are taken from the dev file as a whole if they're present, this means that lists like the "Languages" list, won't be merged anymore. All the values will be taken from the dev file and the list in the common file will be ignored if the list is present in the dev file.
We decided against converting the arrays to objects as that'd mean that we'd have to specifically set each object to null if we didn't want to include it anymore. …
=> Environment files merging with overwriteMerge

.github/workflows/build.yml
After some testing, I've realized the issues with the e2e tests randomly timing out **are related to the REST API backend** which is kicked off via Docker.
The e2e timeouts appear to occur when the e2e tests start running **before** the REST API backend has completed it's startup process.  In other words, there is a small window where the Docker container has already successfully started, but the REST API is not yet available at http://localhost:8080/server/ because Tomcat has not finished booting up.   
I was able to verify this by adding a simple `curl http://localhost:8080/server/api' (see https://github.com/DSpace/dspace-angular/pull/1068/commits/12f8e82aa23b6236ce447377a64d1732c00d20cb). I found that command returns a Tomcat 404 error when e2e tests end up timing out, but it returns …
=> Ensure REST API is up/available for e2e tests

src/app/app.component.spec.ts, src/app/app.component.ts, src/app/breadcrumbs/breadcrumb/breadcrumb-config.model.ts, src/app/breadcrumbs/breadcrumbs.component.html, src/app/breadcrumbs/breadcrumbs.component.spec.ts, src/app/breadcrumbs/breadcrumbs.component.ts, src/app/breadcrumbs/breadcrumbs.service.spec.ts, src/app/breadcrumbs/breadcrumbs.service.ts, src/app/core/breadcrumbs/breadcrumbsProviderService.ts, src/app/core/breadcrumbs/dso-breadcrumbs.service.ts, src/app/core/breadcrumbs/i18n-breadcrumbs.service.ts, src/app/process-page/process-breadcrumbs.service.ts
Fixes #982
Because `ngOnInit` for `BreadcrumbsComponent` was called after the component was created (so as part of the routing operation), there was a race condition between the component and the first routing event. Most of the time `ngOnInit` got called before the `NavigationEnd` event. But sometimes it didn’t. It most frequently didn’t for the first client-side page render because all the data needed for the route is already in cache. That makes the first client-side routing operation a lot faster than average.
The solution was to listen for route changes _before_ routing.
Most logic of `BreadcrumbsComponent` was moved to a new service `BreadcrumbsService`. The init code of this service is called in `AppComponent`, such that it is run before routing, hence no routing events are missed. …
=> Fix trail not showing on item pages

src/app/core/data/comcol-data.service.spec.ts, src/app/core/data/data.service.spec.ts, src/app/core/data/data.service.ts, src/app/core/tasks/tasks.service.ts
* Fixes #1027
If you try to retrieve an object that is cached but stale. It will automatically be re-retrieved and the stale version in the cache will be overwritten. However currently it is possible in rare circumstances to still get that stale object returned first, before you the re-retrieved version. That means that if you add e.g. the getFirstCompletedRemoteData operator in line, that first stale object is the only one that you'll ever get.
This PR ensures that a stale object can no longer be emitted first from a findBy method on a dataservice. When useCachedIfAvailable is false, it also ensures a cached, completed (but not stale) object can't be emitted first.
This issue is hard to recreate, because in most cases the new request replaces the old one in the store almost immediately. …
=> Fix issue where stale RemoteData is emitted first

src/app/submission/submit/themed-submission-submit.component.ts
* Fixes issue introduced by #1042
After #1042 was merged the submission page would crash when creating a new submission, due to a mistake in the component name in ThemedSubmissionSubmitComponent
Using this PR the submission should no longer crash, with or without a theme.
=> Fix issue where the themed submission page would crash 

src/app/+collection-page/collection-page-routing-paths.ts, src/app/+collection-page/edit-collection-page/collection-metadata/collection-metadata.component.spec.ts, src/app/+collection-page/edit-collection-page/collection-metadata/collection-metadata.component.ts, src/app/+collection-page/edit-item-template-page/edit-item-template-page.component.html, src/app/+collection-page/edit-item-template-page/edit-item-template-page.component.spec.ts, src/app/+collection-page/edit-item-template-page/edit-item-template-page.component.ts, src/app/+item-page/edit-item-page/abstract-item-update/abstract-item-update.component.ts, src/app/core/data/item-template-data.service.ts, src/assets/i18n/en.json5
* Fixes https://github.com/DSpace/dspace-angular/issues/1034
This PR fixes all the bugs listed in the above mentioned issue with regards to the Collection's item template
* Ensured that the Item template is getting used in the edit template item screen instead of the collection's metadata
* Ensured that adding/deleting metadata works properly without errors
* Ensured that the delete call only returns one notification
How to test this PR
* Build this Angular branch
* Go to a collection and create an Item template
* Add and delete metadatavalues, ensure that it works
* Delete the item template afterwards, ensure that only one notification is shown
=> Bugs on Collection Item Template fix

src/app/+item-page/edit-item-page/edit-item-page.component.html, src/app/+item-page/edit-item-page/edit-item-page.component.spec.ts, src/app/+item-page/edit-item-page/edit-item-page.component.ts, src/app/+item-page/edit-item-page/edit-item-page.routing.module.ts, src/app/+item-page/item-page-edit-metadata.guard.ts, src/app/+item-page/item-page-routing.module.ts, src/app/core/data/feature-authorization/feature-authorization-guard/dso-page-feature.guard.spec.ts, src/app/core/data/feature-authorization/feature-authorization-guard/dso-page-feature.guard.ts, src/app/shared/dso-page/dso-page-edit-button/dso-page-edit-button.component.html, src/assets/i18n/en.json5
- Fixes #1047
- Lays groundwork for #1073
- Related to https://github.com/DSpace/DSpace/issues/3201
This PR moves the permission checks for the edit item page to its sub-pages.
Each page located at `/edit/*` now has its own guard to check for the required permissions.
For this PR, only the authorization features `canEditMetadata` and `administratorOf` were considered. 
This can be fairly easily extended to consider all authorization features once https://github.com/DSpace/DSpace/issues/3201 has been implemented and there's a decision made on the mapping mentioned in #1073.  
The pages located at `/edit/metadata` and `/edit/relationships` are shown to users that have canEditMetadata permissions on the item, all other `/edit/*` pages are only shown to users that have `administratorOf` …
=> Edit item page permissions fixes

src/app/+lookup-by-id/lookup-guard.spec.ts, src/app/+lookup-by-id/lookup-guard.ts
* Fixes https://github.com/DSpace/DSpace/issues/3113
This PR fixes the handle redirect issue. This means that navigating to `http://localhost:4000/handle/{handle}` will now properly redirect to the Item page
* Added a "hdl:" prefix to the handle before being sent to the pid endpoint in REST
How to test this PR:
* Please set up this Angular branch
* Please set up the REST branch from this PR: https://github.com/DSpace/DSpace/pull/3194
* Navigate to {dspace.url}/handle/{handle} in Angular for a handle that's connected to an Item in the REST API
* Verify that you get redirected to the Item page
=> Handle redirect for items not working fix

src/app/core/auth/auth.interceptor.ts, src/app/core/shared/metadata.utils.spec.ts, src/app/core/shared/metadata.utils.ts
* Fixes https://github.com/DSpace/dspace-angular/issues/876
This PR ensures that the LGTM issues are either resolved or ignored.
* Either fix the issues that LGTM reported or added an ignore line
This PR can be tested by inspecting LGTM and ensuring that no security issues are shown
=> Fix or address string escaping / replacement issues reported by LGTM

src/app/core/registry/registry.service.spec.ts, src/app/core/registry/registry.service.ts
* Fixes #1067
* Angular counterpart of REST PR: https://github.com/DSpace/DSpace/pull/3205
The call to create a new metadatafield previously sent an empty string for the qualifier if no value was provided.
This leads the backend to create a metadatafield with an empty string, instead of the customary `null` value.
On the backend side -> This is currently being addressed in the PR mentioned above as well (So that other UI-specific solutions don't need to specifically 'know' not to send an empty qualifier)
On the Angular side, we make sure to 'transform' the empty qualifier to a `null` value
Please add a more detailed description of the changes made by your PR. At a minimum, providing a bulleted list of changes in your …
=>  UI sends wrong request when creating new metadata field without qualifier

src/app/+item-page/edit-item-page/item-delete/item-delete.component.spec.ts, src/app/+item-page/edit-item-page/item-delete/item-delete.component.ts
* Fixes https://github.com/DSpace/dspace-angular/issues/1054
When an entity type has no existent relations the item deletion is not executed. This case has been handled and we can now proceed further even without related types.
To validate this PR the steps to reproduce the behavior can be followed as described in the related issue https://github.com/DSpace/dspace-angular/issues/1054
=> Error deleting an item when its entity type has no relations

src/app/shared/mocks/submission.mock.ts, src/app/shared/uploader/uploader.component.ts, src/app/submission/form/submission-form.component.html, src/app/submission/form/submission-form.component.spec.ts, src/app/submission/form/submission-form.component.ts, src/app/submission/sections/sections.service.spec.ts, src/app/submission/sections/sections.service.ts
* Fixes #957
* Fixes #849
- The dropzone on the submission form will no longer be rendered when the submission form does not include an upload section.
- When a file is dropped on the submission forms dropzone, the page will not automatically scroll to the top of the age anymore. The dropzone and its progress bar is now always visible at the top of the page, similar to the collection dropdown.  
- Collections without an upload section in their form definition, should no longer show the dropzone on their submission page
- Dropping a file anywhere on the submission page should no longer cause the page to scroll up, but should always show the progress bar at the top of the page, independently from the user's current scroll position.
=> Submission dropzone issues

src/app/core/shared/operators.ts, src/app/shared/form/builder/ds-dynamic-form-ui/ds-dynamic-form-control-container.component.html, src/app/submission/edit/submission-edit.component.spec.ts, src/app/submission/edit/submission-edit.component.ts, src/app/submission/submit/submission-submit.component.spec.ts, src/app/submission/submit/submission-submit.component.ts
* Fixes #1094
* ~Depends on #1092~
* ~Requires DSpace/DSpace#3224~
This PR will auto update the item input in the submission form when the item changes. That way, when a relationship is added the form will update.
It will also fix an issue where the lookup button wasn't shown for repeatable relationship only fields, when they already had a value
You can test this PR by verifying that relationships can be added and removed regardless of whether they're for a mixed field.
~This PR seems bigger than it is, because it depends on #1092 You can see only the changes in this PR [here](https://github.com/atmire/dspace-angular/compare/4Science:CST-3782-final-adjustments...atmire:fix-1094)~
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not …
=> Fix support for adding and removing relationships in relationship-only fields in the submission

src/app/+home-page/home-news/home-news.component.html, src/app/footer/footer.component.html, src/app/shared/lang-switch/lang-switch.component.spec.ts, src/assets/i18n/ar.json5, src/assets/i18n/cs.json5, src/assets/i18n/de.json5, src/assets/i18n/en.json5, src/assets/i18n/es.json5, src/assets/i18n/fi.json5, src/assets/i18n/fr.json5, src/assets/i18n/hu.json5, src/assets/i18n/ja.json5, src/assets/i18n/lv.json5, src/assets/i18n/nl.json5, src/assets/i18n/pl.json5, src/assets/i18n/pt-BR.json5, src/assets/i18n/pt-PT.json5, src/assets/i18n/sw.json5, src/assets/i18n/tr.json5, src/themes/dspace/app/+home-page/home-news/home-news.component.html
Replaces #1089.
This makes minor updates to the "base" theme to replace usages of DuraSpace with LYRASIS.
It also updates our "dspace" theme to display the Testathon message that @bram-atmire created in #1089.  I simply moved this code into the "dspace" theme so that it would be used by default (as that's the default theme).
=> Minor updates to base and dspace theme for Testathon.

src/app/submission/sections/license/section-license.component.html
Render html in the license section of the submission form.
1. Change `dspace/config/default.license` to contain html.
2. Submit a new item. The html should be rendered correctly in the license section of the form.
**Before**
**After**
=> Quick win: Allow html in license section of submission form

docker/cli.assetstore.yml, docker/db.entities.yml, docker/docker-compose-ci.yml, docker/docker-compose-rest.yml
The Docker Compose scripts in `DSpace/dspace-angular` have become slightly out of sync with those in `DSpace/DSpace`.
This PR syncs them back up, namely by updating the following:
1. Porting https://github.com/DSpace/DSpace/pull/3225 to dspace-angular
2. Updating dspace-angular compose scripts to use Solr 8.x, as we forgot to modify the scripts in this repository after https://github.com/DSpace/DSpace/pull/3020 was merged.
The best test for these changes is the GitHub CI.  I'll also run manual testing via Docker to verify it's working properly & report back in the comments.
=> Update Docker Compose scripts to resync with DSpace/DSpace

src/app/header-nav-wrapper/header-navbar-wrapper.component.scss
* Fixes #1111 
This PR resolve issue with nav menu that wasn't shown when navbar is collapsed
- Load up homepage
- Drag window to be very small, until the 3-line menu option appears in upper right.
- Click it and check the menu is shown.
=> Fix visibility issue with collapsed navbar menu

src/app/+browse-by/+browse-by-switcher/browse-by-decorator.ts, src/app/+browse-by/+browse-by-switcher/browse-by-switcher.component.spec.ts, src/app/+browse-by/+browse-by-switcher/browse-by-switcher.component.ts, src/app/+item-page/simple/item-types/shared/item-relationships-utils.ts, src/app/core/cache/builders/build-decorators.ts, src/app/core/cache/builders/link.service.spec.ts, src/app/core/cache/builders/link.service.ts, src/app/core/data/relationship.service.spec.ts, src/app/core/data/relationship.service.ts, src/app/core/shared/operators.ts, src/app/shared/cookies/browser-klaro.service.spec.ts, src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/relationship.effects.spec.ts, src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/relationship.effects.ts, src/app/shared/metadata-representation/metadata-representation-loader.component.spec.ts, src/app/shared/metadata-representation/metadata-representation-loader.component.ts, src/app/shared/metadata-representation/metadata-representation.decorator.ts
* Fixes #992
* Fixes #993
This PR fixes a number of tests that were broken or disabled due to the Angular 10 upgrade.
Changes made:
- Created injector for every exported function that requires testing, so we can inject it into the component and spy on the injected property from our test cases
- Fixed all test cases that were disabled with `xdescribe` using this approach
- Reverted changes to `relationship.effects.spec.ts` related to debounceTime, added an InjectionToken for the operator and injected it into the effects. Modified the test cases to create a spy on this injected operator.
How to test:
- The test cases should all succeed.
- Related UI pages should be unaffected by the changes, e.g. item pages containing relationships, edit relationships page...
_This checklist provides a …
=> Angular 10 upgrade test fixes

src/app/core/data/eperson-registration.service.spec.ts, src/app/core/data/eperson-registration.service.ts, src/app/forgot-password/forgot-password-form/forgot-password-form.component.ts
- Fixes #1113
Fixed "Forgot Password" page getting replaced with (stuck) loading animation
- Fixed issue in `EpersonRegistrationService#searchByToken` 
- Requests for cached `Registration` objects don't get sent
- The method tried to use the UUID of these unsent requests to retrieve the `Registration`
- Added a unit test to cover this scenario
- Fixed a double notification when submitting the form
**Reviewing:**
1. Create a new account (if needed) at https://demo7.dspace.org/ (or locally)
2. Use the "Forgot Password" page.
3. Password reset link will be sent via email
4. Click the link. The Forgot Password page should appear (and stay up).
=> Fix forgot password page

src/app/+item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.ts, src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/dynamic-lookup-relation-modal.component.spec.ts, src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/dynamic-lookup-relation-modal.component.ts
* Fixes #1103
Remove submission-based initialization of `DsDynamicLookupRelationModalComponent#item`
* Removed `DsDynamicLookupRelationModalComponent#setItem` 
* Along with calls, services & `subs` attribute
* Removed services from unit tests
* When opening a relationship lookup modal from `EditRelationShipListComponent`, set the modal's `collection` to the owning Collection of the Item being edited
**Reviewing**
1. Authenticate as an admin
2. Edit an item. Open its "Relationships" tab. Click on any of the "Add" buttons. 
The relationship lookup modal should open (and not get stuck in the "loading" animation)
3. Open a submission in a collection with lookup enabled. Click on the lookup button next to the field
The relationship lookup modal should open (and not get stuck in the "loading" …
=> Fix relationship modal on item page

src/app/+my-dspace-page/my-dspace-configuration.service.spec.ts, src/app/core/shared/search/search-configuration.service.spec.ts, src/app/core/shared/search/search-configuration.service.ts, src/app/shared/search/paginated-search-options.model.spec.ts, src/app/shared/search/search-filters/search-filter/search-filter.component.ts, src/app/shared/search/search-filters/search-filter/search-range-filter/search-range-filter.component.scss, src/app/shared/search/search-filters/search-filter/search-range-filter/search-range-filter.component.ts, src/app/shared/search/search-options.model.spec.ts, src/app/shared/search/search-options.model.ts, src/styles/_custom_variables.scss
* Fixes #1112
Fix filtering by date range
* `_custom_variables.scss`: Initialize `--ds-slider-handle-width: 18px; ` so the handles show up as handles instead of just lines
* Add an `'equals'` operator to range filters. 
This used to be optional, but now the backend returns 422 if no operator is specified.
* Set the fallback max date to the current year (used to be 2018)
* Fix horizontal position of vertical lines in range handles (were forced all the way to the left)
* Fix `.search-filter-wrapper` getting stuck with `.closed` when actually in open state
**Reviewing**
1. Search on https://demo7.dspace.org/ or a local instance
2. Filter by date (range) -- results should load and be filtered by the specified date (range).
3. Drag the 'max' handle all the way to …
=> Fix date filter bugs

src/app/access-control/group-registry/group-form/group-form.component.spec.ts, src/app/access-control/group-registry/group-form/group-form.component.ts
Fixes #1127
When navigating away from an "edit group" page (Access Control), the group list would be shown, regardless of user intentions. This PR eliminates a call to `router.navigate` such that navigation works again as intended.
- Log into DSpace
- Open the group list (sidebar > Access Control > Groups)
- Open the edit page of any group
- Navigate to any page and observe that the expected page is opened. (Without this PR, the group list would always open.)
=> Fix edit group navigation bug

src/app/+admin/admin-sidebar/admin-sidebar.component.ts
Fixes #1125
Fixes #1019 (by removing disabled features)
Fixes #1155 (by removing disabled features)
- Removed duplicate `curation_tasks` menu item because it would be overridden by [this item](https://github.com/atmire/dspace-angular/blob/fe4fe9e8d34fff27a9def8ad483f6170f09176d8/src/app/%2Badmin/admin-sidebar/admin-sidebar.component.ts#L497) anyway.
- Commented out all menu items that currently don't have a link defined.
Log into DSpace and verify that all disabled menu items are gone from the sidebar.
=> Remove menu options for disabled features

src/app/shared/dso-selector/dso-selector/authorized-collection-selector/authorized-collection-selector.component.spec.ts, src/app/shared/dso-selector/dso-selector/authorized-collection-selector/authorized-collection-selector.component.ts, src/app/shared/dso-selector/dso-selector/dso-selector.component.html, src/app/shared/dso-selector/dso-selector/dso-selector.component.spec.ts, src/app/shared/dso-selector/dso-selector/dso-selector.component.ts, src/assets/i18n/en.json5
* Fixes #1114
I wasn't able to reproduce the exact issue from #1114. I suspect it was caused by a corrupt discovery index in the rest side. But this PR should address the strange behaviours from #1114 and fix them to give more feedback to the user.
**Changes / Fixes**
- The first time you load the list, an "empty" message would appear before the list pops up. This should now be replaced by a proper loading indicator until the list is loaded.
- Scrolling down to the bottom of the list would not directly load the next page, but still display a loading indicator as if it was. The "fake" loading indicator is now removed and replaced by one that only appears when a next page is actually loading. Also fixed the issue of the next page not starting to load when we reach the bottom of the list.
- …
=> Fix dso-selector issues

src/app/+admin/admin-import-metadata-page/metadata-import-page.component.spec.ts, src/app/+admin/admin-import-metadata-page/metadata-import-page.component.ts, src/app/shared/dso-selector/modal-wrappers/export-metadata-selector/export-metadata-selector.component.spec.ts, src/app/shared/dso-selector/modal-wrappers/export-metadata-selector/export-metadata-selector.component.ts
- Fixes #1132
- Fixes #1133
- Depends on https://github.com/DSpace/DSpace/pull/3276
- Remove `-e` option from `MetadataImportPageComponent`, fix tests and simplify code.
- Remove `-f` option from `ExportMetadataSelectorComponent`, fix tests and simplify code.
- Pass uuid (instead of handle) to `ExportMetadataSelectorComponent`
Make sure metadata import and export work again.
=> Update metadata import export script params

.github/workflows/build.yml
This PR fixes our CI build by pinning us to Chrome/ChromeDriver v90, at least until this bug with ChromeDriver v91 is fixed: https://bugs.chromium.org/p/chromium/issues/detail?id=1205107
As you'll see in the code changes, I've decided to make this configurable based on whether a `CHROME_VERSION` environment variable is specified at the top of our `build.yml`.  
* When specified, we pin to that version of Chrome & manually install a compatible version of ChromeDriver.  (I found that we had to do a manual install in this scenario, as our usual tools would not work to downgrade.)
* If that variable is unspecified, we default to installing the latest stable version of both.
This PR only impacts the automated CI, so assuming GitHub Actions succeeds this can be merged.
=> Add option to pin to a specific version of Chrome/ChromeDriver in our CI process

src/app/core/browse/browse.service.spec.ts, src/app/core/browse/browse.service.ts
Fixes DSpace/DSpace#3230 (Angular part)
Encode URI characters when constructing url in browse.service.ts.
Before this change, e.g. https://demo7.dspace.org/browse/author?bbm.rpp=100&value=Biomolecular%20%26%20Analytical%20Mass%20Spectrometry%20(BAMS) does not show any items.
After this change the same page should show 4 items.
=> Escape browse by author data requests

src/app/core/submission/submission-cc-license-url-data.service.ts
* Fixes #1208 
Fix the name of the search link from submissioncclicenseUrls
Enable the cclicense step and try to use it. Without this fix anwers to the cc questions will not lead to a license selection.
=> Fix the rel name for the submissioncclicenseUrls-search link

angular.json, src/app/app.component.html, src/app/app.component.ts, src/app/root/root.component.html, src/app/root/root.component.spec.ts, src/app/root/root.component.ts, src/app/root/themed-root.component.ts, src/index.html, src/styles/_global-styles.scss, src/styles/startup.scss
* Fixes #1093
* Fixes #1134
This PR creates a separate dedicated css file that contains only the style needed to render the full screen loader. That's all that's shown before the theme is loaded by angular, so this way we no longer have to hardcode any theme into index.html, fixing #1093 
It also shows the full screen loader when themes are switched, preventing the brief flash showing the header in the old theme reported in #1134
To test this PR: 
- configure two themes that have noticeably different background colors for the header. 
- confiture one (Theme A) to match a specific route, the other (Theme B) to be the fallback for all other routes
- open the route that matches Theme A
- navigate to a route that matches theme B
- Verify that you see all components in Theme A, followed by a …
=> Fix theme switching issues

src/themes/dspace/app/+home-page/home-news/home-news.component.html
Tiny change to update `home-news.component.html` in our `dspace` theme to no longer reference Testathon or Beta 5.
I'll merge this right after the build succeeds as it's minor cleanup
=> Remove references to Testathon & Beta 5 from Demo / Default theme

src/app/+item-page/simple/field-components/specific-field/author/item-page-author-field.component.ts, src/app/+item-page/simple/item-types/publication/publication.component.html, src/app/+item-page/simple/item-types/publication/publication.component.spec.ts, src/app/+item-page/simple/item-types/untyped-item/untyped-item.component.html, src/app/+item-page/simple/item-types/untyped-item/untyped-item.component.spec.ts, src/app/+item-page/simple/metadata-representation-list/metadata-representation-list.component.spec.ts, src/app/+item-page/simple/metadata-representation-list/metadata-representation-list.component.ts, src/app/core/shared/dspace-object.model.ts, src/app/entity-groups/research-entities/item-pages/project/project.component.html
This PR fixes https://github.com/DSpace/dspace-angular/issues/1196
Currently the authors section appears twice on all item pages for untyped items and publications, once using a metadata only component (ItemPageAuthorField), and once using a component that renders related entities as links (MetadataRepresentationList).
The MetadataRepresentationList doesn't support multiple metadatafields yet, so it only lists 'dc.contributor.author' metadata now, while the ItemPageAuthorField also lists 'dc.creator' metadata.
While fixing this, we also discovered a bug in the MetadataRepresentationList: when the user is unauthorised for the related item, no author metadata is displayed.
* The MetadataRepresentationList component has been altered to support multiple metadata …
=> Remove duplicate author field

src/app/+admin/admin-sidebar/admin-sidebar-section/admin-sidebar-section.component.html, src/app/+admin/admin-sidebar/admin-sidebar.component.html, src/app/+admin/admin-sidebar/expandable-admin-sidebar-section/expandable-admin-sidebar-section.component.html, src/app/shared/menu/menu-item/link-menu-item.component.html, src/app/shared/menu/menu-item/onclick-menu-item.component.html
Fixes #1170
This PR ensures that users can tab through the sidebar menu using the keyboard.
Currently the expandable menus are still separated into two parts where the first is the icon, and the second is the link itself.
Tabbing through the menu will only pass over the icons. The text next to icon will be ignored to avoid tabbing to the same link twice.
The issue of separation of the icon and text will be addressed as part of #1185.
* Log in as an administrator
* Verify that you can tab over all the entries in the side bar menu
* Verify that pressing enter on a collapsed menu will open it and that you can navigate through the submenu using tab
=> Fix admin sidebar link a11y issues

src/app/core/data/request.service.spec.ts, src/app/core/data/request.service.ts
* Fixes #1224 
Encode each segment that comes from the function's inputs separately with `encodeURIComponent`, instead of once at the end with `encodeURI`.
See #1224 for steps on how to test.
* do proper uri encoding in requestService.uriEncodeBody
* add unit test
=> Workflow rejection reasons are not properly encoded

src/app/shared/object-collection/shared/mydspace-item-submitter/item-submitter.component.html, src/app/shared/object-list/type-badge/type-badge.component.html, src/styles/_bootstrap_variables.scss, src/themes/custom/styles/_theme_sass_variable_overrides.scss, src/themes/dspace/styles/_theme_sass_variable_overrides.scss
* Fixes #1151 
* Fixes #1154 
* Fixes #1156 
* Fixes #1160
* ~Depends on #1221~
Reverted to Bootstrap's `$gray-` values to fix contrast issues
* Set `$gray-` values back to Bootstrap defaults in `src/styles/_bootstrap_variables.scss` as well as `src/themes/*/styles/_theme_sass_variable_overrides.scss`
* With the default `$gray-100`, `badge-light` becomes too light; changed badge classes to `badge-info`
* Now blue instead of gray
* Deque analysis / go over the contrast problems listed in the issues referenced above
~**This PR seems bigger than it is, because it depends on #1221 You can see only the changes in this PR [here](https://github.com/atmire/dspace-angular/compare/move-header-changes-to-dspace-theme. …
=> Fix contrast issues with grays

src/assets/i18n/en.json5
Adds a missing i18n key which is visible when doing the following:
1. Go to MyDSpace
2. Click button to "Import metadata from external source"
3. You'll see that an entry in the list is `submission.import-external.source.sherpaJournalIssn`.
This tiny PR fixes that issue by adding the i18n key
=> Add missing i18n key for Sherpa Journals by ISSN

src/app/+admin/admin-sidebar/admin-sidebar.component.ts, src/app/access-control/access-control-routing-paths.ts, src/app/access-control/access-control-routing.module.ts, src/app/access-control/group-registry/group-page.guard.spec.ts, src/app/access-control/group-registry/group-page.guard.ts, src/app/access-control/group-registry/groups-registry.component.html, src/app/access-control/group-registry/groups-registry.component.spec.ts, src/app/access-control/group-registry/groups-registry.component.ts, src/app/core/data/feature-authorization/feature-id.ts, src/app/core/eperson/models/group-dto.model.ts, src/assets/i18n/en.json5
* Fixes #1124
* Requires DSpace/DSpace#3293
A community or collection admin now no longer has access to `/access-control/epeople`, only site admin do.
Community/Collection admins can now only edit the groups on which they have `canManageGroup` authorization (see DSpace/DSpace#3293). This gets checked for every group in the groups list view, and check by guard on a group edit page. If the user is a site admin, this authorization check is not done for every group since they can edit any group.
- Logged in as general/site admin
* Sidebar => Access control => People is visible
* Direct navigation to `/access-control/epeople` is possible
- Logged in as community or collection admin
* Sidebar => Access control => Only Groups is visible
* Direct navigation to `/access-control/epeople` is Not …
=> Access Control - Groups only editable by Com/Col admin if group related to com/col & Only site admin access to access control epeople

src/app/core/json-patch/builder/json-patch-operations-builder.ts, src/app/shared/date.util.ts, src/app/shared/form/builder/ds-dynamic-form-ui/models/date-picker-inline/dynamic-date-picker-inline.component.html, src/app/shared/form/form.component.ts, src/app/shared/mocks/submission.mock.ts, src/app/submission/form/submission-form.component.ts, src/app/submission/sections/form/section-form-operations.service.spec.ts, src/app/submission/sections/form/section-form-operations.service.ts, src/app/submission/sections/upload/file/edit/section-upload-file-edit.component.scss, src/app/submission/sections/upload/file/edit/section-upload-file-edit.component.ts, src/app/submission/sections/upload/file/edit/section-upload-file-edit.model.ts, src/app/submission/sections/upload/file/section-upload-file.component.ts
* Fixes #1110 
* Fixes #1121 
* Fixes #1119 
* Fixes #1195 
* Fixes #1144
* Fixes #1220 
* Fixes #1229 
Fixes the problems reported on each issues. For what concerning the bitstream embargo issue (#1119) I've also fixed the form visualization because the form fields appeared disaligned
Check the bugs reported are no longer exist
=> Fixes for submission forms bugs

src/app/+collection-page/delete-collection-page/delete-collection-page.component.html, src/app/+community-page/delete-community-page/delete-community-page.component.html, src/app/shared/comcol-forms/delete-comcol-page/delete-comcol-page.component.ts, src/assets/i18n/en.json5
* Fixes #1122
Disable community/collection delete button while the delete operation is being processed
- go to community/collection delete page
- confirm deletion 
- check the delete button is disabled and it can't be clicked again
=> Disable community/collection delete button while the delete operation is being processed

src/app/+item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.html, src/app/+item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.spec.ts, src/app/+item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.ts, src/app/+item-page/edit-item-page/item-relationships/item-relationships.component.ts, src/app/core/shared/item.model.ts
Fixes #1238
This PR adds pagination to the item edit relationships page.
Changes:
* Paginate relationships
* Added tests for pagination
Test instructions:
* Create an item with multiple types of relationships (e.g. start from https://github.com/DSpace-Labs/AIP-Files/releases/tag/demo-entities-data)
* Add more than 5 relationships of the same type such that pagination appears for that type
* Make sure that both the rightward and leftward relationships are loaded properly
* Make sure that adding and deleting a relationship still works
=> Add pagination to edit relationships tab

src/app/submission/form/collection/submission-form-collection.component.spec.ts, src/app/submission/form/collection/submission-form-collection.component.ts
* Fixes #1234
Fix issue when switching submission's collection between those with different submission definition
Follow instruction present in the #1234 and check the issue is not present anymore
=> Fix issue when switching submission's collection between those with different submission definition

src/app/core/json-patch/json-patch-operations.actions.ts, src/app/core/json-patch/json-patch-operations.reducer.spec.ts, src/app/core/json-patch/json-patch-operations.reducer.ts, src/app/core/json-patch/json-patch-operations.service.spec.ts, src/app/core/json-patch/json-patch-operations.service.ts, src/app/shared/testing/submission-json-patch-operations-service.stub.ts, src/app/submission/edit/submission-edit.component.spec.ts, src/app/submission/edit/submission-edit.component.ts
* Fixes #1217
When the user leaves the submission page the state related to the aborted submission must be totally erased.
To achieve the goal a new NgRx Action has been added (`DELETE_PENDING_JSON_PATCH_OPERATIONS`). This action is dispatched on the _OnDestroy_ hook of the `SubmissionEditComponent`. The reducer destroy every data related to the aborted submission.
=> Delete pending json patch operations

src/app/core/auth/auth.actions.ts, src/app/core/auth/auth.effects.spec.ts, src/app/core/auth/auth.effects.ts, src/app/core/auth/auth.reducer.spec.ts, src/app/core/auth/auth.reducer.ts, src/app/core/auth/auth.service.ts, src/app/core/auth/server-auth.service.ts, src/app/shared/testing/auth-service.stub.ts
* Fixes #1179 
Fixed issue with authorization request encountered while logging-in with shibboleth
Check the bug reported is no longer exist
=> [CSTPER-144] Fixed issue with authorization request encountered while logging-in with shibboleth

src/app/shared/file-download-link/file-download-link.component.html, src/app/shared/file-download-link/file-download-link.component.ts, src/app/submission/sections/upload/file/section-upload-file.component.html, src/app/submission/sections/upload/file/section-upload-file.component.spec.ts, src/app/submission/sections/upload/file/section-upload-file.component.ts
* Fixes #1265
Fix issue #1265
Follow steps described in the #1265 and check if all works properly
**List of changes in this PR** :
With this PR SubmissionSectionUploadFileComponent make use of the existing FileDownloadLinkComponent to allow downloading of the uploaded files
=> fix bitstream download during submission

src/app/+browse-by/+browse-by-metadata-page/browse-by-metadata-page.component.ts, src/app/app.component.ts, src/app/app.module.ts, src/app/core/auth/auth.actions.ts, src/app/core/auth/auth.effects.ts, src/app/core/auth/auth.interceptor.ts, src/app/core/auth/auth.reducer.spec.ts, src/app/core/auth/auth.reducer.ts, src/app/core/auth/auth.service.spec.ts, src/app/core/auth/auth.service.ts, src/app/core/auth/selectors.ts, src/app/core/utilities/enter-zone.scheduler.ts, src/app/core/utilities/leave-zone.scheduler.ts, src/app/root/root.component.ts, src/app/shared/auth-nav-menu/auth-nav-menu.component.spec.ts, src/app/shared/auth-nav-menu/user-menu/user-menu.component.spec.ts, src/app/shared/idle-modal/idle-modal.component.html, src/app/shared/idle-modal/idle-modal.component.spec.ts, src/app/shared/idle-modal/idle-modal.component.ts, src/app/shared/mocks/auth.service.mock.ts, src/assets/i18n/en.json5, src/config/auth-config.interfaces.ts, src/environments/environment.common.ts, src/environments/mock-environment.ts
* Fixes #1173 ('[Deque Analysis] User is not warned of session timeout')
There are two timers introduced, one for the token refresh, and one for the session time.
The first timer starts when a token is stored, a configurable time later, this token is refreshed and the timer restarts. If something goes wrong with the token refresh a notification is shown and the user is logged out. Whether or not the token needs to be refreshed, which is checked with any change on the authToken, is dependent on the `expires` property given to the token, based on REST config `jwt.login.token.expiration`, subtracted the UI configurable `auth.rest.time-left-before-token-refresh` (and current date, since the `token.expires` is `{currentTimeInMillisecondsAtTokenCreation}+jwt.login.token.expiration`).
The second …
=> Improve session timeout UX

src/app/shared/testing/sections-service.stub.ts, src/app/submission/form/collection/submission-form-collection.component.spec.ts, src/app/submission/form/collection/submission-form-collection.component.ts, src/app/submission/form/submission-form.component.html, src/app/submission/form/submission-upload-files/submission-upload-files.component.spec.ts, src/app/submission/form/submission-upload-files/submission-upload-files.component.ts, src/app/submission/sections/sections.service.spec.ts, src/app/submission/sections/sections.service.ts, src/app/submission/sections/upload/file/section-upload-file.component.ts
* A similar issue was brought up before: #844
Fixed some hardcoded submission section IDs. 
We came across this issue when debugging for an instance which had a custom ID for the upload section.
* Replaced `SectionsService#isSectionAvailable` calls with `SectionsService#isSectionTypeAvailable`
* Added `SectionsService#isSectionType` to replace hardcoded check for an upload section in `WorkspaceItem`
**Reviewing**
* No noticeable difference expected with the default configuration
=> Fix hardcoded submission section IDs

src/app/+browse-by/+browse-by-date-page/browse-by-date-page.component.spec.ts, src/app/+browse-by/+browse-by-date-page/browse-by-date-page.component.ts, src/app/shared/date.util.ts, src/app/shared/form/builder/ds-dynamic-form-ui/models/date-picker/date-picker.component.ts, src/app/shared/search/search-filters/search-filter/search-range-filter/search-range-filter.component.ts, src/app/submission/sections/upload/file/edit/section-upload-file-edit.component.ts
* Fixes #1256
In several areas of the UI (especially related to embargo dates) we use localized versions of dates (e.g. `getFullYear()`, `getMonth()`, `getDate()`).  This causes odd behavior when using the UI from a location with a vastly different time than UTC, and results in the UI sometimes accidentally changing embargo dates, etc.
This PR fixes those issues by ensuring we are always using UTC dates when interacting with Typescript `Date` object.  While the main bug is with the embargo date, I decided to do a find & replace on these methods, as I expect odd behavior would occur elsewhere as well.
As a sidenote, we should keep in mind that this behavior is in line with DSpace v6 (and below). In older versions of DSpace, both the UI and Backend used UTC dates only. So, this PR is …
=> Ensure we are always using UTC dates in the UI, as the backend expects/uses UTC-based dates

src/app/submission/form/footer/submission-form-footer.component.html, src/app/submission/form/footer/submission-form-footer.component.spec.ts, src/assets/i18n/en.json5
* Fixes #1207 
this PR tries to solve usability issue on submission form reported in #1207 
* Place the discard button, as the previous versions, on the left in the button bar separated from the other ones.
* Change deposit button's class 
* Add a text describing the saving status of the submission
=> improve positioning of buttons in the submission form

src/app/+collection-page/collection-item-mapper/collection-item-mapper.component.html, src/app/+collection-page/collection-item-mapper/collection-item-mapper.component.spec.ts, src/app/+collection-page/collection-item-mapper/collection-item-mapper.component.ts, src/app/+item-page/edit-item-page/item-collection-mapper/item-collection-mapper.component.spec.ts, src/app/shared/object-select/collection-select/collection-select.component.spec.ts, src/app/shared/object-select/collection-select/collection-select.component.ts, src/app/shared/object-select/item-select/item-select.component.html, src/app/shared/object-select/item-select/item-select.component.spec.ts, src/app/shared/object-select/item-select/item-select.component.ts, src/app/shared/object-select/object-select/object-select.component.ts
* Fixes #1203
The Object Selector component has been enhanced. Is now possible to pass a FeatureID to check against to decide whether an item is selectable or not according to this authorization check.
The CollectionItemMapperComponent now inject the feature `canManageMappings` to the inner object selector component. This way only those items on which the user has that authorization will be selectable to be part of the mapping request.
=> Cannot map new items with Collection Admin

src/app/+bitstream-page/bitstream-page-routing.module.ts, src/app/+bitstream-page/legacy-bitstream-url.resolver.spec.ts, src/app/+bitstream-page/legacy-bitstream-url.resolver.ts, src/app/app-routing-paths.ts, src/app/app-routing.module.ts, src/app/core/data/bitstream-data.service.ts, src/app/core/shared/operators.spec.ts, src/app/core/shared/operators.ts
* Fixes #1147
* Requires DSpace/DSpace#3294
This PR adds support for JSPUI and XMLUI-style bitstream download URLs
It adds route paths for XMLUI and JSPUI style bitstream download URLs to the bitstream page module, and uses the new LegacyBitstreamUrlResolver, to resolve those routes to be reusable by the existing bitstream-download page.
**Note** we went over the 4 hour estimate by 3 hours (7 total), because we tried to do the redirect using guards first, which is the way angular recommends. However it is currently not possible to do so without replacing the URL (which is not ideal: if your link contains one small mistake, e.g. your copy/paste didn't include the last character, you want to be able to fix it, not have the URL change to `/404`). This angular issue tracks the problem, and …
=> Add support for legacy bitstream download URLs

src/app/shared/resource-policies/form/resource-policy-form.component.spec.ts, src/app/submission/sections/upload/file/section-upload-file.component.spec.ts
* Fixes issue introduced by #1262
Ever since #1262 was merged, a number of tests involving dates fail on my machine, but don't on github. When dates were compared the expected dates were always 2 hours off the actual result.
This PR addresses this by using the dateToISOFormat function on the expected dates.
Please verify that with this PR the tests work in your timezone and on github
=> Fix timezone issue with test dates

src/app/core/dspace-rest/dspace-rest.service.ts, src/app/core/log/log.interceptor.ts
* Fixes #1279 (most critical issue, the CORRELATION_ID empty issue will be moved to a new ticket)
This PR adds a check to see if the correlation id exists before adding it to the header.
It also improves the error handling of DSpaceRestService. JS errors (as opposed to error responses) are now thrown on unmodified. That will give us a stacktrace for these kinds of errors in the future.
- Open an incognito window, or clear your cookies
- Disable javascript
- Open this PR in prod mode
- Verify that the page loads properly
=> Fix issue where the app wouldn't load for the first request in prod mode

.github/workflows/build.yml, src/app/core/metadata/metadata.service.spec.ts, src/app/core/metadata/metadata.service.ts
* Relates to #1228 (earlier meta tag work) 
* Relates to #1279  and other recent work to fix SSR (server side rendering)
This PR makes two small improvements for SEO + SSR.  While these two improvements are not directly related, they are both necessary to improve SEO + SSR in version 7.0
1. First, modify the syntax of our `<meta>` tags slightly.  Currently all meta tags use a `property` attribute (e.g. `<meta property="" content=""/>`) when they are supposed to use a `name` attribute (e.g. `<meta name="" content=""/>`) like in 6.x.  This is a minor, but important, issue as the HTML5 `<meta>` tag only has a `name` attribute.  See this [good SO answer](https://stackoverflow.com/questions/22350105/whats-the-difference-between-meta-name-and-meta-property).  See this commit for the change …
=> SEO + SSR fixes: Fix <meta> tag syntax and add a basic test that SSR is working

src/app/core/locale/locale.service.spec.ts, src/app/core/locale/locale.service.ts
* Fixes #1188
This PR adds the "lang" attribute to the html tag with the current language.
Start the angular front-end and check if the html has the correct language attribute. 
Change the language and check if the attribute changes accordingly.
=> Language attribute on HTML tag

src/app/admin/admin-sidebar/admin-sidebar-section/admin-sidebar-section.component.html, src/app/admin/admin-sidebar/admin-sidebar-section/admin-sidebar-section.component.ts, src/app/admin/admin-sidebar/admin-sidebar.component.html, src/app/admin/admin-sidebar/admin-sidebar.component.scss, src/app/admin/admin-sidebar/admin-sidebar.component.spec.ts, src/app/admin/admin-sidebar/admin-sidebar.component.ts, src/app/admin/admin-sidebar/expandable-admin-sidebar-section/expandable-admin-sidebar-section.component.html, src/app/admin/admin-sidebar/expandable-admin-sidebar-section/expandable-admin-sidebar-section.component.scss, src/app/admin/admin-sidebar/expandable-admin-sidebar-section/expandable-admin-sidebar-section.component.spec.ts, src/app/admin/admin-sidebar/expandable-admin-sidebar-section/expandable-admin-sidebar-section.component.ts, src/app/navbar/expandable-navbar-section/expandable-navbar-section.component.html, src/app/navbar/expandable-navbar-section/expandable-navbar-section.component.spec.ts, src/app/navbar/expandable-navbar-section/expandable-navbar-section.component.ts, src/app/navbar/navbar-section/navbar-section.component.html, src/app/navbar/navbar-section/navbar-section.component.ts, src/app/shared/menu/menu-item/link-menu-item.component.html, src/app/shared/menu/menu-item/link-menu-item.component.spec.ts, src/app/shared/menu/menu-item/link-menu-item.component.ts, src/app/shared/menu/menu-item/onclick-menu-item.component.html, src/app/shared/menu/menu-item/onclick-menu-item.component.spec.ts, src/app/shared/menu/menu-item/onclick-menu-item.component.ts, src/themes/dspace/styles/_global-styles.scss
* Fixes #1185
Address accessibility issues with the admin sidebar
* Made HTML valid: only `<li>` elements in sidebar's `<ul>`
* Combined menu item icons & text into a single `<a>` element
* Added ARIA attributes
* `aria-expanded`
* `aria-disabled`
* Improved keyboard UX
* Expand the sidebar once you "tab into it"
* Adjusted item spacing so focus outlines are more clear
* Double checked that items in collapsed submenus can't receive focus
* Run deque a11y check
* The sidebar should look & act the same as on `main`
* (Except keyboard navigation, which should be improved as described above)
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are …
=> Fix sidebar a11y issues

src/app/profile-page/profile-page.module.ts, src/themes/custom/app/profile-page/profile-page.component.ts
* Fixes #1308
Changes the profile page component in the custom theme to use the template and scss file of the base theme by default, the same way all the other components in the custom theme do.
Test this PR by enabling the custom theme and verifying that the profile page works properly, without errors in the console.
=> fix the profile page component in the custom theme

cypress/integration/homepage.spec.ts
Immediately after merging #1301, I noticed that the accessibility check in `homepage.spec.ts` seems to randomly *fail* for color contrast issues.  This sort of inconsistency in color contrast has also been reported in cypress-axe tool we are using, see component-driven/cypress-axe#98
As I'm currently working on a PR to run automated accessibility checks, I'll look into this issue in that work & ensure the new PR doesn't result in randomish failures, even if it means we don't automate tests for color contrast.
Therefore, this PR is just temporarily disabling that accessibility check until it is fixed in follow-up work.  That way this random failure doesn't get in the way of other development.
=> Temporarily disable a11y check until random failure for color contrast can be fixed

src/app/item-page/bitstreams/upload/upload-bitstream.component.spec.ts, src/app/item-page/bitstreams/upload/upload-bitstream.component.ts
* Fixes #1286 
This PR fixes the issue where new bitstreams couldn't be uploaded in the UI on the edit item page anymore.
Go to an edit item page and select the Bitstreams tab.
Upload a new bitstream to this item and make sure it is working again.
=> Fixed edit item bitstreams

src/app/item-page/edit-item-page/item-metadata/edit-in-place-field/edit-in-place-field.component.html, src/app/item-page/edit-item-page/item-metadata/edit-in-place-field/edit-in-place-field.component.spec.ts, src/app/shared/input-suggestions/validation-suggestions/validation-suggestions.component.html, src/app/shared/input-suggestions/validation-suggestions/validation-suggestions.component.spec.ts, src/app/shared/input-suggestions/validation-suggestions/validation-suggestions.component.ts
* Fixes #1317
When editing an item metadata, it is not possible change metadata field name since its input field is disabled. 
This to prevent errors reported in issue #1317. 
Despite of what estimated, this update took us 2 hours.
* added disable input to ValidationSuggestionComponent
* edit-in-place-field-component html changed so that its ds-validation-suggestion is disabled, using above input field, during metadata update and deletion operations, this change 
* Log in into dspace7
* from left menu select edit -> item and choose an item to edit
* go to "metadata" tab
* Click the …
=> edit item metadata fix

README.md, src/app/navbar/expandable-navbar-section/expandable-navbar-section.component.html, src/app/navbar/expandable-navbar-section/expandable-navbar-section.component.spec.ts, src/app/navbar/expandable-navbar-section/expandable-navbar-section.component.ts
Small improvement to the fixes to #1167 in PR #1252
Deque retested those header fixes, and found one issue was only partially fixed. 
* If you use a Keyboard to select the "All of DSpace" menu in the Header, you can open it by pressing "Enter"
* However, once it is open, there is no way to close it using only the keyboard.  
This PR fixes that issue by ensuring pressing "Enter" will open/close that menu based on the current status. 
* Review code changes
* Test keyboard interaction of header menu
* Tab to the "All of DSpace" menu, press "Enter" (or spacebar).  It should open
* Click Tab again, reselecting "All of DSpace".  press "Enter" (or spacebar) again. Now it should close.
* Verify you can still tab to a submenu (e.g. "By Subject") and press "Enter" to go to that browse by page.
=> Header Accessibility Fix: Allow enter key or spacebar to expand or contract menu based on current active status

src/assets/i18n/en.json5
Fixes the tooltips you get when you hover over the icons for Curation Task and Administer Workflow in the sidebar:
Verify that the messages are there now when you hover over those icons
=> Fix menu icon i18n messages

src/app/item-page/item-page-routing.module.ts
* Fixes #1370 
* Fixes #1384 
This PR fix issue with "Request a Copy" page that was responding to improper routes
Check if the issues reported #1370 #1384 are fixed
=> Fix issue with request a copy functionality route

docker/docker-compose-rest.yml
Small update to `docker-compose-rest.yml` to "sync" it up with the `docker-compose.yml` in the DSpace/DSpace repo: https://github.com/DSpace/DSpace/blob/main/docker-compose.yml
These files should be kept in sync at all times (to avoid oddities in CI or similar), and it looks like I forgot to copy over the changes that I applied in https://github.com/DSpace/DSpace/pull/7999
Assuming this passes in GitHub CI, I'm going to merge immediately just to resync these files.
=> Sync with DSpace/DSpace docker-compose setup

angular.json
After moving to a new laptop and installing Angular CLI globally (`npm install -g @angular/cli`), all of my `ng` commands now prompt me to enable or disable analytics for `dspace-angular`.  The prompt looks like...
```
Would you like to share anonymous usage data about this project with the Angular Team at
Google under Google’s Privacy Policy at https://policies.google.com/privacy? For more
details and how to change this setting, see http://angular.io/analytics. (y/N)
```
Either answer updates our `angular.json`, which obviously gets annoying...as that change could be accidentally committed back in any future PR.
I suspect this is updated behavior in a more recent version of Angular CLI (as I didn't notice this until I moved to a new laptop).  However, the only way to seemingly disable …
=> Disable CLI analytics by default

package.json
* Fixes #1409
Adds a new `yarn config:dev:check:rest` command, which is the equivalent of `yarn config:check:rest`, but for *development* environments (as the latter command only works for production).
Test the new script in a development environment, with an `environment.dev.ts`
=> Add a config:dev:check:rest option for checking dev environment settings

src/app/access-control/group-registry/group-form/group-form.component.spec.ts, src/app/access-control/group-registry/group-form/group-form.component.ts, src/app/access-control/group-registry/group-form/validators/group-exists.validator.ts, src/assets/i18n/en.json5
* Fixes #1386 
A new validator has been introduced (group-exists.validator.ts). When a new group is created it checks whether or not this group already exists, in this case it inhibits form submit. 
Such validator does not apply when editing an already existing group.
Create a group with a name not already assigned to others, then try to create a group with the same name, "Save" button will be disabled and a warning message will appear under the "name" field. 
No warning will appear when editing the already existing group
* group-exists.validator.ts validator added
* validator injected into group-form.component.ts
See instructions for Reviewers
_This checklist provides a reminder of what we are going to …
=> group creation validator

src/app/process-page/detail/process-detail.component.html, src/app/process-page/detail/process-detail.component.ts, src/app/process-page/overview/process-overview.component.html, src/app/process-page/overview/process-overview.component.spec.ts, src/assets/i18n/en.json5
* Fixes #1402 
Start and end time of processes were shown using:
- local timezone with a custom pattern in process overview page;
- UTC witn no custom pattern in process detail page.
UTC is now used also in overview page, and the same date pattern has been applied in detail page.
The following labels have been changed in `en.json5`:
- `process.overview.table.start`
- `process.overview.table.finish`
The style of buttons has been changed to match design guidelines.
=> [CST-4903] The start time and end time of the export process are different

src/app/process-page/process-page.resolver.ts
* Fixes #1405 
Process status remained "running" because process page resolver (`src/app/process-page/process-page.resolver.ts`) retrieved the process from cache.
=> [CST-4918] Process status remains Running in detail page

src/app/shared/dso-selector/dso-selector/dso-selector.component.html, src/styles/_global-styles.scss
Fixed two minor annoyances with Bootstrap modals
1. Made the modal backdrop color transition smoother
* Replicating: open a "new/edit DSO" modal on https://demo7.dspace.org/home
the animation starts out with a fully dark background instead of transparent
* Seems like this is an issue with `opacity` transitions; animating the background between fully transparent and an equivalent RGBA color solves it
2. Fixed scrolling background when opening a modal
* Replicating: open a modal on https://demo7.dspace.org/search?spc.page=1&query=&spc.sf=score&spc.sd=DESC&spc.rpp=40
* This is a side effect of the `focus` method ~ `dsAutoFocus` in `ds-dso-selector`, solved by using  `ngbAutofocus` instead
* An alternative solution could be to [call focus with `{ preventScroll: …
=> Fix minor modal UX issues

.github/workflows/build.yml, .github/workflows/docker.yml, Dockerfile, docker/README.md, docker/docker-compose.yml
Corresponding Docker Action for DSpace/DSpace in https://github.com/DSpace/DSpace/pull/8058
This PR adds a new `docker.yml` GitHub action, which is configured to automatically build DSpace Docker images and push to DockerHub.
This includes the following setup:
* New `docker.yml` action runs for all pushes, releases and PRs.  However, PRs _only_ build the Docker images (to verify no new build errors occur). PRs do NOT push updated Docker images to DockerHub
* When a new commit occurs on `main`, images will all be built and tagged in DockerHub with `dspace-7_x`
* When a new commit occurs on a different branch, images will be built and tagged with that branch name.
* When a new tag is created in GitHub, images will all be built and tagged in DockerHub with same tag as the DSpace release.
=> Add GitHub action to build Docker images and push to DockerHub

.github/workflows/docker.yml
After running #1440  on `main` for the first time (after merging it), I've realized two things that were missing from our initial `docker.yml` action.
1. We need to disable this workflow action from running on forks.  Otherwise, it will always fail in forked repos (as the user who owns the fork cannot push Docker images to our DockerHub account).
2. We need to only run this workflow action for maintenance branches (e.g. `dspace-6_x`, etc), and not other branches we use occasionally (e.g. `rest-demo` which is the branch used by the api7.dspace.org demo backend).
This PR makes those minor changes/updates.
This PR is ported from https://github.com/DSpace/DSpace/pull/8059, which makes the same changes for our DSpace/DSpace repo.
=> Disable Docker image build action on forked repos & on non-maintenance branches

LICENSE, NOTICE, README.md
Related to PR https://github.com/DSpace/DSpace/pull/8061
GitHub is able to detect the type of OSS license, provided that your `LICENSE` file doesn't contain a bunch of custom text.  See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#detecting-a-license
This PR simply cleans up the formatting of our `LICENSE` file so that it matches a standard BSD 3-Clause License.  This includes:
* Minor formatting changes
* Replacing outdated text "Neither the name DuraSpace nor the name of the DSpace Foundation" with "Neither the name of the copyright holder" (which is the standard BSD language).
* Copy over `NOTICE` file from main "DSpace/DSpace" repository (this was accidentally missing)
* Moving our note about …
=> Cleanup our LICENSE file so GitHub can detect our BSD license

docker/docker-compose-ci.yml, docker/docker-compose-rest.yml
Update our docker-compose configs for 'rest' and 'ci' to use Solr 8.11.  Porting of Solr changes applied to backend in https://github.com/DSpace/DSpace/pull/8069
I've tested this locally and found now issues. These are all relatively minor updates...so assuming CI passes, I'll move forward with merging.
=> Update Docker to use latest Solr 8

src/assets/i18n/de.json5
Fixes #1453 
The `de.json5` German language pack was missing a closing quote on one line, which caused it to not work.  See #1453.
=> German language syntax fix, add trailing quote

src/app/shared/resource-policies/resource-policies.component.ts
* Fixes #1456
The resource policy component used [legacy relative router paths](https://angular.io/api/router/ExtraOptions#relativeLinkResolution). However we disabled support for that in #1403 and #1452, so these paths needed to be updated to the new format
Follow the instructions in #1456, and verify that these buttons all work now
=> Update legacy relative links to angular 11 format

src/app/breadcrumbs/breadcrumbs.component.html, src/app/breadcrumbs/breadcrumbs.component.scss, src/app/breadcrumbs/breadcrumbs.component.spec.ts, src/app/entity-groups/journal-entities/item-list-elements/search-result-list-elements/journal-issue/journal-issue-search-result-list-element.component.html, src/app/entity-groups/journal-entities/item-list-elements/search-result-list-elements/journal-volume/journal-volume-search-result-list-element.component.html, src/app/entity-groups/journal-entities/item-list-elements/search-result-list-elements/journal/journal-search-result-list-element.component.html, src/app/entity-groups/research-entities/item-list-elements/search-result-list-elements/project/project-search-result-list-element.component.html, src/app/item-page/edit-item-page/item-bitstreams/item-edit-bitstream/item-edit-bitstream.component.html, src/app/item-page/edit-item-page/item-metadata/edit-in-place-field/edit-in-place-field.component.html, src/app/item-page/field-components/metadata-uri-values/metadata-uri-values.component.html, src/app/item-page/field-components/metadata-values/metadata-values.component.html, src/app/shared/file-download-link/file-download-link.component.html, src/app/shared/object-list/metadata-representation-list-element/plain-text/plain-text-metadata-list-element.component.html, src/app/shared/object-list/search-result-list-element/item-search-result/item-types/item/item-search-result-list-element.component.html, src/app/shared/truncatable/truncatable-part/truncatable-part.component.html, src/styles/_custom_variables.scss, src/styles/_global-styles.scss
* Fixes #1429
This PR makes sure very long words and urls for metadata and file names don't overflow on the Edit Item Page and Item page.
For the file names on the item's `edit/bitstream` page and titles in the trail, the word should be truncated and end in an ellipsis. For all other occurrences, the [.dont-break-out](https://css-tricks.com/snippets/css/prevent-long-urls-from-breaking-out-of-container/) class was added. 
Metadata:
* Add a metadata field with a very long word or url (without spaces and/or hyphens) to an item
* Check that the text does not overflow the field on both the Item Page and the Edit Item Page `/metadata` tab.
Title metadata:
* Add a title metadata field with a very long word or url (without spaces and/or hyphens) to an item
* Check that the title does not overflow …
=> Handling very long strings for metadata and file names

src/app/shared/collection-dropdown/collection-dropdown.component.html, src/app/shared/collection-dropdown/collection-dropdown.component.ts
* Fixes #1421
* In collection dropdown component, moved the return statement that returned the collection list outside the condition that checks if it's the final page. 
* Also changed the condition that checks final page, it wasn't necessary to sum the elements per page.
* Deleted !(isLoading | async) condition that didn't allowed the show collection list if there were new collections loading
* Changed infiniteScrollDistance and infiniteScrollThrottle parameters so the load of the collection is more fluent. I took as a reference the AuthorizedCollectionSelectorComponent. 
Both CollectionDropdownComponent and AuthorizedCollectionSelectorComponent had similar behaviour, perhaps they could be combined into a single component in the future
* Go to My Dspace page 
* Create a new item via …
=> Fix to collection selection window not loading successfully.

src/app/submission/sections/upload/file/edit/section-upload-file-edit.component.html, src/app/submission/sections/upload/file/edit/section-upload-file-edit.component.spec.ts, src/app/submission/sections/upload/file/edit/section-upload-file-edit.component.ts, src/app/submission/sections/upload/file/section-upload-file.component.html, src/app/submission/sections/upload/file/section-upload-file.component.scss, src/app/submission/sections/upload/file/section-upload-file.component.spec.ts, src/app/submission/sections/upload/file/section-upload-file.component.ts
* Fixes #1337 
* Fixes #1359 
* Fixes #1399 
* Fixes #1415 
* Fixes DSpace/DSpace#7977 (this was actually a **dspace-angular** issue)
The **Edit bitstream** form has been moved in a modal. Several bugs in the form, mostly related to the **Access condition type**, have been fixed.
1. The **Edit bitstream** form (`section-upload-file-edit.component`) is now displayed inside a modal. Saving process is managed within the modal component.
2. When  **Access condition type** is changed the PATCH does not fail anymore.
* Bug reason: when the previous access condition type had a start date or an end date and the new condition type did not have it the previously saved date was still included in the patch, although the corresponding form field was deactivated
3. **Grant …
=> Upload files - Edit bitstream (improvements and bug fixes)

src/app/core/data/feature-authorization/feature-id.ts, src/app/profile-page/profile-page.component.html, src/app/profile-page/profile-page.component.spec.ts, src/app/profile-page/profile-page.component.ts
* Fixes [#7959](https://github.com/DSpace/DSpace/issues/7959)
* Requires https://github.com/DSpace/DSpace/pull/8050
This PR fixes the Angular part of the issue where Shibboleth users were able to change their password using the DSpace UI.
It removes the `Security` form on the `Profile` page for users that are not allowed to change their password using the `canChangePassword` feature retrieved from the backend.
- Log in using the default DSpace login UI and visit the profile page at `/profile`. You should be able to change your password.
- Log in using Shibboleth (make sure Shibboleth is enabled for you backend server) and visit the profile page at `/profile`. You should not be able to change your password, and the `Security` part of the form should not be shown.
=> Disallow Shibboleth users to change password

src/app/access-control/epeople-registry/eperson-form/eperson-form.component.html, src/app/access-control/epeople-registry/eperson-form/eperson-form.component.spec.ts, src/app/access-control/epeople-registry/eperson-form/eperson-form.component.ts
* Fixes #1349 
Admin can now reset other users' password
Reset password button, that was disabled by default, is now enabled.
Reset password functionality has been implemented.
=> Admin is unable to reset other users' password

src/app/core/json-patch/json-patch-operations.service.ts, src/app/submission/form/footer/submission-form-footer.component.html, src/app/submission/form/footer/submission-form-footer.component.spec.ts, src/app/submission/objects/submission-objects.effects.spec.ts, src/app/submission/objects/submission-objects.effects.ts
This PR fixes #1358
Currently, during submission, the "Deposit" button is disabled until all requirements for the deposit has been fulfilled.
As a fix for #1358, this PR would change it so the "Deposit" button is always enabled, but fix it to where it gives the same input as a save would, if it doesn't meet the requirements.
Changes made:
- Removed "disabled" input for the deposit button when requirements aren't met (but keep it disabled when a save/deposit is being processed)
- Modified the saved-and-deposit effect to fire a `SaveSubmissionFormSuccessAction` when the requirements aren't met. This will trigger the processing of the json patch response into error fields being displayed and the progress bar finishing.
- The deposit didn't allow for an empty json patch to be sent, which …
=> Always enable deposit button

src/app/process-page/form/process-form.component.spec.ts, src/app/process-page/form/process-form.component.ts
This PR fixes #1445
This PR fixes an error occurring when trying to run a script through Scripts & Processes without any arguments/parameters, even if that script allows it.
Changes made:
- Before submitting, it checks if the parameters are empty (meaning undefined, null or empty array) and replace it with an empty array to ensure no "undefined" errors occur after
- Added a test case covering this
How to test:
- Log in as a site administrator
- Go to the /processes page
- Create a new process and select a script that allows empty parameters (e.g. index-discovery)
- Save
- This should now work as expected and create a process for the script
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating …
=> Scripts & Processes without parameters fix

src/app/app.module.ts, src/app/app.reducer.ts, src/app/core/log/log.interceptor.spec.ts, src/app/core/log/log.interceptor.ts, src/app/correlation-id/correlation-id.actions.ts, src/app/correlation-id/correlation-id.reducer.spec.ts, src/app/correlation-id/correlation-id.reducer.ts, src/app/correlation-id/correlation-id.service.spec.ts, src/app/correlation-id/correlation-id.service.ts, src/modules/app/browser-app.module.ts, src/modules/app/server-app.module.ts
* Fixes #1281
* A `correlationId` field was added to the store, where it can be initialized both server- and client-side
* A service was added to resolve the `correlationId` from a cookie or the store, or generate it on demand if there isn't one yet.
* Initialization logic was moved from `AppModule` to `BrowserAppModule` & `ServerAppModule` in order to initialize _after_ the store is rehydrated. Because of this the client can pick up a correlation ID generated by the server if it doesn't have a cookie yet.
1. Start up a local Rest server and the UI using this PR branch in prod mode
2. Clear cookies or open an incognito window
3. In the Rest server logs, check that the correlation ID is present for all calls made by the node server
4. In the …
=> Move correlation ID to store

docker/docker-compose.yml
Very small fix to our `docker-compose`.  In recent versions of Docker, env variables cannot have boolean values.  This error occurs on `main`:
```
ERROR: The Compose file 'docker/docker-compose.yml' is invalid because:
services.dspace-angular.environment.DSPACE_UI_SSL contains false, which is an invalid type, it should be a string, number, or a null
```
This tiny PR fixes the issue by ensuring booleans are strings.
=> Docker-Compose Environment variables must be strings or numbers, not booleans

src/app/core/core.module.ts, src/app/core/eperson/group-data.service.ts
* Fixes #1494
The reason for this issue is that the `@dataService` annotation for the GroupDataservice isn't registered yet when the LinkService tries to resolve the group link on the eperson module. To solve it, I removed the `providedIn: 'root'` from GroupDataservice and provided it manually in CoreModule, which ensures that it is loaded in time.
Verify that the profile page works as it should
=> Fix user profile page

src/app/entity-groups/research-entities/submission/item-list-elements/org-unit/org-unit-suggestions/org-unit-input-suggestions.component.html, src/app/entity-groups/research-entities/submission/item-list-elements/person/person-suggestions/person-input-suggestions.component.html, src/app/footer/footer.component.html, src/app/item-page/field-components/collections/collections.component.html, src/app/navbar/expandable-navbar-section/expandable-navbar-section.component.html, src/app/shared/auth-nav-menu/auth-nav-menu.component.html, src/app/shared/chips/chips.component.html, src/app/shared/input-suggestions/filter-suggestions/filter-input-suggestions.component.html, src/app/shared/input-suggestions/input-suggestions.component.html, src/app/shared/input-suggestions/validation-suggestions/validation-suggestions.component.html, src/app/shared/lang-switch/lang-switch.component.html, src/app/submission/sections/container/section-container.component.html
We have a number of `<a>` tags that shouldn't do anything without javascript. A lot of those use `href="#"`, which is fine when the JS code that registers the click event has already loaded, but while the app is loading, these links will actually work and redirect you to `/#` which reloads the page.
Prime example is the login dropdown in the header. If you click that before the page has fully loaded, the page will reload.
This PR replaces those with `javascript:void(0);` which won't do anything if clicked. 
Using `javascript:void(0);` instead of `href="#"` for links that don't need to link anywhere has been recommended by deque for other cases before. (Although the more accessible solution is not to use a link at all if it's not going to redirect you anywhere when clicked)
Run the app in …
=> Replace href="#" with href="javascript:void(0);" everywhere

src/app/app-routing-paths.ts, src/app/app-routing.module.ts, src/app/app.module.ts, src/app/core/data/root-data.service.spec.ts, src/app/core/data/root-data.service.ts, src/app/core/server-check/server-check.guard.spec.ts, src/app/core/server-check/server-check.guard.ts, src/app/core/services/server-response.service.ts, src/app/page-internal-server-error/page-internal-server-error.component.html, src/app/page-internal-server-error/page-internal-server-error.component.ts, src/app/page-internal-server-error/themed-page-internal-server-error.component.ts, src/app/root/root.component.ts, src/app/shared/menu/menu.component.ts, src/assets/i18n/en.json5
* Fixes #1389 
This PR is based on the previous https://github.com/DSpace/dspace-angular/pull/1407 but resolve issues encountered after the merge. 
For testing this PR it's sufficient to change the angular environment file to point to an wrong rest server host. It's possible to test also cors errors by changing the ui running port so that it is different from 4000
* Created a new 500 error page
* Created a `ServerCheckGuard` that verify if root api endpoint works properly, if not redirect to the 500 error page
=> [CST-4880] Add ServerCheckGuard in order to show internal server error page when rest server is not available

src/app/submission/form/submission-form.component.ts, src/app/submission/objects/submission-objects.effects.ts
* Fixes #1502  
* Fixes https://github.com/DSpace/DSpace/issues/8133
Fixes bug reported
check if bug repoorted are fixed
=> Fix submission upload

scripts/env-to-yaml.ts
* Fixes #1525 
N/A
```
yarn env:yaml src/environments/environment.production.ts
```
should output without top level environment
```
production: true
universal:
preboot: false
async: true
time: false
rest:
ssl: false
host: localhost
port: 8080
nameSpace: /dspace-local
```
=> [Issue 1525] Unwrap environment during conversion to YAML

src/app/shared/bitstream-download-page/bitstream-download-page.component.html, src/app/shared/bitstream-download-page/bitstream-download-page.component.ts, src/assets/i18n/en.json5
* Fixes #1477 
A "Back" button has been added to the download page
Open any item with an attached file, e.g. [this one](https://demo7.dspace.org/items/014153ff-a6c9-4f08-92f6-e7d638d54986), and download the file. The download page should have a "Back" button.
=> [CST-5341] Link back to the item page in the now downloading page

src/app/core/data/default-change-analyzer.service.ts, src/app/core/dspace-rest/dspace-not-null.serializer.ts
* Fixes https://github.com/DSpace/dspace-angular/issues/1532
* Related rest contract: https://github.com/DSpace/RestContract/blob/main/resourcepolicies.md
The creation of the these patches is done in `default-change-analyzer.service.ts` `#diff`
Serialisation of objects (the resource policy) before & after changes are done via library 'cerialize' => `DSpaceSerializer` => `node_modules/cerialize/src/serialize.ts` `#Serialize`
As well as creation of patch requests base on the difference op those via library 'fast-json-patch' => `node_modules/fast-json-patch/module/duplex.d.ts` `#compare`
=> But any field that has value null before and not after, should get ADD not REPLACE patch
=> Added in a serialiser which removes all fields whose value is null from the serialised object and used it for …
=> Fix so newly added value on resource policy result in ADD patch, not REPLACE

src/app/browse-by/browse-by-date-page/browse-by-date-page.component.ts, src/app/shared/date.util.ts
* Fixes #1523 
This component assigns to the variable `lowerLimit`a default value from the environment. Then it overwrites this value with the year from the metadata `dc.date.issue` of the first search result, if present.
If the metadata format is wrong, then the default value `lowerLimit` becomes undefined, and this causes loader to be shown indefinitely.
An additional check has been added to the metadata value. The correct behaviour can be tested by replacing the `dc.date.issue` of the first search result with a random non-numeric string.
=> [CST-5316] "Browsing by issue date" is stuck on loading

src/app/submission/sections/form/section-form.component.spec.ts, src/app/submission/sections/form/section-form.component.ts
* #1427
* #1507
Porting the two PRs mentioned above to repositories with custom submission forms that include  `<visibility>` tags reveals a bug: 
* When a form contains a **pre-filled out-of-scope field** (e.g. a field with `<visibility>workflow</visibility>` while in the workspace), it will always be included in the `diffResult` [here](https://github.com/DSpace/dspace-angular/blob/fb2d22d7a25761580e3fc9aba5f7cfd04a3c7ee5/src/app/submission/sections/form/section-form.component.ts#L242) because it's excluded from `this.formData`
* This causes `hasMetadataEnrichment` to return true, which forces the form component to re-initialize when it doesn't have to
This PR addresses this bug by adding a scope check.
* New method: `inCurrentSubmissionScope`, used to filter which keys to include in …
=> Fix forced re-init due to out-of-scope fields

src/app/core/auth/auth.effects.spec.ts, src/app/core/auth/auth.effects.ts
* Fixes #1515
Invalidates the authorization cache before the REST API is called to generate a new token. This prevents the original and incomplete cached authorization object from being reused.  
See #1515 for more discussion.
=> Invalidate the authorization cache before retrieving token for auth cookie.

src/environments/environment.ts
leaving production env to true
* Fixes #1554 
...
=> [Issue 1527] Set default env preboot to false

config/config.example.yml, src/config/default-app-config.ts, src/environments/environment.test.ts
Follow up to #1573 from @raihantopu
This is a small PR to enable Bengali by default in the Angular UI.  I used this to test #1573, so I know it works.   So, once GitHub CI approves, I plan to merge this immediately.
=> Enable Bengali by default

src/app/shared/search/search-filters/search-filter/search-range-filter/search-range-filter.component.scss
* Originally noticed when working on #1138
Currently, date range sliders in search facets cover the full width of the facet, which causes the handles to jut out a little bit to the left/right.
This works fine, but causes those handles to get pushed behind the facet's padding during the collapse/expand animation.
This PR fixes this by padding the sliders so that the ends of handles at the min/max positions are flush with the slider itself
https://user-images.githubusercontent.com/31547038/159553028-db9f5275-b4fe-4d0f-94b3-67d3643ad28b.mov
Confirm that
* the slider handles are no longer cut in half during the animation when positioned at the ends of the slider
* the date range sliders still work as they did
_This …
=> Pad date range sliders to fix search facet animation issues

src/assets/i18n/fr.json5
**French translation reviewed and updated**
These are the main changes:
I have :
- added missing translations (more than ~300 variables)
- corrected the content of a few variables (partial translation and/or wrong translation or translation that deviated from the original); fixed a few typos (e.g. connexion instead of connection for "login")
- standardized the use of « some text » instead of "some text"
- standardized the spacing (among others : one blank before "?", ":", "!" (better yet would be to use a non-breaking space)
- removed the erroneous use of capital letters (e.g. "La Collections et la Communauté" => "La collection et la communauté")
- standardized the verb tenses for some variables (infinitive instead of imperative)
- added articles where they were missing (e.g. "Supprimer …
=> French translation reviewed and updated

src/app/core/metadata/metadata.service.spec.ts, src/app/core/metadata/metadata.service.ts, src/app/core/shared/operators.ts
* Fixes https://github.com/DSpace/DSpace/issues/8205
There is a check done for the 3 cases (primary bitstream, only bitstream, first bitstream with valid format) where a file download link is added to the Google Scholar Meta tag "citation_pdf_url", that verifies bitstream is "downloadable", i.e. that checks `AuthorizationDataService.isAuthorized(FeatureID.CanDownload, {bitstreamSelfLink})`. This ensures embargoed files, or files that are not accessible without login, their download link does not end up under this tag.
In production mode:
- Go to an item with an embargoed file, e.g. [7da772e5-0493-4380-b08d-512b827ae5e5](https://demo7.dspace.org/entities/publication/7da772e5-0493-4380-b08d-512b827ae5e5)
- [View source](view-source:https://demo7.dspace.org/entities/publication/7da772e5-0493- …
=> Fix for embargoed file links on Google Scholar Meta Tag "citation_pdf_url" 

src/app/shared/input-suggestions/filter-suggestions/filter-input-suggestions.component.html, src/app/shared/input-suggestions/input-suggestions.component.scss, src/app/shared/search/search-filters/search-filter/search-facet-filter-options/search-facet-selected-option/search-facet-selected-option.component.spec.ts, src/app/shared/search/search-filters/search-filter/search-facet-filter/search-facet-filter.component.spec.ts, src/app/shared/search/search-filters/search-filter/search-facet-filter/search-facet-filter.component.ts, src/app/shared/search/search-filters/search-filter/search-hierarchy-filter/search-hierarchy-filter.component.spec.ts, src/app/shared/search/search-filters/search-filter/search-hierarchy-filter/search-hierarchy-filter.component.ts, src/app/shared/search/search.utils.spec.ts, src/app/shared/search/search.utils.ts
* Fixes #1575
Fixed problem which made it impossible to use the search input filed to add new subject filters, fixed the layout of how the suggestions are displayed and prevented empty filters from being added.
* Fixed error where subject filters selected from the input field would not generate a correct Solr search query (`,query` needed to be appended to the url).
* Fixed an error where removing a filter caused the operator to be appended to the filter name (caused by previous fix).
* Use the search input field to add 2 filters
* Remove one filter
* `,Query` has been appended to search filter name in side navigation and in url
* Fixed CSS bug where the suggestions would be displayed over the input field.
* Fixed selected filter from still being displayed in …
=> Fix search field on search hierarchy filter component

src/app/shared/menu/menu-item-type.model.ts, src/app/shared/menu/menu-item/external-link-menu-item.component.html, src/app/shared/menu/menu-item/external-link-menu-item.component.spec.ts, src/app/shared/menu/menu-item/external-link-menu-item.component.ts, src/app/shared/menu/menu-item/link-menu-item.component.spec.ts, src/app/shared/menu/menu-item/models/external-link.model.ts, src/app/shared/menu/menu.module.ts, src/app/shared/shared.module.ts
Because `LinkMenuItemComponent` uses the Angular router, it can't readily support links to pages _outside_ of Angular, i.e.
* Links to external pages
* Links to internal static assets (e.g. a PDF file)
This PR introduces `ExternalLinkMenuItemComponent` for those use cases.
* Add `ExternalLinkMenuItemComponent` & `ExternalLinkItemModel`
* New `MenuItemType` value: `EXTERNAL`
Start up a local instance at [pr_external-links-in-menus_testing](https://github.com/ybnd/dspace-angular/tree/pr_external-links-in-menus_testing)
The header should include 
* A new "Banner Image" link, which should link to the banner image via a relative URL
* A new "GitHub" dropdown, with links to the REST & DSpace repos
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You …
=> Support external links in menus

Dockerfile
Related to discussion on Slack where @kshepherd noticed our `dspace-angular` Docker container was only listening on `localhost`.  This caused the UI to be unresponsive _unless_ you accessed it from within the running Docker container (via wget or similar)
During the Angular 13 upgrade (#1567), the `yarn serve` command (which is used to run the app in dev mode) was updated to use `ng serve` (Angular) instead of `node`.  This had the unfortunate side effect of limiting the `dspace-angular` docker container to listening only on `localhost` instead of on `0.0.0.0` (default for `node`) because `ng serve` defaults to localhost, see https://angular.io/cli/serve
This small PR fixes our `Dockerfile` to specify `--host 0.0.0.0` to ensure it listens to all IP addresses, and not only to `localhost`. …
=> Fix Dockerfile for Angular 13 updates

config/config.example.yml, src/config/default-app-config.ts
* Follow-up to #1519 (which was just merged)
This tiny PR just ensures that the new Turkish translation is available in our language dropdowns. 
Because this is a tiny configuration change & I've tested it myself, I'm going to merge this immediately after CI succeeds.
=> Enable Turkish lang pack in dropdown list

src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/search-tab/dynamic-lookup-relation-search-tab.component.html, src/app/shared/search-form/search-form.component.html, src/app/shared/search/search.component.ts, src/app/shared/search/themed-search.component.ts
* Fixes #1588
This PR enables the search scope selector button that was unintentionally disabled
Check if the scope selector works in the search page
=> Enabled search scope selector

src/mirador-viewer/mirador.html, webpack/webpack.mirador.config.ts
* Fixes #1611
The webpack build for Mirador was failing after we upgraded to webpack version 5. It complained about a missing node dependency. This fixes the problem by updating the `webpack.mirador.config` with a fallback.
The "url" dependency is actually not required since Mirador includes a polyfill in its own dependencies, so the fallback is just an empty module: { url: false }. 
We were also missing a webpack dependency: `html-webpack-plugin`.  It appears to be removed from package.json at some point, but frankly it was unnecessary. I just modified the webpack configuration to use the existing `copy-webpack-plugin` instead.
Build Mirador (yarn run build:mirador). The build should succeed and you should be able to see the embedded Mirador viewer inside an iiif-enabled view.
List of …
=> Mirador webpack build fix.

src/app/app-routing-paths.ts, src/app/core/submission/resolver/submission-object.resolver.ts, src/app/item-page/full/full-item-page.component.html, src/app/item-page/full/full-item-page.component.spec.ts, src/app/item-page/full/full-item-page.component.ts, src/app/shared/mydspace-actions/claimed-task/claimed-task-actions.component.html, src/app/shared/mydspace-actions/claimed-task/claimed-task-actions.component.spec.ts, src/app/shared/mydspace-actions/claimed-task/claimed-task-actions.component.ts, src/app/shared/mydspace-actions/pool-task/pool-task-actions.component.html, src/app/shared/mydspace-actions/pool-task/pool-task-actions.component.spec.ts, src/app/shared/mydspace-actions/pool-task/pool-task-actions.component.ts, src/app/shared/mydspace-actions/workflowitem/workflowitem-actions.component.html, src/app/shared/mydspace-actions/workflowitem/workflowitem-actions.component.spec.ts, src/app/shared/mydspace-actions/workflowitem/workflowitem-actions.component.ts, src/app/shared/mydspace-actions/workspaceitem/workspaceitem-actions.component.html, src/app/shared/mydspace-actions/workspaceitem/workspaceitem-actions.component.spec.ts, src/app/shared/mydspace-actions/workspaceitem/workspaceitem-actions.component.ts, src/app/shared/object-detail/my-dspace-result-detail-element/item-search-result/item-search-result-detail-element.component.ts, src/app/workspaceitems-edit-page/item-from-workspace.resolver.spec.ts, src/app/workspaceitems-edit-page/item-from-workspace.resolver.ts, src/app/workspaceitems-edit-page/workspace-item-page.resolver.spec.ts, src/app/workspaceitems-edit-page/workspace-item-page.resolver.ts, src/app/workspaceitems-edit-page/workspaceitems-edit-page-routing-paths.ts, src/app/workspaceitems-edit-page/workspaceitems-edit-page-routing.module.ts, src/app/workspaceitems-edit-page/workspaceitems-edit-page.module.ts, src/assets/i18n/en.json5
* Fixes #1514
* Fixes #772 
This PR add a view item button in the mydspace results list for the following objects : 
- workspace item
- workflow item
- claim task (it's already present, but now is always visible)
- pool task
the view button redirect to the existing full item page already used for the claim
Check that in the mydspace page all the mentioned objects have a working view item button. Check also the #1514 is fixed
=> Add view item button for mydspace objects

src/app/shared/rss-feed/rss.component.html, src/assets/i18n/en.json5
* Follow-up to #1444 
After merging #1444, the `main` branch no longer passes e2e tests because of accessibility failures detected: https://github.com/DSpace/dspace-angular/runs/6428607199?check_suite_focus=true
I'm not sure how these were not detected in #1444's build, but this small PR fixes the issue by ensuring the new button/link has discernible text.
Assuming this passes automated CI, I'm going to merge this immediately as otherwise all e2e will fail until this is fixed.
=> Fix RSS accessibility issue: link has no discernible text

src/app/item-page/item-page.resolver.spec.ts, src/app/item-page/item-page.resolver.ts
* Fixes #1654 
* Parsed the itemRoute through angular’s URL serializer, and serializing it again afterwards before comparing them
* Added tests to prove it works
Set the `dspace.entity.type` of an Item to a string containing a comma and search for that Item. If you aren't already on the page the resolver will trigger the navigate and it shouldn't throw errors anymore and you should be able to view the page correctly.
=> Fix entitytype redirect encoding issue

src/app/collection-page/edit-collection-page/collection-roles/collection-roles.component.spec.ts, src/app/community-page/edit-community-page/community-roles/community-roles.component.spec.ts, src/app/shared/comcol/comcol-forms/edit-comcol-page/comcol-role/comcol-role.component.html, src/app/shared/comcol/comcol-forms/edit-comcol-page/comcol-role/comcol-role.component.spec.ts, src/app/shared/comcol/comcol-forms/edit-comcol-page/comcol-role/comcol-role.component.ts, src/assets/i18n/en.json5
* Fixes #1557
* Backend PR: https://github.com/DSpace/DSpace/pull/8286
Show error notifications when Community/Collection role Group creation/deletion fails.
1. Run a local DSpace instance at the backend PR's branch
2. Select (or create) a Collection with the admin account assigned to the first workflow role
3. Deposit a new submission, confirm that it appears in the admin account's pool on `/mydspace`
4. Edit the Collection: attempt to delete the first role' Group
* A notification should pop up informing you that this can't be done
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). …
=> Show notifications when failing to create/delete role Groups

.github/workflows/docker.yml
Port of https://github.com/DSpace/DSpace/pull/8315 over to `dspace-angular`
Like https://github.com/DSpace/DSpace/pull/8315, this PR ensures that future PRs will only trigger an AMD64 build. The ARM64 build will only occur when a PR is merged into main or when a new tag is created.
There's unfortunately no way to fully test this without merging this PR.
=> Docker Fixes: Ensure multiple architecture build is disabled for PRs

docker/db.entities.yml, docker/docker-compose-ci.yml
Ensure CI docker backend always runs DB migrations, even when out of order.  In other words, this PR updates the CI process to now run `./dspace database migrate ignored` instead of simply `./dspace database migrate`. This ensures that the database backend also applies any migrations which run "out of order" (based on the name of the migration).
Small PR to debug/fix the current issues with e2e tests.  Currently the Docker backend that e2e tests require is failing to start up properly.
This has fixed the issue!
=> Fix continuous integration e2e backend failures

src/app/shared/truncatable/truncatable-part/truncatable-part.component.html
* Introduced in #1619
The new truncatable toggle buttons use a single space for the gap with their icons.
This becomes noticeable when hovering over the button
* Before this PR:
* After this PR:
Confirm that the hover decoration issue shown above doesn't occur.
=> Truncatable toggle: spacing between icon & label as margin instead of whitespace

src/app/core/pagination/pagination.service.spec.ts, src/app/core/pagination/pagination.service.ts, src/app/item-page/edit-item-page/item-collection-mapper/item-collection-mapper.component.ts
* Fixes #1675 
This small PR updates the Collection Mapper to work the same as the Item Mapper.  On `main` the Collection Mapper wasn't specifying a sort order, which defaulted to `sort=id` causing the 422 error described in #1675. This small PR just ensures a sort order is specified.
NOTE: I could not find any way to add specs for this. The [current specs have a mock which specify the sort order should be `title ASC`](https://github.com/DSpace/dspace-angular/blob/main/src/app/item-page/edit-item-page/item-collection-mapper/item-collection-mapper.component.spec.ts#L69), but then the current code failed to set itself up the same way.  So, this PR essentially just corrects the code to align with the existing mock in the specs.
* Ensure #1675 is no longer reproducible
=> Fixes Collection Mapper by ensuring UI sends a valid sort option

src/app/submission/sections/accesses/section-accesses.component.spec.ts, src/app/submission/sections/accesses/section-accesses.component.ts, src/app/submission/sections/upload/file/edit/section-upload-file-edit.component.spec.ts, src/app/submission/sections/upload/file/edit/section-upload-file-edit.component.ts, src/app/submission/submission.module.ts
* Fixes #1696
* Fixes #1697
follow instructions in the issues and check they are fixed
=> Submission item/bitstream access conditions fixes

src/app/curation-form/curation-form.component.spec.ts, src/app/curation-form/curation-form.component.ts, src/app/shared/handle.service.spec.ts, src/app/shared/handle.service.ts, src/assets/i18n/en.json5
* Fixes #1705
* Caused by the changes in https://github.com/DSpace/dspace-angular/pull/938
https://github.com/DSpace/dspace-angular/pull/938 changed the community and collection handles to be complete URLs instead of just prefix/local-name
This PR adds a service with a normalizeHandle method to convert URL handles to the prefix/local-name format
Verify that the curation tasks on edit community and collection pages work
=> Fix curation tasks started from the edit community or collection page

config/config.example.yml
Fixes #1714
Small cleanup of the description of the settings to clarify how to set the "ui" and "rest" configs.  See #1714 for more details.
=> Cleanup descriptions in comments of example config to clarify "ui" and "rest" sections

src/app/register-page/register-email/themed-register-email.component.ts, src/app/register-page/register-page-routing.module.ts, src/app/register-page/register-page.module.ts, webpack/webpack.common.ts
When customizing DSpace we tend to end up with two or three additional themes, all of which spam
```
WARNING: <theme module> is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.
```
I've had a few situations where I've overlooked warnings because they were simply pushed off screen by all of the "normal" theme warnings; and if the build succeeds it's very easy to just move on.
Having those perpetual warnings conditions everyone to pay less attention to the relevant ones.
This PR introduces a filter via [Webpack's `ignoreWarnings` property](https://webpack.js.org/configuration/other-options/#ignorewarnings) to address this.
Case in point: adding this filter brings two warnings wrt. components of the `custom` …
=> Filter webpack warnings

src/app/submission/sections/license/section-license.component.ts, src/app/submission/sections/license/section-license.model.ts, src/assets/i18n/en.json5, src/assets/i18n/es.json5
* Fixes #1487
Make label and error messages for license-step accept-checkbox translatable and add translation for English and Spanish.
* Apply the changes suggested by @atarix83  in this comment to add the i18n keys: https://github.com/DSpace/dspace-angular/issues/1487#issuecomment-1011082613
* Add the translation for English and Spanish
* Use the TranslateService in onSectionInit function to force the translation of the checkbox label
Start a new submission and check that the checkbox label and the error message that appears when the checkbox is unchecked are translated for Spanish and English.
=> Make label and error messages for license-step accept-checkbox translatable

src/app/shared/dso-selector/modal-wrappers/export-metadata-selector/export-metadata-selector.component.spec.ts, src/app/shared/dso-selector/modal-wrappers/export-metadata-selector/export-metadata-selector.component.ts
The current metadata export does not export the hidden fields. This PR fixes that issue by adding the `-a` option to the script that is invoked.
Export the metadata of a collection or community.
Verify that hidden metadata such as dc.description.provenance is exported together with the other metadata.
=> Add admin option to export all fields in the metadata export

src/styles/_vendor.scss, src/styles/base-theme.scss, src/themes/custom/styles/theme.scss, src/themes/dspace/styles/theme.scss
* Fixes #1679
Moved `node_modules` imports from the `theme.scss` files into `_vendor.scss` and imported that file in the `theme.scss` files
- Created a file called `_vendor.scss` in the /src/style folder
- Moved all imports with `node_modules` in their path from `base-theme.scss` to that file
- Put the vendor import at the place where the topmost `node_modules` import was in `base-theme.scss`
- Dif the same for theme.scss in the dspace and custom themes
- Build in production mode and look that everything still looks the same in all themes
=> Moved 3rd party css imports to separate file

config/config.example.yml, src/config/default-app-config.ts
Small PR to enable the Swedish language pack contributed by @jokermanse in #1673 
I've already tested this locally & it works.  It's a very minor default configuration change to ensure that Swedish (Svenska) appears as an option in the language menu. I'll merge it immediately once tests all pass.
=> Enable Swedish language

src/app/shared/browse-by/browse-by.component.spec.ts, src/app/shared/browse-by/browse-by.component.ts, src/app/shared/object-list/browse-entry-list-element/browse-entry-list-element.component.html, src/app/shared/object-list/browse-entry-list-element/browse-entry-list-element.component.spec.ts, src/app/shared/object-list/browse-entry-list-element/browse-entry-list-element.component.ts
* Fixes #1713
* Fixes https://github.com/DSpace/DSpace/issues/8470
This PR solves the issue where when clicking a browse entry, the current page is incorrectly transferred to the page you clicked.
It also makes sure that when you click the '**<-- All browse results**', you are returned to the same page number as where you originally were redirected from.
Using `api7.dspace.org` backend, visit `[dspace]/browse/author?bbm.page=112` .
Scroll down and click browse entry '**Simmons, Cameron**'.
This should redirect you to the **first** page of this author's articles: the pagination buttons at the bottom should show that you are on the first page.
Clicking '**<-- All browse results**' should send you back to the 112th page of the author browse-by pages: `[dspace]/browse/author?bbm.page=112`
=> Fix pagination in metadata browse links

src/app/process-page/detail/process-detail.component.html, src/app/process-page/detail/process-detail.component.spec.ts, src/app/process-page/detail/process-detail.component.ts, src/app/process-page/overview/process-bulk-delete.service.spec.ts, src/app/process-page/overview/process-bulk-delete.service.ts, src/app/process-page/overview/process-overview.component.html, src/app/process-page/overview/process-overview.component.spec.ts, src/app/process-page/overview/process-overview.component.ts, src/assets/i18n/en.json5
* Fixes #1660
This PR contains functionality to delete processes.
On a process page, a delete button has been added that will delete the current process and navigate the user back to the overview page.
On the overview page, a trash bin icon has been added that can be clicked to toggle a process for deletion. This allows a user to select a bunch of processes for deletion. When 1 or more processes are selected, a button will be shown to delete all the processes.
To test the individual process deletion, perform the following steps: 
* Navigate to a process detail page
* Click the delete button
* Confirm the delete in the popup
* Verify that you are navigated to the overview page and that the process has been deleted
To test the bulk process deletion, perform the following steps: 
* Navigate …
=> Add delete process functionality

src/app/submission/import-external/submission-import-external.component.html, src/app/submission/import-external/submission-import-external.component.spec.ts, src/assets/i18n/en.json5
* Fixes #1678
a new `<div>` has been added to html component for import from external sources, displaying an ad-hoc error message whenever REST call to query external system returns a 500 http error code.
* added a `div` providing an error message in case of 500 http error code returned by REST endpoint performing live import query
* added a test to check correct display of above mentioned `div` in case of 500 error.
The 500 error code behavior is hard to reproduce, …
=> External provider query error

config/config.example.yml, src/app/home-page/home-page.component.html, src/app/home-page/home-page.component.ts, src/app/home-page/home-page.module.ts, src/app/home-page/recent-item-list/recent-item-list.component.html, src/app/home-page/recent-item-list/recent-item-list.component.spec.ts, src/app/home-page/recent-item-list/recent-item-list.component.ts, src/assets/i18n/en.json5, src/config/app-config.interface.ts, src/config/default-app-config.ts, src/config/homepage-config.interface.ts, src/environments/environment.test.ts
#667 
* Fixes #667 
Displaying Recent Submissions on the Repository's homepage with option of configuring number of items required to be displayed.
Update the "rpp" variable in the config.example.yml with the item count that needs to be displayed in the Recent Submission section.
If you do not want to display any item under the Recent Submission section, keep the "rpp" count = 0.
Restart the server for the change to take effect, and no need to re-build the application.
Home page will show the Recent Submission section below the community list with the latest items submitted.
Upon clicking the Load more button, users will be redirected to the search results page, and items will list in descending order based on the submission date.
If there is no item submitted in the repository or rpp = …
=> Displaying Recent Submissions on the homepage

scripts/test-rest.ts
Fixes issue reported in https://groups.google.com/g/dspace-tech/c/XU7KFZGOr94/m/aeAlQZo5BQAJ 
Some proxies (namely nginx) may chunk JSON data in responses from the REST API.  This tiny PR ensures that the `yarn test:rest` script can handle chunked data.
Simply put, it updates the existing code to use the 'data' and 'end' events to ensure that we don't just read the first chunk of data, and instead keep reading until the 'end' event fires.  See the docs on `http.ClientRequest` for more details: https://nodejs.org/api/http.html#class-httpclientrequest
* Review the changes
* Test `yarn test:rest` on a valid REST API and ensure it works.  If you happen to have a REST API where data is returned in chunks that'd be even better. 
This PR is based heavily on code sent to me by Sean Kalynuk (U of …
=> Ensure `yarn test:rest` reads all JSON data, not just first chunk

src/app/core/pagination/pagination.service.spec.ts, src/app/core/pagination/pagination.service.ts
This PR adds an optional `NavigationExtras` argument to `PaginationService.updateRoute()`, allowing for some more flexibility.
In particular, we needed this change in one of our client repositories in order to support pagination within tabbed views on a single page. Without `replaceUrl: true`, `PaginationService.updateRoute()` resulted in two location history entries for every on page. 
As far as I'm aware we don't have any similar issues in base DSpace yet, but this little change is worthwile in case we ever do -- and to improve extensibility.
Confirm that this change is useful and won't affect any current uses of `PaginationService` (it's opt-in only)
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior …
=> Add an optional `NavigationExtras` argument to `PaginationService.updateRoute`

package.json, scripts/serve.ts, server.ts, src/app/init.service.ts, src/config/config.server.ts, src/modules/app/browser-init.service.ts, startup-message.ts
* Fixes #1778
* Fixes #1795
Issue #1795: The config building mechanism has been updated to always include the default config from config.yml first. This config is then overwritten by environment config (e.g. config.dev.yml).
Issue #1795: : The 'yarn run serve' command has been repaired to use the proper 'ui' config.
* The 'buildAppConfig' method in config.server.ts has been updated to always use the default config.yml first
* Getting the default config.dev.yml path has been moved to a separate method 'getDefaultConfigPath', the 'getLocalConfigPath' method has been renamed to 'getEnvConfigFilePath'.
* The 'yarn run serve' command has been updated to use the serve.ts file
* The cli parameters in this file have been updated with '--configuration development'
* The version in package.json has …
=> Repair config issues

config/config.example.yml, src/config/default-app-config.ts
This is a small PR to enable the Kazakh translation provided by @myrza1 in #1297
As it's simply a configuration change, I'll merge it after tests succeed.
=> Enable Kazakh translation by default

src/app/core/submission/submission-cc-license-data.service.spec.ts, src/app/core/submission/submission-cc-license-data.service.ts
Testing an issue on the current main branch, I have seen that the Creative Commons selector of the submit form is not loading. The problem seems to be an unimplemented function findAll in SubmissionCcLicenseDataService after applying PR #1791  
I have tried to fix the problem by implementing the function in a similar way to other data services and it seems to work fine.
* Activate the cclicense step in item-submission.xml
* Check that the cc selector is not loaded in a new submission and the javascript console shows an error
* Apply the patch and test again
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the …
=> Creative Commons selector is not loading

src/app/core/auth/auth-request.service.spec.ts, src/app/core/auth/auth-request.service.ts, src/app/page-error/themed-page-error.component.ts, src/app/page-internal-server-error/themed-page-internal-server-error.component.ts, src/app/pagenotfound/themed-pagenotfound.component.ts, src/app/shared/theme-support/theme.service.spec.ts, src/app/shared/theme-support/theme.service.ts
* Fixes #1829
* Fixes #1830
This PR bundles fixes for a few bugs that were (re)introduced recently:
* Theme CSS not loading when `ui.nameSpace` is set
* Stylesheet links were added with an absolute path instead of relative
* This was originally fixed in #1642 [here](https://github.com/DSpace/dspace-angular/pull/1642/files#diff-884f7f49640e5923f6bcac4c51d90340330a178f662defbe61e5f5aac1c512deR271) and reintroduced in #1741 when that method was moved to `theme.service.ts`.
* Blank page instead of error page when REST server is down
* The `checkTokenCookie$` NgRx effect would 
* This was introduced in #1805 by refactoring authentication requests to follow the pattern we use for equivalent DataService methods, highlighting …
=> Regression fixes

src/app/home-page/home-page.module.ts, src/app/home-page/recent-item-list/recent-item-list.component.html, src/app/home-page/recent-item-list/recent-item-list.component.spec.ts, src/app/home-page/recent-item-list/recent-item-list.component.ts, src/app/thumbnail/thumbnail.component.spec.ts, src/app/thumbnail/thumbnail.component.ts
* Fixes #1855
This PR fixes list thumbnails in the "Recent Items" section on the homepage. The cause ended up being a combination of the following three bugs:
* `ds-recent-item-list` was not updated to match the changes in #1780 (`followLink('thumbnail')` and CSS class to determine thumbnail placeholder font)
* `HomePageModule` was not set up with all entity classes; it would render results as plain Items, skipping the custom SVG images for e.g. Projects
* `ds-thumbnail` would sometimes fall back to the placeholder even when the default image was valid (faulty logic from #1694)
**TODO:**
Make sure `browseBy.showThumbnails` is set to true and confirm that #1855 can no longer be replicated.
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need …
=> Fix recent submissions list thumbnails

src/app/my-dspace-page/my-dspace-new-submission/my-dspace-new-submission.component.ts, src/assets/i18n/en.json5, src/assets/i18n/fr.json5
* Fixes #1765
Send the user directly to the submission page instead of showing a potential misleading notification.
* Removed the notification when uploading a single file in `my-dspace-new-submission.component.ts`.
* Redirect the user to the generated link instead.
* Removed unused translations in `en.json5` and `fr.json5`.
**See #1765 for more information about the problem and how to reproduce it.**
=> After drag & drop: Redirect the user and remove the notification

server.ts, src/app/core/services/browser-hard-redirect.service.spec.ts, src/app/core/services/browser-hard-redirect.service.ts, src/config/config.util.spec.ts, src/config/default-app-config.ts, src/config/ui-server-config.interface.ts, src/environments/environment.test.ts
* Fixes #1721
* Alternative to https://github.com/DSpace/dspace-angular/pull/1725
This PR fixes #1721 by checking for the presence of the `x-forwarded-proto` and `x-forwarded-host` headers server side, and using them instead of the default `host` and `protocol` properties on the request if they are available.
To stay on par with https://github.com/DSpace/dspace-angular/pull/1725, I also added the same small extra fix to ensure a redirect ends up in the browser's history
Run the app in prod mode. And test it with and without a proxy server in front that's configured to use the `x-forwarded` headers
Test that the `citation_pdf_url` on an item page always contains a URL that uses with the correct host and protocol, with and without using a proxy server .
To test the redirect change, download …
=> Use values from x-forwarded headers in getOrigin server side

src/app/item-page/mirador-viewer/mirador-viewer.component.spec.ts, src/app/item-page/mirador-viewer/mirador-viewer.component.ts, src/app/item-page/mirador-viewer/mirador-viewer.service.ts
Fixes a bug in `mirador-viewer.component` that incorrectly sets the `multi` property when images are added to bundles other than `ORIGINAL`.
The PR modifies the Angular UI to look for images in ALL eligible Bundles, not just  ORIGINAL.
**Some quick background:** the `multi` property is set by the `mirador-viewer.component` component and is passed to the Mirador viewer, which in turn uses the property to create internal configuration at startup. (The default Mirador behavior is to add right thumbnail navigation when `multi` is 'true.') `multi` should be true whenever the Item has multiple image bitstreams.
_Sorry! I just realized I didn't submit this bug fix earlier!! It's a fairly minor fix so if it can make it into 7.4 that would be great._
* Create an IIIF-enabled Item with more than …
=> Bug fix for multiple IIIF image property

src/app/access-control/epeople-registry/epeople-registry.component.ts, src/app/access-control/group-registry/groups-registry.component.ts
* Fixes #1870
Fixes the issue where deleting an EPerson from `/access-control/epeople` caused the search request to be repeated forever.
Seems like this was caused by the new invalidation logic in the data service (depentent requests) interacting with the old invalidation logic in the component. The problem can be fixed by removing the `reset()` call when the delete succeeds.
Also fixes the issue were the groups list on `/access-control/groups` wouldn't update after deleting a group. It looks like this wasn't a recent issue. It was caused by [a `return` inside an  `if` that lacked an `else` ](https://github.com/DSpace/dspace-angular/blob/main/src/app/access-control/group-registry/groups-registry.component.ts#L149), so …
=> Fix infinite loop when deleting an EPerson

src/app/item-page/field-components/metadata-uri-values/metadata-uri-values.component.spec.ts, src/app/item-page/field-components/metadata-values/metadata-values.component.spec.ts, src/app/item-page/field-components/metadata-values/metadata-values.component.ts, src/app/item-page/simple/field-components/specific-field/abstract/item-page-abstract-field.component.spec.ts, src/app/item-page/simple/field-components/specific-field/author/item-page-author-field.component.spec.ts, src/app/item-page/simple/field-components/specific-field/date/item-page-date-field.component.spec.ts, src/app/item-page/simple/field-components/specific-field/generic/generic-item-page-field.component.spec.ts, src/app/item-page/simple/field-components/specific-field/item-page-field.component.spec.ts, src/app/item-page/simple/field-components/specific-field/uri/item-page-uri-field.component.spec.ts, src/config/default-app-config.ts
This is a continuation of https://github.com/DSpace/dspace-angular/pull/1851/.
This PR is merged already, but apparently the code causes test failures sometimes.
I've updated the tests so they are more stable and should no longer fail now.
=> repair tests bis

src/assets/i18n/pt-BR.json5
Fully translated til line 538 and other small corrections.
=> pt-BR translation contribution

src/app/shared/form/builder/ds-dynamic-form-ui/ds-dynamic-form-control-container.component.html, src/app/shared/form/builder/ds-dynamic-form-ui/models/ds-dynamic-input.model.ts, src/app/shared/form/builder/form-builder.service.spec.ts, src/app/shared/form/builder/form-builder.service.ts, src/app/shared/form/builder/parsers/concat-field-parser.ts, src/app/shared/form/form.service.spec.ts, src/app/shared/form/form.service.ts, src/app/shared/mocks/form-builder-service.mock.ts
* Fixes #1353
Currently, `name` fields in submission forms are not flagged as invalid when they return as a server error (i.e.: empty required field)
Came across three separate tiny issues while debugging & fixing this
* `FormBuilderService.findById` was expecting the `id` of one of the group's inputs to end in a numeric suffix. I haven't been able to track down where this extra suffix would be set, so I'm assuming this was a bug.
IMO, for the field to be flagged "correctly", we should flag the _group_ itself so that _both_ inputs show an error
* When a whole group is marked as invalid, its inputs should also be marked invalid. As far as I'm aware this will only affect the case of invalidation via server errors.
* With these "concat fields", the individual inputs will _also_ get an error …
=> Fix error validation for required `name` fields in submission

src/app/shared/object-list/object-list.component.scss
* Fixes #1874
Adds a z-index to `ds-selectable-list-item-control` to ensure it gets rendered higher than the thumbnail
Verify that you can select a checkbox or radio button in the relationship modal
=> Fix z-index issue with thumbnails in item list checkboxes

src/app/core/eperson/models/workspaceitem.resource-type.ts, src/app/core/submission/models/workspaceitem.model.ts, src/app/submission/sections/form/section-form.component.spec.ts, src/app/submission/sections/form/section-form.component.ts
* Fixes #1822
During workflow, after selecting an entity in a metadata (i.e dc.contributor.author) the value is not displayed in the UI but the relation is effectivelly created.
Currently there are two strict equality comparisions which always return false in section-form-component.ts when checking for submission scope. The patch allow proper comparision between values.
There are similar patches using boxing elsewere in the code. I think this is caused by the deserialisation of the response by angular which type submissionObject.type as string instead of an instance of the class «ResourceType». Casting submissionObject allow us to compare the strings.
A more robust solution would likely be to adjust how angular deserialise the response into a submissionObject. However it would also …
=> Fix for PR#1822 - Adjusted two equality checks for scope type which always return false.

src/app/access-control/group-registry/group-form/members-list/members-list.component.ts, src/app/core/eperson/group-data.service.spec.ts, src/app/core/eperson/group-data.service.ts
* Fixes #1879
Similar to https://github.com/DSpace/dspace-angular/issues/1870, this issue was caused by an infinite loop of re-requests because both the group and the eperson had been manually invalidated in the past.
However because of https://github.com/DSpace/dspace-angular/pull/1846 this is no longer necessary. Removing the manual invalidation of the group fixes the issue
Verify that you can add and remove members to groups without problems. Keep an eye on the network tab to ensure the number of requests remains in check
=> Fix issue when deleting a member from a group

src/app/admin/admin-registries/bitstream-formats/bitstream-formats.component.spec.ts, src/app/admin/admin-registries/bitstream-formats/bitstream-formats.component.ts
* Fixes #1882
The issue here was older, likely introduced by https://github.com/DSpace/dspace-angular/pull/975: the `BitstreamFormatDataService` had been refactored to work using RemoteData objects, but the delete method in the component wasn't updated afterwards. As a consequence the error notification is shown when the dataService emits the first time, to indicate that the response is pending. When it emits again afterwards, once the response comes in, the success notification is shown. 
The solution was to add [a `getFirstCompletedRemoteData()`](https://github.com/DSpace/dspace-angular/pull/1886/files#diff-7e77f4781bd13dbee4cc856d0e48e82644b594f2b5ea1e2957da6fcbd4075551R70) operator
I also refactored the delete method to get rid of the nested subscribes
Delete bitstreamformats …
=> Fix dual notification when deleting bitstreamformats

src/app/core/data/base/data-service.decorator.spec.ts
* Fixes #1920
Replaced the timestamp (intended to produce unique "testType" instances) with UUID, because intermittent failures are occurring when tests are running quickly enough that the "new Data().getTime()" function is returning the same timestamp for multiple tests.
* In "src/app/core/data/base/data-service.decorator.spec.ts", replaced the use of timestamps to create unique "testType" objects in the "beforeEach" with UUIDs, to ensure that unique "testType" objects are created even if the tests complete in under a millisecond.
The test failures described in #1920 are …
=> Issue 1920 - "data-service.decorator.spec.ts" tests fails intermittently

src/app/shared/form/builder/ds-dynamic-form-ui/models/ds-dynamic-concat.model.ts
**References**
* Fixes #1892 
A bug was discovered with name fields that are not repeatable - they do not obey type bind.
This was found to be because the form control model used is `dynamic-concat-model` and this model did not specifically set required type bind configuration.
This pull request fixes the issue for concat model, but there may be other form control models around that have the same issue. If more are found in the short term, I will rename this issue / PR and continue committing fixes to other form control models here.
* See instructions at #1892
=> [#1892] Apply type-bind properly to concat fields that are not dynamic arrays

src/app/shared/form/builder/ds-dynamic-form-ui/models/list/dynamic-list-checkbox-group.model.ts
Checkbox groups were always displayed, because they did not include the type-bind relations. This commit adds the missing property
* Adds `typeBindRelations` property to `DynamicListCheckboxGroupModel` and `DynamicListCheckboxGroupModelConfig`
Verify functionality: 
1. Have a type-bound field with `input-type` of `list` and `repeatable`set to `true` in your submission form
2. Regardless of the type-binding setup the field will always display
3. Apply patch
4. The field is now only displayed for the type bound types
_This checklist provides a reminder of what we are going to look for when reviewing your PR. …
=> Fix missing type-bind relations for checkbox group

src/app/item-page/field-components/metadata-values/metadata-values.component.html, src/app/item-page/simple/field-components/specific-field/generic/generic-item-page-field.component.ts, src/app/item-page/simple/item-types/publication/publication.component.html, src/app/item-page/simple/item-types/untyped-item/untyped-item.component.html
* https://github.com/DSpace/dspace-angular/pull/1851
This PR bundles a few minor fixes related to https://github.com/DSpace/dspace-angular/pull/1851
* Even spacing between comma-separated MDVs (e.g. subjects)
This was an older issue, caused by line breaks within the `<span>`, which Angular translates into unwanted spacing. Now we include a space in the separator itself: `', '`
* Made `enableMarkdown` an input of `ds-generic-item-page-field` so it's easier to enable Markdown for arbitrary Item page fields
* When the new `dsMarkdown` pipe is combined with the new `.preserve-line-breaks` CSS class, line breaks in Markdown are effectively doubled. Therefore, we shouldn't add this class when rendering Markdown.
Confirm that this PR solves the issues listed above and that the changes are …
=> Minor fixes related to line breaks & Markdown in metadata fields

src/app/navbar/expandable-navbar-section/expandable-navbar-section.component.html, src/app/navbar/expandable-navbar-section/expandable-navbar-section.component.scss, src/app/navbar/navbar-section/navbar-section.component.html, src/app/navbar/navbar-section/navbar-section.component.scss, src/app/navbar/navbar.component.html, src/app/navbar/navbar.component.scss, src/app/navbar/navbar.component.spec.ts, src/app/navbar/navbar.component.ts, src/app/root/root.component.html, src/app/shared/animations/slide.ts, src/app/shared/auth-nav-menu/auth-nav-menu.component.html, src/app/shared/auth-nav-menu/user-menu/user-menu.component.html, src/app/shared/auth-nav-menu/user-menu/user-menu.component.spec.ts, src/app/shared/auth-nav-menu/user-menu/user-menu.component.ts, src/assets/i18n/en.json5, src/themes/dspace/app/navbar/navbar.component.html, src/themes/dspace/app/navbar/navbar.component.scss, src/themes/dspace/styles/_global-styles.scss
* Fixes #1890 
* Fixes #1891 
* On wide screens clicking on the user icon opens the user menu. On narrow screens clicking on the user icons redirects to logout page, and other user menu voices are missing from the UI. With this PR, on narrow screens, when user is logged:
* missing user menu voices have been added to the expandable menu
* user icon has been replaced with logout icon, and the tooltip has been replaced accordingly
* Horizontal alignment and vertical arrangement of menu items has been fixed
* The behaviour of the root component has been fixed when the admin sidebar is open
All changes have been made for both dspace and base theme.
When sidebar was open, a left padding of the same size of the sidebar was added to the inner-wrapper of the root …
=> Fix issues with user menu on different screen sizes

src/app/collection-page/edit-collection-page/collection-source/collection-source-controls/collection-source-controls.component.html
* Partial fix for DSpace/DSpace#8298 (along with DSpace/DSpace#8551)
This issue was found during work on https://github.com/DSpace/DSpace/pull/8551 in the DSpace repository. While testing that bug I noticed that the `lastHarvested` and `message` fields are reversed in the HTML template. This fixes the issue so that they're displayed next to the correct label.
=> DS-8298: fixes issue where the lastHarvested and message fields were reversed

src/app/shared/date.util.spec.ts
* Fixes #1941 
Some unit tests were failing when the timezone of the OS had a positive UTC/GMT offset. This has been fixed by using UTC date format as input for the tested methods:
```javascript
// const date = new Date(2022, 5, 3);
const date = new Date(Date.UTC(2022, 5, 3));
```
If you live in a region where the UTC/GMT offset is negative, then change the time zone of your OS so that the UTC/GMT offset is positive (e.g. Europe Central Time, GMT+0100). You can check the offset on your browser's console: 
```javascript
console.log(new Date())
```
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't …
=> Test cases of date.util.spec.ts fixed

src/app/shared/rss-feed/rss.component.spec.ts, src/app/shared/rss-feed/rss.component.ts
* Fixes #1905 
This small PR fixes the path issues in the RSS link. 
See #1905 for testing instructions.
=> DS-1905: fixes route function to match default value of websvc.opensearch.svccontext

src/assets/i18n/fr.json5
Adding missing params and their french translations for : licence approval, SHERPA,  external sources and processes.
=> Addition of missing params

.github/pull_request_template.md, CONTRIBUTING.md, README.md
* Fixes DSpace/DSpace#8294
Copies/updates the CONTRIBUTING.md file from https://github.com/DSpace/DSpace/pull/8568 into `dspace-angular`
Minor updates have been added to align with the PR template for this codebase
=> Add CONTRIBUTING docs and resync with PR template

.github/workflows/codescan.yml
Port of Code Scanning from DSpace/DSpace#8548 to Angular UI
Enables GitHub [Code Scanning](https://docs.github.com/en/code-security/code-scanning) via a new GitHub Action defined in `codescan.yml`
This will (eventually) replace our usage of LGTM.com, as LGTM is retiring later this year (after being integrated into GitHub).  See https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/
Currently, Code Scanning is configured with default settings & enabled for all PRs and all commits to `main`.
**It appears this PR has run it's own initial scan** which can be found in the "Code scanning results" in the checks below.  This can be used to review this PR is working, and it shows that we have some code cleanup/analysis to do. It is also possible some of these are false …
=> Update to use GitHub CodeQL for code scanning (Angular UI)

src/app/shared/dso-selector/modal-wrappers/create-community-parent-selector/create-community-parent-selector.component.html, src/app/shared/search-form/scope-selector-modal/scope-selector-modal.component.html, src/assets/i18n/en.json5, src/themes/custom/app/shared/dso-selector/modal-wrappers/create-community-parent-selector/create-community-parent-selector.component.html
* Fixes #1726 
* Fixes #1728 
* Fixes #1729
Missing translations have been added, 'or' hard coded has been moved to i18n files.
* Components having 'or' hard coded have been updated with usage of translations
* missing translations added to i18n files
**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, screenshots or description of a new feature, or reasons behind specific changes.
=> [CST-7693] Missing Translations added

src/app/register-email-form/register-email-form.component.spec.ts, src/app/register-email-form/register-email-form.component.ts
* Fixes #1983 
Updates our regex validator for email addresses to use the documented regex in the HTML5 specs for a valid email: https://html.spec.whatwg.org/multipage/input.html#valid-e-mail-address
This ensures that uppercase characters are now acceptable in emails, along with some other missing special characters which were not accepted by our previous regex.
* Verify code & new test for uppercase characters
* Manually test that uppercase characters no longer throw a validation error (making the input box red)
=> Fix email validation regex to use email validation regex from HTML5 specs

.github/workflows/build.yml, Dockerfile, README.md, cypress.json, docker/docker-compose-ci.yml, package.json, yarn.lock
* Addresses #1865
Upgrade `eslint-plugin-jsdoc` to make `yarn install` succeed.  With this change, dspace-angular builds successfully and seems to run well using Node v18.10.0.
* upgrade eslint-plugin-jsdoc to 39.3.6
=> Support Node v18

src/app/breadcrumbs/breadcrumbs.component.html, src/app/breadcrumbs/breadcrumbs.component.spec.ts
Small PR based in [Angular Issue](https://github.com/DSpace/dspace-angular/issues/1794)
Expected result:
=> Use full community, collection and item names in breadcrumb navigation

Dockerfile
After merging #2000 , the Docker build for arm64 platforms started failing because Python is not found. See https://github.com/DSpace/dspace-angular/actions/runs/3706259487.  
I don't believe this issue is directly related to #2000 (as least I'm not seeing the direct relation), but may be the result of a recently update to the base `node:18-alpine` image for arm64.
This small PR fixes the issue. I've tested this in my own CI builds and verified that the Docker arm64 image now builds successfully.
=> Fix Docker arm64 build

src/app/collection-page/collection-page-routing.module.ts, src/app/community-page/community-page-routing.module.ts, src/app/item-page/item-page-routing.module.ts, src/assets/i18n/fr.json5
This fixes the issue that the "Statistics" option in the header switches places.
* Added the index parameter to the different required routing modules
How to test this PR:
1. Set up a base DSpace instance ( this happens on https://demo7.dspace.org/home for example)
2. Browse along Community / Collection / Item pages -> notice that the "Statistics" link in the header changes place
3. Set up a DSpace instance with the changes of this PR and verify this behaviour has been fixed
=> Fix statistics option position in header on different DSO pages

src/app/shared/form/builder/ds-dynamic-form-ui/ds-dynamic-form-control-container.component.spec.ts, src/app/shared/form/builder/ds-dynamic-form-ui/ds-dynamic-form-control-container.component.ts, src/app/shared/form/builder/ds-dynamic-form-ui/existing-metadata-list-element/existing-metadata-list-element.component.scss, src/app/shared/form/builder/ds-dynamic-form-ui/existing-relation-list-element/existing-relation-list-element.component.html, src/app/shared/form/builder/ds-dynamic-form-ui/existing-relation-list-element/existing-relation-list-element.component.spec.ts
* Fixes #1974
Fixes problem with missing thumbnails and bad placeholder layouts for relationships in submission forms.
* Added thumbnail follow link for related item lookups
* Modified html template for `ds-existing-relation-list-element` to fill entire row regardless of how much text is shown in the item metadata.
=> Fix for related item thumbnail images.

config/config.example.yml, src/app/access-control/group-registry/group-form/group-form.component.ts, src/app/admin/admin-registries/bitstream-formats/format-form/format-form.component.ts, src/app/collection-page/collection-form/collection-form.models.ts, src/app/community-page/community-form/community-form.component.ts, src/app/shared/form/builder/parsers/textarea-field-parser.ts, src/config/default-app-config.ts, src/config/form-config.interfaces.ts, src/environments/environment.test.ts
* Fixes #1798
Currently, by default, dspace-angular generates textarea elements with spellcheck="false" attributes. This PR enables the spellcheck attribute value to be set via config. The default behavior has been updated to spellcheck="true" to match the DSpace v6 default behavior.
Fire up the devserver and confirm that textarea form fields have the spellcheck="true" attribute value. Spellcheck behavior will depend on browser settings, but if spellchecking is not disabled spelling mistakes will be highlighted.
To verify the original behavior (spellcheck="false") set `form.spellCheck: false` in the config and repeat.
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are …
=> Enable / disable spellcheck for textarea inputs via config

config/config.example.yml, src/config/default-app-config.ts
* Follow up to #2001 which provides the actual Polish translations (thanks again @michdyk !)
This small PR just updates our default configuration to enable Polish in the list of supported languages.
I used the changes in this PR to test #2001, so once this passes our GitHub CI, I'm going to merge it immediately.
=> Enable Polish language by default

src/assets/i18n/en.json5
* Required by https://github.com/DSpace/DSpace/pull/8593
Tiny PR to add the missing i18n key for the new DataCite import source added in https://github.com/DSpace/DSpace/pull/8593
As I used this tiny PR to test the backend PR, I know it works.  **I'll merge it immediately after GitHub CI passes.**
=> Add DataCite to i18n list of sources

src/assets/i18n/es.json5
Hi @tdonohue here is my proposal to solve this problem.
* Fixes #2059 
The file `es.json5` just needed to add an space for the label `pagination.showing.label`
1. Login as adminsitrator.
2. Visit: /mydspace?configuration=workflow
3. change the language to spanish
4. You will notice that there is a space between the text "mostrando" (showing) and the number
* es.json5 file
=> adding space in es.json5 for pagination.showing.label

src/app/item-page/edit-item-page/item-operation/item-operation.component.html, src/assets/i18n/ar.json5, src/assets/i18n/bn.json5, src/assets/i18n/cs.json5, src/assets/i18n/de.json5, src/assets/i18n/en.json5, src/assets/i18n/es.json5, src/assets/i18n/fi.json5, src/assets/i18n/fr.json5, src/assets/i18n/gd.json5, src/assets/i18n/hu.json5, src/assets/i18n/ja.json5, src/assets/i18n/kk.json5, src/assets/i18n/lv.json5, src/assets/i18n/nl.json5, src/assets/i18n/pt-BR.json5, src/assets/i18n/pt-PT.json5, src/assets/i18n/sv.json5, src/assets/i18n/sw.json5, src/assets/i18n/tr.json5, src/assets/i18n/uk.json5
Hi @tdonohue, I did the activity with ID 470077 found in issue #1190. I will be attentive to any comment 👍 .
* Fixes part of #1190
I modified the text "withdraw..." and "Move..." according to Tim's specifications. Also, I added the aria-label attribute to support people with disabilities. I modified the translation of some countries to adapt to this change.
I modified the .json5 files to accommodate the requested change. Also I added an aria-label tag in the buttons requested by Tim so that the aria-label attribute contains the text according to the language.
* Changed texts in .json5 files. (item.edit.tabs.status.buttons.withdraw.button and item.edit.tabs.status.buttons.move.button)
* aria-label added added for 2 buttons in: item-operation.component.html
1. …
=> fixed ID 470077. Purpose of the link is not clear in context

src/app/admin/admin-sidebar/admin-sidebar.component.ts, src/app/core/data/feature-authorization/feature-id.ts, src/app/menu.resolver.spec.ts, src/app/menu.resolver.ts, src/app/root/root.component.ts, src/app/shared/menu/menu.service.spec.ts, src/app/shared/menu/menu.service.ts, src/app/shared/testing/menu-service.stub.ts
* Fixes [#1643](https://github.com/DSpace/dspace-angular/issues/1643)
* Lays groundwork for [#1331](https://github.com/DSpace/dspace-angular/issues/1331)
* [Related backend PR](https://github.com/DSpace/DSpace/pull/8607)
* Frontend: hides admin sidebar sections for users who lack relevant permissions.
* Backend: adds authorization features to support the frontend changes.
* The menu resolver now checks the new `canSubmit` and `canEditItem` authorizations to determine whether to add the corresponding sections to the admin sidebar for a logged-in user.
* If this results in the user having no permissions at all, the admin sidebar is omitted altogether.
1. Make some users:
1. one with no permissions at all
2. one with write permissions on a single item (or admin …
=> Fix user authorization issues with admin sidebar

src/app/search-navbar/search-navbar.component.scss
* Fixes #1393
Problem: the search box has a transparent background, and on medium screens it overlaps with main menu on medium screen
Solution: the search box background has been replaced with opaque white.
=> [CST-7221] Opaque search bar

src/app/item-page/edit-item-page/edit-item-page.component.html
Hi @tdonohue ✋, I am submitting this pull request as a solution to activity ID 470076 in issue 1190. Regarding "Selected state of the element is missing or incorrect."
* Fixes first issue noted in #1190
in each of the tabs of the page that opens when editing an item, an aria-selected has been added, if the tab is active, it will have the value of "true", if not, it will have the value of "false".
* _[attr.aria-selected]="page.page === currentPage"_ added in _edit-item-page.component.html_
To test my PR:
1. Login as adminsitrator
2. Edit any item
3. check the value of aria-selected of each li tag in the displayed tab.
=> aria-selected added to Item Edit "Status" Tab. Fixed ID: 470076

config/config.example.yml, package.json, server.ts, src/config/cache-config.interface.ts, src/config/default-app-config.ts, src/environments/environment.test.ts, src/index.html, yarn.lock
* Relates to #1954 and #1921
This PR adds basic, in-memory page caching of all *public* server-side rendered pages.  As most SSR requests are for public (anonymous access) pages, this can significantly increase the speed of the site.  
(However, it has no impact on the speed of SSR for authenticated content -- as it's not possible to cache this access-restricted content since it is much more dynamic & may include user-specific, sensitive information.)
* Adds a new `serverSide` section to the `cache` settings in `config.yml`:
```
serverSide:
debug: false
botCache:
max: 1000
timeToLive: 86400000 # 1 day
allowStale: true
anonymousCache:
max: 0
timeToLive: 10000 # 10 seconds
allowStale: true
```
* Updates the `Cache-Control` HTTP Header behavior to help a user's …
=> Add Caching of SSR public pages. Update default Cache-Control HTTP header

src/app/header/context-help-toggle/context-help-toggle.component.ts, src/app/shared/context-help-wrapper/context-help-wrapper.component.ts
Follow-up on #2030: This PR just contains a minor fix to remove some unnecessary subscriptions. This is just an improvement to code quality, it does not fix any bugs or add new features.
There were some unnecessary subscriptions in `ContextHelpWrapperComponent` and `ContextHelpToggleComponent` to observables which were only being used in their respective templates. These subscriptions have been removed.
No behavior is changed; it should suffice to take a glance at the diff.
=> Remove unnecessary subscriptions

src/app/core/breadcrumbs/dso-breadcrumbs.service.ts
* Fixed #2090
Fixes issue where withdrawn item page won't load in SSR.  The issues was with the breadcrumbs loading for a withdrawn item.
See steps to reproduce in #2090
=> Fix for "cannot read properties of undefined" error for Withdrawn Items

src/app/search-page/search-page.component.html, src/app/shared/search/search-results/search-results.component.html, src/app/shared/search/search-results/search-results.component.ts, src/app/shared/search/search-results/themed-search-results.component.ts, src/app/shared/search/search.component.html, src/app/shared/search/search.component.ts, src/app/shared/search/themed-search.component.ts
* Fixes #2010
This PR add a flag to enabled/disabled the csv export button when using the search.component. With this PR by default the export button is hidden and is enabled only for the public search.
Check if the export button is shown only in the public page and not in other places as described here #2010
=> Add flag to show/hide csv export button

src/app/app.module.ts, src/app/shared/form/form.module.ts
* Fixes #2099 
Check the bug is fixed
=> Fix issue with missing matcher providers

src/app/shared/search/search-labels/search-label/search-label.component.ts, src/app/shared/search/search-labels/search-labels.component.ts
Hello @tdonohue i have good news. I've fixed **Removing a filter generates an invalid query**. I will be attentive to any comments. 😄 
* Fixes #1998
When user unselect a filter tag option, the query is executed succesfully.
* i moved stripOperatorFromFilterValue from `search-labels` component to `search-label`.
1. go to search section.
2. apply two subject queries.
3. unselect any of them
4. you will see that the query is executed succesfully
=> avoiding error when user unselect a filter option

src/app/shared/form/chips/chips.component.html, src/app/shared/form/chips/chips.component.spec.ts
Hello @tdonohue this is mi pull request. i will be attentive to any comment. 👍  (sorry for a lot of pull request, i was struggling with the github sync hehe).
* Fixes #1187 with ID 469537
This pull request solves ID 469537. Now ds-chips component has role list and listitem
1. Login as administrator
2. Create new item.
3. add keywords for dc.subject
4. see the div with _role="list"_, you can see inside of this div there are elements with _role="listitem"_.
* Instead of using _ul_ and _li_ they were replaced to _div role="list"_ and _div role="listitem"_ respectivelly to keep the input inside the container.
* Test changed from li.nav-item to div.nav-item
=> ul and li replaced to role list and listitem

src/app/shared/mydspace-actions/workspaceitem/workspaceitem-actions.component.html, src/assets/i18n/en.json5
Hello @tdonohue i have already with the 3rd task for this issue. I will be attentive to any comments.
* Fixes #1186 (ID 470750)
I added an `aria-label` for edit, delete and view buttons in my dspace section.
* `aria-label` added in edit, view and delete button inside of `workspaceitem-actions.component.html` file.
* i chanfed the text for: `submission.workflow.generic.delete-help` in en.json5
1. login as administrator.
2. go to my dspace section
3. open the browser console. You will see that the three buttons has aria-label according to the tooltip.
=> Buttons have same name but different actions.

src/app/collection-page/collection-page.component.ts
Hello @tdonohue i have already finished with this issue. I hope it is worth for DSpace. ✋
* Fixes #2044
Pagination Size in Browser Recent Submission is related to the configuration yml file.
1. Configure browseBy: pageSize with the desired number.
2. Go to any collection with items
3. in Recent Submission tab the items will be paginated according to the number
* pageSize instead of static number (5) is dinamically configured: `pageSize: this.appConfig.browseBy.pageSize`
**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, screenshots or description of a new feature, or reasons behind specific changes.
=> pageSize applied in Recent Submissions

src/app/browse-by/browse-by-metadata-page/browse-by-metadata-page.component.ts
Hello @tdonohue ✋. i already finished this issue. I will be attentive to any comments.
* Fixes #2128
Browse By Metadata page will work correctly on numeric 'value' param.
i just avoid the symbol "+" in "+startsWith" to prevent conversion from string to number.
1. login
2. select any section from "all of DSpace" that its index is according to a metadata value.
3. Search for an item that has leading "0". (like in the issue)
4. you should be able to find the item.
=> browse-by-metadata-page works correctly on numeric 'value' param

src/app/browse-by/browse-by-date-page/browse-by-date-page.component.spec.ts, src/app/browse-by/browse-by-date-page/browse-by-date-page.component.ts, src/app/browse-by/browse-by-metadata-page/browse-by-metadata-page.component.ts, src/app/core/browse/browse.service.ts
Attempts to set an upper limit to the browse by year options. So for example if a collection contains publications from 2001- 2010 the first year in the dropdown list is 2010 (not 2023). 
* Modified the browse-by-date-page.component to set the upper limit by checking the date field of the most recent item.
* Modified the browse.service function to accept an optional SortDirection parameter.
To test this, browse a collection in which no item has a date.issued value from 2023. The first year in the pulldown should match the most recent item in the collection. Note that if the most recent item doesn't have a properly formatted date then the year option will default to the current (2023) year.
_This checklist provides a reminder of what we are going to look for …
=> Added upper limit to browse by date (year)

.github/workflows/docker.yml, Dockerfile.dist, docker/README.md, docker/docker-compose-dist.yml, docker/dspace-ui.json
* The direct motivation is similar to: DSpace/DSpace#8679
Adds a Dockerfile for building a dspace-angular dist image. This can be used to deploy the default ui using a relatively small (currently ~300mb) Docker image.
```
docker build -f Dockerfile.dist -t dspace/dspace-angular:dspace-7_x-dist .
docker compose -f docker/docker-compose-dist.yml build
docker compose -f docker/docker-compose-dist.yml up -d
docker logs -f dspace-angular
```
Changes are exclusively Docker related. No other project files are impacted. 
Check that things work as expected at: http://localhost:4000/ -- should be running with the Demo site backend
You may need to use `docker-compose` rather than `docker compose` depending on how compose is installed.
=> Build & publish dspace/dspace-angular imgs with -dist suffix

Dockerfile, docker/README.md, docker/docker-compose-dist.yml, docker/docker-compose-rest.yml, docker/docker-compose.yml
* Ports changes from https://github.com/DSpace/DSpace/pull/8679 to `dspace-angular` docker scripts
Makes the following small updates to our Docker scripts for UI
* Ports  changes from https://github.com/DSpace/DSpace/pull/8679 to `docker-compose-rest.yml` script
* Updates default `Dockerfile` to use development mode & provides with 4GB default memory
* Without this 4GB memory change, the UI sometimes fails to start up and throws a `JavaScript heap out of memory` error.
* Updates README and comments to enhance our documentation for these docker scripts.
* Try the instructions at https://wiki.lyrasis.org/display/DSPACE/Try+out+DSpace+7#TryoutDSpace7-InstallviaDocker  (which use the scripts in `dspace-angular`) and ensure everything starts properly.
* I've done this testing myself and it's …
=> Minor docker / compose updates based on recent changes to backend

docker/docker-compose-rest.yml
This issue was discovered by Andrés Sendra in Slack.
The configset directories in the `docker-compose-rest.yml` are incorrect after https://github.com/DSpace/DSpace/pull/8679 was merged.  They need to be the same as the configset directories defined in the backend's Docker scripts here: https://github.com/DSpace/DSpace/blob/main/docker-compose.yml#L110-L117
This PR is a follow-up to #2189 which simply removes the "/dspace" subdirectory which no longer exists under the "/configsets" folder.
=> Fix Docker solr configset directories

src/app/admin/admin-import-batch-page/batch-import-page.component.ts, src/assets/i18n/en.json5
* Fixes https://github.com/DSpace/DSpace/issues/8668
* Companion PR: https://github.com/DSpace/DSpace/pull/8735
This PR adds a check for an HTTP 413 response from the backend when importing an SAF file and displays a different message to the user.
1. Go to /admin/batch-import
2. Upload an SAF file larger than 512 MB
=> DS-8668: adds check for HTTP 413 status code when importing an SAF file

src/app/core/data/item-data.service.ts, src/app/item-page/edit-item-page/item-move/item-move.component.spec.ts, src/app/item-page/edit-item-page/item-move/item-move.component.ts
* Fixes #1702 
* Requires DSpace/DSpace#8717 (if a REST API PR is required to test this)
Fixes an issue where the inheritPolicies parameter is not being sent when users request to move item collection and select the box "Inherit policies" when in the Move collection page
* Add inheritPolicies flag to moveCollection method in item-move.component.ts
* Updated relevant test classes to account for new parameter
=> Fix #1702 - Move item collection with inheritPolicies support

.github/workflows/build.yml, .github/workflows/issue_opened.yml, .github/workflows/label_merge_conflicts.yml
* Applying fixes from https://github.com/DSpace/DSpace/pull/8780 to `dspace-angular`
This PR  applies the GitHub action fixes from https://github.com/DSpace/DSpace/pull/8780 to `dspace-angular`.  See that PR for more details.
>I've split our Codecov upload to a separate job (so it can be restarted separately from the rest of the build) and made it auto-retry up to 5 times.
>
> While I was at it, I did a minor update to latest version of a few other github actions.
Additional fixes specific to `dspace-angular` in this PR:
* Updated Cypress action to latest version.  Removed the unnecessary `headless` flag as Cypress defaults to headless mode & that flag displays a warning.
* Fix Yarn caching warning by updating caching syntax to latest example: …
=> Split Codecov GitHub action to separate job & add retries. Update other actions.

src/app/core/core.module.ts
Fixes #2195 
Somewhere along the way the ItemRequest module is no longer being exported.  This results in a blank page in the UI whenever you visit an ItemRequest page:
http://localhost:4000/request-a-copy/[token]
* Create a request for copy
* Restrict a bitstream
* Login as a user without privileges and submit a request for copy.
* As a user who can respond to the request, login and visit http://localhost:4000/request-a-copy/[token]
* Verify on `main` that you see a blank page.
* Verify that with this PR, the request a copy page loads & you can then either approve or reject the request.
=> Add missing export for ItemRequest module

src/app/core/auth/auth.actions.ts, src/app/core/auth/auth.effects.spec.ts, src/app/core/auth/auth.effects.ts, src/app/core/auth/auth.reducer.spec.ts, src/app/core/auth/auth.reducer.ts, src/app/core/auth/auth.service.ts, src/app/core/auth/selectors.ts, src/app/shared/testing/auth-service.stub.ts, src/modules/app/browser-init.service.ts
* Fixes #1665
After the final redirect from external Shibboleth authentication the page content is not updated with new, authorized content. This PR tracks when an authentication cookie was returned in the final external redirect. When external authentication is detected the cache is invalidated and the page  is initialized with fresh data.
* When the external authentication cookie is detected during initialization the store is updated with a value to indicate external authentication. This process is started by function in `init.service`.
* The `browser-init.service` checks for external authentication and invalidates the cache if found.
**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, screenshots or description …
=> Shibboleth page update after authentication

src/app/header-nav-wrapper/header-navbar-wrapper.component.scss, src/app/header-nav-wrapper/themed-header-navbar-wrapper.component.scss, src/app/header/header.component.scss, src/app/search-navbar/search-navbar.component.scss, src/app/shared/auth-nav-menu/auth-nav-menu.component.html, src/app/shared/auth-nav-menu/auth-nav-menu.component.scss, src/app/shared/auth-nav-menu/auth-nav-menu.component.spec.ts, src/themes/dspace/app/header-nav-wrapper/header-navbar-wrapper.component.ts, src/themes/dspace/app/header/header.component.html, src/themes/dspace/app/header/header.component.scss, src/themes/dspace/app/navbar/navbar.component.scss
Currently the mobile navbar does not open on the home page and on other pages like the item page the navbar is not being shown correctly for both the `dspace` and the `custom` theme.
This PR also makes it easier to customise the color and the hover color from the header icons by using the same variable for all of them (using the css variables `--ds-header-icon-color` & `--ds-header-icon-color-hover`).
- `HeaderNavbarWrapperComponent`: applied the `--ds-nav-z-index` on the wrapper
- Applied the css variables `--ds-header-icon-color` & `--ds-header-icon-color-hover` on every header icon
**Guidance for how to test and review this PR:**
- Uncomment the `custom` theme in `src/themes/eager-themes.module.ts`
- For both the `dspace` and the `custom` theme check the …
=> Fixed mobile navbar not expanding & use same css variable for all header icons

config/config.example.yml, src/config/default-app-config.ts
Follow up to #2210 (Thanks again @Zerosoul1990!)
This small PR just updates our default configuration to enable Vietnamese in the list of supported languages.
I used the changes in this PR to test #2210, so once this passes our GitHub CI, I'm going to merge it immediately.
=> Enable Vietnamese language pack

src/app/submission/sections/license/section-license.component.html
The submission page packs the deposit license into a rectangle regardless of whitespace in the original.  This patch preserves whitespace in the license text.
* `preserve-line-breaks` class added to the license text element.
To test:  write a default license with line breaks in it and see if they show up when you start a submission.
=> Enable line breaks in deposit license during submission.

src/app/shared/view-mode-switch/view-mode-switch.component.html, src/app/shared/view-mode-switch/view-mode-switch.component.spec.ts
Use more semantically appropriate elements for list controls and markup that better aligns with WCAG recommendations.
This issue originally brought to my attention because our accessibility auditing tools flag the links as having empty link content. While in practice they read fine to me in my testing using the NVDA screen reader, other assistive technology might not infer that the icon title should be used as the link text.
The crux of this change is to use more semantically appropriate elements for the view mode switch controls. The use of button elements is more appropriate as they don't imply a significant change of context the way that a link element does. The other change here is to explicitly include the name for the control in the button element itself, instead of as part of the …
=> View mode switch accessibility

src/app/core/locale/locale.service.spec.ts
* Fixes #1917 (unit tests only)
* Unit test were failing on machines with `it` locale
=> [DURACOM-99] Tests fixed

src/app/shared/form/builder/ds-dynamic-form-ui/models/dynamic-vocabulary.component.ts, src/app/shared/form/builder/models/form-field-metadata-value.model.ts
Avoid an authority key lookup in DsDynamicVocabularyComponent when it starts with "will be generated::"
Fixes #2197
During initialization for DsDynamicVocabularyComponent, avoid an authority key lookup when it starts with "will be generated::".
* Added FormFieldMetadataValueObject.hasAuthorityToGenerate() method to check if the authority key still needs to be generated
* In DsDynamicVocabularyComponent.getInitValueFromModel(), skip the Solr authority lookup if the key still needs to be generated. This lets the logic fall through to the default else that creates initValue$ from the existing FormFieldMetadataValueObject
When ORCID authority is enabled, you can now lookup an author, save the submission for later, and when you reopen the submission, the correct …
=> Fix #2197 authority key lookup

tsconfig.json
Since the upgrade of the e2e tests to Cypress 12 in PR #2127, the [jasmine Matchers](https://github.com/JamieMason/Jasmine-Matchers#-api) all throw errors like the ones in the screenshots below (I currently use IntelliJ 2023.1.2 - IU-231.9011.34).
To fix this issue the `cypress.config.ts` just needs to be excluded in the `tsconfig.json` file.
**Guidance for how to test your PR:**
- Check if you have the same issue on the latest version of the code
- If you do check that this fixes the issue
- Check that the cypress tests don't have such errors
=> Fix jasmine Matchers functions not properly indexing in IntelliJ

src/assets/i18n/ar.json5, src/assets/i18n/bn.json5, src/assets/i18n/ca.json5, src/assets/i18n/cs.json5, src/assets/i18n/de.json5, src/assets/i18n/en.json5, src/assets/i18n/es.json5, src/assets/i18n/fi.json5, src/assets/i18n/fr.json5, src/assets/i18n/gd.json5, src/assets/i18n/hu.json5, src/assets/i18n/ja.json5, src/assets/i18n/kk.json5, src/assets/i18n/lv.json5, src/assets/i18n/nl.json5, src/assets/i18n/pl.json5, src/assets/i18n/pt-BR.json5, src/assets/i18n/pt-PT.json5, src/assets/i18n/sv.json5, src/assets/i18n/sw.json5, src/assets/i18n/tr.json5, src/assets/i18n/uk.json5
fixes https://github.com/DSpace/dspace-angular/issues/2219 by removing the json object for key form.other-information which avoids to load subordinated translation keys
* Fixes #2219 
- removed json object in translation files which blocks loading subordinated translation files used by some components
- it's certainly easier and faster to proof that behaviour of json objects in the translation files on other keys
- e.g. use `"form": {},` or `"submission": {},` to check if the translation messages in the submission forms are not loaded.
* removed json object in translation files
* added missing `form.other-information` keys which are displayed in AuthorityValues on the Choice UI
_This checklist provides a reminder of what we are going to look for when reviewing …
=> Correctly load choice ui form.other-information translation keys

src/assets/i18n/de.json5
Added missing German translation for "browse.startsWith".
* Not necessary on these minor changes
Added missing German translation for "browse.startsWith".
* Only added missing German translation for "browse.startsWith".
Should be covered by automatic tests?
=> German translation for "browse.startsWith"

src/app/shared/menu/menu.service.spec.ts, src/app/shared/menu/menu.service.ts
* Replaces https://github.com/DSpace/dspace-angular/pull/2283
Some logic meant to copy route params to menu link params didn't work properly if the menu link contained a param, but the route didn't have a matching one
- Verify that the DSO routes containing a colon work properly now (they should redirect to the login page if you're logged out, or to 404 if you're logged in). e.g.
- `/collections/sample:path`
- `/communities/ab:cd`
- Verify what happens if you use the name of the route param in the route. e.g.
- `/items/:id:foo`
- Verify that regular DSO routes still work
- Verify that context sensitive statistics links in the header menu still work (which is the reason the method causing the issue was written in the first place)
=> Fix issue where a colon in a uuid would get misinterpreted as a route param

src/app/shared/starts-with/date/starts-with-date.component.ts, src/app/shared/starts-with/starts-with-abstract.component.ts
* Fixes #2214
Currently the browse-by-date component appears to be initialized multiple times via router updates. One of these updates seems unnecessary and removing it solves the problem with item links.
The removed line might actually needed in cases that I haven't found. But if it's truly redundant then removing might be a quick fix for #2214
=> Possible fix for browse-by-date links

src/assets/i18n/en.json5
The current message is not correct English. Note, there seems to be a mix of "don't" and "do not" language. Perhaps we should harmonize that eventually.
* Update English language string
Make sure the Angular application builds and runs with no errors in the UI.
=> src/assets/i18n: fix English permission string

src/app/shared/search/search-filters/search-filter/search-filter.component.html
Fixes  #2242 
This pull request adds the filter name into the aria-label attribute for the search filter buttons so that screen reader users can better understand the purpose of each filter. 
A bit messy, but this seemed like the simplest way to fix this without introducing new translation strings.
=> Add filter name to search filter button aria-label.

.gitignore, src/mirador-viewer/config.default.js, webpack/webpack.mirador.config.ts
Users can easily update the mirador configuration for their site today, but we haven't done a good job of explaining and supporting this. 
This makes a few small changes that should help. 
- By default the mirador webpack build now looks for a file in the `src/mirador-viewer` directory named `config.default.js` and uses this for out-of-the-box mirador configuration.
- Users can edit this file directly, but they have the option of creating a copy named `config.local.js`. If present, this file is used to build mirador. This allows the site to maintain a local configuration file that's distinct from the distribution copy.
These changes don't affect our current instructions for building the Mirador viewer, but later we might want to add a callout in the documentation that highlights these …
=> Update of mirador configuration and webpack

src/app/access-control/epeople-registry/epeople-registry.component.ts, src/app/access-control/epeople-registry/eperson-form/eperson-form.component.ts, src/app/core/data/request.service.spec.ts, src/app/core/data/request.service.ts
* Fixes [#2291](https://github.com/DSpace/dspace-angular/issues/2291)
There has been a refactor of the methods participating in EPerson delete action, including avoiding nested subscriptions and removing unnecessary events.
* First, refactor the `delete() `method of `EPersonFormComponent`, in order to avoid nested subscriptions and manage of disabling the delete button when the delete of the entity is confirmed (since the request takes a whole and the button can be clicked again). After the delete has finished successfully, we only need to notify the user for the status of the deletion, there is no need to trigger a submit of the form. So the `this.submitForm.emit()` is removed.
* Second, the` reset() `method of `EPeopleRegistryComponent` is refactored for the …
=> Delete EPerson from "Edit EPerson" form 

src/app/core/data/signposting-data.service.spec.ts, src/app/core/data/signposting-data.service.ts
* Relates to https://github.com/DSpace/dspace-angular/pull/2248
Fix a bug with a wrong string replace within the signposting data service.
Because the demo rest server url is `https://api7.dspace.org/server/api` the [replace done to remove `/api`](https://github.com/DSpace/dspace-angular/blob/main/src/app/core/data/signposting-data.service.ts#L28) just removed the first occurrence of it and this led to make a request with a wrong url.
=> [CST-5729] fix issue with signposting endpoint url replace

src/app/bitstream-page/bitstream-download-page/bitstream-download-page.component.ts
* Relates to https://github.com/DSpace/dspace-angular/pull/2248
Fix a small bug for which the signposting Links into the response header were duplicated for the bitsrteam download page
=> [CST-5729] Fix duplicate links for download page

src/assets/i18n/de.json5
This PR resolves a minor bug in `de.json5` in which two different translations of `scopenote` can be found. As it is not clear which translation is preferable I suggest a combined translation including both terms.
=> resolve German translation inconsistency in scopenote

src/app/shared/upload/uploader/uploader.component.html
* Fixes #2307
The input field of the file uploader was missing an unique ID, causing issues when multiple uploaders are used on the same page
To reproduce the bug:
- add two or more uploaders to a test component
- drag and drop works fine on both uploader
- if you click "browse" button on the second uploader the file will be uploaded using the first one
=> Multiple uploaders in the same page don't work

src/app/collection-page/collection-form/collection-form.component.ts, src/app/collection-page/edit-collection-page/collection-metadata/collection-metadata.component.spec.ts, src/app/collection-page/edit-collection-page/collection-metadata/collection-metadata.component.ts, src/app/community-page/community-form/community-form.component.ts, src/app/item-page/edit-item-page/item-status/item-status.component.ts, src/app/shared/comcol/comcol-forms/comcol-form/comcol-form.component.ts, src/app/shared/comcol/comcol-forms/edit-comcol-page/comcol-metadata/comcol-metadata.component.ts, src/app/shared/comcol/comcol-forms/edit-comcol-page/edit-comcol-page.component.ts
* Fixes #2300 
Fixed the behavior of collection/community/item components in order to initialize the form correctly and to ensure that the item's template is always up to date.
* First, the initialization of CollectionMetadataComponent is changed in order to ensure that the item's template is always up to date. To do so it is checked if the `NavigationEnd` or a `Scroll` event followed by a `NavigationEnd` event is finished.
This way we track the URL change or the refresh of the page.
* Second, in `CollectionFormComponent` the logic from the `ngOnInit` is separated to a new method `initializeForm()` , in order to call this method on `ngOnChanges` . Since we get the data as `Input`, we need to initialize the form as often as the data changes (the component is …
=> Edit section in sidebar menu: edit page of selected item / collection / community does not refresh

src/app/footer/footer.component.html, src/app/footer/footer.component.spec.ts, src/app/footer/footer.component.ts
* Fixes #2323 
This fix hides "Send feedback" link when feedback feature is disabled (CanSendFeedback feature ID)
Set `feedback.recipient=` in `local.cfg` to disable feedback feature
=> [DURACOM-160] Hide "Send feedback" link when CanSendFeedback is false

src/app/community-list-page/community-list/community-list.component.html, src/app/shared/object-list/collection-list-element/collection-list-element.component.html, src/app/shared/object-list/community-list-element/community-list-element.component.html
* Related to #2250
Minor adjustment to community and collection item counts. Instead of using the Bootstrap `lead` class, which reduces weight but increases size, we should use the `font-weight-light` class. This reduces the weight alone.
See: https://getbootstrap.com/docs/4.6/utilities/text/#font-weight-and-italics
Before (in my custom theme, but the effect is the same in the default theme):
<p align="center">
</p>
After:
<p align="center">
</p>
* Change the CSS class used in the community and collection counts
Reviewers should build the frontend and make sure the style of the item counts looks OK.
=> src/app: adjust item count style

src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.html, src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.ts
At the moment, the dynamic scrollable dropdown component is not usable by keyboard alone. There's no way to expand the dropdown without resorting to the mouse. This violates [success criterion 2.1.1](https://www.w3.org/TR/WCAG21/#keyboard) of the Web Content Accessibility Guidelines (WCAG) 2.1. 
This creates a barrier for any keyboard only users looking to complete any submission form that uses the dropdown component.
1. Add a keydown event to the template.
2. Add a corresponding keydown event handler to the component
With these changes, you can now interact with the component by: 
1. Tab to a dropdown in a submission form (e.g. dc.type)
2. With the dropdown focused, push space or enter to toggle the dropdown. Alternatively, you can use the up or down arrow …
=> Add the ability to expand / collapse via keyboard

server.ts
* Fixes #2333
With this PR only successful page are saved into the SSR cache. In this way bitstream download page which return a 302 code is not saved 
check issue described into #2333 is fixed
=> fix for bitstreams are not visible to crawlers when caching is enabled

src/app/core/data/dso-redirect.service.spec.ts, src/app/core/data/dso-redirect.service.ts, src/app/core/services/hard-redirect.service.ts, src/app/core/services/server-hard-redirect.service.spec.ts, src/app/core/services/server-hard-redirect.service.ts
* Fixes #2265 
Minor changes to the `dso-redirect.service.ts` to ensure it returns a `301 Moved Permanently` redirect when running during server side rendering (SSR).  This required changes to the existing HardRedirectService to support 301 redirects.
Added specs for all changes as well.
* Attempt to reproduce bug in #2265 using `/handle/[prefix]/[suffix]` paths to an existing Community, Collection or Item.
* Verify that a 301 redirect now occurs.
=> Implement basic 301 Redirect for DSpace 6.x URLs when SSR is used.

src/app/request-copy/deny-request-copy/themed-deny-request-copy.component.ts
* Fixes #https://github.com/DSpace/dspace-angular/issues/2351
The themed-deny-request-copy.component erroneously includes the custom theme's deny-request-copy component instead of its own.
This is the `main` port of DSpace `dspace-7_x` pull request. See: #2354
=> src/app: fix path to deny-request-copy component

.github/workflows/docker.yml
* This is a port of https://github.com/DSpace/DSpace/pull/8942 to `dspace-angular`.  It syncs our Docker build processes to both repos.
Small PR which changes the "docker" GitHub action to build all our Docker images **in parallel** as much as possible.
I noticed in the later stages of 6.x that building all 7 of our Docker images back-to-back-to-back would sometimes take **several hours** (as each image also was built twice, once for `linux/amd64` and once for `linux/arm64`).  
**Also updates `main` branch to be tagged as `latest` in DockerHub.**  The `dspace-7_x` branch continues to be tagged as `dspace-7_x` in DockerHub. This small change ensures `main` has a different Docker image than `dspace-7_x`.
* Assuming the Docker build in this PR doesn't throw errors, this is a good "smoke …
=> GitHub Actions: Split Docker images into separate jobs to run in parallel.  Enable 'latest' tag. (for dspace-angular)

Dockerfile.dist, docker/README.md, docker/cli.yml, docker/docker-compose-ci.yml, docker/docker-compose-dist.yml, docker/docker-compose-rest.yml, docker/docker-compose.yml
* Follow-up to #2359
Currently, our Docker scripts on `main` are still referencing the `dspace-7_x` tagged Docker images.  However in #8942, we updated `main` branch to generate Docker images with the `latest` tag.  (The `dspace-7_x` tag in DockerHub is to be used for the `dspace-7_x` branch in GitHub.)
In other words:
* `main` branch in GitHub should always use `latest` tag in DockerHub
* `dspace-7_x` branch in GitHub should always use `dspace-7_x` tag in DockerHub
This PR ensures that our Docker scripts on `main` are always referencing the tag `latest` from DockerHub.  (This ensures that `main` isn't accidentally using Docker images from our `dspace-7_x` brach)
(Corresponding PR was submitted to backend as well: https://github.com/DSpace/DSpace/pull/8974)
* Assuming Docker images build …
=> Replace all old docker "dspace-7_x" tags with "latest" on main

src/app/shared/utils/markdown.pipe.ts
- Fixes #2170
- Maintenance PR  #2392
Fixed MathJax code being displayed twice, this is because a HTML tag `mjx-assistive-mml` is created for screen readers to be able to read the MathJax code. Because the `dsMarkdown` pipe sanitises the HTML it transformed this hidden HTML tag to text instead leading to the MathJax code being displayed twice.
* Added the `mjx-assistive-mml` HTML tag (and it's child HTML tags) to the `sanitizeHtml`'s `allowedTags` to ensure it won't be turned into text
**Guidance for how to test/review this PR:**
* Create a new item with the following content in `dc.description.abstract`:
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam rutrum mi ligula, eget luctus diam ultricies vitae ${\ell}$. Quisque elit libero, …
```
=> Fixed MathJax code being displayed twice by `dsMarkdown` pipe

src/app/shared/utils/markdown.pipe.ts
- Port of #2397 to `dspace-7_x`.
=> [Port dspace-7_x] Fixed MathJax code being displayed twice by `dsMarkdown` pipe

src/app/profile-page/profile-page.component.ts
* Fixes https://github.com/DSpace/dspace-angular/issues/2379
When the user is changing the password the more specific validation error message is popped up instead of unclear, the default message. The error message is loaded from the response error message.
Updated `profile-page.component.ts`: The validation patch response is processed in the way that the error message from the response is added into notification message.
Try to change the password for some user.
1. Fill in a correct password.
2. Fill in a new password into password input …
=> Show error message from the password validation response

.github/workflows/port_merged_pull_request.yml
This is a temporary update to the `backport-action` used to port PRs between `main` and `dspace-7_x`.
It is being added to test korthout/backport-action#372 .  If it works properly, this should allow the `backport-action` to also work for PRs which **have merge commits**.  
Will test shortly with https://github.com/DSpace/dspace-angular/pull/2408 -- this is an example of a small PR which has a merge commit as the second commit: https://github.com/DSpace/dspace-angular/pull/2408/commits
This PR is just to document *why* I'm pushing these changes to our `backport-action`.  I'll merge it immediately to allow us to test this new behavior.
=> Enable early release of backport-action to test korthout/backport-action#372

.github/workflows/port_merged_pull_request.yml
Reverts DSpace/dspace-angular#2424
Unfortunately, this didn't work as planned.  Undoing it. 
Details at https://github.com/korthout/backport-action/pull/372#issuecomment-1670270189
=> Revert "Enable early release of backport-action to test korthout/backport-action#372"

README.md, config/config.example.yml, config/config.yml, docker/README.md, docker/docker-compose-dist.yml, docs/Configuration.md, src/app/core/services/browser-hard-redirect.service.ts, src/app/core/services/hard-redirect.service.ts, src/app/core/services/server-hard-redirect.service.ts
This PR is necessary to finalize the migration from https://demo7.dspace.org to https://demo.dspace.org (and https://sandbox.dspace.org)
It removes all mentions of https://demo7.dspace.org and https://api7.dspace.org from our codebase and configs.
On our `main` branch, configurations will be updated to use https://sandbox.dspace.org, as this is the new demo site which will automatically sync with the `main` branch.
On our `dspace-7_x` branch, configurations will be updated to use https://demo.dspace.org, as this is the new demo site which will automatically sync with the `dspace-7_x` branch.  (This is handled in a separate PR against `dspace-7_x`, see #2453)
=> Replace mentions of demo7.dspace.org and api7.dspace.org with new demo URLs

src/themes/custom/app/footer/footer.component.ts, src/themes/custom/app/header-nav-wrapper/header-navbar-wrapper.component.ts, src/themes/custom/app/shared/auth-nav-menu/auth-nav-menu.component.ts, src/themes/custom/app/shared/object-list/object-list.component.ts, src/themes/custom/app/workflowitems-edit-page/workflow-item-send-back/workflow-item-send-back.component.ts
* Fixes #2437 
- Correct the path in commented-out code in the custom theme's
components
- Clarify that the workflow-item-send-back.component.scss file is a stub (it has no corresponding SCSS file in the base theme)
n/a
(see description)
Issue #2437 contains a description of how to reproduce. With this patch applied, confirm the bug is no longer present, and that the footer is easily customizable.
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). …
=> 2437 Correct and clarify commented-out code in several custom components

.github/workflows/port_merged_pull_request.yml
Port of https://github.com/DSpace/DSpace/pull/9036 to `dspace-angular`
Enables a brand new feature of the `korthout/backport-action` GitHub action we are using: https://github.com/korthout/backport-action/#merge_commits
Ensures that when a ported PR is created, merge commits are skipped (i.e. not cherry picked).  Currently, if the original PR has a merge commit, the port will fail with an error.
Will merge immediately.  This PR is just to document the minor config change
=> [GitHub Actions] When porting a PR, skip any merge commits

README.md, config/config.example.yml, config/config.yml, docker/README.md, docker/docker-compose-dist.yml, docs/Configuration.md, src/app/core/services/browser-hard-redirect.service.ts, src/app/core/services/hard-redirect.service.ts, src/app/core/services/server-hard-redirect.service.ts
Port of #2452 to `dspace-7_x`.
This includes the same commits EXCEPT that it adds a single change:
* Configuration on `dspace-7_x` is updated to use the new https://demo.dspace.org/server/ demo backend by default (as demo.dspace.org auto-updates based on the `dspace-7_x` branch)
**THIS SHOULD NOT BE MERGED UNTIL THE NEW https://demo.dspace.org/ IS LAUNCHED** (later this week)
The updated configurations in this PR require the new demo REST API Backend at https://demo.dspace.org/server/ _to exist_ before they will function properly.  I'll merge this once that site has been fully deployed.
=> [Port dspace-7_x] Replace mentions of demo7.dspace.org and api7.dspace.org with new demo URLs

package.json
* Fixes #2433
When you have 2 fields with input-type `list` which use value pairs which contains a same value for one of their `<pair>`s, you cannot select that value in the second field.
**List of changes in this PR:**
* In `DsDynamicListComponent` I updated the checkboxes/radio buttons id attribute and prefixed it with the metadata fiel
**Guidance for how to test & review this PR:**
1. Create a submission form with 2 fields with input-type `list`
2. Link both fields to a `<value-pairs>` which contains this `<pair>`:
```xml
<pair>
<displayed-value>Other</displayed-value>
<stored-value>other</stored-value>
</pair>
```
3. In the submission form try selecting the `Other` value from the second field, it should select the correct field and not the one from the first field
=> Input type list doesn't work correctly if multiple value-pairs have the same pair value

src/app/shared/search-form/search-form.component.spec.ts, src/app/shared/search-form/search-form.component.ts
* Fixes [`#2159`](https://github.com/DSpace/dspace-angular/issues/2159)
I made a little fix, now when search submit is trigger, it must return to first page. I think this is the correct behaviour for search components.
1. Open https://demo7.dspace.org/search (in this case, the /search route)
2. Go to the last results page
3. Change the query to test → bound to have fewer results than everything
4. "Your search returned no results"
5. The pagination UI is not shown, the only way to find out you're on a page that doesn't exist is through the URL: it will still have e.g. spc.page=170
* First, I added firstPage Query Param to force navigating to first Page after submit
* Second, I changed …
=> Fix to Pagination position is retained between searches #2159

src/app/community-list-page/community-list-page.component.html, src/app/community-list-page/community-list-service.ts, src/app/community-list-page/community-list/community-list.component.html, src/app/community-list-page/community-list/community-list.component.ts, src/app/community-list-page/show-more-flat-node.model.ts
* Fixes #2251 
Cdk-tree was re-rendering itself completely on each datasource change because no [trackBy](https://material.angular.io/cdk/tree/overview#trackby) function had been defined. It could not establish what was new and what was old. So a quick win :)
Build the front end and expand communities and collections on the community list page and contrast with https://demo7.dspace.org/community-list
* trackBy method for cdk-tree
* minor styling changes
=> 2251 accessibility issues on the community list page

src/assets/i18n/de.json5, src/assets/i18n/en.json5, src/assets/i18n/es.json5, src/assets/i18n/hu.json5, src/assets/i18n/it.json5, src/assets/i18n/pt-PT.json5, src/assets/i18n/vi.json5
* Fixes #2398
changed curation-task.task.register-doi.label back to curation-task.task.registerdoi.label and added German translation
Renamed the translation string identifier in all json5 files it was already present and added a German translation.
* curation-task.task.register-doi.label -> curation-task.task.registerdoi.label
* Log in as admin
* Go to curation tasks
* Open Task dropdown
* Last entry should show 'Register DOI' instead of curation-task.task.registerdoi.label
=> fix(i18n): curation-task.task.registerdoi.label

src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.html, src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.spec.ts
* Fixes  #2145
On item submission page, the value of first dropdown automatically resets to the first value present in the dropdown on pressing "enter" in any of the textbox. _Now this has been fixed._
1. Go to Item submission page
2. Select book from “type” dropdown. (Select any value other than first value in dropdown)
3. Click on text box with label as "identifier" and then press enter.
* First, I change the event that triggers the OnSelect function, before it was onClick, now it is "keydown.enter". I made this change because the bug was in the click event, when the detect change was made to some other input (as explained in issue 2145), the click event was triggered on the dropdown by …
=> Fix to Value of dropdown changes automatically on item submission page

config/config.example.yml
As of DSpace Angular 7.2 the configuration syntax has changed from TypeScript to YAML, but the comments in the example configuration are still using TypeScript syntax.
Note: the [User Interface Customization page on the DSpace 7 wiki](https://wiki.lyrasis.org/display/DSDOC7x/User+Interface+Customization) shows YAML keys without quotes in most cases. I'm not sure if it's optional (especially the regex ones).
=> config/config.example.yml: fix example syntax

src/app/item-page/simple/related-entities/related-entities-search/related-entities-search.component.html, src/app/shared/search/search-export-csv/search-export-csv.component.ts
- Related to flag added in #2093 
This PR fixes two issues:
- CSV export got disabled by default in #2093  with the purpose of disabling it for submission, but should be enabled for related-entities-search on item pages
- CSV export ignored `fixedFilter` on the `PaginatedSearchOptions` import when creating the process
Changes made:
- Enabled CSV export through `related-entities-search` component, making the button available again on item pages
- Parsed the `fixedFilter` to a `-f` parameter (in the expected format) on the process
How to test:
- Log in as administrator
- Visit an entity page containing related entities
- Verify the csv export button is visible on the related entities search at the top-right of the results
- Click the export button
- Verify the exported results contains the …
=> CSV export fixes

package.json
- Maintenance PR  #2404
In https://github.com/DSpace/dspace-angular/pull/961 `removeByHrefSubstring()`  was renamed to`setStaleByHrefSubstring()`, but its [return statement](https://github.com/DSpace/dspace-angular/blob/884aa0743096b4bfe946679aa48ad3f5727575df/src/app/core/data/request.service.ts#L316-L319) was never updated. It will still only emit if the requests are removed from the store entirely, which will no longer happen now. This means it will never emit.
This PR updates it so it emits after all requests are set to stale instead.
=> Fix `setStaleByHrefSubstring` not emitting true when all requests are stale

package.json
- Port of #2349 to `dspace-7_x`.
=> [Port dspace-7_x] Fix `setStaleByHrefSubstring` not emitting true when all requests are stale

server.ts
Default values of both `botCache` and `anonymousCache` are defined in `default-app-config.ts`. 
This PR removes redundant default values from `server.ts`.
=> remove redundant cache default values from server.ts

src/app/admin/admin-registries/metadata-schema/metadata-schema.component.html
This PR implements a minor HTML change which improves the "find in page" of your prefered web browser. Currently, it is not possible to search for metadata field names of the form `schema.element.qualifier` using the "find in page" function, e.g. in /admin/registries/metadata/dc.
=> remove obsolete label element in metadata-schema.component.html

src/app/shared/search/search-filters/search-filter/search-facet-filter-options/search-facet-selected-option/search-facet-selected-option.component.html, src/app/shared/search/search-labels/search-label/search-label.component.html
* Fixes #2501
Don't apply `.text-capitalize` on selected metadata values in the search filters. We should not be changing the visual display of metadata values.
Navigate to the search page and select a metadata value in one filter. Confirm that the value is NOT capitalized when selected.
* Remove `.text-capitalize` class from selected search filters
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). …
=> Don't capitalize metadata values in search

src/app/item-page/edit-item-page/item-bitstreams/item-edit-bitstream/item-edit-bitstream.component.html, src/app/item-page/edit-item-page/item-bitstreams/item-edit-bitstream/item-edit-bitstream.component.spec.ts, src/app/shared/cookies/klaro-configuration.ts
* Fixes #2446
Fixed 2 urls not working correctly when using a baseHref (`ui.nameSpace`)
* Used `[routerLink]` instead of `[href]` in order to let Angular automatically add the correct baseHref prefix on the edit item bitstreams page
* Fixed the privacy policy link on the cookie setting popup
=> Fix some routes not using the correct baseHref

src/assets/i18n/it.json5
I've checked the whole it.json5 file in order to find missing or wrong Italian translations, and then I fixed those errors.
The changes have been made to the it.json5 file only, so it should not pose any issue as long as it is a valid json5 file.
* Fixed missing or wrong Italian translations
=> Fix missing or wrong Italian translations

src/app/core/data/request.service.spec.ts, src/app/core/data/request.service.ts, src/app/core/data/root-data.service.spec.ts, src/app/core/data/root-data.service.ts, src/app/core/server-check/server-check.guard.spec.ts, src/app/core/server-check/server-check.guard.ts, src/modules/app/browser-init.service.ts
* Fixes #2482 
The issue was caused by the fact that the guard made a new request to the api every time something subscribed to the result of its canActivateChild method. That happened more then once per route change
The solution was to use the cached /api response, and invalidate that cache on every NavigationStart event. That way, the first subscriber triggers the re-request, and all the others use the cached version.
Open the network tab in the browser's dev tools, and check that there's one a single /api request every time you change the route
Also verify that if the backend becomes unavailable, that you're redirected to the 500 error page the next time you change the route
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not …
=> Fix multiple api calls on route change

src/app/core/data/request.service.spec.ts, src/app/core/data/request.service.ts, src/app/core/data/root-data.service.spec.ts, src/app/core/data/root-data.service.ts, src/app/core/server-check/server-check.guard.spec.ts, src/app/core/server-check/server-check.guard.ts, src/modules/app/browser-init.service.ts
Port of https://github.com/DSpace/dspace-angular/pull/2510 by @artlowel to `main`.
=> [Port main] Fix multiple api calls on route change

src/app/browse-by/browse-by-metadata-page/browse-by-metadata-page.component.ts
* Fixes #2494 
Simply clears the `startsWith` property if no URL parameter is given so that no text is present when we aren't actively searching on a query.
To test this PR just follow the steps from the issue and verify no text stays present ( I tested against demo.dspace.org)
=> Fix browse by visual bug

src/app/submission/form/section-add/submission-form-section-add.component.html
* Fixes https://github.com/DSpace/dspace-angular/issues/2535
Hides the disabled [+Add More] button in top right corner of submission causing confusion
With **no** disabled steps (default):
- Go to submission in default submission form, eg https://demo.dspace.org/workspaceitems/33406/edit
- There is a no more disabled [+Add More] button in top right corner of submission causing confusion
With disabled steps:
- Set `mandatory="false"` in `item-submission.xml`: `<step-definition id="traditionalpagetwo" mandatory="false">` on the default second describe step
- Verify in submission of default submission form that the [+Add More] button in top right corner is now present again & contains a dropdown containing the second described step (if clicked adds that step to the submission)
=> Issue 2535 hide add more button submission if no disabled sections 7.x

src/app/shared/sass-helper/css-variable.service.ts
* Fixes https://github.com/DSpace/dspace-angular/issues/2450
Checks all stylesheets stylesheet that are being readed from document, whether the cssRules property exists. If not, than the stylesheet is not processed.
- the stylesheet without cssRules can be applied by some browser-plugins, see the issue for more details. It might also be possible to inject them manually.
- added filter to filter the document.stylesheets being processed later in code
- added check for the cssRules property `cssRules`. Without the `hasOwnProperty('cssRules')` method check the page will remain blank.
- See the issue for details how to reproduce the bug with specific browser addons that inject stylesheets into the DOM.
_This …
=> Check cssRules before css variables are read from stylesheet

src/app/shared/sass-helper/css-variable.service.ts
This reverts #2454 (i.e. commit fa79c358c09cb52ed142ef122e08b77de880685d)
Fixes #2557  (which was an accidental side effect of the changes in #2454)
See details in #2557.  This bug is appearing on all demo sites and locally.
=> Revert 2454 "Check cssRules before css variables are read from stylesheet"

src/app/request-copy/email-request-copy/email-request-copy.component.html
Message is optional: remove req in [disabled]
* Fixes #2440 
It removes the check for an empty message for the submit button [disabled] attribute
Attempt to grant a request and confirm that now the message is optional
* Very simple fix removing the message emptiness check
=> Fix Request-a-Copy grant form optional message not optional in form validation

src/app/core/data/request.service.spec.ts
Because tests are executed slower on CICD it can sometimes take one second or more to execute the `RequestService#setStaleByHref(href)`, when the test arrives inside the subscribe, a create new `RequestStaleAction` with the current time is created (this can already be a few seconds after `RequestService#setStaleByHref(href)` was called). To prevent such errors we can just expect that `lastUpdated` will be a number instead of comparing the actual values. The purpose of that test is to check the type of `RequestUpdateAction` returned by the function and not the date when it was created, so this doesn't have any side effects. [This is an example of such a failure.](https://github.com/DSpace/dspace-angular/actions/runs/6580387915/job/17878258713)
=> Fix RequestService test sometimes failing in CICD

src/app/core/data/feature-authorization/authorization-data.service.ts, src/app/core/data/feature-authorization/authorization-utils.ts, src/app/shared/log-in/container/log-in-container.component.ts, src/app/shared/log-in/log-in.component.html, src/app/shared/log-in/log-in.component.ts, src/app/shared/log-in/methods/log-in.methods-decorator.ts
* Fixes #2515
* Related #2414
Fixes bug where the `LogInComponent` turns blank when submitting invalid username/password combination.
Instead of hiding the `LogInContainerComponent` by checking it's content, now it hides it by checking if the login method has a component with a `rendersAuthMethodType` decorator.
You can test it locally but I wasn't able to reproduce the bug myself with my local setup
=> Fix display LogInComponent turning blank when entering wrong username/password combination

src/app/core/data/feature-authorization/authorization-data.service.ts, src/app/core/data/feature-authorization/authorization-utils.ts, src/app/shared/log-in/container/log-in-container.component.ts, src/app/shared/log-in/log-in.component.html, src/app/shared/log-in/log-in.component.ts, src/app/shared/log-in/methods/log-in.methods-decorator.ts
Manual Port of #2530 by @alexandrevryghem to `dspace-7_x`
=> [Port to dspace-7_x] Fix display LogInComponent turning blank when entering wrong username/password combination

src/app/item-page/edit-item-page/item-move/item-move.component.html, src/assets/i18n/en.json5
* Backport of [Fix inherit policies at item move](https://github.com/DSpace/dspace-angular/pull/2423)
* Required by REST PR: https://github.com/DSpace/DSpace/pull/9039
Adds a tooltip to the "Inherit policies" checkbox on the "item move" page informing the user about the meaning of this option and warning them that the operation cannot be undone.
* In `ItemMoveComponent` template: Adds a tooltip to `inheritPoliciesCheckbox`. 
* Visit the item move page and hover over the "Inherit policies" checkbox to verify that the tooltip shows up.
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to …
=> [Port to dspace-7_x] Fix inherit policies at item move (Angular)

src/app/shared/form/vocabulary-treeview/vocabulary-treeview.component.html, src/app/shared/form/vocabulary-treeview/vocabulary-treeview.component.ts
The `vocabulary-treeview` uses the `description` variable to show an i18n label:
this.translate.get(`search.filters.filter.${this.vocabularyOptions.name}.head`).pipe(
map((type) => lowerCase(type)),
).subscribe(
(type) => this.description = this.translate.get('vocabulary-treeview.info', { type })
);
The label used to contain a `type` parameter, but it doesn't contain it anymore.
Therefore this code can be safely removed and the label can be used directly in the HTML template.
The tree view uses `fa-angle-right` and `fa-angle-down` FA icons, which have different widths. When an item is expanded it is no longer aligned with other items:
I added the `fa-fw` class to give the icons a fixed width:
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You …
=> Fix i18n labels and alignment in vocabulary-treeview

package.json, src/ngx-translate-loaders/translate-browser.loader.ts, src/ngx-translate-loaders/translate-server.loader.ts, webpack/helpers.ts, webpack/webpack.common.ts
* Fixes #2461
* Maintenance PR #2578
In this PR I added hashes to the translation files & ensured that the translation files are retrieved with those hashes in production mode.
- Created a function to calculate the hashes of the json5 files and stored them using the `EnvironmentPlugin` to be able to retrieve them in the app using `process.env.languageHashes`
- Customised the `CopyWebpackPlugin` to add the hash to the json file name (only in production mode)
- Customised the `TranslateBrowserLoader` & `TranslateServerLoader` to retrieve the language file with the hash saved in `process.env.languageHashes` (only in production mode)
- Fixed an error with the `build:prod` command where the `NODE_ENV` was not being set. This made it impossible to know whether you …
=> i18n production improvements

src/app/admin/admin-registries/metadata-schema/metadata-field-form/metadata-field-form.component.ts
This PR adds a small improvement to the "create metadata field" form by changing the type of the scope form field to textarea. By this change the insertion of multi-line scope notes is better supported.
=> allow insertion of multi-line scope notes in MD field registry

src/app/breadcrumbs/breadcrumbs.component.scss, src/app/header/header.component.scss, src/app/navbar/expandable-navbar-section/expandable-navbar-section.component.scss, src/app/navbar/navbar.component.scss, src/styles/_custom_variables.scss, src/themes/dspace/app/navbar/navbar.component.scss
When you create a custom theme who doesn't extend the `dspace` theme, you can't change the background color of the header. It is also not possible to change the navbar background color using CSS variables.
* Made sure the default `HeaderComponent` in `src/app` now also sets the `background-color: var(--ds-header-bg)`
* Made it possible to change the navbar background color with the new CSS variable `--ds-navbar-bg` (this is maybe not useful if you use the navbar in the same way as the `dspace` theme. But for custom themes who use the `HeaderComponent` & `NavbarComponent` from `src/app` this is useful, because the the navbar is rendered underneath the header)
* Fixed `NavbarComponent` incorrectly dividing the css variable `--ds-content-spacing` by 3
**Include …
=> Minor css variables fixes for header & navbar

src/app/shared/sass-helper/css-variable.service.ts
* Fixes #2450
check stylesheets in the dom before reading the css variables from them. If some error occurs reading the stylesheet cssRules (see the issue, f.e. it is some cross-origin stylesheet from some plugin which is not-readable) the exception is catched and the css variable not extracted from the stylesheet.
see https://github.com/DSpace/dspace-angular/issues/2450 and https://github.com/DSpace/dspace-angular/issues/2557  and the previous PR https://github.com/DSpace/dspace-angular/pull/2454 for an overview over the discussion, especially the exception and the difference to the previous PR.
See the issue for details how to reproduce the bug with specific browser addons that inject stylesheets into the DOM. 
Also login into the …
=>   Check cssRules before css variables are read from stylesheet (again)

src/app/shared/form/builder/ds-dynamic-form-ui/models/date-picker/date-picker.component.spec.ts, src/app/shared/form/builder/ds-dynamic-form-ui/models/date-picker/date-picker.component.ts, src/app/shared/form/number-picker/number-picker.component.ts
* Fixes https://github.com/DSpace/dspace-angular/issues/2588
There have been changes on `DsDatePickerComponent` and `NumberPickerComponent` affecting the `maxYear` value, because the issue was caused by the restriction set by `maxYear`  value on `DsDatePickerComponent`. `update()` method in `NumberPickerComponent` is fixed in order to emit the changes when the value is greater than the maxValue. This change triggers the form validations. 
* First, `maxYear` variable should not get its value by `initialYear` ( because for eg. in our case the initialYear's value is 23), but it should consider `now.getUTCFullYear()` and start from the actual year (+ 100 , existing part).
But in case it is entered a greater value than `now.getUTCFullYear() + 100` , the behavior …
=> Fix "Submission input type date doesn't work properly once a value has been set"

cypress/support/commands.ts, package.json
* Fixes a bug in e2e tests which was an accidental side effect of https://github.com/DSpace/dspace-angular/pull/2464
* Adds a `user-agent` to e2e tests which generate statistics, as that's now required after https://github.com/DSpace/DSpace/pull/9157 was merged on backend
Fixes broken `homepage-statistics.cy.ts` tests based on a few recent changes:
* e2e tests need to run in Production mode for i18n text to always load.  This impacted tests more when running them locally via `yarn e2e`.  See first commit in this PR
* e2e test utility for generating usage statistics MUST have a `user-agent` which makes it look like a browser.  This is required because https://github.com/DSpace/DSpace/pull/9157 updated our user-agent list to include `HeadlessChrome`, thus ignoring all statistics from …
=> Fix e2e tests by running in production mode & using a user-agent for statistics

src/styles/_global-styles.scss, src/themes/dspace/app/header/header.component.html, src/themes/dspace/app/header/header.component.scss, src/themes/dspace/app/navbar/navbar.component.html, src/themes/dspace/app/navbar/navbar.component.scss
This PR adds some Bootstrap-style utility classes to handle horizontal and vertical gaps between flexbox elements.
A `gap-*` class adds a space between elements of the same size of `m-*` and `p-*` Bootstrap classes, while `gapx-*` and `gapy-*` classes allow to set horizontal and vertical gaps.
These classes will allow to handle spacing between many elents of the DSpace UI in a simpler way (currently the spacing is managed by manually adding margins to each element).
For example, in `dso-edit-menu.component.html`:
```html
<div class="dso-edit-menu d-flex"> 
<div *ngFor="let section of (sections | async)" class="ml-1"> 
<ng-container
*ngComponentOutlet="(sectionMap$ | async).get(section.id)?.component; injector: (sectionMap$ | async).get(section.id)?.injector;"></ng-container>
</div>
</div> …
```
=> Utility gap-* classes for flexbox

src/app/submission/objects/submission-objects.effects.ts
* Fixes #2577 
* Fixes #1924
This is a quick fix for the problems mentioned before. It's not resolving the general problem with `reRequestOnStale` [mentioned here](https://github.com/DSpace/dspace-angular/issues/2577#issuecomment-1781429053)
Check the mentioned bugs are fixed
**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, screenshots or description of a new feature, or reasons behind specific changes.
=> Fix cache issue when depositing a submission

src/app/shared/form/builder/ds-dynamic-form-ui/models/tag/dynamic-tag.component.ts, src/app/shared/form/vocabulary-treeview/vocabulary-treeview.component.html, src/app/shared/form/vocabulary-treeview/vocabulary-treeview.component.ts, src/assets/i18n/en.json5
* Fixes #2435
* Requires DSpace/DSpace#9181
This PR adds support for adding custom input in submission fields that are controlled by a vocabulary
* Altered the `VocabularyTreeviewComponent` class and html template to show an "Add" (i18n message) button. This button is disabled if the vocabulary is closed, or if no text is given.
* Altered the `DynamicTagComponent` class so that custom user input is supported. If results are present from the vocabulary autofill, the custom user input is appended to the bottom of the list, this is done since a value from the vocabulary is preferred.
An in-depth "how-to-test" guide is included in the back end PR as these PR's can not be tested separately  
_This checklist provides a reminder of what we are going to look for when …
=> Support for freetext values in submission for vocabulary controlled `onebox` and `tag` types

src/app/shared/form/builder/ds-dynamic-form-ui/ds-dynamic-type-bind-relation.service.ts
Per default, dspace only supports type-bind for values of non-repeatable type-bound list elements (Radiobutton Group) This change also allows to use repeatable type-bound list elements (Checkbox Group) for type binding. This enables the submission process to support type-bind in case of using repeatable dc.type selection for an item.
* This PR introduces a small change inside "src/app/shared/form/builder/ds-dynamic-form-ui/ds-dynamic-type-bind-relation.service.ts". Here it is checked, wether the current _relatedModel_ is a CHECKBOX_GROUP. If so, the Subject _relatedModel.valueUpdates_  is used instead of …
=> Support type-bind of elements based on repeatable list type-bound element (CHECKBOX_GROUP)

src/app/breadcrumbs/breadcrumbs.component.html, src/app/breadcrumbs/breadcrumbs.component.scss, src/app/header-nav-wrapper/header-navbar-wrapper.component.html, src/app/header-nav-wrapper/header-navbar-wrapper.component.scss, src/app/home-page/home-news/home-news.component.html, src/app/home-page/home-news/home-news.component.scss, src/app/navbar/navbar.component.scss, src/app/root/root.component.html, src/styles/_custom_variables.scss, src/styles/_global-styles.scss, src/themes/dspace/app/header-nav-wrapper/header-navbar-wrapper.component.html, src/themes/dspace/app/header-nav-wrapper/header-navbar-wrapper.component.scss, src/themes/dspace/app/header-nav-wrapper/header-navbar-wrapper.component.ts, src/themes/dspace/app/home-page/home-news/home-news.component.html, src/themes/dspace/app/home-page/home-news/home-news.component.scss, src/themes/dspace/app/navbar/navbar.component.scss
* Fixes #2341
The `ds-header-navbar-wrapper` component covers the media player control buttons because it had an higher z-index than its sibling `<main>` element, which contains the `ngx-gallery-preview` component.
Note that the media preview component itself has the highest z-index, but only the z-index of `<main>` should be taken into account.
In this PR I removed the z-index of `ds-header-navbar-wrapper` and I added the same z-index to the `ds-navbar` component, which is only shown when the collapsible navbar is expanded on mobile screens.
Ensure that the media viewer is enabled:
```yml
mediaViewer:
image: true
video: true
```
Open any item with an image, e.g. https://sandbox.dspace.org/entities/publication/ffc161e0-1bd9-415c-a479-ae48b63c43e8
- **On desktop and mobile:** click on the …
=> Media viewer controls rendered behind DSpace header

src/app/community-list-page/community-list-service.ts, src/app/community-list-page/community-list/community-list.component.html, src/app/community-list-page/community-list/community-list.component.spec.ts, src/app/community-list-page/community-list/community-list.component.ts
https://github.com/DSpace/dspace-angular/pull/2597#pullrequestreview-1722898879
This PR fixes two issues with the community collection list page:
- The show more button not rendering after selection and more pages available.
- When multiple show more nodes without unique id, the nodes are not being placed or expanding correctly.
Set `communityList.pageSize` to a small number (less than half the number of top-level communities and less then subcommunities under a community).
```
communityList:
pageSize: 4
```
Navigate to [Communities & Collections](http://localhost:4000/community-list) page. Click show more pages and expand communities/subcommunities which multiple pages at the same level. The described issues above should no longer occur.
* The condition to …
=> Communities & Collections tree browser updates - Replaced #2597

src/app/access-control/group-registry/group-form/group-form.component.ts, src/app/access-control/group-registry/group-form/members-list/members-list.component.html, src/app/access-control/group-registry/group-form/members-list/members-list.component.spec.ts, src/app/access-control/group-registry/group-form/members-list/members-list.component.ts, src/app/access-control/group-registry/group-form/subgroup-list/subgroups-list.component.html, src/app/access-control/group-registry/group-form/subgroup-list/subgroups-list.component.spec.ts, src/app/access-control/group-registry/group-form/subgroup-list/subgroups-list.component.ts, src/app/access-control/group-registry/groups-registry.component.ts, src/app/core/eperson/eperson-data.service.spec.ts, src/app/core/eperson/eperson-data.service.ts, src/app/core/eperson/group-data.service.spec.ts, src/app/core/eperson/group-data.service.ts, src/app/core/eperson/models/eperson-dto.model.ts, src/app/workflowitems-edit-page/advanced-workflow-action/advanced-workflow-action-select-reviewer/reviewers-list/reviewers-list.component.spec.ts, src/app/workflowitems-edit-page/advanced-workflow-action/advanced-workflow-action-select-reviewer/reviewers-list/reviewers-list.component.ts, src/assets/i18n/en.json5
* Fixes #2512
* Requires DSpace/DSpace#9125 (which provides the new `isNotMemberOf` REST endpoints required by this PR)
Refactors the "Edit Group" (`/access-control/groups/[:uuid]`) code to no longer have major performance issues for very large Groups (i.e. groups with many members).
This requires the following:
* Replaces all general search() methods across EPerson and Group objects with calls to `isNotMemberOf` REST Endpoints. These endpoints will only return objects which are *not already a member of* the current Group.
* Removes all methods in Angular UI which attempted to determine group membership (e.g. isSubgroupOfGroup() in subgroups-list.component.ts, and isMemberOfGroup() in members-list.component.ts).  No longer needed as `isNotMemberOf` endpoint solves this problem.
* Removes …
=> Fix "Edit Group" page always requests all member Subgroups & EPersons

src/app/shared/form/builder/ds-dynamic-form-ui/ds-dynamic-form-control-container.component.spec.ts, src/app/shared/form/builder/ds-dynamic-form-ui/models/date-picker/date-picker.component.html, src/app/shared/form/builder/ds-dynamic-form-ui/models/date-picker/date-picker.component.spec.ts, src/app/shared/form/builder/ds-dynamic-form-ui/models/date-picker/date-picker.model.ts, src/app/shared/form/builder/form-builder.service.spec.ts
* Fixes #2619 
This PR fixes an issue with double labels for repeatable date fields in submission.
Create an input form with a repeatable date input and look at it in submission, it should no longer display multiple labels for repeatable date fields.
=> Fix for repeatable date field labels

src/app/core/data/dso-redirect.service.spec.ts, src/app/core/data/dso-redirect.service.ts
* Fixes #2517
Fixed a bug in `DsoRedirectService` which caused the service to redirect the user to the wrong page when a custom `ui.nameSpace` is set.
* Updated the `DsoRedirectService` to add the baseHref/nameSpace in front of absolute routes.
- Check that by setting `ui.nameSpace` to for example `/dspace-angular` the handle redirect still works when you go to `/dspace-angular/handle/{handle}` and that it redirects you to the correct dso page
- Check that it still works when using the default nameSpace `/`
=> Fix handle redirect not working with custom nameSpace

src/app/item-page/edit-item-page/edit-item-page.routing.module.ts, src/app/item-page/edit-item-page/item-page-access-control.guard.ts, src/app/item-page/edit-item-page/item-page-curate.guard.ts
Fixes #2609 
Users without the necessary authorizations (and especially anonymous users) should not have access to administrator pages.
Instead, they should be redirected to the login page, or be shown a 403 page.
Admin:
- When accessing "/edit/access-control" as the administrator, we navigate successfully.
- When accessing "/edit/curate" as the administrator, we navigate successfully.
Anonymous users:
- If in the url the page the name "/edit/access-control"
- The page automatically redirects to the login page
- If in the url the page the name "/edit/curate"
- The page automatically redirects to the login page
=> Fixes "some item edit pages are accessible by anonymous users"

src/app/item-page/edit-item-page/item-operation/itemOperation.model.ts, src/app/item-page/edit-item-page/item-status/item-status.component.html, src/app/item-page/edit-item-page/item-status/item-status.component.spec.ts, src/app/item-page/edit-item-page/item-status/item-status.component.ts
Fixes #2618
The order should be fixed. Permanently deletion should be the last option.
The order of the buttons in status tab is fixed
=> Edit-item view: random order of buttons in status tab

package.json, src/app/shared/menu/menu.component.spec.ts, src/app/shared/menu/menu.component.ts
* Fixes #2601
When a subsection is added to a menu section that has no subsections, the subsections won't appear if the component has already been rendered. To fix this we now not only check if new sections were added/removed, but also if the component that should be used to render that specific section has changed. This way the components will render again when we add a subsection to a section, because then the top level id still won't have changed, but the component that the top level sections  should use to render will have.
* The `distinctUntilChanged(compareArraysUsingIds)` check from `MenuComponent` has been moved to `MenuService#getMenuTopSections`
* In `MenuComponent` the `distinctUntilChanged` that is responsible for setting the value of `sectionMap$` …
=> Fixed menu not updating when a new sub section is added after rendering has already completed

.github/workflows/docker.yml
This PR enables building of the amd64 and arm64 images simultaneously.
Logic borrowed from https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners
Once both images finish, the manifest is sent to Docker Hub, allowing for a single image that has both the amd64/arm64 images.
This will allow for faster building of the amd64 image, and being sent to Docker Hub, while the arm64 image is still being built.
* Creates a matrix for the target arch (amd64, arc64).
* Merges the two docker images and pushes the manifest to Docker Hub at completion
**Include guidance for …
=> Setup the Docker GH Action for Matrix Building

.github/workflows/docker.yml
* Fixes a bug in #2644 discovered after the merger
Fix bug in Docker build process, where the manifests for the `latest` and `latest-dist` images on DockerHub were invalid. 
The core issues was that in #2644, both the `latest` and `latest-dist` build processes were sharing the same artifact to store their digests.  When the manifest was built for one of those tags, it was including **every digest** that had been built so far.  
This behavior resulted in the `latest` tag in DockerHub having a manifest that included all the following:
* The `latest` image version for AMD64
* The `latest-dist` image version for AMD64
* The `latest` image version for ARM64
It also meant that the `latest-dist` tag ONLY included the longest running image:
* The `latest-dist` image for ARM64
The reason for this …
=> Fix bug in Docker image build process which caused tags to have improper manifests in DockerHub

.github/workflows/docker.yml
* Fixes another bug initially in #2644 which I overlooked in #2648
This is a minor fix to the directory structure of where `latest-dist` digests are stored.  This fix is necessary so that the new matrix process works properly... without it, the `latest-dist` digests cannot be found, resulting in issues in DockerHub.
* Will be merged immediately as this is only possible to test after the PR is merged.  I've triple-checked my work though, so I feel this should *finally* get these parallel Docker image builds working properly
Once this is succeeding on `main`, all these changes will be backported to `dspace-7_x`.
=> Follow-up Docker image build fix. Fix directory structure for `latest-dist` digests

.github/workflows/build.yml, .github/workflows/codescan.yml, .github/workflows/docker.yml, .github/workflows/port_merged_pull_request.yml, .github/workflows/pull_request_opened.yml
Follow-up to #2650 
This PR is just updates to our GitHub actions including:
1. Deploying to demo.dspace.org or sandbox.dspace.org after updates to our DockerHub images.  (This used to be done via a webhook on DockerHub. But, moving it to GitHub actions so that we can have better control over when the re-deployment is called.)
2. Fixing a minor bug in the `build.yml` where the Codecov.io (code coverage) upload is not automatically retrying on failure.  The issue seems to be that an upload failure doesn't throw an error by default, so we have to set `fail_ci_if_error: true` in the Codecov action to get the retry process to work properly.
3. Upgrading all action plugins to latest versions
* No review is necessary. If these actions continue to work properly then this is a successful update.
=> GitHub Actions Updates: Redeploy Sandbox via Docker & Fix retry of Codecov upload

.github/workflows/docker.yml
Small change to `docker.yml` to immediately redeploy demo/sandbox when the AMD64 image is built.  This allows us to redeploy without waiting on the ARM64 image (which can sometimes take an hour).
=> Redeploy demo/sandbox more quickly by only waiting for AMD64 Docker image to complete

.github/workflows/build.yml, .github/workflows/codescan.yml, .github/workflows/docker.yml, .github/workflows/port_merged_pull_request.yml, .github/workflows/pull_request_opened.yml
This PR is a direct port (cherry-pick) of all the following PRs to `dspace-7_x`:
* #2644
* #2648
* #2650
* #2649
* #2658
The purpose of this PR is to simply "synchronize" the GitHub Actions configuration between `main` and `dspace-7_x`.  No code changes to DSpace have been made.
=> [Port dspace-7_x] Port recent GitHub Action changes

src/app/admin/admin-registries/metadata-schema/metadata-schema.component.ts
* Fixes #2599
`MetadataSchemaComponent` should always unslect all the checkboxes when switching to a different schema in the registry.
* Deselect all the fields from the `MetadataSchemaComponent` when destroying the component, this is needed because they are stored in the ngrx store.
=> Deselect all metadata fields when switching between metadata schemas in registry

.github/workflows/docker.yml
In https://github.com/DSpace/DSpace/pull/9213 a new `reusable-docker-build.yml` was created for DSpace/DSpace at https://github.com/DSpace/DSpace/blob/main/.github/workflows/reusable-docker-build.yml
This was based on refactoring in `dspace-angular` in #2644.  Therefore, as a final refactor for `dspace-angular`, we can easily update the `docker.yml` script to use that `reusable-docker-build.yml`.
This PR makes that refactor.  A similar PR will be needed for `dspace-7_x` to use the `dspace-7_x` version of `reusable-docker-build.yml`
=> [Docker] Refactor to simply use the reusable-docker-build.yml from DSpace/DSpace.

src/assets/i18n/en.json5
* Fixes #2678
Fixed the edit bitstream description label.
=> Updated bitstream read description in en.json5

src/app/access-control/group-registry/group-form/members-list/members-list.component.html, src/app/access-control/group-registry/group-form/members-list/members-list.component.spec.ts, src/app/access-control/group-registry/group-form/members-list/members-list.component.ts, src/app/core/eperson/eperson-data.service.ts, src/app/workflowitems-edit-page/advanced-workflow-action/advanced-workflow-action-select-reviewer/reviewers-list/reviewers-list.component.spec.ts
* Fixes #2661
* Related #2391
Since the creation of the new separate ePerson pages the ePerson route includes the id of the ePerson. This PR now fixes this route in both the display ePerson tab & the search ePerson tab on the edit group page.
* Fixed the link on edit group for both the display ePerson tab & the search ePerson tab
* Removed the now unused method `EPersonDataService.getEPeoplePageRouterLink()` since it's better to use `getEPersonsRoute()` directly
=> Fixed ePerson link on edit group page

src/app/community-list-page/community-list/community-list.component.html, src/app/item-page/field-components/metadata-values/metadata-values.component.html
* Fixes #2492
Fix erroneous whitespace inside link text in community-list cdk tree and browse definition links.
Build the frontend and make sure the links on `/community-list` look and work as expected.
* Remove newlines in link text
=> Fix whitespace in links due to newlines

src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.html, src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.ts
Port of #2733  by @jensvannerum to `dspace-7_x`.
<hr />
Manual port of patch from `main` because I had issues with the base branch and ended up rebasing, squashing, merging it manually in c02b46ca7d4c5baad8c8902bd7a6dc56c4ee8a0b.
=> [Port dspace-7_x] Use keyboard to select values

src/assets/i18n/en.json5
This PR fixes a typo in the english translation of `info.feedback.page_help`.
=> fixed typo in info.feedback.page_help

src/app/shared/comcol/comcol-page-logo/comcol-page-logo.component.html, src/app/shared/comcol/comcol-page-logo/comcol-page-logo.component.scss, src/styles/_custom_variables.scss
References
Fixes https://github.com/DSpace/dspace-angular/issues/2745
Description
To prevent logos to be over sized we added a configuration possibility so that on each environment we can restrict the size to a number of defined pixels.
Instructions for Reviewers
In order to test try creating a new collection or community uploading a very large picture as logo to check if it is rendered within the defined configuration sizes.
Checklist
My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
My PR passes [ESLint](https://eslint.org/) validation using yarn lint
My PR doesn't introduce circular dependencies (verified via yarn check-circ-deps)
My PR includes [TypeDoc](https://typedoc.org/) …
=> Add logo max constraints

src/app/core/json-patch/json-patch-operations.reducer.ts
It was discovered that when many modifications of the submission form are done within a section, the PATCH request to update the section processes unnecessary patches on the back end. i.e. Change name, then title, then date multiple times, then name and title again. Only the last changes per input are necessary for the patch and the preceding by op and path are unnecessary to process on the backend.
Determine the use case for providing the backend with all the UI form manipulations. If there is no valid use case, there is excessive processing done for each patch operation included that will nullify a previous patch.
- for each new patch operation dispatched, dedupe any existing patch operations that where stored previously
To test concern:
Open inspector tools …
=> Dedupe patch operations by op and path

.github/workflows/build.yml, docker/cli.assetstore.yml, docker/cli.yml, docker/docker-compose-ci.yml, docker/docker-compose-rest.yml
* Fixes the problem described in #2788.  It's an improvement on that PR which ensures we don't need to duplicate the definition of `dspacenet` into multiple locations
* Related to similar backend fixes in https://github.com/DSpace/DSpace/pull/9303
Fixes issue where `cli.yml` may try to use the wrong/incorrect network.  This same problem was seen on the backend after upgrading to recent versions of Docker, see https://github.com/DSpace/DSpace/issues/9302 and fixes in https://github.com/DSpace/DSpace/pull/9303
This PR resyncs `cli.yml` in this codebase with [`docker-compose-cli.yml` from DSpace/DSpace](https://github.com/DSpace/DSpace/blob/main/docker-compose-cli.yml).
It also resyncs `cli.assetstore.yml` with [`cli.assetstore.yml` from …
=> Fix issue with cli.yml not using same network as backend. 

.github/workflows/build.yml, docker/cli.assetstore.yml, docker/cli.yml, docker/docker-compose-ci.yml, docker/docker-compose-rest.yml
Manual port of #2791 by @tdonohue to `dspace-7_x` branch.  This port had to be done manually because `main` and `dspace-7_x` docker scripts use different versions of Docker images with slightly different settings.
=> [Port dspace-7_x] Fix issue with cli.yml not using same network as backend.

src/assets/i18n/de.json5
This PR removes the German translation of `admin.workflow.item.workflow` which use the plural form instead of the singular form. 
As this translation is used as the text of an item badge it should the singular form.
=> fix German translation of admin.workflow.item.workflow 

src/app/item-page/edit-item-page/item-status/item-status.component.ts
Fix for missing Register DOI button under Edit Item > Status tab
* Fixes #2765 
Fix initialOperations variable typo and return ops array with register-doi op successfully added is the register doi configuration is enabled
=> Fix missing Register DOI button if configuration enabled

src/app/info/privacy/privacy-content/privacy-content.component.html, src/assets/i18n/ar.json5, src/assets/i18n/bn.json5, src/assets/i18n/ca.json5, src/assets/i18n/cs.json5, src/assets/i18n/de.json5, src/assets/i18n/en.json5, src/assets/i18n/es.json5, src/assets/i18n/fi.json5, src/assets/i18n/fr.json5, src/assets/i18n/gd.json5, src/assets/i18n/hu.json5, src/assets/i18n/it.json5, src/assets/i18n/ja.json5, src/assets/i18n/kk.json5, src/assets/i18n/lv.json5, src/assets/i18n/nl.json5, src/assets/i18n/pt-BR.json5, src/assets/i18n/pt-PT.json5, src/assets/i18n/sv.json5, src/assets/i18n/sw.json5, src/assets/i18n/tr.json5, src/assets/i18n/uk.json5
Minor updates to i18n strings for clarity and consistency. For example:
- `"mydspace.status.mydspaceWaitingController": "Waiting for controller"` — what is a "controller"?
After some discussion on Slack we decided that "reviewer" is more clear than "controller".
As well as some others:
- `"mydspace.results.no-uri": "No Uri"` — URI is an acronym and should be capitalized
- `"mydspace.search-form.placeholder": "Search in mydspace..."` — lower case mysdspace
- `"mydspace.title": "MyDSpace"` — camel case MyDSpace
- `"nav.user-profile-menu-and-logout": "User profile menu and Log Out"` — why is "Log Out" capitalized?
- Standardize `email` instead of `e-mail` because there were 61 occurrences of the former and only seven of the latter, and `e-mail` seems antiquated
Build the application and …
=> Minor updates to i18n strings for clarity and consistency

package.json
* Fixes #2353
The lookup in external sources is not available in `Edit Item > Relationships`. We can only add internal DSpace entities there as a linked item, now we will also be able to import a new item from an external source there.
* `DsDynamicLookupRelationModalComponent`: List all the external sources which are enabled/configured in the popup modal
**Guidance for how to test and review this PR:**
- Initialise the entities with `initialize-entities -f dspace/config/entities/relationship-types.xml`
- Create 2 collections, one with entity type `Publication` and one with `Person`
- In `item-submission.xml` use those 2 collection handles to link to their respective `submission-name`s: `Publication` & `Person`
- Add `orcid.api-url = …
=> Added support to import from external source on Edit Item > Relationships

src/app/submission/sections/upload/file/edit/section-upload-file-edit.component.spec.ts, src/app/submission/sections/upload/file/edit/section-upload-file-edit.component.ts
Bug fix. Saving bitstream edits is failing when the submission form does not include access conditions. This PR adds a check that prevents access condition processing when the property doesn't exist in the form.
This can be tested by [removing access options](https://wiki.lyrasis.org/display/DSDOC7x/Submission+User+Interface#SubmissionUserInterface-Modifyingaccessconditions(embargo,etc.)presentedforBitstreams) from the `UploadConfiguration` (by removing all "ref" tags). Then upload and edit a bitstream in the submission form. Try to save the changes. Prior to applying this PR you should see an error in console.
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always …
=> File edit component updated to work for forms without access conditions.

src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.ts
(Manual) port of #2733 by @jensvannerum to `dspace-7_x`.
NOTE: This only contains the final two commits that are visible in #2733.  That's because the first 5 commits were previously backported/squashed in #2764
=> [Port dspace-7_x]  Use keyboard to select values (part 2)

src/app/search-navbar/search-navbar.component.spec.ts, src/app/search-navbar/search-navbar.component.ts
A site search (issued by the search box in the navigation bar) should not adopt existing URL query parameters. For example, a site search that is issued in the context of MyDSpace will adopt `configuration=workspace` as a URL query parameter.
The normal user would not expect that a site search considers only a subset of all items in the repository. It is commonly expected that a site search behaves consistent regardless of the context from which the search was started.
=> site search should not adopt existing URL query string parameters

config/config.example.yml, src/app/core/submission/vocabularies/vocabulary.data.service.spec.ts, src/app/core/submission/vocabularies/vocabulary.data.service.ts, src/app/core/submission/vocabularies/vocabulary.service.spec.ts, src/app/core/submission/vocabularies/vocabulary.service.ts, src/app/dso-shared/dso-edit-metadata/dso-edit-metadata-field-values/dso-edit-metadata-field-values.component.html, src/app/dso-shared/dso-edit-metadata/dso-edit-metadata-form.ts, src/app/dso-shared/dso-edit-metadata/dso-edit-metadata-value/dso-edit-metadata-value.component.html, src/app/dso-shared/dso-edit-metadata/dso-edit-metadata-value/dso-edit-metadata-value.component.spec.ts, src/app/dso-shared/dso-edit-metadata/dso-edit-metadata-value/dso-edit-metadata-value.component.ts, src/app/dso-shared/dso-edit-metadata/dso-edit-metadata.component.html, src/app/dso-shared/dso-shared.module.ts, src/app/shared/form/builder/ds-dynamic-form-ui/models/dynamic-vocabulary.component.ts, src/app/shared/form/builder/ds-dynamic-form-ui/models/onebox/dynamic-onebox.component.html, src/app/shared/form/builder/ds-dynamic-form-ui/models/onebox/dynamic-onebox.component.ts, src/app/shared/form/directives/authority-confidence-state.directive.ts, src/app/shared/testing/vocabulary-service.stub.ts, src/assets/i18n/en.json5, src/config/default-app-config.ts, src/config/submission-config.interface.ts, src/environments/environment.test.ts
* Fixes #1758
* Requires DSpace/DSpace#9239
This PR uses the existent `DsDynamicOneboxComponent` and `DsDynamicScrollableDropdownComponent` components to be able to edit metadata controlled by vocabularies in item's metadata edit form in the same way that is done in submission form.
* Use components `DsDynamicOneboxComponent` and `DsDynamicScrollableDropdownComponent` in item's metadata edit form for fields controlled by vocabularies:
* `DsDynamicOneboxComponent`: is used for vocabularies that use a autocomplete functionality and for hierarchical vocabularies
* `DsDynamicScrollableDropdownComponent`: is used for vocabularies configured with value-pairs element in input-forms.xml (dc.type, dc.language.iso, etc.)
* Add a function to the Vocabulary service to …
=> Implement vocabulary value selectors in item’s metadata edit form

src/app/item-page/edit-item-page/edit-item-page.component.html, src/app/item-page/simple/item-page.component.ts
_Related issue:_
* Fixes #2842
when configuration ldn.enabled=false, anonymous item page landing shows an 'undefined' error on browser console.
Error is not present landing on item page as anonymous or logged user, with the ldn.enabled configuration evaluated as true or false.
=> fix 'undefined' error on anonymous item page landing

src/app/shared/form/builder/ds-dynamic-form-ui/models/tag/dynamic-tag.component.ts
The condition within the `onBlur` event handler method for the tag input field has an error when the [model.hasAuthority](https://github.com/DSpace/dspace-angular/blob/main/src/app/shared/form/builder/ds-dynamic-form-ui/models/tag/dynamic-tag.component.html#L24) is falsy.
This causes the text entered to not be converted to a subject "chip" and is not added to the form for patch submission.
Check the [view template](https://github.com/DSpace/dspace-angular/blob/main/src/app/shared/form/builder/ds-dynamic-form-ui/models/tag/dynamic-tag.component.html#L49) for whether an [element reference](https://github.com/DSpace/dspace-angular/blob/main/src/app/shared/form/builder/ds-dynamic-form-ui/models/tag/dynamic-tag.component.ts#L42) will be rendered or not. Minimizing cyclomatic complexity helps …
=> Element reference for typeahead directive is only defined when model has authority

src/app/system-wide-alert/alert-form/system-wide-alert-form.component.spec.ts, src/app/system-wide-alert/alert-form/system-wide-alert-form.component.ts
* Fixes #2876
This PR fixes an issue where alerts can be activated with empty message string. This made it impossible to disble it until you added a message
I simply added a check to not update/create the system wide alert if the form is invalid. I can also create a backend PR if this is a rule we want to inforce there too
- Run `DELETE FROM systemwidealert;` to remove existing alert messages if you have any
- Click on the activate button an verify that if the rest of the form has not been filled in correctly the alert isn't created
- After filling in a message the button should still work like before (directly updating the alert without having to click on the save button)
=> System-wide alert shouldn't be created when the message is empty

yarn.lock
Manual port of #2872 from @dependabot to `dspace-7_x`
=> [Port dspace-7_x] Bump webpack-dev-middleware from 5.3.3 to 5.3.4

yarn.lock
Manual port of #2867 to `dspace-7_x` branch.
=> [Port dspace-7_x]  Bump follow-redirects from 1.15.5 to 1.15.6 

.github/workflows/build.yml, .github/workflows/issue_opened.yml, .github/workflows/pull_request_opened.yml
Related to https://github.com/DSpace/DSpace/pull/9454
Recently, we've had random (increasingly frequent) errors from the Codecov action regarding uploading code coverage results to [codecov.io](https://codecov.io/).  The recommended fix is to update to the latest version of the action & add the (newly required) `CODECOV_TOKEN` (which has also been added as a repository secret in GitHub)
Therefore, this PR does that and also updates all other GitHub actions to the latest version
Assuming all actions succeed, this will be merged immediately.  It adds no code to DSpace itself
=> Update all GitHub Actions & add token for Codecov.io

src/app/entity-groups/research-entities/submission/item-list-elements/org-unit/org-unit-suggestions/org-unit-input-suggestions.component.scss, src/app/entity-groups/research-entities/submission/item-list-elements/person/person-suggestions/person-input-suggestions.component.scss
When Font Awesome was updated from v5.5.0 to v6.2.1 the CSS Pseudo-elements were not correctly updated this small PR fixes this issue. More information on this can be found [here](https://fontawesome.com/docs/web/setup/upgrade/pseudo-elements#updating-font-rule-syntax).
Verify that the icons are now rendered correctly again
- The easiest way to check this is by going to `Edit Item > Relationships` of a publication and click on `+ Add` on the `Authors (persons)` & `Organizational Units` sections
=> Fixed Font Awesome CSS Pseudo-elements not rendering in v6.x

src/app/register-email-form/register-email-form.component.html
Add references/links to any related issue:
* Fixes #2918 
This is a really small PR, which fixes the new-user-registration if the verification is disabled. 
* Added check for _registrationVerification_ to the html-template file.
Currently, if you try to register on https://sandbox.dspace.org using the registration form, you get an error (documented in #2918). Currently it only works if the `registration.verification.enabled` is set to `true`. I added a small check, if the registrationVerfication is enabled or not and now it works for me.
Guideline for testing:
* Set the `registration.verification.enabled` to `false` on the backend side
* Start your frontend and try to register with a new email adress. 
To check, if the captcha still works:
* Activate the …
=> Add check for registration verification to the register email form.

src/app/home-page/home-page.component.html, src/app/home-page/home-page.component.scss, src/app/home-page/home-page.component.ts, src/app/shared/search/search.component.html
* Fixes #2942
* Related #2844
In the previous PR I did not realise that the `ds-themed-configuration-search-page` already used the `ds-page-with-sidebar`. In that PR I added an extra `ds-page-with-sidebar` around the `ds-themed-configuration-search-page` causing it's empty floating content column to block clickevents on the components underneath it. This PR refactors the home page to use the `ds-page-with-sidebar` inside the `ds-themed-configuration-search-page` instead, this is done with the new content projection selector `searchContentTop`.
=> Fixed home page links being unclickable

src/app/shared/dso-selector/dso-selector/dso-selector.component.html, src/app/shared/dso-selector/dso-selector/dso-selector.component.ts
- Fixes #2767
Fix for infinite scroll.
The selector for the infinite scroll wasn't targeting the right infinitescroll container.
Changed infinitescrollcontainer to use id
Added a random seed made of alphanumerical character to avoid duplicated id
1. Go into MyDSpace
1. Then try to add for example a new publication
1. When the list of collections is shown scroll down
1. Make sure the infinite scrolldown works
=> Fix infinite scroll

src/app/access-control/bulk-access/browse/bulk-access-browse.component.html, src/app/access-control/epeople-registry/epeople-registry.component.html, src/app/access-control/epeople-registry/eperson-form/eperson-form.component.html, src/app/access-control/group-registry/group-form/members-list/members-list.component.html, src/app/access-control/group-registry/group-form/subgroup-list/subgroups-list.component.html, src/app/access-control/group-registry/groups-registry.component.html, src/app/admin/admin-registries/bitstream-formats/bitstream-formats.component.html, src/app/admin/admin-registries/metadata-schema/metadata-schema.component.html, src/app/collection-page/collection-item-mapper/collection-item-mapper.component.ts, src/app/item-page/edit-item-page/item-bitstreams/item-edit-bitstream-bundle/paginated-drag-and-drop-bitstream-list/paginated-drag-and-drop-bitstream-list.component.html, src/app/item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.html, src/app/item-page/full/field-components/file-section/full-file-section.component.html, src/app/item-page/versions/item-versions.component.html, src/app/process-page/overview/process-overview.component.html, src/app/shared/object-detail/object-detail.component.html, src/app/shared/object-grid/object-grid.component.html, src/app/shared/object-list/object-list.component.html, src/app/shared/object-select/collection-select/collection-select.component.html, src/app/shared/object-select/collection-select/collection-select.component.ts, src/app/shared/object-select/item-select/item-select.component.html, src/app/shared/object-select/item-select/item-select.component.spec.ts, src/app/shared/object-select/item-select/item-select.component.ts, src/app/shared/object-select/object-select.model.ts, src/app/shared/object-select/object-select/object-select.component.ts, src/app/shared/pagination/pagination.component.ts
=> [Port dspace-7_x] Fixed pagination issues on item mapper

src/app/collection-page/collection-page-routing.module.ts, src/app/community-page/community-page-routing.module.ts, src/app/core/breadcrumbs/community-breadcrumb.resolver.ts, src/app/core/breadcrumbs/dso-breadcrumb.resolver.spec.ts, src/app/core/breadcrumbs/dso-breadcrumb.resolver.ts, src/app/core/core.module.ts, src/app/core/submission/resolver/submission-links-to-follow.ts, src/app/core/submission/resolver/submission-object.resolver.ts, src/app/core/submission/resolver/submission-parent-breadcrumb.resolver.ts, src/app/core/submission/submission-parent-breadcrumb.service.ts, src/app/submission/submission.service.ts, src/app/workflowitems-edit-page/item-from-workflow-breadcrumb.resolver.ts, src/app/workflowitems-edit-page/item-from-workflow.resolver.spec.ts, src/app/workflowitems-edit-page/item-from-workflow.resolver.ts, src/app/workflowitems-edit-page/workflowitems-edit-page-routing.module.ts, src/app/workspaceitems-edit-page/item-from-workspace-breadcrumb.resolver.ts, src/app/workspaceitems-edit-page/item-from-workspace.resolver.spec.ts, src/app/workspaceitems-edit-page/item-from-workspace.resolver.ts, src/app/workspaceitems-edit-page/workspaceitems-edit-page-routing.module.ts, src/assets/i18n/en.json5
=> [Port dspace-7_x] Added missing/incomplete breadcrumbs on create community/collection/item pages

docker/docker-compose-ci.yml, docker/docker-compose-rest.yml
Manual port of #2966 to `dspace-7_x`.
This fixes an error that also occurs if you attempt to run the backend using the guide at https://wiki.lyrasis.org/display/DSPACE/Try+out+DSpace+7   When doing so, the `dspacedb` container will fail to start with this error:
```
Error: Database is uninitialized and superuser password is not specified.
You must specify POSTGRES_PASSWORD to a non-empty value for the
superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".
```
=> Update REST and CI docker compose scripts to sync with 7.x backend

docker/README.md, docker/docker-compose-ci.yml, docker/docker-compose-rest.yml
This small PR ensures that our `docker-compose-rest.yml` (for running backend) and `docker-compose-ci.yml` (for running e2e tests) are up-to-date and synced with the [Backend's `docker-compose.yml`](https://github.com/DSpace/DSpace/blob/main/docker-compose.yml)
This fixes an error that also occurs if you attempt to run the backend using the guide at https://wiki.lyrasis.org/display/DSPACE/Try+out+DSpace+8   When doing so, the `dspacedb` container will fail to start with this error:
```
Error: Database is uninitialized and superuser password is not specified.
You must specify POSTGRES_PASSWORD to a non-empty value for the
superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".
```
* Assuming CI tests all succeed, I plant to merge this immediately.  Without it, the …
=> Update REST and CI docker compose scripts to sync with 8.0 backend

src/themes/custom/app/browse-by/browse-by-taxonomy/browse-by-taxonomy.component.ts, src/themes/custom/app/collection-page/collection-page.component.ts, src/themes/custom/app/collection-page/edit-item-template-page/edit-item-template-page.component.ts, src/themes/custom/app/community-page/community-page.component.ts, src/themes/custom/app/community-page/sections/sub-com-col-section/sub-collection-list/community-page-sub-collection-list.component.ts, src/themes/custom/app/forgot-password/forgot-password-email/forgot-email.component.ts, src/themes/custom/app/forgot-password/forgot-password-form/forgot-password-form.component.ts, src/themes/custom/app/header/header.component.ts, src/themes/custom/app/home-page/home-page.component.ts, src/themes/custom/app/item-page/simple/item-page.component.ts, src/themes/custom/app/item-page/simple/item-types/publication/publication.component.ts, src/themes/custom/app/item-page/simple/item-types/untyped-item/untyped-item.component.ts, src/themes/custom/app/login-page/login-page.component.ts, src/themes/custom/app/my-dspace-page/my-dspace-page.component.ts, src/themes/custom/app/navbar/expandable-navbar-section/expandable-navbar-section.component.ts, src/themes/custom/app/profile-page/profile-page.component.ts, src/themes/custom/app/register-page/register-email/register-email.component.ts, src/themes/custom/app/shared/browse-by/browse-by.component.ts, src/themes/custom/app/shared/comcol-page-browse-by/comcol-page-browse-by.component.ts, src/themes/custom/app/shared/lang-switch/lang-switch.component.ts, src/themes/custom/app/shared/loading/loading.component.ts, src/themes/custom/app/shared/object-list/object-list.component.ts
-   Fixes #2977
This PR fixes the issue where running the DSpace UI with the "custom" theme resulted in many features not working properly. The root cause was identified as the themed components having mismatched imports compared to their base components. The PR addresses this by ensuring that all themed components have the same imports as their base components.
The changes made in this PR include:
-   Ensuring consistency in imports between themed components and their base components.
-   Verifying that all fixed components now work correctly in the custom theme.
**Testing Instructions:**
1.  Enable the custom theme.
2.  Build the UI in production mode using `yarn build:prod` and serve using `yarn serve:ssr`.
3.  Access the homepage and ensure that all features are working as expected. …
=> Synced the imports of the custom theme with the imports of the base component so custom theme works again

cypress/e2e/item-template.cy.ts, src/app/dso-shared/dso-edit-metadata/dso-edit-metadata.component.ts
* Fixes #2938 
Updated the `retrieveDataService()` method to address an issue where the Template Item page for creating a new Item Template for a Collection fails to load. The method now correctly returns the `updateDataService` when available instead of returning empty.
* Updated the `retrieveDataService()` method to return the `updateDataService` when available instead of returning empty, resolving the issue with the non-loading Template Item page.
* Added e2e test to verify the display of specific elements on the item template page.
How to test:
1.  Edit a Collection.
2.  Click "+Add" under Template Item.
3.  Verify that the page successfully loads without any indefinite loading.
4.  Perform additional actions such as canceling, editing, or deleting the …
=> Fixed the problem that creating template item results in page which never finishes loading

src/app/admin/admin-sidebar/admin-sidebar.component.scss, src/app/root/root.component.html, src/app/root/root.component.ts, src/themes/custom/app/root/root.component.ts
* Fixes #2927
This PR fixes the issues with the admin sidebar scrollbar on Firefox on Windows by allocating more space to the scrollbar.
* In the root component a class is added to identify the browser and the OS according to the user agent (e.g. `browser-firefox browser-firefox-windows`
* In the `admin-sidebar` component the value of `--ds-dark-scrollbar-width` is overridden when `browser-firefox-window` class is present
Note that `--ds-dark-scrollbar-width` has two purposes:
* define the scrollbar width (this is not supported by Firefox)
* allocate space to the scrollbar (`min-width: calc(var(--ds-admin-sidebar-collapsible-element-width) - var(--ds-dark-scrollbar-width));`)
This PR allows to override any property of a CSS class as follows:
```css
.my-class {
// class properties …
```
=> Fix issue with the admin sidebar scrollbar on Firefox/Windows

docker/cli.assetstore.yml, docker/cli.ingest.yml, docker/cli.yml, docker/db.entities.yml, docker/docker-compose-ci.yml, docker/docker-compose-dist.yml, docker/docker-compose-rest.yml, docker/docker-compose.yml
* Related to DSpace/DSpace#9522 , which made the same changes to the backend docker compose scripts.
The "version" tag in a Docker Compose file is now obsolete.  See docs at https://docs.docker.com/compose/compose-file/04-version-and-name/#version-top-level-element-obsolete
This PR just removes all those tags as we are now seeing warnings like this when rebuilding Docker images:
```
time="2024-05-01T11:14:05-05:00" level=warning msg="C:\\DSpace\\docker-compose.yml: `version` is obsolete"
time="2024-05-01T11:14:05-05:00" level=warning msg="C:\\DSpace\\docker-compose-cli.yml: `version` is obsolete"
```
* This is an extremely minor change.  As long as warning disappears & builds all succeed, I'll merge immediately.
=> Remove obsolete "version" tag from Docker Compose files (Angular version)

src/app/shared/form/builder/form-builder.service.spec.ts, src/app/shared/form/builder/parsers/concat-field-parser.ts, src/app/shared/form/builder/parsers/date-field-parser.spec.ts, src/app/shared/form/builder/parsers/disabled-field-parser.spec.ts, src/app/shared/form/builder/parsers/dropdown-field-parser.spec.ts, src/app/shared/form/builder/parsers/dropdown-field-parser.ts, src/app/shared/form/builder/parsers/field-parser.ts, src/app/shared/form/builder/parsers/list-field-parser.spec.ts, src/app/shared/form/builder/parsers/lookup-field-parser.spec.ts, src/app/shared/form/builder/parsers/lookup-name-field-parser.spec.ts, src/app/shared/form/builder/parsers/name-field-parser.spec.ts, src/app/shared/form/builder/parsers/name-field-parser.ts, src/app/shared/form/builder/parsers/onebox-field-parser.spec.ts, src/app/shared/form/builder/parsers/parser-factory.ts, src/app/shared/form/builder/parsers/relation-group-field-parser.spec.ts, src/app/shared/form/builder/parsers/row-parser.spec.ts, src/app/shared/form/builder/parsers/series-field-parser.spec.ts, src/app/shared/form/builder/parsers/series-field-parser.ts, src/app/shared/form/builder/parsers/tag-field-parser.spec.ts, src/app/shared/form/builder/parsers/textarea-field-parser.spec.ts
Backport to DSpace 7.x for #2640
=> [Port dspace-7_x] More meaningful regex error messages

cypress/e2e/collection-create.cy.ts, cypress/e2e/community-create.cy.ts, src/app/collection-page/create-collection-page/create-collection-page.component.html, src/app/collection-page/create-collection-page/create-collection-page.component.ts, src/app/community-page/create-community-page/create-community-page.component.html, src/app/community-page/create-community-page/create-community-page.component.ts, src/app/shared/comcol/comcol-forms/create-comcol-page/create-comcol-page.component.ts
* Fixes #2941
Fixes the bug where clicking "Save" when creating a new Community or Collection doesn't provide any visual feedback to the user. This PR introduces a loading animation to indicate that the backend is processing the request.
-   Added `isLoading$: BehaviorSubject<boolean>` property to the `CreateComColPageComponent`.
-   Implemented logic to show and hide the loading animation in `onSubmit` method.
-   Added `ds-themed-loading` component to the HTML files of `CreateCollectionPageComponent` and `CreateCommunityPageComponent`.
=> Clicking save on create community and collection pages provides user feedback

src/app/root/root.component.ts
* Fixes #3000
Fix bug where "navigator" may be null in SSR mode
* Verify error no longer occurs as described in #3000
* This error has also displayed in e2e test logs in GitHub CI.  If it's no longer displayed there, then this is working as well.
=> Fix `TypeError: Cannot read properties of undefined (reading 'userAgent')`

src/assets/i18n/fr.json5
Addition to the json5 french file to fix missing parameters for access control and batch loading in DSpace.
=> French translations for missing parameters (access control and batch loading)

scripts/sync-i18n-files.ts, src/app/item-page/edit-item-page/item-move/item-move.component.html, src/app/shared/dso-selector/dso-selector/dso-selector.component.ts, src/assets/i18n/en.json5, src/assets/i18n/fr.json5, src/assets/i18n/nl.json5
* Fixes #598
Currently the `sync-i18n` script can't be executed because of a type issue caused by [the Typescript 4.4 update](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-4.html#defaulting-to-the-unknown-type-in-catch-variables---useunknownincatchvariables). Because this PR was ridiculously small I also fixed another issue at the same time. The second fix makes the DSO type in the `dso-selector` translatable.
- Added an if statement to `sync-i18n-files.ts` to verify that the variable returned by the catch block is of type `Error`
- Added translation keys for the 3 DSO types that use the `dso-selector`: Community, Collection & Item
**Guidance for how to test/review this PR:**
- Verify that you can run the `sync-i18n` script again
- …
=> Fix sync-i18n script throwing a compile error & added some missing translation keys

config/config.example.yml, src/assets/i18n/ar.json5
Added Arabic Translation
Added ar.json5 translation and modified config files to include this translation
Added Arabic translation
Updated config.example.yml
=> Added Arabic Translation

package.json, yarn.lock
Manual port of #2994 to `dspace-7_x` using `yarn upgrade ejs@^3.1.10`
=> [Port dspace-7_x] Bump ejs from 3.1.9 to 3.1.10

src/app/core/submission/submission-rest.service.spec.ts, src/app/core/submission/submission-rest.service.ts
* [7_x REST PR](https://github.com/DSpace/DSpace/pull/9507)
* [7_x angular PR](https://github.com/DSpace/dspace-angular/pull/2987)
* [main REST PR](https://github.com/DSpace/DSpace/pull/9508)
* [main angular PR](https://github.com/DSpace/dspace-angular/pull/2988) (this PR)
This PR aims to improve performance for submission by removing default full projection for workflow/workspace items and instead allowing support for embedded properties.
Changes:
* Added links for "item", "submitter" and "collection" on workflow/workspace items (annotations, link repositories etc.)
* Removed `projection=full` from submission item on angular side and replaced with embed parameters, this should reduce _a lot_ of the server and page's load.
* Modified test cases that expect embedded properties to either …
=> Submission performance

src/app/core/submission/submission-rest.service.spec.ts, src/app/core/submission/submission-rest.service.ts
* [7_x REST PR](https://github.com/DSpace/DSpace/pull/9507)
* [7_x angular PR](https://github.com/DSpace/dspace-angular/pull/2987) (this PR)
* [main REST PR](https://github.com/DSpace/DSpace/pull/9508)
* [main angular PR](https://github.com/DSpace/dspace-angular/pull/2988)
This PR aims to improve performance for submission by removing default full projection for workflow/workspace items and instead allowing support for embedded properties.
Changes:
* Added links for "item", "submitter" and "collection" on workflow/workspace items (annotations, link repositories etc.)
* Removed `projection=full` from submission item on angular side and replaced with embed parameters, this should reduce _a lot_ of the server and page's load.
* Modified test cases that expect embedded properties to either …
=> 7.x - Submission performance

src/app/core/submission/submission-rest.service.spec.ts, src/app/core/submission/submission-rest.service.ts
* Fixes a small bug in #2988 discovered via our e2e tests (`submission.cy.ts`)
On `main` and `dspace-7_x` after #2988 was merged, the submission e2e tests began to fail (almost randomly). 
After digging into the issue locally, I found the cause was that the Submission Form would occasionally **hang indefinitely** at a "Loading ..." page.  After testing locally, I found I was able to reproduce that on my local machine via the following steps:
1. Start the UI in production mode (`yarn build:prod; yarn serve:ssr`).  Might also be reproducible in dev mode.
2. Login and visit any "In Progress Submission" (i.e. WorkspaceItem) from MyDSpace
3. While the submission form is visible, click the reload button in your browser several times.
4. Eventually (sometimes on first reload) you'll find the …
=> Ensure `item` is also embedded in submission form

src/assets/i18n/en.json5
* Adds missing i18n keys which are also referenced in https://github.com/DSpace/DSpace/issues/9501
OpenAIRE is missing a lot of i18n keys, for example:
This PR adds them & removes a few keys which were duplicated
* Check code
* Verify that this fixes missing keys that can be found in import from external sources
=> Add missing i18n keys for OpenAIRE external sources.

src/app/process-page/form/process-form.component.ts, src/app/process-page/overview/table/process-overview-table.component.spec.ts, src/app/process-page/overview/table/process-overview-table.component.ts, src/assets/i18n/en.json5
* Requires DSpace/DSpace#9401
* Replaces #2995
This pull request addresses the issue of null users causing crashes in the process overview page. It includes changes to handle null users gracefully by returning an i18n message for unknown users and switching from `getFirstSucceededRemoteDataPayload` to `getFirstCompletedRemoteData` to ensure proper emissions.
-   Wrapping the method in an if/else to check for non-empty IDs and return an i18n message for unknown users if necessary.
-   Changing `getFirstSucceededRemoteDataPayload` to `getFirstCompletedRemoteData` and using `switchMap` to handle emissions based on whether the remote data has succeeded.
-   Writing unit tests to cover all possible cases (valid ID, invalid ID, null ID).
Please ensure to test the …
=> Handle Null Users Gracefully in Process Overview Page

src/app/item-page/field-components/metadata-uri-values/metadata-uri-values.component.html, src/app/item-page/field-components/metadata-uri-values/metadata-uri-values.component.spec.ts, src/app/item-page/field-components/metadata-uri-values/metadata-uri-values.component.ts
* Fixes #2834
This feature request proposes adding a new optional input parameter to the `<ds-metadata-uri-values>` component in order to specify the link target, allowing metadata links to open in a new window/tab.
* Added a new optional input parameter `linkTarget` to the `<ds-metadata-uri-values>` component. The default value of this parameter is `_blank`, this will make sure the link is opened in a new window/tab.
* Added a test case in the `src/app/item-page/field-components/metadata-uri-values/metadata-uri-values.component.spec.ts` to verify the correct application of the `linkTarget` attribute to metadata links.
How to test: 
* Go to an item page, for example a publication
* Click on the link that's under the URI-title
* The link now opens in a new …
=> Allow opening ds-metadata-uri-values links in a new window

src/app/dso-shared/dso-edit-metadata/dso-edit-metadata-value/dso-edit-metadata-value.component.html, src/app/dso-shared/dso-edit-metadata/dso-edit-metadata-value/dso-edit-metadata-value.component.spec.ts, src/app/dso-shared/dso-edit-metadata/dso-edit-metadata-value/dso-edit-metadata-value.component.ts
* Related to #2653
While testing the functionality introduced by #2653 to edit authority-controlled values in the current main branch, I have observed that it is failing to load the initial values of the authority field because the model parameter used by these fields are not properly initialized. This PR changes how this model parameter is created to ensure its existence when the field is initialized.
To reproduce the bug, edit an existing authority-controlled field value in edit item page, such as 'dc.type', 'dc.subject', or 'dc.contributor.author'. The field should load the initial value, but it remains empty, and the console shows the following error: `ERROR TypeError: this.model is null `
=> Error loading the initial value when editing an authority field in edit item page

src/app/notifications/qa/events/quality-assurance-events.component.html, src/app/notifications/qa/events/quality-assurance-events.component.ts, src/assets/i18n/ar.json5, src/assets/i18n/en.json5
* Fixes https://github.com/DSpace/dspace-angular/issues/3023
There were initially two different button groups: for admin users and the other for non-admin users (which was allowing non-admin users only to undo an action).
Now, when the topic is marked as `WITHDRAWN` or `REINSTATED`, we display only the button group containing a delete button for submitter users. Conversely, for other topics, submitter users will see all three buttons.  Although the button group remains the same for admin and non-admin users, the delete button's functionality varies. For non-admin users, it acts as  '`UNDO`' action (as it was in the previous behavior for non admin users) and for the administrator it will be a '`REJECTED`’ action.
**Screenshots**
=> Allow submitter users to accept/ignore suggestions

src/app/core/cache/models/request-param.model.ts, src/app/core/data/relationship-data.service.ts, src/app/core/data/relationship-type-data.service.ts, src/app/core/eperson/eperson-data.service.spec.ts, src/app/core/eperson/eperson-data.service.ts, src/app/core/notifications/qa/events/quality-assurance-event-data.service.spec.ts, src/app/core/notifications/qa/events/quality-assurance-event-data.service.ts, src/app/core/statistics/usage-report-data.service.ts, src/app/core/submission/correctiontype-data.service.ts, src/app/core/submission/submission-cc-license-url-data.service.ts, src/app/core/submission/vocabularies/vocabulary.data.service.spec.ts, src/app/core/submission/vocabularies/vocabulary.data.service.ts, src/app/core/submission/workflowitem-data.service.ts, src/app/core/submission/workspaceitem-data.service.spec.ts, src/app/core/submission/workspaceitem-data.service.ts
* Fixes #2724
This PR encodes all the `RequestParam`s values. I added an optional parameter to still make it possible to provide already encoded values if needed. This has also an added advantage that it will throw errors for all values that are not created by using the `new RequestParam` constructor, since the third parameter will be missing.
* Encode the value received in `RequestParam` by default
* Removed the `encodeURIComponent()` of values that were given as parameters to `RequestParam` to prevent values from being encoded twice
**See #2724 ~~& #2727~~ for how to test this PR ~~(#2727 is only reproducible in production mode)~~**
=> Encode all `RequestParam` values

src/app/core/breadcrumbs/dso-name.service.spec.ts, src/app/core/eperson/models/eperson.model.ts
* Fixes #2947
Extend the EPerson render types to make the dso-name factory for EPersons work.
* extend Render Type of EPerson with `EPerson` value. Currently the constructor.name is `i` falling back to the default factory. Lists of EPerson seems not to be used currently anywhere and the epeople registry uses some table so this should have no impact on other parts of the code.
* Test Case: people with no last or firstname should now be displayed without leading or trailing whitespace in the epeople registry overview. Before this change these entries should have some whitespace because in the `dso-name.service` the fallback goes to deprecated `dso.name` which constructs the name in some other way.
* provided tests for displaying the eperson name.
**Include …
=> Fix display of dso names for EPersons

src/app/shared/resource-policies/form/resource-policy-form.model.ts, src/assets/i18n/ar.json5, src/assets/i18n/bn.json5, src/assets/i18n/ca.json5, src/assets/i18n/cs.json5, src/assets/i18n/de.json5, src/assets/i18n/el.json5, src/assets/i18n/en.json5, src/assets/i18n/es.json5, src/assets/i18n/fi.json5, src/assets/i18n/fr.json5, src/assets/i18n/gd.json5, src/assets/i18n/hi.json5, src/assets/i18n/hu.json5, src/assets/i18n/it.json5, src/assets/i18n/ja.json5, src/assets/i18n/kk.json5, src/assets/i18n/lv.json5, src/assets/i18n/nl.json5, src/assets/i18n/pl.json5, src/assets/i18n/pt-BR.json5, src/assets/i18n/pt-PT.json5, src/assets/i18n/sr-cyr.json5, src/assets/i18n/sr-lat.json5, src/assets/i18n/sv.json5, src/assets/i18n/sw.json5, src/assets/i18n/tr.json5, src/assets/i18n/uk.json5, src/assets/i18n/vi.json5
Hi @tdonohue, I'm @jtimal partner. We have been working on this issue and we will send you the PR.
* Fixes #1719 
We have added a maxLength to the name input and a hint to advice max characters.
- Add/Edit a policy
- the input only allows to use 30 characters and shows a hint
* Policy name input max length
* Policy name input hint
* i18n values
=> added maxlength and hint to resource policy

src/app/shared/eperson-group-list/eperson-group-list.component.ts
This is an extremely small PR to just remove an unnecessary `console.log` line which appears to have been used for debugging.  It's only visible in your browser's DevTools Console when editing a resource policy.
=> Remove unnecessary console.log

src/app/search-page/configuration-search-page.component.ts, src/app/shared/object-collection/shared/listable-object/listable-object-component-loader.component.spec.ts, src/app/shared/object-list/item-list-element/item-types/item/item-list-element.component.html, src/app/shared/object-list/item-list-element/item-types/item/item-list-element.component.spec.ts, src/app/shared/object-list/item-list-element/item-types/item/item-list-element.component.ts, src/app/shared/search/search-filters/search-filter/search-hierarchy-filter/search-hierarchy-filter.component.spec.ts, src/app/shared/search/search-filters/search-filter/search-hierarchy-filter/search-hierarchy-filter.component.ts, src/app/shared/search/search.component.spec.ts, src/app/shared/search/search.component.ts, src/app/shared/sidebar/page-with-sidebar.component.html, src/app/shared/testing/truncatable-service.stub.ts, src/app/statistics/angulartics/dspace-provider.ts
* Port of #2651
* Port of #2732
* Fixes #2970
* Prevent vocabulary undefined from being retrieved in hierarchy filter when none is configured
* Don't retrieve the accessStatus when item.showAccessStatuses is false
=> [Port dspace-7_x] Multiple discovery backports 

src/app/shared/object-list/search-result-list-element/item-search-result/item-types/item/item-search-result-list-element.component.html, src/app/shared/object-list/search-result-list-element/search-result-list-element.component.ts
Hi @tdonohue, I'm @jtimal partner, I like to share this PR with you:
* Fixes #2203 
Add a method to search-result-list-element component to show all the authors and if the author's name is highlighted its displayed anyways (if author's list length allow it)
To reproduce the error we need an item with two or more dc.contributor.author:
- Create and deposit a new item
- Add to metadata two or more dc.contributor.author
- Use search tool to find the item
* Added a method to combine the highlighted authors and other authors' name
* Changed the method used to displayed the list of authors in result list
=> Fix Author search result without co-author

src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/relationship.effects.spec.ts, src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/relationship.effects.ts, src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/search-tab/dynamic-lookup-relation-search-tab.component.html, src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/search-tab/dynamic-lookup-relation-search-tab.component.scss
=> [Port 8.x] Fix for not all CREATE/DELETE Relationship requests coming through, during submission entity lookup

src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/relationship.effects.spec.ts, src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/relationship.effects.ts, src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/search-tab/dynamic-lookup-relation-search-tab.component.html, src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/search-tab/dynamic-lookup-relation-search-tab.component.scss
The entity lookup modal used during submission has options to create/remove multiple relationships at a time. Currently however, REST is sometimes overwhelmed by getting too many of these requests at once, and some relationship creations/deletions might not come through. 
This PR ensures that the requests are sent synchronously. This makes it so REST only receives them one at the time, and can process them one by one. 
Ideally, these type of issues can be avoid all together with the proposed submission refactor ( #858  ).
**List of changes**
- Removed the "Select/Deselect all" options from the dropdown in the DynamicLookupRelationSearchTab template, as well as the select button next to the dropdown.
- Until #858 is resolved, the load would be too high anyways.
- Users can still choose a …
=> Fix for not all CREATE/DELETE Relationship requests coming through, during submission entity lookup

src/assets/i18n/cs.json5
Added full translation of DSpace 7.6 frontend into Czech language 
Please notify us of any translation you disagree with on specified email, alongside  opening a new pull request.
=> Czech DSpace 7 UI translation by NTK

src/app/system-wide-alert/alert-banner/system-wide-alert-banner.component.html, src/app/system-wide-alert/alert-form/system-wide-alert-form.component.html
* Fixes #3019.
Adds HTML support to the system-wide alert banner.
The commit only includes two simple changes, as explained in https://github.com/DSpace/dspace-angular/issues/3019#issuecomment-2103135271.
In a second commit (I did it in a separate commit to ease the PR review), I also reformatted the code of the HTML templates, since the indenting was a bit mangled.
To test, log in as an admin, and set a system-wide alert message with HTML code in it.
Some examples of the result:
=> Add HTML support on system-wide alert (Fixes #3019)

src/config/ssr-config.interface.ts, src/environments/environment.production.ts, src/environments/environment.test.ts, src/environments/environment.ts
* Follow-up to #2067 and #2934 
This PR changes the default setting of `inlineCriticalCss` to `false` (disabled) in order to improve the SSR (Server Side Rendering) performance.
For details about this change, see discussion in #2067, especially https://github.com/DSpace/dspace-angular/pull/2067#issuecomment-2015441135
Also see other references on web about poor performance of `inlineCriticalCss`:
* https://github.com/angular/universal/issues/2106
* https://medium.com/@e94kai/angular-12-server-side-rendering-optimization-2b8a30208c11
* For detailed testing, I'm going to **deploy this minor change immediately to https://sandbox.dspace.org** .  That will allow us to test this new default setting via Testathon and beyond.
If accepted, this should be ported to `dspace-7_x`.  However, it will …
=> Disable `inlineCriticalCss` by default for better SSR performance

src/app/core/data/feature-authorization/authorization-data.service.spec.ts, src/app/core/data/feature-authorization/authorization-data.service.ts
* Fixes #3045
Because in PR #2725 all `RequestParam` values were encoded, and that the self link don't encode all the characters (for example it doesn't encode slashes and colons) it causes the frontend to think that the links are not identical. To fix this issue now the uri parameter is simply not encoded in angular so that it doesn't complain about this issues anymore, this was how it was done before PR #2725. The ideal fix would be to fix this in the backend but this might require more changes in the core of DSpace, so we should probably wait until after the 8.0 release for that in order to have enough time to test everything. [This is an example](https://sandbox.dspace.org/server/api/discover/search/objects?f.author=%2F,equals) of another endpoint where the same behaviour can be …
=> Fix self link don't match warnings for authorization endpoint

src/app/shared/search/search-filters/search-filter/search-authority-filter/search-authority-filter.component.html, src/app/shared/search/search-filters/search-filter/search-facet-filter/search-facet-filter.component.ts, src/app/shared/search/search-filters/search-filter/search-hierarchy-filter/search-hierarchy-filter.component.html, src/app/shared/search/search-filters/search-filter/search-text-filter/search-text-filter.component.html
Hi @tdonohue, I'm @jtimal partner. We have been working on this issue and we will send you the PR.
* Fixes #2352
Validation for hide search text field in the filter section if the number of facet values does not exceed the maximum number of facet values shown
The change is applied in the filters: Subject, Item Type and Authors
For replicate, you realize a general search and  select a filter with few results or search directament a term with few filter
For example, this is the view general
this is the same view with a filter wit few results:
* First, the main change is applied in: search-facet-filter.component.ts  
* Second, i created a validation for control  for show or not, considering the maximum number of facet and the current number of facet and assign in …
=> Hide search text field when number of facet values is less than the maximum

src/app/core/submission/workspaceitem-data.service.spec.ts, src/app/core/submission/workspaceitem-data.service.ts
* Fixes #2923
Fixed user redirect after creating a new version of an item. Replaced the old method `this.getIDHref()` with `this.searchData.getSearchByHref()`.
* Implemented new solution inside method `findByItem()`;
* Changed tests.
**To Test**:
- Connect as administrator;
- Find and open an item in the repository;
- Click on the new version button in the upper left of the page;
- Add text to describe the version and then click on Create;
- Want a few seconds, a confirmation message appears: New version has been created with version number 2;
- The new version submission form is displayed.
=> #2923 - Fixed redirect on new Item version creation

src/app/shared/page-size-selector/page-size-selector.component.html, src/app/shared/search/search-settings/search-settings.component.html, src/app/shared/sidebar/sidebar-dropdown.component.html, src/app/shared/sidebar/sidebar-dropdown.component.ts
* Fixes #2996
This was simply caused because the `EventEmitter` in `SidebarDropdownComponent` used a name that is used as a standard DOM event. This caused the emit to occur multiple times and break the page
=> Fixed page size change and sorting not working on comcol pages

src/app/core/data/base/delete-data.spec.ts, src/app/core/data/base/delete-data.ts, src/app/item-page/edit-item-page/item-delete/item-delete.component.html, src/app/item-page/edit-item-page/item-delete/item-delete.component.ts, src/app/item-page/full/full-item-page.component.spec.ts, src/app/item-page/full/full-item-page.component.ts, src/app/item-page/item-page.resolver.spec.ts, src/app/item-page/item-page.resolver.ts, src/app/item-page/simple/item-page.component.spec.ts, src/app/item-page/simple/item-page.component.ts
* Fixes #3068
Fixed performance issues that cause the delete item page to completely break when it has relationships. This was because it subscribed to functions returning Observables. While fixing this bug I also saw that accessing an edit item page with an invalid ID would not redirect you to the 404 page so I also fixed this. Also fixed the issue that prevented the user from being redirected when selecting some virtual metadata to copy
* Fixed the delete item page completely freezing by creating two new DTO classes: `RelationshipTypeDTO` & `RelationshipDTO`. Theses classes will contain all the `Observable`s that are needed in the HTML template. By saving this in one object we prevent resubscribing to all those observables every time change detection is …
=> Fixed delete item page freezing when having relationships

src/app/core/data/base/identifiable-data.service.spec.ts, src/app/core/data/base/identifiable-data.service.ts, src/app/core/data/version-history-data.service.spec.ts, src/app/core/data/version-history-data.service.ts, src/app/core/submission/workflowitem-data.service.ts, src/app/shared/dso-page/dso-versioning-modal-service/dso-versioning-modal.service.ts, src/app/shared/mydspace-actions/claimed-task/approve/claimed-task-actions-approve.component.spec.ts, src/app/shared/mydspace-actions/claimed-task/approve/claimed-task-actions-approve.component.ts, src/app/submission/objects/submission-objects.effects.spec.ts, src/app/submission/objects/submission-objects.effects.ts, src/assets/i18n/bn.json5, src/assets/i18n/ca.json5, src/assets/i18n/en.json5, src/assets/i18n/es.json5, src/assets/i18n/fr.json5, src/assets/i18n/gd.json5, src/assets/i18n/hu.json5, src/assets/i18n/it.json5, src/assets/i18n/kk.json5, src/assets/i18n/pt-BR.json5, src/assets/i18n/pt-PT.json5, src/assets/i18n/sv.json5
Manual port of #2761 by @ybnd  to `dspace-7_x`
=> [Port dspace-7_x] Fix caching issues for versioning 

src/app/app.component.ts, src/app/core/data/object-updates/object-updates.reducer.ts, src/app/core/data/object-updates/object-updates.service.ts, src/app/core/data/relationship-data.service.ts, src/app/item-page/edit-item-page/abstract-item-update/abstract-item-update.component.ts, src/app/item-page/edit-item-page/item-bitstreams/item-bitstreams.component.html, src/app/item-page/edit-item-page/item-relationships/edit-item-relationships.service.spec.ts, src/app/item-page/edit-item-page/item-relationships/edit-item-relationships.service.ts, src/app/item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.html, src/app/item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.spec.ts, src/app/item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.ts, src/app/item-page/edit-item-page/item-relationships/edit-relationship/edit-relationship.component.ts, src/app/item-page/edit-item-page/item-relationships/item-relationships.component.html, src/app/item-page/edit-item-page/item-relationships/item-relationships.component.spec.ts, src/app/item-page/edit-item-page/item-relationships/item-relationships.component.ts, src/app/item-page/edit-item-page/virtual-metadata/virtual-metadata.component.html, src/app/item-page/edit-item-page/virtual-metadata/virtual-metadata.component.spec.ts, src/app/item-page/edit-item-page/virtual-metadata/virtual-metadata.component.ts, src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/dynamic-lookup-relation-modal.component.html, src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/dynamic-lookup-relation-modal.component.ts, src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/search-tab/dynamic-lookup-relation-search-tab.component.ts, src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/search-tab/themed-dynamic-lookup-relation-search-tab.component.ts, src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/selection-tab/dynamic-lookup-relation-selection-tab.component.ts, src/app/shared/testing/base-data-service.stub.ts, src/app/shared/testing/edit-item-relationships.service.stub.ts, src/app/shared/testing/entity-type-data.service.stub.ts, src/app/shared/testing/item-data.service.stub.ts, src/app/shared/testing/object-updates.service.stub.ts, src/app/shared/testing/relationship-data.service.stub.ts, src/assets/i18n/en.json5
* Fixes #2978
* Fixes #1511
* Fixes #2998
* PR for 7.x: #3059
This component fixes various bugs related to the `Edit Item > Relationships` tab. This PR fixes the bugs preventing  relationships to be created, adds support for adding relationships between the same type of entities and it also fixes the bug where removing a relationship while explicitly saying that you want to keep the virtual metadata as plaintext metadata fields.
* Moved all the logic to create the relationships and display the success/ error notifications to `EditItemRelationshipsService`
* Fixed multiple bugs in `EditRelationshipListComponent` that prevented the `submitModal` to emit (which caused the modal never to close after clicking save)
* Added support for same entity type relationships …
=> Fixed creation & deletion of relationships not working correctly & added same entity type relationship support

src/app/access-control/group-registry/group-form/members-list/members-list.component.html, src/app/access-control/group-registry/group-form/members-list/members-list.component.spec.ts, src/app/access-control/group-registry/group-form/members-list/members-list.component.ts, src/app/core/eperson/eperson-data.service.ts, src/app/item-page/edit-item-page/modify-item-overview/modify-item-overview.component.spec.ts, src/app/item-page/edit-item-page/modify-item-overview/modify-item-overview.component.ts, src/app/shared/mydspace-actions/claimed-task/abstract/claimed-task-actions-abstract.component.ts, src/app/shared/mydspace-actions/claimed-task/approve/claimed-task-actions-approve.component.ts, src/app/shared/mydspace-actions/claimed-task/decline-task/claimed-task-actions-decline-task.component.ts, src/app/shared/mydspace-actions/claimed-task/edit-metadata/claimed-task-actions-edit-metadata.component.ts, src/app/shared/mydspace-actions/claimed-task/rating/advanced-claimed-task-action-rating.component.ts, src/app/shared/mydspace-actions/claimed-task/reject/claimed-task-actions-reject.component.ts, src/app/shared/mydspace-actions/claimed-task/return-to-pool/claimed-task-actions-return-to-pool.component.ts, src/app/shared/mydspace-actions/claimed-task/select-reviewer/advanced-claimed-task-action-select-reviewer.component.ts, src/app/shared/mydspace-actions/claimed-task/switcher/claimed-task-actions-decorator.ts, src/app/workflowitems-edit-page/advanced-workflow-action/advanced-workflow-action-select-reviewer/reviewers-list/reviewers-list.component.spec.ts, src/app/workflowitems-edit-page/advanced-workflow-action/advanced-workflow-action-select-reviewer/reviewers-list/reviewers-list.component.ts, src/app/workflowitems-edit-page/workflow-item-action-page.component.ts
* Fixes #3031
Fixed issue causing advanced workflow actions returning in a 404 page and fixed issues with `ReviewersListComponent` not working correctly anymore after the `MembersListComponent` page [refactor](https://github.com/DSpace/dspace-angular/commit/1f15b21ba969dafb5a86f264e33044b36d0a3138).
- Fixed `ADVANCED_WORKFLOW_TASK_OPTION_DECORATOR_MAP` having incorrect option key (this caused the 404 issue)
- Changed the `ePeopleMembersOfGroup` back to `BehaviorSubject<PaginatedList<EpersonDtoModel>>` because the first `<table>` of `members-list.component.html` is used to display all the users of the `Reviewers` group so the option to select & unselect a member should exist there. In the future it would maybe be better to add support to provide the `group` …
=> Fix advanced workflows throwing 404

src/app/item-page/simple/field-components/specific-field/item-page-field.component.ts, src/app/item-page/simple/metadata-representation-list/metadata-representation-list.component.ts
Manual port of #2953 by @atarix83 to `dspace-7_x`
=> [Port dspace-7_x] Avoid metadata representation element is rendered twice when checking the browse configuration

src/app/item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.ts
* Fixes DSpace/dspace-angular#1387
* Requires DSpace/DSpace#9621
Fixes the item edit relationships tab showing relationships under multiple labels when those relationship types have the same `leftwardType`/`rightwardType` (but different entity types).
* Passed the `relatedEntityType` to the request to retrieve the relationships of each individual relationship section
**Guidance for how to test/review this PR:** See DSpace/dspace-angular#1387
=> Fixed item edit relationships with same type name but different entities all being shown under same label

src/app/item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.ts
Manual port of #3098 by @alexandrevryghem to `dspace-7_x`
=> [Port dspace-7_x] Fixed item edit relationships with same type name but different entities all being shown under same label

src/app/core/data/relationship-data.service.spec.ts, src/app/core/data/relationship-data.service.ts, src/app/item-page/edit-item-page/item-relationships/edit-item-relationships.service.spec.ts, src/app/item-page/edit-item-page/item-relationships/edit-item-relationships.service.ts, src/app/item-page/edit-item-page/item-relationships/edit-relationship-list-wrapper/edit-relationship-list-wrapper.component.html, src/app/item-page/edit-item-page/item-relationships/edit-relationship-list-wrapper/edit-relationship-list-wrapper.component.spec.ts, src/app/item-page/edit-item-page/item-relationships/edit-relationship-list-wrapper/edit-relationship-list-wrapper.component.ts, src/app/item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.spec.ts, src/app/item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.ts, src/app/item-page/edit-item-page/item-relationships/edit-relationship/edit-relationship.component.ts, src/app/item-page/edit-item-page/item-relationships/item-relationships.component.html, src/app/item-page/edit-item-page/item-relationships/item-relationships.component.ts, src/app/item-page/simple/item-types/shared/item-relationships-utils.ts, src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/dynamic-lookup-relation-modal.component.html, src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/dynamic-lookup-relation-modal.component.spec.ts, src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/dynamic-lookup-relation-modal.component.ts, src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/search-tab/dynamic-lookup-relation-search-tab.component.html, src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/search-tab/dynamic-lookup-relation-search-tab.component.ts, src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/search-tab/themed-dynamic-lookup-relation-search-tab.component.ts, src/app/shared/search/search.component.spec.ts, src/app/shared/search/search.component.ts, src/app/shared/search/themed-search.component.ts
* Fixes last remaining bugs noticed during #3060
* Backport PR #3109
This PR fixes 2 remaining bugs. A caching issue where the selected status of the relationship popup modal would stay cached even after deleting a relationship. And also an issue where only one side of the same entity type relationship would be shown on the edit item relationship page (for example both `isDepartmentOfDivision` & `isDivisionOfDepartment` should be shown). It also hides the item you are currently on in the search results of the popup modal.
* When removing a relationship the item you are on is invalidated, but the item on the other side of the relationship wasn't, so this has now been fixed in `EditItemRelationshipsService#submit`
* Every search request in the relationship popup …
=> Fixed caching & same entity type relationship with different left/rightwardtype bugs on edit item relationships

src/app/shared/menu/menu-item/link-menu-item.component.html
* Fixes #2957 
Follow the steps described in the related issue using different browsers (Chrome, Firefox, Edge, Safari) and check if the error still exists. 
* Changed key-listener to keydown in order to work on chrome browsers.
=> Fixes: Site hangs when selecting items via keyboard from the hamburger menu

src/app/shared/loading/loading.component.html
* Fixes ID 469022 in #1175
* Based on research, This change arose from the need to make the ds-loading component more accessible, and was addressed in issue #1175.
In the ds-loading component I added the attribute aria-live=“polite” to the label and to the div containing the “spinner” conditional. In the div containing the “loading balls” I added the attribute aria-hidden=“true”. Based on my research, the aria-live=“polite” attribute tells screen readers that dynamic content can be updated, but is not urgent. This is useful for status messages or informational updates that don't require immediate interruption. And the aria-hidden=“true” attribute hides non-relevant content from screen readers. Such as spans within the loader that have no useful information.
These changes improve the …
=> Improving accessibility of the ds-loading component

src/styles/_custom_variables.scss, src/styles/_global-styles.scss
* Partial Fix for #2668
* Replaces PR #https://github.com/DSpace/dspace-angular/pull/2715 
For resolve comments on PR Cookie setting menu accessibility bug fixed
* Added --green1 variable style to change the background color on cookie settings
* Added --green1 in color for  hyperlink
* Text color as dark in the accept button
Using the util : https://webaim.org/resources/contrastchecker/, i found the color constrast for color `#333 `
And edit the var color implemented by former by  PR mentioned, getting the following
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't …
=> Fix - Change color Contrast in cookie settings box

src/app/bitstream-page/bitstream-page-routes.ts, src/app/collection-page/edit-collection-page/collection-source/collection-source.component.html, src/app/collection-page/edit-collection-page/collection-source/collection-source.component.ts, src/app/item-page/edit-item-page/abstract-item-update/abstract-item-update.component.ts, src/app/item-page/edit-item-page/item-bitstreams/item-bitstreams.component.ts, src/app/shared/trackable/abstract-trackable.component.spec.ts, src/app/shared/trackable/abstract-trackable.component.ts
Fixes #3116
Manual port of #3121 to`main`.
Also contains a fix for the bitstream routing module sometimes complaining about `Error: NG04014: Invalid configuration of route 'bitstreams/handle/:prefix/:suffix/:filename'. One of the following must be provided: component, loadComponent, redirectTo, children or loadChildren`
=> [Port main] Remove Bitstreams on edit-item-page doesn't work

src/assets/i18n/en.json5
All OpenAIRE searches return…publications
* Related to https://github.com/DSpace/DSpace/pull/9631
* Updates i18n keys added in #2979 
This small PR makes minor updates to the OpenAIRE i18n keys added in #2979.
While working on https://github.com/DSpace/DSpace/pull/9631, I realized the previous i18n keys were misleading.  When searching OpenAIRE via external sources, the results returned are **always** publications/articles.  So, i18n keys like "OpenAIRE Authors" were misleadingly suggesting you might receive *author/person* results.
Keys have been updated to instead say: "OpenAIRE Search by Authors", "OpenAIRE Search by Title", etc.
* No code was changed, just i18n keys
* Review the key changes, and if desired, test them by trying to import metadata via OpenAIRE as described in …
=> Minor updates to i18n text for OpenAIRE external sources. 

src/assets/i18n/ar.json5, src/assets/i18n/ca.json5, src/assets/i18n/cs.json5, src/assets/i18n/el.json5, src/assets/i18n/en.json5, src/assets/i18n/es.json5, src/assets/i18n/fi.json5, src/assets/i18n/fr.json5, src/assets/i18n/hi.json5, src/assets/i18n/hu.json5, src/assets/i18n/it.json5, src/assets/i18n/kk.json5, src/assets/i18n/pl.json5, src/assets/i18n/pt-BR.json5, src/assets/i18n/pt-PT.json5, src/assets/i18n/sr-cyr.json5, src/assets/i18n/sr-lat.json5, src/assets/i18n/vi.json5
As part of a rebranding in 2015 Crossref started stylizing their name as "Crossref" instead of "CrossRef".
See: https://www.crossref.org/blog/the-logo-has-landed/
* Rename "CrossRef" in i18n strings
* Make sure "Crossref" is displayed in the user interface instead of "CrossRef" (for example, on the MyDSpace import from external sources page)
=> src/assets/i18n: CrossRef → Crossref

src/app/core/json-patch/json-patch-operations.reducer.spec.ts, src/app/core/json-patch/json-patch-operations.reducer.ts, src/app/core/submission/submission-parent-breadcrumb.service.ts, src/app/core/submission/submission-rest.service.ts, src/app/submission/sections/upload/section-upload.component.ts
* Fixes #3050
* Fixes #3136
* Fixes #3137 
This PR fixes the mentioned issues.
Regarding the #3050 the problem was due a wrong order the replace and add patch operation were sent with the patch request.
It depends on two aspects:
- firstly the date field has a different handling of the patch operation according to the way the field is edited. Indeed when clicking on the arrows button an add operation is always sent regardless a previous value exists for the date. Whereas when the field is edited by entering a value manually a replace operation is sent when the date already have a value
- the other problem found is that recently we introduced an optimization to avoid to send several patch operations of the same type (e.g add, replace, delete etc) all referring to the same metadata in order …
=> Fix error which prevent submitter to deposit a new item

src/app/core/json-patch/json-patch-operations.reducer.spec.ts, src/app/core/json-patch/json-patch-operations.reducer.ts, src/app/core/submission/submission-parent-breadcrumb.service.ts, src/app/core/submission/submission-rest.service.ts
Manual port of #3138 by @atarix83 to `dspace-7_x`
NOTE: This only contains 2 of the 3 commits. It fixes both #3050 and #3136 for 7.x. (The third bug did NOT impact 7.x)
=> [Port dspace-7_x] Fix error which prevent submitter to deposit a new item

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md, CONTRIBUTING.md
This PR adds minor changes to our contribution docs & PR template:
* Adds a requirement to align with Accessibility guidelines
* Adds a requirement to use i18n keys
* Adds a requirement to **provide details on how to test PRs**.  (I've noticed that some developers do this better than others. It really is a **requirement** as we don't have a large pool of reviewers at this time)
These requirements are being MOVED from https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-ContributionChecklist  The goal is to minimize duplication, and move this checklist entirely to GitHub
This PR also makes minor changes to issue templates.  Namely, it changes bold text into headers to make these issues a bit more readable. (Sections in the issue ticket are better …
=> [GitHub Config] Minor updates to Contribution docs & issue/PR templates

src/app/core/forward-client-ip/forward-client-ip.interceptor.ts
* Fixes #2902
Forward the client's user-agent instead of Node's. Code by @mark-cooper in https://github.com/DSpace/dspace-angular/issues/2902#issuecomment-2067342387.
* Adjust `forward-client-ip` component to also forward the client's user-agent along with the client's IP
*Note: there was a small discussion about whether to rename the `forward-client-ip` component to `forward-client-headers` and the consensus seemed to be that it was not important for 7.x and 8.x, but maybe we can do that for 9.0.*
To see the client headers you must look in the web server logs, which mean you must run the modified code on a server which has a full set up like Apache HTTPD or Nginx etc. Where before you would see Node.js's …
=> Forward client's user-agent instead of Node's

docker/README.md, docker/docker-compose-rest.yml
Changes in Docker syntax to be Docker V2 compliant. Change "docker-compose" command to "docker compose".
=> Docker compose syntax changes

src/app/dso-shared/dso-edit-metadata/dso-edit-metadata.component.html
* Fixes #1193
Addition of the "aria-label" attribute to the add, save, discard and undo buttons on the metadata editing page to ensure that they are "visible" to screen readers, even when the CSS is completely disabled.
* The html of the dso-edit-metadata component has been changed.
* The "aria-label" attribute has been added to all the buttons in the component.
* The translation key used in the "title" of each button has been used for "[attr.aria-label]".
To reproduce:
* Log in to dspace as an administrator.
* Go to an item and click on the edit button.
* Go to the "Metadata" section.
* Check the page with an accessibility tool.
=> Accessibility on the Edit metadata tab

src/app/shared/cookies/klaro-configuration.ts
* Fixes #3145 for DSpace 7
Declining the Google reCaptcha cookies, would also make it impossible to save the Klaro preferences cookies themselves because of an incorrect regex added to its configuration. This would mean that your Klaro cookie preferences were automatically removed when declining the Google reCaptcha cookies. This bug was likely the result of copy-pasting previous configurations.
1. Make sure your Google ReCaptcha key is configured in the backend
2. Open a new window where your cookie preferences aren't saved yet (new incognito/private window)
3. a. Click 'Decline' on the cookie pop-up
OR
b. 'Customize' and then 'Accept selected', and make sure the 'Registration and Password recovery' is disabled on the cookies pop-up
4. Refresh the page 
5. The Klaro cookies pop-up should …
=> [Port dspace-7_x] Fixed bug when declining Google ReCaptcha cookie preferences

src/app/info/feedback/feedback-form/feedback-form.component.html, src/app/shared/cookies/klaro-configuration.ts
* Fixes #3145
* Port for 7.x: #3147
Declining the Google reCaptcha cookies, would also make it impossible to save the Klaro preferences cookies themselves because of an incorrect regex added to its configuration. This would mean that your Klaro cookie preferences were automatically removed when declining the Google reCaptcha cookies. This bug was likely the result of copy-pasting previous configurations.
1. Make sure your Google ReCaptcha key is configured in the backend
2. Open a new window where your cookie preferences aren't saved yet (new incognito/private window)
3. a. Click 'Decline' on the cookie pop-up
OR
b. 'Customize' and then 'Accept selected', and make sure the 'Registration and Password recovery' is disabled on the cookies pop-up
4. Refresh the page 
5. The Klaro cookies …
=> Fixed bug when declining Google ReCaptcha cookie preferences

Dockerfile.dist
This PR fixes a warn message that occurs when the Docker image is being built:
```
=> WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match
```
=> Docker build: fix FromAsCasing warning

src/app/core/shared/client-math.service.ts, src/app/core/shared/math.service.spec.ts, src/app/core/shared/math.service.ts, src/app/core/shared/server-math.service.ts, src/app/shared/utils/markdown.directive.ts
* Fixes #3111
With this PR, LaTeX formulas are rendered with mathjax before any markdown rendering is applied. This fixes unwanted behaviors described on the linked issue.
* Applied mathjax rendering before markdown rendering (if mathjax is enabled);
* Removed `nativeWindow` injection in `client-math.service` (since it's a Client-Side-Rendering service, there is no need to use the injection);
* Included the popular LaTeX `$$` delimiter in the list of approved delimiters.
To test this PR, try to use this text in any place where the markdown rendering is enabled:
`...measurements in (EDT-TTF-CONH$_2$)$_2^{+}$[BABCO$^{-}$] (EDT-BCO) confirmed the absence...`.
It should render fine, instead of showing a broken formula and some italic text.
=> [#3111] fix markdown rendering applying before mathjax rendering

src/app/shared/upload/file-dropzone-no-uploader/file-dropzone-no-uploader.component.html, src/app/shared/upload/file-dropzone-no-uploader/file-dropzone-no-uploader.scss
* Fixes #3189
The “position-fixed” bootstrap class in the html of the “ds-file-dropzone-no-uploader” component was getting in the way of the navbar links.
* The bootstrap class “position-fixed” on lines 2 and 9 in the html of the “ds-file-dropzone-no-uploader” component has been removed.
To reproduce:
1. Log in to DSpace as an administrator.
2. Reveal the left-hand sidebar menu, click Import and then click either Metadata or Batch Import (ZIP).
3. See that the navigation links in the header are available again.
=> Enabling navbar links in import section

src/app/shared/upload/file-dropzone-no-uploader/file-dropzone-no-uploader.component.html, src/app/shared/upload/file-dropzone-no-uploader/file-dropzone-no-uploader.component.ts
* Fixes #3219
Resolution of the following problem: the code may have tried to set the value of the file input field directly or was linked incorrectly to ngModel. This led to errors because browsers do not allow the value of a file field (<input type="file">) to be set programmatically for security reasons.
Changes made to the "ds-file-dropzone-no-uploader" component:
* Removal of ngModel from the file input field.
* Modification of "EventEmitter" in "@Output() onFileAdded".
* Correction of the onDrop and onDragOver methods making use of events (change, drop, dragover) to manipulate files and the state of the drag and drop area.
* Addition of event.stopPropagation() to control the behavior of drag and drop events.
* Creation of the handleFileInput method to correctly process file …
=> Improving the file browser for importing metadata

src/app/workspaceitems-edit-page/workspaceitems-edit-page-routes.ts
This PR removes a duplicated `/delete` route in `WorkspaceitemsEditPageModule`.
=> WorkspaceitemsEditPageModule: remove duplicated delete route

src/app/shared/search/search-filters/search-filter/search-range-filter/search-range-filter.component.html, src/app/shared/search/search-filters/search-filter/search-range-filter/search-range-filter.component.ts
* #3094 
* Updated the slider implementation in `SearchRangeFilterComponent` to comply with WCAG 2.1 Success Criterion 3.2.2 (On Input). This improvement ensures that slider value changes no longer trigger automatic page reloads, enhancing user control over when context changes occur.
* **Updated Slider Event Handling**: Replaced `(onDebounce)="onSubmit()"` with `(change)="onSliderChange($event)"` to prevent automatic page reloads when slider values change. This ensures users have control over when the page context updates.
* **Refactored Form Submission**: Decoupled slider value updates from form submission, allowing users to submit changes only when they choose, thus preventing unintended context changes.
* **Enhanced User Control**: By separating slider …
=> #3094 - Update date slider to prevent automatic page reloads

src/app/notifications/suggestion-targets/publication-claim/publication-claim.component.ts
* Follow up to #3048
After merging #3048, `main` is now throwing this lint error:
```
/home/runner/work/dspace-angular/dspace-angular/src/app/notifications/suggestion-targets/publication-claim/publication-claim.component.ts
Lint errors found in the listed files.
Error:   110:3  error  Lifecycle interface 'AfterViewInit' should be implemented for method 'ngAfterViewInit'. (https://angular.io/styleguide#style-09-01)  @angular-eslint/use-lifecycle-interface
```
This small PR fixes that error
=> Fix lint error regarding missing interface

src/app/item-page/simple/related-entities/tabbed-related-entities-search/tabbed-related-entities-search.component.html, src/app/navbar/expandable-navbar-section/expandable-navbar-section.component.html, src/app/shared/form/vocabulary-treeview/vocabulary-treeview.component.html
These are minor fixes that were required in order to fix some issues regarding accessibility on the item page & the browse controlled vocabulary page.
In order to detect these issues we used [Silktide](https://silktide.com/)
* Fixed issues where the search tabs on the item pages didn't have the correct roles (only an issue when multiple tabs are available)
* Removed id `browseDropdown` from `ExpandableNavbarSectionComponent`, since it's not used anywhere an that component is also not meant to be browse specific. This caused a duplicate id issue when you used 2 expandable secitons in your navbar
* Fixed missing label for the search input field on the browse by controlled vocabulary pages
=> Minor accessibibity fixes

src/assets/i18n/de.json5
* Fixes https://github.com/DSpace/dspace-angular/issues/3259
A Typo has been fixed  in the German translation
=> Typo in German translation

src/app/shared/search/search-filters/search-filter/search-filter.component.html
Hi @tdonohue, I'm @jtimal partner, I like to share this PR with you:
* Fixes #2682
I change the color for the text in the section of filters on search view
I used tailwind for fix that bug and i was able replicated that bug on emulator IOS using Iphone 14 PRO MAX
* First set color black default on text in filter section
* Second set color white default on text in filter section when the phone has mode dark on, this validation was by tailwind
Evidences:
Bug replicated
Fix applicated
=> Set color black on filter section for mobile

src/app/item-page/versions/item-versions.component.html
* Fixes #3252
This PR removes the method calls from the template that return Observables causing an infinite rerendering of the page.
* Created a `VersionsDTO` containg all the data that is required to render the template in order to prevent the infinite recreation of the `canEditVersion` `Observable`.
Test that everything still work correctly on the item page & the edit item version history tab both for items with and without any versions.
=> Fixed Edit Item's Version History crashing

src/assets/i18n/en.json5
Supplements: https://github.com/DSpace/DSpace/pull/9639#pullrequestreview-2270236552
Provided error label for https://github.com/DSpace/DSpace/pull/9639
Provided error label 
- [x ] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- x[ ] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [ x] My PR **passes [ESLint](https://eslint.org/)** validation using `yarn lint`
- [x ] My PR **doesn't introduce circular dependencies** (verified via `yarn check-circ-deps`)
- [ x] My PR **passes all specs/tests and includes new/updated specs or tests** based on the [Code Testing …
=> Provided label for cclicense required error

webpack/webpack.browser.ts
Watching all these directories can cause systems to exceed maximum watched files / inotify limits, especially in dev mode with IDEs etc also watching files.
I've included node_modules, and some basic vcs and project dirs that should be excluded.
```
watchOptions: {
// Ignore directories that should not be watched for recompiling angular
ignored: [
'**/node_modules', '**/_build', '**/.git', '**/docker',
'**/.angular', '**/.idea', '**/.vscode', '**/.history', '**/.vsix'
]
},
```
It's actually not super trivial to 'see' watched files, but if you can reproduce the underlying issue (get your system into a state where inotify limit is exceeded), then you can run with and without this change, and review any errors listed, to see whether the file watcher is _attempting_ to watch e.g. node_modules …
=> Ignore some paths from file watcher

src/modules/app/browser-init.service.ts
Page content and admin menu weren't updating correctly after Shibboleth authentication. The change here forces the browser app to request fresh content after obtaining an auth token.
* Fixes #1953 and #1665
Changes in 7.6.1 reintroduced the bugs reported in #1953 and #1665.  This PR implements the original step of setting all of cached objects stale. Unfortunately, I was only able to test this on a production 7.6.1 instance but it should work with 8.0 as well.
Testing with Shibboleth has become more difficult since https://samltest.id/ is no longer available. If anyone has a test instance running with Shib that would be a great help. 
* Updated the browser init service to call requestSerice.setStaleByHrefSubstring() directly rather than via the root data …
=> Fixed page and admin menu for Shibboleth auth

package.json, yarn.lock
Manual port of #3318 to `dspace-8_x`.  I've already tested this locally and it seems to work fine in 8.x
=> [Port dspace-8_x]  Bump body-parser and express

.github/workflows/build.yml, package.json, server.ts, yarn.lock
Manual port of #3329 to `dspace-7_x`.
**Note that the minimum supported version of Node.js is now v18 LTS, as the [previous v16 LTS is end of life](https://nodejs.org/en/about/previous-releases). We will need to update documentation for the DSpace 7.6.3 release. We might even want to update our CI for DSpace 7 to use v18 and v20.**
=> [Port dspace-7_x] updates isbot dependency to newest version

src/assets/i18n/en.json5
* Fixes #3330 
Changed 4 instances of 'occured' to 'occurred'. 
Fixed typos. Deploy PR and observe typo has been fixed.
=> DS-3330: Updated en.json5 to fixed typo for 'occurred'

src/app/shared/utils/markdown.directive.spec.ts, src/app/shared/utils/markdown.directive.ts
The markdown directive currently sets `this.el.innerHTML` directly to `value` if markdown is disabled in config and forcePreview is not set. This means unsanitized HTML can end up making its way into the `innerHTML` of an element when somebody uses the `[dsMarkdown]=....` directive.
This small pull request ensures the `innerHTML` is always sanitized.
New tests are included to prove this behaviour (the template is initialised with `test<script>alert(1)</script>` and we check that in all cases, the div innerHTML is equal only to `test`.
* Try to inject unsafe HTML in a `[dsMarkdown]` directive (you can do this via metadata value, or as a raw string), with both `environment.markdown.enabled` true, and false. In both cases HTML should be correctly sanitized.
* You should notice that in main …
=> Always sanitize HTML passed to dsMarkdown even if markdown rendering is disabled

src/app/thumbnail/thumbnail.component.html, src/app/thumbnail/thumbnail.component.spec.ts, src/app/thumbnail/thumbnail.component.ts
* Fixes #3134
This PR removes the unnecessary `*ngVar`s in the `ThumbnailComponent`. When you disable caching and you run dspace in prod mode you will still be able to see that the content is retrieved twice, but this can't be avoided. The first time it is triggered by the SSR and the second time by CSR. We can't change that, but we should still remove the `*ngVar`s since they are actually not necessary and `*ngVar`s also trigger `fixture.detectChanges()` every time there is interaction with the template so that's not really good for performance.
We actually don't need those `BehaviourSubject`s because we don't subscribe to them except in the template, so I just converted them back to regular string/boolean fields. Everything should still work like they did before.
=> Removed unnecessary *ngVars from ThumbnailComponent

cypress.config.ts, cypress/e2e/item-edit.cy.ts, cypress/e2e/login-modal.cy.ts, cypress/support/commands.ts, package-lock.json, package.json
* Replaces #3309 (created by @dependabot)
Upgrades us to Cypress 13.15.0 which also resolves a security alert related to Cypress v12  (NOTE: This alert doesn't impact production as Cypress is only used to run e2e tests.)
In addition to the Cypress upgrade, the following minor changes were made to ensure better e2e test stability:
* Updates to `item-edit.cy.ts` to check that the proper tab is active.  This solves some random e2e failures which were occurring when an accessibility scan was triggered *before* the tabs were fully loaded on the page.  This check forces Cypress to wait for the tabs to appear before proceeding.
* Updates to `login-modal.cy.ts` to fix a minor bug & to simplify the CSS selectors.
* Updates to `command.ts` to simplify CSS selectors.  (The CSS selector cleanup here …
=> Upgrade to Cypress 13.15.0

package.json, yarn.lock
Manual port of https://github.com/DSpace/dspace-angular/pull/3343 to dspace-7_x
Does NOT include a bump of `browser-sync` as that's not defined as a dependency in dspace-7_x.
=> [Port dspace-7_x] Bump send, express and serve-static

src/app/shared/browse-by/browse-by.component.spec.ts, src/app/shared/browse-by/browse-by.component.ts
* Fixes #3408
* Related #2832
Fixes the browse by date's year dropdown not always showing the available years. This bug was caused by #2832 since it was only a partial port #2722 to `dspace-7_x`. This fix is not required for DSpace 8.0+ since it has already been fixed there during the refactor with a more appropriate fix (https://github.com/DSpace/dspace-angular/commit/6e29f306a75fd04dd5bdb5086eafd264f3259692) that can't be backported since it would require PR #2339 to be backported as well.
* Moved the initialization of the `objectInjector` to `ngOnChanges`, in order to assure that the `StartsWithDateComponent` is re-rendered when one of the injector parameters is updated.
=> Fix browse by date's year dropdown being empty on DSpace 7.6.2+

yarn.lock
* This is a PR from @dependabot generated in the https://github.com/DSpace-Labs/dspace-angular-8x/ repo (used to visualize security issues in `dspace-8_x`).  See https://github.com/DSpace-Labs/dspace-angular-8x/pull/1
* This PR is a follow-up to #3324 , which didn't update `body-parser` completely.
Bumps [body-parser](https://github.com/expressjs/body-parser) from 1.20.2 to 1.20.3.
- [Release notes](https://github.com/expressjs/body-parser/releases)
- [Changelog](https://github.com/expressjs/body-parser/blob/master/HISTORY.md)
- [Commits](https://github.com/expressjs/body-parser/compare/1.20.2...1.20.3)
=> [dspace-8_x] Bump body-parser from 1.20.2 to 1.20.3

.github/dependabot.yml
Create dependabot.yml.  Add an initial configuration which does the following:
* Checks for dependency updates weekly.  Automatically creates PRs for non-major updates (i.e. minor and patch only)
* Configures groups for Angular & NgRx updates to ensure these dependencies are updated together in a single PR.  (Otherwise, dependabot will attempt to send a PR per dependency)
* Enables dependabot also on `dspace-8_x` and `dspace-7_x` branches (currently, all branches have identical settings)
References
* https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/customizing-dependency-updates
* https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates#enabling-dependabot-version-updates
I don't believe there is …
=> Configure Dependabot to also attempt minor/patch updates for dependencies

cypress/e2e/collection-page.cy.ts
Frequently, the `collection-page.cy.ts` is failing because the e2e test times out before the Collection Page fully loads.  This simply updates the test to wait on the list of Recent Submissions before performing any other tests.
* If e2e tests succeed, I'll merge this immediately.  This failure is occurring frequently on the 7.x branch (only)
=> [dspace-7_x] Fix Collection Page e2e test. Wait on Recent Submissions

cypress/e2e/header.cy.ts, src/app/shared/lang-switch/lang-switch.component.html
In testing the many `dependencies` related PRs from `dependabot`, I've realized that a common test that I perform manually (in some scenarios) is to simply check if i18n translations are still working (by using the globe in the UI header)
So, rather than do that manually, here's an e2e test that verifies the basics by checking that we can switch from English to German and back (and that everything works).
* This only involves e2e tests, so if the tests succeed, then this can be merged.
=> Add basic e2e testing for i18n

cypress/e2e/item-edit.cy.ts, cypress/e2e/item-page.cy.ts
After merging #3432 , the Item page e2e accessibility tests have gotten a bit more flakey.
This small PR attempts to fix them by forcing the e2e tests to wait for the Item page to fully load **before** running an accessibility scan on the page.
* If the e2e tests now fully pass, this was successful.  Otherwise this needs more work
=> [dspace-7_x] Fix flakey Item page accessibility tests by waiting for pages to fuly load

.github/dependabot.yml
Small PR to update our Dependabot rules with new groups for many major dependencies including:
* ESLint
* Testing (Jasmine, Karma, Cypress, etc)
* PostCss
* Sass
* Webpack
These same groups have been enabled for `main`, `dspace-8_x` and `dspace-7_x`
The goal is just to minimize the number of PRs created by Dependabot by ensuring updates to these dependencies are grouped into a single PR.  Often, this is the best approach, as when you update one dependency in this group, you usually have to update them all.
This PR is just to document the reasons for this change.  The only way to test it is to merge it.  Merging immediately.
=> Update dependabot.yml with new PR groups for eslint, testing dependencies, postcss, sass, webpack

angular.json, package.json, yarn.lock
While working with dependabot to update our `dependencies`, I realized that there are three dependencies that are entirely unused in our codebase (and don't appear to have any other dependencies that require them)
* sortablejs (previously used in reorder of subject terms in submission form.  Replaced in #2871 ?)
* sanitize-html (previously used in markdown code, but we now use Angular's built in sanitizer.)
* webfontloader (possibly used to load web fonts back when we used a Google font?  No longer used)
I've fully tested this locally, including submission forms, markdown, and theming.  No issues found.  
This needs to be ported to `main` and possibly to `dspace-7_x`.  I plan to do both, but they'll likely need to be done manually.
* Verify tests all still succeed.
* If desired, test the …
=> Remove unused dependencies (sortablejs, sanitize-html, webfontloader)

package-lock.json, package.json
Follow-up to #3511, which accidentally forgot to remove `@types/sanitize-html`.  
See also #3509 (the 8.x version) which removes `@types/sanitize-html` from `dspace-8_x`.  This change was supposed to be ported to `main` in #3511, but was accidently forgotten.
* This `@types/sanitize-html` dependency is only used in the dev environment for compilation, etc.  So, if this compiles & passes all tests, then it can be merged.
=> Remove unused `@types/sanitize-html` dependency

package.json, postcss.config.js, yarn.lock
Manual port of #3547 to `dspace-7_x`.  See details in that PR.
UPDATE: Tested this port PR manually & ensured there are no bugs introduced in 7.x themes.  No issues found.
=> [Port dspace-7_x] Remove unused PostCSS plugins

package.json, yarn.lock
Manual port of #3550 to `dspace-7_x`
=> [Port dspace-7_x] Bump http-proxy-middleware from 1.0.5 to 2.0.7

src/app/shared/upload/uploader/uploader.component.html
* Fixes #3426
Aligning the browse button to upload a file.
* In the “UploaderComponent” component, the “d-flex align-items-center” bootstrap classes were added to the span containing the text and the button to search for a file and upload it.
* To give spacing between the upload icon and the explanatory text, the “pr-1” class has been added.
To Reproduce:
1. Login.
2. Go to MyDSpace.
3. Note that the upload box at the top of the page now has all its elements aligned.
=> Aligning the browse button

package-lock.json, package.json, postcss.config.js
Several [PostCSS](https://postcss.org/) plugins are installed in DSpace but are unused.  Specifically:
* [`postcss-apply`](https://www.npmjs.com/package/postcss-apply)  (used via `@apply`...which is never used in our SCSS files)
* [`postcss-responsive-type`](https://www.npmjs.com/package/postcss-responsive-type) (used via `responsive`...which is never used in our SCSS files)
Because these are unused, I'm removing them completely.  Both of these plugins also rely on outdated versions of PostCSS.  So, removing them makes it much easier to upgrade PostCSS in the future.
* Ensure UI still compiles and passes tests
* Ensure themes still work.  I've already tested this manually and found no changes in behavior.
=> Remove unused PostCSS plugins

package-lock.json, package.json
* Fixes CVE-2024-21536
Bump `http-proxy-middleware` from 1.0.5 to 2.0.7.
Tested that v2.0.7 works well with DSpace.  
In the DSpace UI, this `http-proxy-middleware` is ONLY used for loading Sitemaps (e.g. `[dspace.ui.url]/sitemap_index.html` when generated) and Signposting (embedded in Item pages under `[dspace.ui.url]/signposting/*` URLs)
* Verify all automated tests pass
* If desired, test Sitemap and Signposting URLs (as described above).  I've tested both and they work well after this update
=> Bump http-proxy-middleware from 1.0.5 to 2.0.7

package.json, postcss.config.js, yarn.lock
Manual port of #3547 to `dspace-8_x`.  See details in that PR.
Tested this port PR manually & ensured there are no bugs introduced in 8.x themes.  No issues found.
=> [Port dspace-8_x] Remove unused PostCSS plugins

package.json, yarn.lock
Manual port of #3550 to `dspace-8_x`
=> [Port dspace-8_x] Bump http-proxy-middleware from 1.0.5 to 2.0.7

src/app/core/breadcrumbs/item-breadcrumb.resolver.ts, src/app/core/browse/browse.service.spec.ts, src/app/core/browse/browse.service.ts, src/app/core/cache/object-cache.reducer.ts, src/app/core/cache/object-cache.service.ts, src/app/core/data/dspace-rest-response-parsing.service.ts, src/app/core/data/relationship-data.service.spec.ts, src/app/core/data/relationship-data.service.ts, src/app/core/data/version-history-data.service.ts, src/app/core/index/index.effects.ts, src/app/home-page/recent-item-list/recent-item-list.component.ts, src/app/item-page/edit-item-page/abstract-item-update/abstract-item-update.component.ts, src/app/item-page/edit-item-page/item-delete/item-delete.component.ts, src/app/item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.ts, src/app/item-page/item-page.resolver.ts, src/app/item-page/item.resolver.ts, src/app/shared/form/builder/ds-dynamic-form-ui/ds-dynamic-form-control-container.component.ts, src/app/shared/utils/relation-query.utils.ts
* Fixes DSpace/DSpace#9316
* Partially solves #3163
* Fixes #2833
Reduced the number of requests sent to the backend by caching embedded null objects (this will prevent unnecessary thumbnail requests). Also added support for caching embedded objects without a self-link. (Credit for this PR goes to @Atmire-Kristof)
* Added support to cache `null` responses.
* Added support to cache embedded objects without `self` links.
* Embedded the `accessStatus` in places where a separate request was made.
**Guidance for how to test/review this PR:**
- On [demo](https://demo.dspace.org/), go to your network tab and select Item Type Publication. Verify that a lot of `thumbnail` and `accessStatus` requests are made.
- Perform the same action with this fix and verify that both …
=> Added support for caching embedded objects without a self link & null responses

src/app/register-email-form/register-email-form.component.html, src/app/register-email-form/register-email-form.component.spec.ts, src/app/register-email-form/register-email-form.component.ts, src/assets/i18n/en.json5, src/assets/i18n/es.json5, src/assets/i18n/pt-BR.json5
* Fixes ##3271
Use of the attributes “attr.aria-label”, “aria-describedby” and “attr.aria-invalid” to improve the user experience when browsing DSpace using a screen reader.
Use of the “attr.aria-label” attribute which provides a clear description of what the user needs to do in the email field. Use of the “aria-describedby” attribute which describes error messages and use of the “attr.aria-invalid” attribute which informs when a field is invalid.
* In the html the attributes attr.aria-label, aria-describedby and attr.aria-invalid have been added.
* Creation of ids in the spans that announce error messages to be used in the aria-describedby attribute.
Note: This PR does not deal with the accessibility of the “Register” button as there is already a PR dealing …
=> Improving accessibility on the new user registration page

src/assets/i18n/fr.json5
* Fixes partially  #3578 
Those french translations focus only on the ORCID module and Researcher Profile feature.
=> Complete tag translations in french for ORCID and Researcher Profile

src/app/bitstream-page/bitstream-authorizations/bitstream-authorizations.component.ts
Trivial RP that fixes an incorrect comment in `BitstreamAuthorizationsComponent`.
=> BitstreamAuthorizationsComponent: update selector and comment to correctly describe component's purpose

src/app/core/shared/metadata.utils.ts
This trivial PR fixes incorrect parameter names in JSDoc.
=> class `Metadata`: rename parameter names in JSDoc from `mapOrMaps` to `mdMapOrMaps`

src/app/shared/cookies/browser-klaro.service.spec.ts, src/app/shared/cookies/browser-klaro.service.ts, src/app/shared/cookies/klaro-configuration.ts
* Related to #2027 
* Broken since upgrade to Klaro 0.7.19. See https://github.com/klaro-org/klaro-js/issues/515
* Fixes #3618
After upgrading to Klaro 0.7.19 (or later), our custom message translations are no longer loading into Klaro.  This can be seen on both https://sandbox.dspace.org and https://demo.dspace.org because the Klaro Cookie pop-up shows the default Klaro text like this:
The main issue is that the Klaro `'zz'` "default translations" no longer seem to work.  The reason is because Klaro only uses the `zz` translations if no other languages can be found, and (as of 0.7.19) the `klaro-no-translations` package is wrongly including all the translations (see https://github.com/klaro-org/klaro-js/issues/515).  So, there's no longer a way to tell Klaro to not include translations …
=> Fix Klaro translations by forcing Klaro to use a zy language code that DSpace will translate

src/styles/_custom_variables.scss, src/styles/_global-styles.scss
* Fixes #2668
Adding and changing some classes in the global scss to make the cookie settings more accessible.
* Added the variable "--very-dark-cyan" in _custom_variables.scss.
* Removed the variable ".cm-btn.cm-btn-success.cm-btn-accept-all" and its styling as it was no longer needed.
* Styled the "Accept all" button by overwriting the style of the ".klaro .cookie-modal .cm-btn.cm-btn-success.cm-btn-accept-all" variables.
* Added "text-decoration: underline;" to the anchors.
* Changed the color of some informational texts, which were previously gray and are now lighter to improve contrast.
* Changed the color of the "Save" button by overwriting the styling of the variables: .klaro .cookie-modal .cm-btn.cm-btn-info.
To reproduce:
1. Visit a DSpace repository …
=> [8.x] Accessibility cookie settings

src/assets/i18n/fr.json5
* Partially Fixes #3578 
Contains all translations in french for new DSpace 8 COAR Notify module.
COAR Notify labels are very technical but as it is a notification protocol, translations have been made with the email or mail exchange in mind. For example, Endorsment has been translated by Approbation ; Acknowledgement by Accusé réception.
Other choices of words made : 
- Patern has been translated by Modèle
- Ingest has been translated by Ingérer or Ingestion
- Review has been translated by Évaluation
- The name of the protocol, COAR Notify, has been kept in english.
=> French translations for COAR Notify  LDN Service

src/app/register-page/create-profile/create-profile.component.html
* Fixes #3655 
This PR resolves an issue where the email address displayed on the profile setup form after a new user registration lacked proper spacing between the email label ("Email Address") and the actual email address. The absence of spacing caused readability issues and hindered the clarity of the label in relation to the email value.
The changes in this PR ensure that the email label and the email address are clearly spaced, improving readability.
- Added appropriate margin spacing to the email label to create visual separation between the label and the email address.
- Ensured that the email label is correctly aligned with the email address to enhance the layout and user experience.
**Testing Instructions:**
1. Register as a new user and submit the …
=> #3655 - Fixes Spacing Issue Between Email Label and Email Address on Profile Setup Form

cypress/e2e/item-edit.cy.ts, src/app/collection-page/collection-page.component.ts, src/app/core/breadcrumbs/item-breadcrumb.resolver.ts, src/app/core/browse/browse.service.spec.ts, src/app/core/browse/browse.service.ts, src/app/core/cache/object-cache.reducer.ts, src/app/core/cache/object-cache.service.ts, src/app/core/data/dspace-rest-response-parsing.service.ts, src/app/core/data/relationship-data.service.spec.ts, src/app/core/data/relationship-data.service.ts, src/app/core/data/version-history-data.service.ts, src/app/core/index/index.effects.ts, src/app/home-page/recent-item-list/recent-item-list.component.ts, src/app/item-page/edit-item-page/abstract-item-update/abstract-item-update.component.ts, src/app/item-page/edit-item-page/item-delete/item-delete.component.ts, src/app/item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.spec.ts, src/app/item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.ts, src/app/item-page/item.resolver.ts, src/app/shared/form/builder/ds-dynamic-form-ui/ds-dynamic-form-control-container.component.ts, src/app/shared/utils/relation-query.utils.ts
Port of #3415 to `dspace-7_x`.
Also restored [these changes](https://github.com/DSpace/dspace-angular/commit/bd8659ac116b4780223c2fea833616990a59b1a3) that were accidentally dropped in #3405 causing the `item-edit.cy.ts` e2e tests to be more flaky again
=> [Port dspace-7_x] Added support for caching embedded objects without a self link & null responses

src/app/core/provide-core.ts
* Fixes #3424
Fix the deserialization of the SystemWideAlert object by providing it to the core model list. This ensures it is called during the application's initialization and included in the type map of object models.
Steps to reproduce the bug can be found #3424.
Screenshots of the results:
=> Fixes the display of the System Wide Alert

Dockerfile.dist, docker/README.md, docker/cli.yml, docker/db.entities.yml, docker/docker-compose-ci.yml, docker/docker-compose-dist.yml, docker/docker-compose-rest.yml, docker/docker-compose.yml
Fixes reference to latest in docker files (since 8_x is no longer latest)
Follow the instructions here:
https://wiki.lyrasis.org/display/DSPACE/Testing+DSpace+Github+Pull+Requests
to stand up a copy of the DSpace backend using docker. Check to make sure it's using the latest 8_x version.
* updated docker files to match their 7_x counterparts
=> Update docker files for 8_x

config/config.example.yml
As of 7.6.2 / 8.0, we now have an option to control Angular's `inlineCriticalCss`.  This is **incorrectly documented** in our `config.example.yml` as being `environment.universal.inlineCriticalCss`.  
The correct config is `environment.ssr.inlineCriticalCss` as shown in https://github.com/DSpace/dspace-angular/blob/main/server.ts#L248 and https://github.com/DSpace/dspace-angular/blob/main/src/config/ssr-config.interface.ts
This small PR corrects the example in `config.example.yml` and cleans up a few other minor comments around the example configs in that file.
* This `config.example.yml` is not used anywhere in our codebase.  It's meant for documentation purposes & as a simple example.  So, this small PR does not require testing.
=> Fix incorrect example in `config.example.yml`

config/config.example.yml
Manual port of #3683 to `dspace-7_x`
=> [Port dspace-7_x] Fix incorrect example in `config.example.yml`

src/app/item-page/orcid-page/orcid-auth/orcid-auth.component.ts, src/app/item-page/orcid-page/orcid-page.component.ts, src/app/item-page/orcid-page/orcid-sync-settings/orcid-sync-settings.component.spec.ts, src/app/item-page/orcid-page/orcid-sync-settings/orcid-sync-settings.component.ts, src/app/shared/remote-data.utils.ts
---
DSpace 7_x version here: #3182
DSpace 8.x version here: #3216
* Fixes [#8925](https://github.com/DSpace/DSpace/issues/8925)
This PR solves various issues related to the orcid synchronization feature (those issues were related to the stale status of a request saved inside the cache). The full list of issues can be found here: [#8925](https://github.com/DSpace/DSpace/issues/8925).
You should check the behavior of the synchronization page, as suggested inside the issue [#8925](https://github.com/DSpace/DSpace/issues/8925).
Moreover, you should check that the `code` parameter of the URL is cleared once the account has been connected successfully by using the proper button (`Connect to Orcid`)
* Introduces reactive states derived from item inside orcid-sync page …
=> Orcid Authorization / Synchronization Page Fixes

src/app/shared/dso-selector/modal-wrappers/create-community-parent-selector/create-community-parent-selector.component.html, src/app/shared/dso-selector/modal-wrappers/create-community-parent-selector/create-community-parent-selector.component.spec.ts, src/app/shared/dso-selector/modal-wrappers/create-community-parent-selector/create-community-parent-selector.component.ts
* Fixes #3288 
This PR introduces a change to the CreateCommunityParentSelectorComponent to display the admin-div section only to users with Site Administrator privileges.
The key changes include:
- **New** `isAdmin$` **Observable:** Added an isAdmin$ observable to the CreateCommunityParentSelectorComponent to track admin status.
- **Conditional Rendering**: Added a `<div>` with `data-test="admin-div"` in the component's template, which is displayed only if `isAdmin$ `emits `true`.
- **Updated Tests**: Adjusted the unit tests to check for the presence of the `admin-div` based on the admin status.
**How to test:**
1. Log in as Community admin on https://demo.dspace.org/home
2. On the admin bar, click on New -> Community
3. Verify that the admin-div is not visible.
This will confirm that …
=> #3288 - Enabled 'admin-div' only for Site Administrator

src/app/item-page/orcid-page/orcid-auth/orcid-auth.component.ts, src/app/item-page/orcid-page/orcid-page.component.ts, src/app/item-page/orcid-page/orcid-sync-settings/orcid-sync-settings.component.spec.ts, src/app/item-page/orcid-page/orcid-sync-settings/orcid-sync-settings.component.ts
---
DSpace 8 version here: [#31818](https://github.com/DSpace/dspace-angular/pull/3181)
* Fixes [#8925](https://github.com/DSpace/DSpace/issues/8925)
This PR solves various issues related to the orcid synchronization feature (those issues were related to the stale status of a request saved inside the cache). The full list of issues can be found here: [#8925](https://github.com/DSpace/DSpace/issues/8925).
You should check the behavior of the synchronization page, as suggested inside the issue [#8925](https://github.com/DSpace/DSpace/issues/8925).
Moreover, you should check that the `code` parameter of the URL is cleared once the account has been connected successfully by using the proper button (`Connect to Orcid`)
* Introduces reactive states derived from item …
=> [Port dspace-7_x] Orcid Authorization / Synchronization Page Fixes

src/app/shared/search/search-export-csv/search-export-csv.component.spec.ts, src/app/shared/search/search-export-csv/search-export-csv.component.ts, src/app/shared/search/search-filters/search-filter/search-facet-filter/search-facet-filter.component.ts
Manual port of #3693 by @alexandrevryghem to `dspace-8_x`
=> [Port dspace-8_x] Removed unauthorized metadata-export-search request on search page 

cypress/e2e/item-edit.cy.ts, src/app/browse-by/browse-by-page-routes.ts, src/app/collection-page/collection-page-routes.ts, src/app/community-page/community-page-routes.ts, src/app/core/data/base/base-data.service.spec.ts, src/app/core/data/base/base-data.service.ts, src/app/item-page/edit-item-page/abstract-item-update/abstract-item-update.component.ts, src/app/item-page/item-page-routes.ts, src/app/shared/dso-page/dso-edit-menu-resolver.service.ts
* Fixes #3584
* Fixes #3425
Fixed the issue where switching between item pages could cause an infinite loading screen. This issue was caused by requests made in `dsoEditMenuResolver` that set the `useCachedVersionIfAvailable` to `false`. The problem arose due to a change in the timing of when a request is actually sent to the backend. Since Angular 16, an [`asapScheduler`](https://github.com/DSpace/dspace-angular/blob/757d23e74d0cc731b2e64ad093ce0e3a80f6ff68/src/app/core/data/request.service.ts#L450) causes requests to sometimes happen sooner. This broke [this logic](https://github.com/DSpace/dspace-angular/blob/757d23e74d0cc731b2e64ad093ce0e3a80f6ff68/src/app/core/data/base/base-data.service.ts#L344-L348), which prevents cached data (when the cache is disabled) and stale data from being …
=> Fix infinite loading on item pages and optimize menu resolver usage

.github/workflows/build.yml, .github/workflows/docker.yml, Dockerfile, Dockerfile.dist, docker/cli.yml, docker/db.entities.yml, docker/docker-compose-ci.yml, docker/docker-compose-dist.yml, docker/docker-compose-rest.yml, docker/docker-compose.yml
Manual port of #3754 to `dspace-8_x`
=> [Port dspace-8_x][GitHub Actions][Docker] Update Docker scripts & GitHub Actions to use ghcr.io instead of docker.io

src/app/access-control/epeople-registry/eperson-form/eperson-form.component.ts, src/app/shared/object-detail/my-dspace-result-detail-element/item-detail-preview/item-detail-preview.component.html, src/app/shared/object-detail/my-dspace-result-detail-element/item-detail-preview/item-detail-preview.component.ts
* Fixes #3571
* Continuation of #3585
* `dspace-7_x` backport: https://github.com/DSpace/dspace-angular/pull/3721
Fixed issue where the edit EPerson page didn't show the comcol names when they weren't already cached. Also removed a template observable call from `ItemDetailPreviewComponent`.
* Embedded the `Group`'s linked `object` in the group overview of edit `EPerson`. Otherwise only already cached communities and collections would have a visible name
=> Embed the community/collection on the edit EPerson page

src/app/access-control/epeople-registry/epeople-registry.component.html, src/app/access-control/epeople-registry/epeople-registry.component.ts, src/app/access-control/epeople-registry/eperson-form/eperson-form.component.html, src/app/access-control/epeople-registry/eperson-form/eperson-form.component.spec.ts, src/app/access-control/epeople-registry/eperson-form/eperson-form.component.ts, src/app/access-control/group-registry/group-form/group-form.component.html, src/app/access-control/group-registry/group-form/group-form.component.spec.ts, src/app/access-control/group-registry/group-form/group-form.component.ts, src/app/admin/admin-registries/bitstream-formats/bitstream-formats.component.html, src/app/admin/admin-registries/bitstream-formats/bitstream-formats.component.spec.ts, src/app/admin/admin-registries/bitstream-formats/bitstream-formats.component.ts, src/app/admin/admin-registries/metadata-registry/metadata-registry.component.html, src/app/admin/admin-registries/metadata-registry/metadata-registry.component.spec.ts, src/app/admin/admin-registries/metadata-registry/metadata-registry.component.ts, src/app/admin/admin-registries/metadata-registry/metadata-schema-form/metadata-schema-form.component.html, src/app/admin/admin-registries/metadata-registry/metadata-schema-form/metadata-schema-form.component.spec.ts, src/app/admin/admin-registries/metadata-registry/metadata-schema-form/metadata-schema-form.component.ts, src/app/admin/admin-registries/metadata-schema/metadata-field-form/metadata-field-form.component.spec.ts, src/app/admin/admin-registries/metadata-schema/metadata-schema.component.html, src/app/admin/admin-registries/metadata-schema/metadata-schema.component.spec.ts, src/app/admin/admin-registries/metadata-schema/metadata-schema.component.ts, src/app/profile-page/profile-page.component.html, src/app/profile-page/profile-page.component.spec.ts, src/app/profile-page/profile-page.component.ts, src/app/shared/object-detail/my-dspace-result-detail-element/item-detail-preview/item-detail-preview.component.html, src/app/shared/object-detail/my-dspace-result-detail-element/item-detail-preview/item-detail-preview.component.ts, src/app/shared/pagination/pagination.component.html, src/app/shared/pagination/pagination.component.ts, src/app/shared/testing/registry.service.stub.ts
Manual port of #3585 & #3720 to `dspace-7_x`
=> [Port dspace-7_x] Removed observable function calls from template (part 1)

src/app/collection-page/collection-page-routing.module.ts, src/app/community-page/community-page-routing.module.ts, src/app/core/data/base/base-data.service.spec.ts, src/app/core/data/base/base-data.service.ts, src/app/item-page/edit-item-page/abstract-item-update/abstract-item-update.component.ts, src/app/item-page/item-page-routing.module.ts
Manual port of #3677 to `dspace-7_x` (the `BaseDataService` fixes are actually not required, but at least this way all supported DSpace versions work in the same way).
The differences with the `dspace-8_x` & `main` PRs are:
- The `menu` resolver is still present on the browse pages. This is because the browse pages are still used to represent the comcol pages on `dspace-7_x` to render the browse tabs (fixed in #2722 for DSpace 8.0)
- The correction type improvement is not present, since this is also a new feature since `dspace-8_x`
=> [Port dspace-7_x] Fix infinite loading on item pages and optimize menu resolver usage

src/app/shared/form/vocabulary-treeview/vocabulary-treeview.component.html, src/app/shared/form/vocabulary-treeview/vocabulary-treeview.component.ts
* Fixes #3366
In the “ds-vocabulary-treeview” component, the following implementations have been made: setting the focus on the search bar when the reset button is clicked. Using aria-live=“polite” so that the message “There were no items to show” is announced to users who use a screen reader and adding the aria-label attribute to the buttons.
* For the focus, the “@ViewChild” decorator and the “ElementRef” class were used to access and manipulate the search bar.
* The aria-live=“polite” attribute has been used to announce the “There were no items to show” message.
* And finally, the aria-label attribute has been added to some buttons.
To reproduce:
1. Using a screen reader and navigating DSpace via keyboard, go to the controlled vocabulary page …
=> Accessibility in vocabulary treeview

src/app/item-page/field-components/metadata-values/metadata-values.component.html, src/app/item-page/field-components/metadata-values/metadata-values.component.spec.ts, src/app/item-page/field-components/metadata-values/metadata-values.component.ts
Manual port of #3322 by @IgorBaptist4 and @Andrea-Guevara to `dspace-7_x`.
Includes porting `hasInternalLink()` method in `metadata-values.component.ts` because this method didn't exist in 7.6.x.
=> [Port dspace-7_x] fix #3241: Configuring the URI link target

src/app/shared/form/chips/chips.component.html, src/app/shared/form/chips/chips.component.scss, src/app/shared/form/chips/chips.component.spec.ts, src/app/shared/form/chips/chips.component.ts
* Fixes #3624 
This PR addresses an issue with multi-row drag-and-drop functionality in DSpace’s item submission form. When chips are distributed across multiple rows, drag-and-drop operations fail due to limitations in the current Angular CDK version (17.3.10). This update ensures correct functionality for dragging and swapping items across rows in DSpace 8.
The changes in this PR ensure that items can be individually dragged between rows without affecting other items in adjacent rows.
- Defined cdkDropListGroup to connect all drag-and-drop items, allowing them to act independently within their respective rows.
- Assigned unique cdkDropList instances to each item to prevent unintended reordering of the entire list.
- Set cdkDropListOrientation to horizontal to …
=> #3624 - Fix Multi-Row Drag-and-Drop Issue for Chips in Item Submission Form

src/app/shared/form/builder/ds-dynamic-form-ui/models/array-group/dynamic-form-array.component.html, src/app/shared/form/builder/ds-dynamic-form-ui/models/array-group/dynamic-form-array.component.ts
* Fixes #3678 
* Fixes #3217
Wrapped the `control.get` method call in order to maintain a consistent link between Models and Controls.
Please, try to reproduce the bug described in #3678 following the same steps included in that issue. 
Here is a video showcasing the bugfix.
https://github.com/user-attachments/assets/f7500905-182a-4306-8dcf-496099142e38
* Wrapped the `control.get` method in a custom method that adds the `startingIndex` property to the `groupModel` and uses that value as the key to get the relative `control`. Since controls are never updated, but elements change their index when they are being reordered, this fixes issues regarding value changes and consequential reordering of items.
* Set up the `formGroupName` as the index stored in the …
=> #3678, #3217 - Fix ordering and changing values of repeatable inputs in submission form

src/app/browse-by/browse-by-date-page/browse-by-date-page.component.ts, src/app/browse-by/browse-by-metadata-page/browse-by-metadata-page.component.ts, src/app/browse-by/browse-by-title-page/browse-by-title-page.component.ts, src/app/menu.resolver.spec.ts, src/app/menu.resolver.ts
This is a backport of [#3753](https://github.com/DSpace/dspace-angular/pull/3753) to 7.x
=> [Port dspace-7_x] Get rid of unnecessary and failing REST requests when navigating between different browse indexes

src/assets/i18n/en.json5, src/assets/i18n/pt-BR.json5, src/assets/i18n/pt-PT.json5
Fixes misspellings in metadata browsing translations.
=> Fixes typo for 'descrption'

src/app/shared/form/builder/ds-dynamic-form-ui/models/lookup/dynamic-lookup.component.html, src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.html, src/app/shared/form/form.service.ts
* Fixes #3723
Fixed issue where hitting enter in a submission form containg a `dropdown`/`lookup` or `lookup-name` field would cause the first one to reset.
* Added `type="button"` to the buttons in those dropdowns, this prevents them from being triggered on submit
* Also added another small fix to the `FormService` class. [The `AbstractControl`'s `errors` property](https://v17.angular.io/api/forms/AbstractControl#errors) can be null when there are no errors, and this caused an issue when it was `null` because then `Object.keys(null)` was being called
=> Fixed dropdown/lookup & lookup-name fields being reset when hitting enter

src/app/item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.spec.ts, src/app/item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.ts
DSpace 8 version of #3143 
This PR fixes an issue in the edit relationship list component where the search modal is always repeatable, regardless of the relationship max cardinality while in the submission forms, you can set it to non-repeatable. 
To make the behaviour more consistent between the submission form modal and the edit relationships modal, the edit relationships modal will now show radio buttons when the max cardinality is set to 1.
- Make sure there is a relationship with max cardinality of one on either the left or the right side and that items are present for both sides of the relationship
- Navigate to an entity that can be linked with the the type with max cardinality 1
- Go to the edit item page > Edit relationships tab and click add on the relevant relationship
- Verify …
=> Add support for non repeatable relationships

src/app/shared/form/builder/ds-dynamic-form-ui/models/lookup/dynamic-lookup.component.html, src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.html, src/app/shared/form/form.service.ts
Port of #3724 to `dspace-8_x`.
=> [Port dspace-8_x] Fixed dropdown/lookup & lookup-name fields being reset when hitting enter

src/app/core/shared/browse-definition.model.ts, src/app/core/shared/hierarchical-browse-definition.model.ts, src/app/core/shared/non-hierarchical-browse-definition.ts, src/app/entity-groups/journal-entities/item-pages/journal/journal.component.spec.ts, src/app/item-page/simple/field-components/specific-field/abstract/item-page-abstract-field.component.spec.ts, src/app/item-page/simple/field-components/specific-field/author/item-page-author-field.component.spec.ts, src/app/item-page/simple/field-components/specific-field/date/item-page-date-field.component.spec.ts, src/app/item-page/simple/field-components/specific-field/generic/generic-item-page-field.component.spec.ts, src/app/item-page/simple/field-components/specific-field/item-page-field.component.spec.ts, src/app/item-page/simple/field-components/specific-field/item-page-field.component.ts, src/app/item-page/simple/field-components/specific-field/uri/item-page-uri-field.component.spec.ts, src/app/item-page/simple/item-types/publication/publication.component.spec.ts, src/app/item-page/simple/item-types/shared/item.component.spec.ts, src/app/item-page/simple/item-types/untyped-item/untyped-item.component.spec.ts, src/app/shared/testing/browse-service.stub.ts
Manual port of #3701 by @KoenP to `dspace-7_x`
=> [Port dspace-7_x] Reduce browse definition requests on simple item page (#3701)

src/app/dso-shared/dso-edit-metadata/dso-edit-metadata-value/dso-edit-metadata-value.component.html, src/app/dso-shared/dso-edit-metadata/dso-edit-metadata-value/dso-edit-metadata-value.component.ts, src/assets/i18n/en.json5
* Fixes #3583
- Added a toggle button to allow free-text input in dropdown fields during item editing.
- It also fixes an issue that caused an error when clicking the "Clear selection" option that .
Edit a dropdown field associated with a vocabulary in the Edit Item page (e.g., `dc.language.iso` or `dc.type`), and verify that free-text input can be enabled or disabled using the button shown below, and that uncontrolled values can be saved.
Also, verify that clicking the "Clear selection" option clears the content and no longer generates an error in the console.
=> Add button to allow free-text editing in the dropdown field of Edit Item

src/app/profile-page/profile-page.component.html, src/app/profile-page/profile-page.component.ts, src/assets/i18n/en.json5
Manual port of #3105 by @VictorHugoDuranS to `dspace-7_x`
=> [Port dspace-7_x] Fix for User profile (/profile): only 20 group memberships shown instead of all

cypress/e2e/admin-add-new-modals.cy.ts, cypress/e2e/admin-edit-modals.cy.ts, cypress/e2e/admin-export-modals.cy.ts, cypress/e2e/item-edit.cy.ts
This small PR is an attempt to stabilize a few randomly failing e2e tests.
1. Sometimes tests which use the Admin sidebar will fail randomly if the sidebar link is not yet visible when it's clicked on.  The first commit in this PR attempts to fix that issue.
2. `item-edit.cy.ts` will sometimes randomly fail if the tabs have not fully loaded.  The second commit attempts to fix this issue by waiting on the current tab to be visible before clicking on it, and then ensuring it's visible again after reload of the page.
* This PR only touches e2e tests.  If those pass, it can be merged.
=> Attempt to stabilize a few randomly failing e2e tests

src/app/shared/comcol/sections/comcol-browse-by/comcol-browse-by.component.ts
* Fixes #3840 
* Related to https://github.com/DSpace/dspace-angular/pull/3753 as this applies the same fix, but to scoped browse-bys
Makes sure the browse-by-switcher component picks up changes in browse type, so the component gets rendered correctly
Test that switching between all types of browses works, both for scoped and non scoped browse pages
However, reviewers may request that you complete any actions in this list if you have not done so. …
=> Fix issue where scoped browse by would not inititialze correct component

src/styles/_bootstrap_variables_mapping.scss
This PR removes the duplicated line 
```
--bs-table-dark-color: #{$table-dark-color};
```
in `_bootstrap_variables_mapping.scss`.
=> SCSS cleanup: remove duplicated line

config/config.example.yml, server.ts, src/config/ssr-config.interface.ts, src/environments/environment.production.ts, src/environments/environment.test.ts, src/environments/environment.ts
* Partially fixes #3110
Only enable Angular SSR for paths in the DSpace sitemap and the home page. This is a compromise after analyzing high CPU usage in DSpace 7+ and discussion with the Google Scholar team. We do not need to be wasting CPU and memory to generate and store SSR pages in the cache for request paths that are not "primary" DSpace objects, for example search and browse—these request paths contain data derived from the primary objects themselves and bots can spend endless time crawling them.
This solution was originally proposed by @vitorsilverio in https://github.com/DSpace/dspace-angular/issues/3110#issuecomment-2324513871.
Some notes:
- This will require manual porting to DSpace 7
- We should keep our eye on upstream work related to `inlineCriticalCss` because it improves …
=> Restrict Angular SSR to paths in the sitemap

config/config.example.yml, server.ts, src/config/universal-config.interface.ts, src/environments/environment.production.ts, src/environments/environment.test.ts, src/environments/environment.ts
Manual port of #3682 to DSpace 7.6.x.
There are minor differences due to a refactoring of the Universal preboot configuration to "SSR" in DSpace 8 and main.
=> [Post dspace-7_x] Restrict Angular SSR to paths in the sitemap

cypress/e2e/admin-add-new-modals.cy.ts, cypress/e2e/admin-edit-modals.cy.ts, cypress/e2e/admin-export-modals.cy.ts
Manual port of #3875 to `main`
=> [Port main] Stabilize e2e tests that use admin sidebar menu

src/app/entity-groups/research-entities/metadata-representations/person/person-item-metadata-list-element.component.html, src/app/entity-groups/research-entities/metadata-representations/person/person-item-metadata-list-element.component.ts, src/app/shared/orcid-badge-and-tooltip/orcid-badge-and-tooltip.component.html, src/app/shared/orcid-badge-and-tooltip/orcid-badge-and-tooltip.component.scss, src/app/shared/orcid-badge-and-tooltip/orcid-badge-and-tooltip.component.spec.ts, src/app/shared/orcid-badge-and-tooltip/orcid-badge-and-tooltip.component.ts, src/assets/i18n/en.json5
* Fixes https://github.com/DSpace/DSpace/issues/9086
* Main port: #3344
* 7.x port: #3346
A new component has been created and added to the `ds-person-item-metadata-list-element` component template. This component shows the ORCID logo and a tooltip on hovering shows the ORCID of the person.
You can see the ORCID logo in a Publication page with authors listed.
In order to show the ORCID logo, an author should have at least the `person.identifier.orcid` metadata set. In this case, the logo is shown with a greyscale filter and a tooltip shows the ORCID with an `(unconfirmed)` clause.
If the author also has the `dspace.orcid.authenticated` metadata value, the logo is shown in full color and the tooltip has no `(unconfirmed)`  clause.
* Created …
=> [Port dspace-8_x] Add orcid icon with tooltip

src/app/entity-groups/research-entities/metadata-representations/person/person-item-metadata-list-element.component.html, src/app/shared/orcid-badge-and-tooltip/orcid-badge-and-tooltip.component.html, src/app/shared/orcid-badge-and-tooltip/orcid-badge-and-tooltip.component.scss, src/app/shared/orcid-badge-and-tooltip/orcid-badge-and-tooltip.component.spec.ts, src/app/shared/orcid-badge-and-tooltip/orcid-badge-and-tooltip.component.ts, src/app/shared/shared.module.ts, src/assets/i18n/en.json5
* Fixes https://github.com/DSpace/DSpace/issues/9086
A new component has been created and added to the `ds-person-item-metadata-list-element` component template. This component shows the ORCID logo and a tooltip on hovering shows the ORCID of the person.
You can see the ORCID logo in a Publication page with authors listed.
In order to show the ORCID logo, an author should have at least the `person.identifier.orcid` metadata set. In this case, the logo is shown with a greyscale filter and a tooltip shows the ORCID with an `(unconfirmed)` clause.
If the author also has the `dspace.orcid.authenticated` metadata value, the logo is shown in full color and the tooltip has no `(unconfirmed)`  clause.
* Created `orcid-badge-and-tooltip` component;
* Included said …
=> [Port dspace-7_x] Add orcid icon with tooltip

src/app/core/data/bitstream-data.service.spec.ts, src/app/core/data/bitstream-data.service.ts
* Fixes #3871
Removes `encodeURIComponent` in [bitstream-data.service.ts#L174](https://github.com/DSpace/dspace-angular/blob/dspace-7.6.2/src/app/core/data/bitstream-data.service.ts#L174) because [RequestParam](https://github.com/DSpace/dspace-angular/blob/dspace-7.6.2/src/app/core/cache/models/request-param.model.ts) is already encoding values
This extra encoding causes spaces to be encoded twice `%20` to `%2520` and URL redirect fails with 404 error.
=> Fix redirect URLs of bitstreams with spaces in filename

src/app/core/data/bitstream-data.service.spec.ts
Manual port of #3876 by @msarmie to `main`.  This port ONLY includes the new unit test, as the bug doesn't exist on `main`.
=> [Port main] Fix redirect URLs of bitstreams with spaces in filename (new test ONLY)

src/app/core/data/bitstream-data.service.spec.ts
Manual port of #3876 by @msarmie to `dspace-8_x`.  This port ONLY includes the new unit test, as the bug doesn't exist on `dspace-8_x`.
=> [Port dspace-8_x] Fix redirect URLs of bitstreams with spaces in filename (new test ONLY)

src/app/bitstream-page/edit-bitstream-page/edit-bitstream-page.component.html, src/app/bitstream-page/edit-bitstream-page/edit-bitstream-page.component.spec.ts, src/app/bitstream-page/edit-bitstream-page/edit-bitstream-page.component.ts, src/app/core/data/bitstream-data.service.ts, src/app/core/data/bundle-data.service.ts, src/app/core/metadata/head-tag.service.ts, src/app/item-page/edit-item-page/item-bitstreams/item-bitstreams.component.html, src/app/item-page/edit-item-page/item-bitstreams/item-bitstreams.component.ts, src/app/process-page/form/scripts-select/scripts-select.component.html, src/app/process-page/form/scripts-select/scripts-select.component.scss, src/app/process-page/form/scripts-select/scripts-select.component.spec.ts, src/app/process-page/form/scripts-select/scripts-select.component.ts, src/app/shared/form/builder/ds-dynamic-form-ui/models/list/dynamic-list.component.html, src/app/shared/form/builder/ds-dynamic-form-ui/models/list/dynamic-list.component.ts, src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.html, src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.spec.ts, src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.ts, src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.model.ts, src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/search-tab/dynamic-lookup-relation-search-tab.component.spec.ts, src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/search-tab/dynamic-lookup-relation-search-tab.component.ts, src/app/submission/sections/cc-license/submission-section-cc-licenses.component.html, src/app/submission/sections/cc-license/submission-section-cc-licenses.component.scss, src/app/submission/sections/cc-license/submission-section-cc-licenses.component.spec.ts, src/app/submission/sections/cc-license/submission-section-cc-licenses.component.ts, src/assets/i18n/en.json5
Manual port of #3694 by @FrancescoMolinaro to `dspace-8_x`
=> [Port dspace-8_x] Prevent request with page size of 9999 (#3694)

src/styles/_custom_variables.scss, src/themes/dspace/app/home-page/home-news/home-news.component.scss, src/themes/dspace/styles/_theme_css_variable_overrides.scss, src/themes/dspace/styles/_theme_sass_variable_overrides.scss
* Fixes #3810 
* Fixes #1157
Improved color contrast of home news content.
* In the “home-news.component” component, the font weight has been increased,
* In the style file “_theme_css_variable_overrides.scss” the banner has been darkened a little.
Use an accessibility tool to see if the home news content is more accessible.
=> Improving the color contrast of home news content

src/app/item-page/simple/related-items/related-items.component.html
* Fixes https://github.com/DSpace/dspace-angular/issues/1183
Reference description in #1183 / Point 1
> (ID 470327) "Purpose of the link is not clear in context." on the "Show 4 more" and "Hide last 4" links which appear in long lists of Entity relationships (especially on Person Entity pages like https://demo.dspace.org/entities/person/5a3f7c7a-d3df-419c-b8a2-f00ede62c60a).
* Improves labels for "Show 4 more" and "Hide last 4"  by making them more by adding also the label/entity it represents: E.g. “Show 4 more Organizational Units “.
* There will be no need for `aria-label` to be provided for simple basic buttons. They have an accessible name, the text itself:   [ARIA: button role - Accessibility | MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role#bas …
=> Improve descriptive labels for show/hide x more buttons for related items (Item/Entity Homepage)

src/app/shared/truncatable/truncatable-part/truncatable-part.component.html, src/app/shared/truncatable/truncatable-part/truncatable-part.component.spec.ts, src/app/shared/truncatable/truncatable-part/truncatable-part.component.ts
Fixes #3073
Fixes keyboard shortcuts of the truncatable-part component, used in the 'Show more' button.
- Go to a page that lists items, such as the home page or a search, with at least one of the items having content long enough for the "Show More" button to be displayed. 
- Click anywhere in a blank area near the item list. Cycle through the DOM elements using the TAB key.
- When the 'Show More'/'Collapse' button is highlighted, you can toggle it using the Enter key or the spacebar.
- Button still works using the mouse
* truncatable-part.component.html:    
- Refactored/simplified the 'Show more' and 'Collapse' buttons into a single button element
- Added event bindings for the enter key and the spacebar
- Added …
=> Fix truncatable-part keyboard accessibility

package-lock.json
* Related to #3894 and #3895
This PR simply bumps the version of `cross-spawn` specified in our package-lock.json to avoid CVE-2024-21538.  `cross-spawn` is only used in development, so it's unlikely this CVE would impact DSpace in production. However, bumping up just in case.
It's a port of #3894 and #3895 to `main`.
=> Bump cross-spawn from 7.0.3 to 7.0.6

src/app/admin/admin-sidebar/expandable-admin-sidebar-section/expandable-admin-sidebar-section.component.ts, src/app/navbar/expandable-navbar-section/expandable-navbar-section.component.html, src/app/navbar/expandable-navbar-section/expandable-navbar-section.component.spec.ts, src/app/navbar/expandable-navbar-section/expandable-navbar-section.component.ts, src/app/shared/menu/menu-section/menu-section.component.ts, src/app/shared/utils/hover-outside.directive.ts, src/themes/custom/app/navbar/expandable-navbar-section/expandable-navbar-section.component.ts
* Fixes #3085
Improved the accessibility of the expandable navbar menu section. For all the keyboard interactions, I based them on the [W3C guidelines](https://www.w3.org/WAI/ARIA/apg/patterns/menubar/). The only behaviors I haven't implemented are the `Left Arrow` & `Right Arrow`.
* Created new `HoverOutsideDirective` to detect when you hover outside a specific element to close the expandable modal. This also works when you open it using your keyboard and hover outside the expandable navbar afterwards
* Added multiple new keyboard interaction behaviors:
* Set focus on the first item when expanding the expandable navbar (with `space` & `enter`)
* Added `Up Arrow` & `Down Arrow` support to navigate through the expandable navbar options
* Close the expandable …
=> Made expandable navbar section more keyboard accessible

config/config.example.yml
This PR fixes a minor syntax error in our `config.example.yml` added in #3709 
Because this example file is only for documentation purposes, we overlooked that these example configs were not valid YAML.
This needs to be ported to 8.x as well, since it exists there.  A manual port will need to be done for 7.x
=> Fix YAML syntax in config.example.yml

config/config.example.yml
Manual port of #3920 to `dspace-7_x`.
This includes one additional fix, which is to rename the `ssr` section back to `universal`.  This section was renamed as of 8.0, but is still called `universal` in 7.x.  See https://github.com/DSpace/dspace-angular/blob/dspace-7_x/src/config/universal-config.interface.ts
=> [Port dspace-7_x] Fix YAML syntax and revert section name to "universal" 

src/app/admin/admin-sidebar/expandable-admin-sidebar-section/expandable-admin-sidebar-section.component.ts, src/app/navbar/expandable-navbar-section/expandable-navbar-section.component.html, src/app/navbar/expandable-navbar-section/expandable-navbar-section.component.spec.ts, src/app/navbar/expandable-navbar-section/expandable-navbar-section.component.ts, src/app/navbar/navbar.module.ts, src/app/shared/menu/menu-section/menu-section.component.ts, src/app/shared/utils/hover-outside.directive.ts
Port of #3581 to `dspace-7_x`.
=> [Port dspace-7_x] Made expandable navbar section more keyboard accessible

src/app/core/auth/auth.interceptor.ts
* Fixes https://github.com/DSpace/DSpace/issues/8312 (see also discussion in duplicate issue #2701)
* Expands on #2414
If LDAP authentication is enabled but Password authentication is not, Angular UI shows a blank login dialog. This PR fixes the issue by forcing Password dialog to be present (as the same password dialog is used in both password- and ldap-based authentication) as part of the enumeration and sorting of login methods. 
Details on functionality: When enumerating the authentication methods for sorting, additional local variables to record whether password auth and/or ldap auth are present. In the special case where ldap auth is present and password auth is not, password auth is added anyway. This is needed because there is no renderAuthMethodFor decorator related to ldap auth …
=> Fix auth in UI with LDAP if password authentication is disabled

src/app/shared/search/search-filters/search-filter/search-facet-filter-options/search-facet-option/search-facet-option.component.html, src/app/shared/search/search-filters/search-filter/search-facet-filter-options/search-facet-option/search-facet-option.component.spec.ts, src/app/shared/search/search-filters/search-filter/search-facet-filter-options/search-facet-option/search-facet-option.component.ts, src/assets/i18n/en.json5, src/assets/i18n/es.json5, src/assets/i18n/pt-BR.json5
* Fixes #3299
Creation of the announceFilter() method to make the selection of filters in the advanced search more accessible.
* In the component “search-facet-option.component” the method “announceFilter()” has been created which, making use of the services “LiveRegionService” and “TranslateService”, creates a message which, as soon as the search filter is clicked, announces to the user that the page will be reloaded and which filter is being applied.
* New translation keys have been added.
1. Go to the search area where the filters are applied https://sandbox.dspace.org/search?query=;
2. Using a screen reader, select a filter and notice that a page reload message is announced.
=> [Port dspace-7_x] Accessibility when selecting a search filter

config/config.example.yml, src/environments/environment.production.ts, src/environments/environment.test.ts, src/environments/environment.ts
* Fixes #3934
This small PR just ensures that `/reload/` paths always trigger SSR.  This fixes the odd behavior seen in #3934.
* Review code
* If you are able to reproduce the issues in #3934, ensure they no longer occur.
* NOTE: For some reason the issues described in #3934 do not seem to occur in all environments. For example, they are not reproducible on sandbox.dspace.org.  However, *when* these issues occur, the fix is to add `/reload/` to the `ssr.paths`.
=> Ensure `/reload/` (hard reload) path is included in SSR paths.

src/app/notifications/suggestion-targets/suggestion-targets.effects.ts
* Fixes #3759 
Modification of the effects used by the suggestion feature to avoid retrieving user suggestions if Researcher profiles are disabled.
Comment out the key :
```
researcher-profile.entity-type = Person 
```
And verify that no error appears in the console when a user authenticates or if the page is reloaded with an authenticated user.
Then, uncomment the key and check that suggestions are still being retrieved. (I'm not using the suggestion feature, I just tested that the function retrieving suggestions is called correctly.)
=> Avoid retrieving user suggestions if Researcher profiles are disabled

config/config.example.yml
Tiny PR to cleanup `config.example.yml` (which is just an example configuration).  This moves the `enablePerformanceProfiler` option for `ssr` to the last item in the list & comments it out by default.  This option should never be used in production and is a debugging tool, so it makes no sense to list it first.
* This changes no code in DSpace.  This `config.example.yml` is unused and is just meant for documentation.
=> Move `enablePerformanceProfiler` option to last in list in `config.example.yml`

src/app/menu-resolver.service.ts
Since I developed the Contents Reports functionality prior to publication of DSpace 8.0, back in 2024, a line has been (accidentally?) deleted from file `menu-resolver.service.ts`, which invokes method `createReportMenuSections()` (still present but never called). This PR reinstates the deleted line, so that accessibility of the Content Reports section in the Admin menu will depend again on the `contentreport.enable` setting on the Java/REST side, as was initially intended.
Note: This PR applies to both DSpace versions 8.1 and 9.
Enable the `contentreport.enable` setting in your Java/REST layer, build and start the server, then start the Angular layer. When you log in with an administrator account, you should see the Content Reports sections in the Admin menu sidebar.
List of changes in …
=> Added missing line to enable access to Content Reports

src/assets/i18n/fr.json5
When configuring the [Identifier step in submission forms](https://wiki.lyrasis.org/display/DSDOC8x/Submission+User+Interface#SubmissionUserInterface-Configuringthe%22Identifiers%22step), french translations were missing. This PR is adding all necessary labels for this step.
=> Update fr.json5 to add identifiers deposit's step translations in french

src/ngx-translate-loaders/translate-server.loader.ts
This PR fixes the ESLint deprecation warning
`'TransferState' is deprecated. TransferState has moved, please import TransferState from @angular/core`
This affects all DSpace version which use Angular 17 or above.
=> fixed deprecated import of TransferState

src/app/core/metadata/metadata.service.ts
* Fixes #4033
Add missing `<meta name="citation_doi" ...>` fields to the XHTML head section for items that have DOIs. This is used by harvesters like Altmetric to monitor attention on identifiers in repositories and academic publishers.
* Adds a `<meta name="citation_doi" content=...>` tag to the `<head>` section item pages containing a DOI in the `dc.identifier.doi` field (default).
This will need to be ported to DSpace 8+ manually.
**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, …
=> Add citation_doi tag to head meta

src/app/core/metadata/head-tag.service.ts
=> [Port main] Add citation_doi tag to head meta

src/app/system-wide-alert/alert-form/system-wide-alert-form.component.spec.ts, src/app/system-wide-alert/alert-form/system-wide-alert-form.component.ts
* Required by https://github.com/DSpace/DSpace/pull/10432 for System Wide Alerts to work properly
Currently, if you set a "countdown timer" on the System-Wide Alert page, the date is sent to the REST API in a non-standard format that looks like this: `Thu, 14 Nov 2019 00:55:16 GMT`
This format seems to work fine for the current codebase, but it cannot be parsed by the backend if you use PR https://github.com/DSpace/DSpace/pull/10432
This small PR updates the date to be sent in ISO-8601 format, e.g. `2019-11-14T00:55:31.820Z`, which is required by https://github.com/DSpace/DSpace/pull/10432
* Should only be merged / tested with https://github.com/DSpace/DSpace/pull/10432
* Verify that System Wide Alerts can now be saved with a countdown timer (previously they would throw an error).
=> System Wide Alerts should send countdown date to REST API in ISO-8601 format

cypress/e2e/admin-sidebar.cy.ts, cypress/tsconfig.json
This small PR fixes two small issues with Cypress e2e tests:
* First, it re-enables an accessibility validation test in `admin-sidebar.cy.ts`, as the prior accessibility issue was fixed in #2178.
* Second, it fixes the `tsconfig.json` for the Cypress tests to allow IDEs (especially VS Code) to recognize `*.cy.ts` files & provide autocomplete, etc. 
* This issue appeared to be related to https://github.com/cypress-io/cypress/issues/26930#issuecomment-1602799361
* The fix was to add `../node_modules` to the (default) list of `typeRoots` that are defined in our root `tsconfig.json` file.  That small addition allows IDEs to more easily locate the type definitions related to Cypress, allowing for autocomplete, etc.
* The first change will be auto-tested by this PR.  If the accessibility check …
=> Minor fixes to Cypress e2e tests

src/app/shared/search/search-filters/search-filters.component.ts
Fix #4053 
The component does not detect navigation changes.
* Search for something in the searchbar  
* Click on the second page
*  Now the filters works
* SearchFiltersComponent
=> Filters disappeared on reload

src/app/bitstream-page/bitstream-download-page/bitstream-download-page.component.spec.ts, src/app/bitstream-page/bitstream-download-page/bitstream-download-page.component.ts, src/app/shared/cookies/browser-orejime.service.ts, src/app/statistics/matomo.service.ts
* Fixes https://github.com/DSpace/dspace-angular/issues/4122
Fixed the bug where downloads were not working when matomo is disabled.
I inserted a check for the `matomo.enabled` configuration setting before using the `matomoService` to add the `visitorId` (that's where the download was failing).
* Added a check for `matomo.enabled` in `BitstreamDownloadPageComponent` to avoid calling a `matomoService` method is matomo is disabled;
* Added tests.
You can easily check that any download now starts when matomo is disabled, and still works when matomo is enabled.
=> [DURACOM-339] fix downloads not working when matomo is disabled

src/themes/dspace/app/home-page/home-news/home-news.component.html
* Fixes DSpace/DSpace#10558
This is a small PR to add a link to the DSpace Release Notes on the homepage.  This is being included to help testers during Testathon to easily locate the release notes.
I've tested this locally to find something that looks good.
=> Add note with link to Release Notes on homepage (for Testathon)

src/assets/i18n/fr.json5
Addition of french translations for Duplicate detection, ROR and Advanced search features.
=> Adding missing french labels

src/app/shared/form/builder/ds-dynamic-form-ui/ds-dynamic-form-control-container.component.html, src/app/shared/form/builder/ds-dynamic-form-ui/ds-dynamic-form-control-container.component.scss, src/app/shared/form/builder/ds-dynamic-form-ui/existing-metadata-list-element/existing-metadata-list-element.component.html, src/app/shared/form/builder/ds-dynamic-form-ui/models/date-picker/date-picker.component.scss
This PR standardizes spacing values for all input form fields and improves input form readability.
1. Updated `ds-dynamic-form-control-container.component.html` to reduce bottom margins on field labels and to remove excess spacing between fields.
2. Extended `ds-dynamic-form-control-container.component.scss` to conform error message margins to hint margins.
3. Extended `ds-dynamic-form-control-container.component.scss` to conform label padding and margins on non-repeatable tag fields to other fields.
4. Centered text vertically in `existing-metadata-list-element.component.html`.
5. Updated `date-picker.component.scss` to conform bottom margin on date field labels to other labels.
**BEFORE**
**AFTER**
How to test or review the PR:
* Create a new item through the …
=> Clean up spacing in input forms

src/app/collection-page/collection-page-routes.ts, src/app/community-page/community-page-routes.ts
* Fixes #4135
Fixed issue where the DSO menus were hidden on the comcol search tabs. This issue is a side effect of the merge between #3994 & #3164
* Added the necessary data on the `/search` route from the community & collection routes to generate the DSO menus there as well
=> Added the DSO menus back to the comcol search tabs

src/app/item-page/bitstreams/request-a-copy/bitstream-request-a-copy-page.component.html, src/app/item-page/bitstreams/request-a-copy/bitstream-request-a-copy-page.component.ts, src/app/request-copy/email-request-copy/email-request-copy.component.ts, src/modules/app/browser-app.config.ts
* Fixes #4145
The issue was caused by the fact that altcha was loaded server side, and that's not supported. When it tries to define the `altcha-widget` the server-side throws an exception.
I fixed it by removing the import everywhere, and putting it in `browser-app.config.ts`
I also removed an unnecessary ngVar, as they can be bad for performance.
Ensure that the ssr error is gone, and that the altcha captchas still work.
However, reviewers may request that you complete any actions in this list if you have not done so. If you are unsure about an item in the checklist, don't hesitate to ask. We're …
=> Fix ssr error by only importing altcha on the client side

src/app/shared/search/search-filters/search-filters.component.html, src/app/shared/search/search-filters/search-filters.component.ts
Port of #4121 for DSpace main branch
* Fix #4097 
Store the state of the computed filters in the array finalFiltersComputed.
The counter filtersWithComputedVisibility doesn't store the count of filters computed when you change between options in the select box in /mydspace, causing the ngIf in the HTML is always false, and no filters options render on the web.
* First, countFiltersWithComputedVisibility now store the count every time a new filter is "computed" till it reach the maximum filters configured.
* Second, added some utility functions to find the current and final counter, and a function to update the count.
* Third, update the ngIf, to use the new functions.
* Fourth, removed the trackBy: trackUpdate in the ngFor because when you enter in /mydspace …
=> [Port main] Store the state of the computed filters

src/app/shared/search/search-filters/search-filters.component.html, src/app/shared/search/search-filters/search-filters.component.ts
* Fixes #4097 
Store the state of the computed filters in the array finalFiltersComputed.
The counter filtersWithComputedVisibility doesn't store the count of filters computed when you change between options in the select box in /mydspace, causing the ngIf in the HTML is always false, and no filters options render on the web.
* First, countFiltersWithComputedVisibility now store the count every time a new filter is "computed" till it reach the maximum filters configured.
* Second, added some utility functions to find the current and final counter, and a function to update the count.
* Third, update the ngIf, to use the new functions.
* Fourth, removed the trackBy: trackUpdate in the ngFor because when you enter in /mydspace from the link in the dropdown it …
=> Store the state of the computed filters

src/app/core/shared/search/search.service.ts
=> trivial change: fixed typo in description of trackSearch method

src/app/shared/cookies/orejime-configuration.ts
* Fixes #4133
* Fixes #3963
This issue was caused by some unintuitive behavior of the orejime cookie popup. If apps are required, their cookies are still automatically deleted before the user has clicked "accept" or "decline" in the popup. And in the case where you don't have optional cookies that popup is never shown, so as a result all required cookies keep being deleted every time you refresh the page.
The solution was to set `optOut: true` for all required apps. This means that the cookies will be assumed to be allowed unless the user turns them off. Since they're required as well, the user can't turn them off. You'd expect `optOut` to be implied by the `required` option. But it seems like it isn't.
- Ensure changes to the language are persisted after you reload the page manually.
- …
=> Fix issue where required cookies are removed by orejime

src/app/shared/access-control-form-container/item-access-control-select-bitstreams-modal/item-access-control-select-bitstreams-modal.component.html, src/app/shared/access-control-form-container/item-access-control-select-bitstreams-modal/item-access-control-select-bitstreams-modal.component.spec.ts, src/app/shared/access-control-form-container/item-access-control-select-bitstreams-modal/item-access-control-select-bitstreams-modal.component.ts
* Fixes #4140
Fixed pagination on the "Select bitstreams" modal of the "Edit Item > Access Control" page.
**Changes**
Refactored ItemAccessControlSelectBitstreamsModalComponent to:
- Simplify how the bitstreams are retrieved.
- Ensure the correct PaginationComponentOptions are being used.
- Upload a lot of bitstreams to the ORIGINAL bundle of an item (at least 6)
- Go the `/edit/access-control` page of that item.
- In the right column, switch "Bitstreams", select "0 bitstreams selected", click the looking glass icon.
- Verify:
- Only the first 5 bitstreams are displayed.
- The pagination header is correct ("Now showing 1 - 5 of X").
- You can use the pagination buttons to show a different set of bitstreams.
- You can still …
=> Fix pagination on the "Select bitstreams" modal of the "Access Control" tab

src/app/access-control/bulk-access/bulk-access.component.spec.ts, src/app/access-control/bulk-access/bulk-access.component.ts, src/app/access-control/bulk-access/settings/bulk-access-settings.component.ts, src/app/shared/access-control-form-container/access-control-array-form/access-control-array-form.component.ts, src/app/shared/access-control-form-container/access-control-form-container.component.ts
- Fixes #3893
- Backport PR #4169
The export button in Bulk Access Management was not considering the state of step 2 in the form. This has been fixed.
* Export button in Bulk Access Management has an extra check in `canExport` now.
* Tests for the component are modified. This includes tests for the new case and some refactoring to handle the dynamically loaded components.
This can be tested by logging in as Admin and navigating to Bulk Access Management. The button should activate only when there is some selection in both steps.
=> Fix export button enabled in bulk access management without selecting step 2

src/app/access-control/bulk-access/bulk-access.component.spec.ts, src/app/access-control/bulk-access/bulk-access.component.ts, src/app/access-control/bulk-access/settings/bulk-access-settings.component.ts, src/app/shared/access-control-form-container/access-control-array-form/access-control-array-form.component.ts, src/app/shared/access-control-form-container/access-control-form-container.component.ts
Port of #4168 to `dspace-7_x`.
=> [Port dspace-7_x] Fix export button enabled in bulk access management without selecting step 2

src/app/shared/search/search-filters/search-filters.component.html, src/app/shared/search/search-filters/search-filters.component.ts
Port of #4121 for DSpace dspace-8_x branch
* Fix #4097 
Store the state of the computed filters in the array finalFiltersComputed.
The counter filtersWithComputedVisibility doesn't store the count of filters computed when you change between options in the select box in /mydspace, causing the ngIf in the HTML is always false, and no filters options render on the web.
* First, countFiltersWithComputedVisibility now store the count every time a new filter is "computed" till it reach the maximum filters configured.
* Second, added some utility functions to find the current and final counter, and a function to update the count.
* Third, update the ngIf, to use the new functions.
* Fourth, removed the trackBy: trackUpdate in the ngFor because when you enter in …
=> [Port dspace-8_x] Store the state of the computed filters

.github/workflows/build.yml
* Inspired by #4145 (now fixed)
After #4145 was discovered by accident, I thought it'd be better to add more automated SSR testing to our GitHub CI process. This PR therefore adds an SSR validation test for Communities, Collections, Items/Publication, Person, Project, OrgUnit and all Journal entity types. 
The new tests are based on the *existing* SSR test that we've had for the Homepage already.
I've verified these new tests would have caught the issue found in #4145 by doing the following:
* I locally reverted the fixes in #4161, and rebuilt & deployed in production mode
* I then manually ran the `wget` command for a Publication entity included in this PR.  
The `wget` command **fails** (returns 1) if #4161 is reverted, but succeeds (returns 0) on main.
* Verify all new `wget` tests …
=> Add additional automated server-side rendering (SSR) tests for all Entity Types

src/app/shared/view-mode-switch/view-mode-switch.component.html
* Fixes #4188
Added tooltips to the view mode switch buttons in the search results to indicate their functionality.
This PR enhances the user experience by providing tooltips on buttons that switch between different view modes in the search results. 
* Updated the `view-mode-switch.component.html` file.
* Added `title` attributes to each view switch button to display tooltips on hover.
However, …
=> Fix: adding tooltips to indicate functionality of buttons when switching views of search results

.eslintrc.json
* Related to #2306
* Closes #2309
Update the ESLint configuration for json5 files.
* Use `plugin:jsonc/recommended-with-json5` instead of `plugin:jsonc/recommended-with-jsonc`
* Use `jsonc/no-irregular-whitespace` plugin instead of ESLint's `no-irregular-whitespace`
=> Update ESLint configuration for json5 files

src/assets/i18n/en.json5
Correct typo in the external-login.confirm-email-sent.info.
* Fixes #4200
=> Correct small typo in en.json5

src/app/shared/object-list/sidebar-search-list-element/item-types/publication/publication-sidebar-search-list-element.component.ts
* Fixes #4194
Untyped items weren't rendered using the correct listableObjectComponent in the edit modal. The reason seemed to be because of the decorators for untyped items had the wrong context in `publication-sidebar-search-list-element.component.ts`. They used the context of the scope select which has to be a mistake because the scope select only shows communities and collections. Changing them to the context publications use fixed the issue.
Verify that untyped items are rendered identically to items in the admin sidebar → edit → item modal
However, reviewers may request that you complete any …
=> fix untyped item display in edit item modal

src/app/shared/form/form.component.ts
Hi @tdonohue, I'm @jtimal partner. We have been working on this issue and we will send you the PR.
* Fixes #2567
Validate value on remove item for submission form only for qualdrop component
*  I added a validation for the model value of the qualdrop component to not emit the delete event if it didn't have a previous value
To reproduce
1) Enter a value for a qualdrop_value field (e.g. dc.identifier.issn)
2) Use the plus button to add another line. Select the same qualifier as above.
3) Leave the newly added line empty (do not enter a value) and click on the delete button
4) Save your item
- [] My PR **aligns with [Accessibility guidelines](https://wiki.lyrasis.org/display/DSDOC8x/Accessibility)** if it makes changes to the user interface.
=> Fix - previously entered qualdrop value field is deleted when adding a new (emtpy) line with the same(!) qualifier and then deleting it 

docker/docker-compose-ci.yml, docker/docker-compose-rest.yml
* Ports changes from https://github.com/DSpace/DSpace/pull/10627 to the Docker Compose scripts in Angular.
Solr 9 compatibility requires minor updates to how Solr image is initialized in our Docker Compose scripts (because Solr changed their own Docker images in version 9).  This is why our e2e tests are currently *failing* on `main`, because the backend is now using Solr 9 (as of https://github.com/DSpace/DSpace/pull/10627)
* If e2e tests now succeed, that means these changes are working properly.
* No changes to DSpace code exist in this PR.  It only updates Docker Compose scripts used to run the backend and e2e tests.
=> Update Docker Compose scripts for Solr 9 compatibility 

src/app/shared/mydspace-actions/mydspace-actions.ts, src/app/shared/mydspace-actions/mydspace-reloadable-actions.spec.ts, src/app/shared/mydspace-actions/mydspace-reloadable-actions.ts, src/app/shared/search/search-filters/search-filter/search-filter.component.ts, src/app/shared/search/search-filters/search-filters.component.html, src/app/shared/search/search-filters/search-filters.component.ts
Fixes https://github.com/DSpace/dspace-angular/issues/4205
This PR fixes a cache issue that occurs after executing any reloadable action in MyDSpace.
The problem arises because we update the rendered results immediately—so the item becomes visible right away—but we don't invalidate the cache. As a result, when the same search request is triggered again (for example, by switching between configurations), the cached data causes a mismatch in the item's render type. This leads to an empty list element appearing in the DOM.
So following the same logic we have on the reload method in src/app/shared/mydspace-actions/mydspace-actions.ts, I have applied a cache invalidation happening after any of the reloadable actions in MyDSpace.
Regarding the second problem mentioned in the issue, the one …
=> [DURACOM-350] fix cache issue after mydspace action

src/assets/i18n/ar.json5, src/assets/i18n/bn.json5, src/assets/i18n/ca.json5, src/assets/i18n/cs.json5, src/assets/i18n/de.json5, src/assets/i18n/el.json5, src/assets/i18n/en.json5, src/assets/i18n/es.json5, src/assets/i18n/fi.json5, src/assets/i18n/fr.json5, src/assets/i18n/gd.json5, src/assets/i18n/hi.json5, src/assets/i18n/hu.json5, src/assets/i18n/it.json5, src/assets/i18n/ja.json5, src/assets/i18n/kk.json5, src/assets/i18n/lv.json5, src/assets/i18n/nl.json5, src/assets/i18n/pl.json5, src/assets/i18n/pt-BR.json5, src/assets/i18n/pt-PT.json5, src/assets/i18n/sr-cyr.json5, src/assets/i18n/sr-lat.json5, src/assets/i18n/sv.json5, src/assets/i18n/sw.json5, src/assets/i18n/tr.json5, src/assets/i18n/uk.json5, src/assets/i18n/vi.json5
We don't need to be capitalizing "Community" and "Collection" in the user interface unless they are at the beginning of a sentence or in a title/header. They are not proper nouns and look out of place.
* Update several occurrences of  "Community" and "Collection" and one "Item" in English i18n strings 
Build the user interface and make sure you can see the new strings. One place these strings occur is in the success message …
=> Adjust unnecessary capitalization in English i18n strings

src/assets/i18n/en.json5
Fixes #4221
This PR adds missing translation keys for the journal volume lookup popup in the submission form.
1. Added the missing translation keys to `en.json5`.
How to test or review the PR:
1.  Start a new submission for a Journal Issue
2.  Click on the lookup icon for adding a Journal Volume
3.  Verify that the labels are all translated
=> Add translation keys for journal submission volume lookup

src/app/core/data/bitstream-data.service.spec.ts, src/app/core/data/bitstream-data.service.ts, src/app/item-page/edit-item-page/item-bitstreams/item-edit-bitstream-bundle/item-edit-bitstream-bundle.component.ts
* Fixes #4137
Disable cache to ensure the updated bitstream format is displayed immediately after update.
Fixes an issue where bitstream format changes did not appear immediately after saving due to cached data. Cache is now disabled specifically when fetching the bitstream's format to ensure the updated value is shown.
**Steps to reproduce the behavior:**
1. Log in as a user with edit item permissions;
2. Go to my space;
3. Select a submitted item;
4. Edit item;
5. Open bitstream tab;
6. Click the Edit button.
7. Change file format.
8. The newly saved format should be displayed.
* Disabled cache when resolving `followLink('format')` by setting `{ useCachedVersionIfAvailable: false }` in `item-edit-bitstream-bundle.component.ts`.
_This checklist provides a …
=> Fix: prevent bitstream format cache issue by disabling cached version

src/app/shared/cookies/browser-orejime.service.spec.ts, src/app/shared/cookies/browser-orejime.service.ts
* Fixes #4106
Since orejime does not have a "global" callback property, we need to apply the method that updates user preferences to each app in orejime's config, and of course we need to call any custom callback already there for each app.
* Created the `applyUpdateSettingsCallbackToApps` method. This method changes the `callback` property of each app by calling the method that updates the saved user settings, and then calls any `callback` function set to that app in config.
* Wrote tests.
To test this PR, you need to add a non-mandatory cookie to the orejime configuration and then enable/disable that cookie. Changes should be persisted on the REST side, and any original callback should be called.
=> [DURACOM-353] fix orejime callbacks

src/app/submission/form/footer/submission-form-footer.component.html
* Fixes #4275
Used a flexbox approach instead of bootstrap columns to improve the UI behavior on medium screens.
To test this PR:
1. Start the project pointing at sandbox, log in;
2. Open a new submission and resize the page. The footer buttons now should be way more responsive.
* Changed the template of the submission footer. No tests have been written since it's a template-only change.
- [] My PR **passes all specs/tests and includes new/updated specs or tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
=> Fix submission footer wrapping on medium screens

src/app/item-page/edit-item-page/item-bitstreams/item-bitstreams.component.ts
- Fixes #4015
- dspace-8_x port #4280 
- dspace-7_x port #4281  
The problem was introduced with [#3694](https://github.com/DSpace/dspace-angular/pull/3694). When the pagination changes, bundles that were retrieved previously were retrieved again and added to the bundles array without checking whether they were already present.
I added checks so bundles are not added multiple times.
Also made some changes to make sure the 'load more' button only shows up when there actually are more bundles to load.
Same as described in #4015:
1. Go to edit item > Bitstreams tab
2. Upload enough dummy files to trigger pagination
3. Use pagination to change table pages
For the 'load more' button to show up, you have to make sure the Item has more than 10 bundles.
I only managed to reliably reproduce the …
=> Fix bitstream tables being duplicated

src/app/core/statistics/models/usage-report.model.ts, src/app/statistics-page/statistics-table/statistics-table.component.html, src/app/statistics-page/statistics-table/statistics-table.component.spec.ts, src/app/statistics-page/statistics-table/statistics-table.component.ts
Hi @tdonohue I have taken a look at this issue and generated this PR:
* Fixes #4204 
This PR resolves a blink that occurs on the site statistics page and some translation issues related to the page.
When you enter to [dspace.site.url]/statistics, the table should load without blink, also the "views" header must be translated if you change the language (before always sets as views)
* Removed an unnecessary request for each point in the statistics table (only site statistics made this request, however the information this request obtained is already included in the report itself)
* Fixed header translation
* Fixed unit tests and e2e tests.
=> fixed flash and translate problems on statistics

src/app/shared/form/builder/parsers/onebox-field-parser.ts
With this PR, the `spellCheck` attribute is also applied to simple input fields based on the application configuration `form.spellCheck`. Currently, the `spellCheck` attribute is only set for textarea fields (see #2003).
=> apply spellCheck configuration to input model

src/app/shared/form/builder/ds-dynamic-form-ui/ds-dynamic-form-control-container.component.scss, src/app/shared/form/builder/ds-dynamic-form-ui/models/list/dynamic-list.component.html, src/app/shared/form/builder/ds-dynamic-form-ui/models/list/dynamic-list.component.spec.ts
- Related #4136
This PR reduces margins on input fields for a more streamlined submission form design.
1. Updated `ds-dynamic-form-control-container.component.scss` to reduce bottom margins on all input field labels.
2. Updated `dynamic-list.component.html` to remove left margins from checkbox and radio button lists.
**BEFORE**
**AFTER**
How to test or review the PR:
-   Create a new item through the admin sidebar.
-   Verify the margin changes in the item submission form.
=> Reduce margins on input fields

src/app/core/eperson/eperson-data.service.spec.ts, src/app/core/eperson/eperson-data.service.ts, src/app/shared/testing/eperson.mock.ts
Fixes https://github.com/DSpace/dspace-angular/issues/4287
Improve patch for EPerson to allow "add" operation.
Inserted "add" operation as possible for EPerson  modification.
Implemented test to ensure presence of "add" operation, created mock.
To reproduce the bug the easiest way is to delete one of the metadata on the DB, e.g. lastname, for an EPerson, and then try to add that metadata via UI. (Step by step at https://github.com/DSpace/dspace-angular/issues/4287).
However, reviewers may request that you complete any actions in this list if you have not done so. If you are unsure about an item in the …
=> [DURACOM-326] fix possible issue on missing value for eperson patch

src/app/shared/eperson-group-list/eperson-group-list.component.ts
* Fixes #4303
Fixed broken pagination of of the People/Group section on the edit resource page introduced by #4290
* Updated the `EpersonGroupListComponent#updateList` to continue listening to pagination changes, to ensure the list automatically gets refershed when you switch to a different page
See #4303 on how to reproduce this bug
=> Fixed broken Pagination of People/Groups on Edit Resource Policy page

src/app/shared/upload/uploader/uploader-options.model.ts, src/app/shared/upload/uploader/uploader.component.ts, src/app/submission/form/submission-form.component.ts
Fix the bitstream upload failure during the workflow editing process when a admin  is impersonating an editor.
The issue was caused by the missing X-On-Behalf-Of header required to handle impersonation during the file upload process.
- Set the X-On-Behalf-Of header with the impersonatingID in the FileUploader class.
- Added a new field, impersonatingID, to the UploaderOptions 
- Updated UploaderOptions to include the impersonatingID parameter, ensuring it propagates correctly during the upload process.
1. Log in as an **admin**
2. Go to **Access Control > Person**
3. Impersonate a **Submitter** (e.g., `dspacedemo+submit@gmail.com`)
4. Deposit an item into a workflow-enabled collection
5. Stop impersonating the **Submitter**
6. Impersonate an **Editor** (e.g., …
=> Bitstream upload failure during the workflow editing process when impersonating an editor

package.json, src/app/item-page/media-viewer/media-viewer.component.html, src/app/item-page/media-viewer/media-viewer.component.spec.ts, src/app/thumbnail/thumbnail.component.ts
* 8.x version of https://github.com/DSpace/dspace-angular/pull/4249
There was already a call to get a shortlivedtoken in the thumbnail component. The issue was that in prod mode, angular didn't detect that the image src had changed afterwards so it didn't rerender the image.
The solution was to use a BehaviorSubject for the src and the isLoading boolean
- Create a bitstream in the ORIGINAL bundle of an item
- Configure an embargo for that bitstream, with a date in the future
- Run `filter-media -f -i ${the item's handle}` on the item containing the bitstream
- Go to the item page as an admin, and verify that you can see that bitstream's thumbnail
- Go to the item page as an anonymous user, and verify that you see a placeholder instead
=> [Port dspace-8_x] Show restricted thumbnails to users with access rights

src/app/item-page/orcid-page/orcid-sync-settings/orcid-sync-settings.component.html, src/app/item-page/orcid-page/orcid-sync-settings/orcid-sync-settings.component.scss
* Fixes #4302 
This PR introduces CSS changes to adjust the layout of checkbox elements in the profile settings of the ORCID page.
Please review the visual alignment and spacing of the checkboxes and labels on the ORCID settings page.
* Changed the `width` of the checkbox `input` and `label` from `100%` to `auto` to prevent full-width stretching.
* Removed the `ms-2` class from the `label` element, as it already includes appropriate left padding via other styles.
However, reviewers may request that you complete any actions in this list if you have not done so. If you are …
=> Fix layout of ORCID settings on profile page

src/assets/i18n/en.json5
Small PR which adds a few missing i18n keys that I stumbled on while testing creation of Entities from the "Edit Item -> Relationships" tab.  These are mostly related to OpenAlex (i.e. using tools in DSpace to import a new Entity from OpenAlex), which is new in 9.0
* I've fully tested this change, and it's only adding some missing i18n keys to our `en.json5` file
=> Add missing i18n labels, mostly for OpenAlex import of related Entities

src/app/footer/footer.component.ts, src/app/shared/cookies/orejime.service.ts, src/app/statistics/matomo.service.spec.ts, src/app/statistics/matomo.service.ts
* Fixes #4309
Changed the injection of `MatomoTracker` and `MatomoInitializerService` so that they are not injected before checking for all Matomo's necessary configuration values.
I tested this without a local Matomo instance: I used Chrome overrides to mimic the same behavior instead, and it seems fine enough. The most important part - except for making sure that the issue is fixed, of course - is checking that there is no regression on Matomo.
* Moved `MatomoTracker` and `MatomoInitializerService` injection after obtaining Matomo's configuration options from the REST config;
* Fixed tests and added a missing `providedIn: root`.
To test this PR:
* Open any `/bitstreams/<uuid>/download` page in SSR with Matomo disabled - there should be no error regarding …
=> Fix matomo SSR error on bitstream download page

.github/workflows/build.yml
* Inspired by trying to **avoid** seeing tickets like #4042 and #4132 occur again.
This small PR adds basic, (Bash) command-line tests into our GitHub build process to verify the following HTTP response codes occur:
* 301 redirect occurs for `/handle/[prefix]/[suffix]` URLs
* 403 error occurs for the `/403` error page
* 404 error occurs for the `/404` error page and an invalid URL
* 500 error occurs for the `/500` error page.
* This PR contains no new DSpace code.  It just adds some Bash commandline tests on to the end of our Build process which verify proper error codes are returned from the DSpace UI as described above.
=> Add basic automated tests to ensure common HTTP Return Codes do not break

src/app/thumbnail/thumbnail.component.scss, src/styles/_global-styles.scss
* Fixes #3339, "No thumbnails available" text going outside the marked area.
Resets the font size of the text that appears in place of thumbnails when there are no thumbnails, to prevent the text from going outside the marked thumbnail area.
The font size of the "No thumbnails available" text has been changed to 0.875rem at resolutions smaller than 992px and 0.4rem at very low resolutions.
* Resolution treatments were added starting at line 219
"@media screen and (max-width: map-get($grid-breakpoints, sm)) {
font-size: 0.4rem;
padding: 0.1rem;
}
@media screen and (min-width: map-get($grid-breakpoints, sm)) and (max-width: map-get($grid-breakpoints, lg)) {
font-size: 0.875rem;
padding: 0.1rem;
}"
in the file "src/styles/_global-styles.scss".
**To test the …
=> Adjust the font size of the 'No thumbnails available' text.

.eslintrc.json, src/app/browse-by/browse-by-page/browse-by-page.component.spec.ts, src/app/browse-by/browse-by-switcher/browse-by-switcher.component.spec.ts, src/app/process-page/form/process-parameters/parameter-value-input/value-input.component.ts, src/app/shared/browse-by/browse-by.component.spec.ts, src/app/shared/comcol/sections/comcol-browse-by/comcol-browse-by.component.spec.ts, src/app/shared/disabled-directive.spec.ts, src/app/shared/dso-selector/modal-wrappers/dso-selector-modal-wrapper.component.ts, src/app/shared/form/builder/ds-dynamic-form-ui/models/dynamic-vocabulary.component.ts, src/app/shared/mydspace-actions/claimed-task/abstract/advanced-claimed-task-actions-abstract.component.ts, src/app/shared/mydspace-actions/claimed-task/abstract/claimed-task-actions-abstract.component.ts, src/app/shared/mydspace-actions/mydspace-actions.ts, src/app/shared/mydspace-actions/mydspace-reloadable-actions.ts, src/app/shared/object-select/object-select/object-select.component.ts, src/app/shared/starts-with/starts-with-abstract.component.ts, src/app/shared/theme-support/test/custom/themed-test.component.spec.ts, src/app/shared/theme-support/test/test.component.spec.ts, src/app/shared/theme-support/themed.component.ts, src/app/submission/sections/models/section.model.ts, src/app/workflowitems-edit-page/advanced-workflow-action/advanced-workflow-action/advanced-workflow-action.component.ts
* Fixes #4328
Implemented the `@angular-eslint/prefer-standalone` rule to enforce using standalone components/directives/pipes.
You can test this linting rule by removing a `standalone: true` property from a component declaration.
Components that are now `standalone` are either abstract components or test components, so no functionality has been degraded.
* Added the @angular-eslint/prefer-standalone rule in `.eslintrc.json`;
* Fixed linting errors;
* Fixed tests that were declaring components (as now they have to import them).
=> Enforce standalone components/directives/pipes via linting

src/app/dso-shared/dso-edit-metadata/metadata-field-selector/metadata-field-selector.component.spec.ts, src/app/dso-shared/dso-edit-metadata/metadata-field-selector/metadata-field-selector.component.ts
* Fixes #4339
Fixed a validation issue that prevents you from submitting unqualified metadata fields, if the unqualified metadata field was added to the registry when 20 qualified fields with the same schema & element were already present in the DB
* Updated the `MetadataFieldSelectorComponent` to sort the field names during the `validate()` call. This ensures that the unqualified field is always present on the first page. I also reused the other `pageOptions` as well, this way if you type out the whole metadata field name correctly, the validate call won't send out an additional network request
**Guidance for how to test or review this PR:** See #4339
=> Fix unqualified metadata field validation in Edit Metadata tab by sorting fields in validation request

src/styles/_truncatable-part.component.scss
* Fixes #1164 
Changed truncatable parts in order to use ellipsis instead of fading text, for a11y purposes.
I decided to use [webkit's line-clamp CSS rule](https://developer.mozilla.org/en-US/docs/Web/CSS/line-clamp) in order to achieve the same result as before, changing only how the truncated part happens to "fade away" - it was a fade to transparency before, it's an ellipsis now.
I think this is the best way to implement this feature, as it is now [widely supported](https://caniuse.com/css-line-clamp). Moreover, we can keep backwards compatibility by just changing the `clamp` mixin, since it's used in all truncatable-part css classes, except for the `clamp-none.fixedHeight.min-<1 to 15>`, which is just applying a `min-height`, so that's ok.
Another great upside of using `line-clamp` …
=> Use ellipsis for truncatable parts

src/app/submission/form/footer/submission-form-footer.component.html
* Fixes #4275
* Backport of #4276 to 8.x
Used a flexbox approach instead of bootstrap columns to improve the UI behavior on medium screens.
To test this PR:
1. Start the project pointing at sandbox, log in;
2. Open a new submission and resize the page. The footer buttons now should be way more responsive.
* Changed the template of the submission footer. No tests have been written since it's a template-only change.
- [] My PR **passes all specs/tests and includes new/updated specs or tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
=> [Port dspace-8_x] fix submission footer wrapping on medium screens

src/app/submission/objects/submission-objects.effects.ts
Last minute bugfix! Tiny and fixes a pretty annoying problem, but I understand if it's come too late.
Fixes cases where a section needs to be disabled on save/init because it is empty and non-mandatory
The problem is in some logic introduced to handle edge cases where the duplicates section should (or should not) display even if it has empty section data
```javascript
// A section is enabled if it is mandatory or contains data in its section payload
// except for detect duplicate steps which will be hidden with no data unless overridden in config, even if mandatory
const enabled = (sectionDefinition.mandatory && (sectionDefinition.sectionType !== SectionsType.Duplicates))
|| (isNotEmpty(action.payload.sections) && action.payload.sections.hasOwnProperty(sectionId)
&& …
```
=> Fix and simplify submission section 'enabled' logic

.github/dependabot.yml
As @angular/core uses the `~` specifier to pin zone.js to a patch version, dependabot should not try to update minor versions in DSpace. We need to use the same version to avoid peer dependency conflicts.
I think we never noticed this until we switched to npm in DSpace 9 because yarn does not complain about conflicts in peer dependencies.
See: https://github.com/angular/angular/blob/18.2.x/packages/core/package.json
* Adjust dependabot configuration to consider patch versions for zone.js
**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, screenshots or …
=> .github/dependabot.yml: adjust rules for zone.js

src/app/shared/form/form.component.ts
This is a very small change that fixes form error handling for repeated fields, by correctly passing the field index to `formBuilderService.findById()` when resolving a parsed field to a dynamic form control model.
Without this change applied, the error is always rendered for the first element only, and in some cases does not correctly invalidate or render an error message at all.
With this change applied, the correct field instance is made invalid and the message displayed.
This might not be noticeable to many DSpace configurations since most errors are "required" errors, where by definition a repeated field is usually not empty/null, but you can test this with a custom error message, or the regex submission config validator.
To test:
- Set up a repeatable onebox field (e.g. subject …
=> Resolve field instance models using index when filtering errors

src/app/shared/form/vocabulary-treeview/vocabulary-treeview.component.spec.ts, src/app/shared/form/vocabulary-treeview/vocabulary-treeview.component.ts
* Fixes #3784 
#3820
#3821 
Two changes are made:
Before initializing a treeview, an attempt is made to retrieve the `preloadLevel` value for the opened vocabulary.
If a value is found the preloadLevel is set to that value, otherwise 1 is used.
Whenever a node is initialized and that node is on a level lower than the preloadLevel, that node is immediately expanded.
- Set config for preLoadLevel, e.g. vocabulary.plugin.srsc.hierarchy.preloadLevel = 3 (values greater than 3 are not recommended for 'srsc')
- Open Browse 'By Subject Category' page (browse/srsc)
- The tree is immediately expanded up to 3 levels
=> Vocabulary preloadlevel fix

config/config.example.yml, src/app/collection-page/collection-page-routes.ts, src/app/community-page/community-page-routes.ts, src/app/shared/comcol/comcol-page-browse-by/comcol-page-browse-by.component.ts, src/app/shared/comcol/sections/comcol-search-section/comcol-search-section.component.spec.ts, src/app/shared/comcol/sections/comcol-search-section/comcol-search-section.component.ts, src/assets/i18n/en.json5, src/config/collection-page-config.interface.ts, src/config/community-page-config.interface.ts, src/config/default-app-config.ts, src/environments/environment.test.ts
This is a manual port of https://github.com/DSpace/dspace-angular/pull/3164 by @abelgomez. It would be great to get this improvement into the 8.x codebase. It doesn't require https://github.com/DSpace/dspace-angular/pull/4138 because https://github.com/DSpace/dspace-angular/pull/3994 wasn't backported to 8.x.
You can follow the instructions for reviewers in the original pull request: https://github.com/DSpace/dspace-angular/pull/3164.
However, reviewers may request that you complete any actions in this list if you have not done so. If you are unsure about an item in the checklist, don't hesitate to …
=> [Port dspace-8_x] Make the default tab for browsing communities and collections configurable in DSpace 8

config/config.example.yml, src/assets/i18n/ru.json5, src/config/default-app-config.ts
* Fixes #4486 
First version of a russian translatrion for DSpace
Change the language using the dropdown
* ru.json5. The main file of the translation.
* config.example.yml. Added the option to the language list
=> Russian translation

src/app/shared/dso-selector/modal-wrappers/create-community-parent-selector/create-community-parent-selector.component.ts
* Fixes #4564
Ensure that the current community appears at the top of the list when adding a sub-community. This PR fixes an issue where the current community was not displayed as expected when creating a sub-community. The problem was caused by the missing call to the parent `ngOnInit()` method in the `CreateCommunityParentSelectorComponent`, which is responsible for initializing the current page's DSO.
To verify this fix, follow the steps below:
1. Log in as a user with permission to create communities.
2. Navigate to an existing community.
3. In the sidebar, click "New → Community".
4. In the "Create a new community in" list, verify that the current community appears at the top of the list.
* Called `super.ngOnInit()` inside the `ngOnInit()` method of …
=> Fix current parent order when creating subcommunity

docker/db.entities.yml, docker/docker-compose-ci.yml, docker/docker-compose-rest.yml
* This is the frontend PR that corresponds with https://github.com/DSpace/DSpace/pull/11099
This updates our frontend's Docker Compose scripts to no longer reference the removed `pgcrypto` images (see https://github.com/DSpace/DSpace/pull/11099). 
* These scripts are used in the frontend's e2e tests.  So, if there are major flaws, then the problems should be found in those tests.
=> [Docker] Remover references to obsolete backend "pgcrypto" images

package-lock.json, package.json
NOTE: This PR was generated by @dependabot in our https://github.com/DSpace-Labs/dspace-angular-9x repository (see https://github.com/DSpace-Labs/dspace-angular-9x/pull/1).  It patches a security alert in `webpack-dev-server` in `dspace-9_x`.
Bumps [webpack-dev-server](https://github.com/webpack/webpack-dev-server) from 4.15.2 to 5.2.1.
- [Release notes](https://github.com/webpack/webpack-dev-server/releases)
- [Changelog](https://github.com/webpack/webpack-dev-server/blob/master/CHANGELOG.md)
- [Commits](https://github.com/webpack/webpack-dev-server/compare/v4.15.2...v5.2.1)
---
updated-dependencies:
- dependency-name: webpack-dev-server dependency-version: 5.2.1 dependency-type: direct:development ...
=> [Dependabot] Bump webpack-dev-server from 4.15.2 to 5.2.1

.github/dependabot.yml
Refactors code added in these two PRs:
* #4483 
* #4424 
Since merging #4424 and #4483, it appears that dependabot has been having issues with our configuration.  We're seeing this error everytime dependabot attempts to run on dependencies:
```
Dependabot encountered '1' error(s) during execution, please check the logs for more details.
+----------------------------------------------------------------------------------------------------+
|                                   Dependencies failed to update                                    |
+------------+--------------------------------+------------------------------------------------------+
| Dependency | Error Type                     | Error Details                                        | …
```
=> [Dependabot] Move zone.js and typescript rules into "ignore" settings and ignore major/minor versions

src/app/shared/geospatial-map/geospatial-map.component.ts
- Related to #3540
Minor improvements regarding the geospatial map zoom & scroll behaviour.
I updated the zoom level in order to be able to zoom out more, this way you can see the whole map. Also blocked users from scrolling above the north pole and below the south pole. I also ensured that when you scroll vertically, that the points are rendered on those maps as well
* Updated the `minZoom` to 1 (this way you can zoom out completely, but I coudl see the point to set it to 1.5 to prevent duplicate continents from being shown)
* Added `maxBounds` & enforced them using `maxBoundsViscosity` to prevent scrolling out of the map
* Enabled `worldCopyJump` to copy the points to neighbouring maps when you scroll too far to the left/right
**Guidance for how to test or …
=> Improved geospatial map bounds & scroll behaviour

src/app/shared/form/builder/ds-dynamic-form-ui/ds-dynamic-form-control-container.component.html, src/app/shared/form/builder/ds-dynamic-form-ui/ds-dynamic-form-control-container.component.scss, src/app/shared/form/builder/ds-dynamic-form-ui/existing-metadata-list-element/existing-metadata-list-element.component.html, src/app/shared/form/builder/ds-dynamic-form-ui/models/date-picker/date-picker.component.scss
Manual port of #4136 by @gingyx to DSpace 7.x.
I think this is a faithful port of the original PR. DSpace 9 switched to Angular Control Flow syntax so the patch had to be adapted to use the old `ngIf` syntax. Below on my DSpace 7.6.3 instance (don't mind the green branding of my theme, the functionality is the same).
The elements for each input are grouped together more coherently and the error text is aligned the same as the hint.
=> [Port dspace-7_x] Clean up spacing in input forms

src/app/shared/form/builder/ds-dynamic-form-ui/ds-dynamic-form-control-container.component.html, src/app/shared/form/builder/ds-dynamic-form-ui/ds-dynamic-form-control-container.component.scss, src/app/shared/form/builder/ds-dynamic-form-ui/existing-metadata-list-element/existing-metadata-list-element.component.html, src/app/shared/form/builder/ds-dynamic-form-ui/models/date-picker/date-picker.component.scss
Manual port of #4180 by @alanorth  and #4136 by @gingyx to `dspace-8_x`.
=> [Port dspace-8_x] Clean up spacing in input forms

src/app/access-control/group-registry/group-form/group-form.component.spec.ts, src/app/access-control/group-registry/group-form/group-form.component.ts
Fixes #4278 
The back button behavior was hardcoded and did not really take into account the previous route. This is now fixed. Raising this against 7_x as per the discussion on #4278.
Start from a community or collection page. Navigate to edit -> Assign roles. Create any role and click on it to navigate to edit group page. Pressing back will now take you back to the original page. 
* group-form.component  edited to consider the previous route in onCancel()
* group-form.component.spec edited to provide routeServiceStub to prevent tests from failing
=> Fix back button behavior on roles page
